// generated by newgenasym  Wed Jun 04 15:57:11 2025


module rtl8305nb (avddh1, avddh2, avddh3, avddh4, avddhpll, avddl1, avddl2,
        avddl3, avddl4, avddlpll, dvddh, dvddl1, dvddl2, dvddl3,
        epad, ibref, \ldind/dis_ld , \p0led/dis_eee , p1led,
        \p2led/dis_rst_blnk , p3led, p4led, resetb, rxin0, rxin1,
        rxin2, rxin3, rxin4, rxip0, rxip1, rxip2, rxip3, rxip4,
        \scl/mdc , \sda/mdio , txon0, txon1, txon2, txon3, txon4, txop0,
        txop1, txop2, txop3, txop4, v12out, v33in, xi, xo);
    inout avddh1;
    inout avddh2;
    inout avddh3;
    inout avddh4;
    inout avddhpll;
    inout avddl1;
    inout avddl2;
    inout avddl3;
    inout avddl4;
    inout avddlpll;
    inout dvddh;
    inout dvddl1;
    inout dvddl2;
    inout dvddl3;
    inout epad;
    inout ibref;
    inout \ldind/dis_ld ;
    inout \p0led/dis_eee ;
    inout p1led;
    inout \p2led/dis_rst_blnk ;
    inout p3led;
    inout p4led;
    inout resetb;
    inout rxin0;
    inout rxin1;
    inout rxin2;
    inout rxin3;
    inout rxin4;
    inout rxip0;
    inout rxip1;
    inout rxip2;
    inout rxip3;
    inout rxip4;
    inout \scl/mdc ;
    inout \sda/mdio ;
    inout txon0;
    inout txon1;
    inout txon2;
    inout txon3;
    inout txon4;
    inout txop0;
    inout txop1;
    inout txop2;
    inout txop3;
    inout txop4;
    inout v12out;
    inout v33in;
    inout xi;
    inout xo;


    initial
        begin
        end

endmodule
