// generated by newgenasym  Mon Aug 31 14:31:33 2020


module zx279200 (atst_pll, atst_pmc, atst_rext_vtoi0, atst_rext_vtoi1,
        bias_lvds_in_1, bias_lvds_in_2, bl_refclk_n0,
        bl_refclk_n1, bl_refclk_p0, bl_refclk_p1, bl_sd_rxn0,
        bl_sd_rxn1, bl_sd_rxn2, bl_sd_rxn3, bl_sd_rxn4,
        bl_sd_rxn5, bl_sd_rxn6, bl_sd_rxn7, bl_sd_rxp0,
        bl_sd_rxp1, bl_sd_rxp2, bl_sd_rxp3, bl_sd_rxp4,
        bl_sd_rxp5, bl_sd_rxp6, bl_sd_rxp7, bl_sd_txn0,
        bl_sd_txn1, bl_sd_txn2, bl_sd_txn3, bl_sd_txn4,
        bl_sd_txn5, bl_sd_txn6, bl_sd_txn7, bl_sd_txp0,
        bl_sd_txp1, bl_sd_txp2, bl_sd_txp3, bl_sd_txp4,
        bl_sd_txp5, bl_sd_txp6, bl_sd_txp7, c0_addr_0, c0_addr_1,
        c0_addr_10, c0_addr_11, c0_addr_12, c0_addr_13, c0_addr_2,
        c0_addr_3, c0_addr_4, c0_addr_5, c0_addr_6, c0_addr_7,
        c0_addr_8, c0_addr_9, c0_avdd_pll_c, c0_avddp_pll_c,
        c0_avddp_pll_p, c0_avss_pll_c, c0_avssp_pll_c,
        c0_avssp_pll_p, c0_ba_0, c0_ba_1, c0_ba_2, c0_cas,
        c0_ck_n0, c0_ck_n1, c0_ck_p0, c0_ck_p1, c0_cke, c0_cs_n0,
        c0_cs_n1, c0_dm_0, c0_dm_1, c0_dm_2, c0_dm_3, c0_dm_4,
        c0_dm_5, c0_dm_6, c0_dm_7, c0_dq_0, c0_dq_1, c0_dq_10,
        c0_dq_11, c0_dq_12, c0_dq_13, c0_dq_14, c0_dq_15, c0_dq_16,
        c0_dq_17, c0_dq_18, c0_dq_19, c0_dq_2, c0_dq_20, c0_dq_21,
        c0_dq_22, c0_dq_23, c0_dq_24, c0_dq_25, c0_dq_26, c0_dq_27,
        c0_dq_28, c0_dq_29, c0_dq_3, c0_dq_30, c0_dq_31, c0_dq_32,
        c0_dq_33, c0_dq_34, c0_dq_35, c0_dq_36, c0_dq_37, c0_dq_38,
        c0_dq_39, c0_dq_4, c0_dq_40, c0_dq_41, c0_dq_42, c0_dq_43,
        c0_dq_44, c0_dq_45, c0_dq_46, c0_dq_47, c0_dq_48, c0_dq_49,
        c0_dq_5, c0_dq_50, c0_dq_51, c0_dq_52, c0_dq_53, c0_dq_54,
        c0_dq_55, c0_dq_56, c0_dq_57, c0_dq_58, c0_dq_59, c0_dq_6,
        c0_dq_60, c0_dq_61, c0_dq_62, c0_dq_63, c0_dq_7, c0_dq_8,
        c0_dq_9, c0_dqs_0, c0_dqs_1, c0_dqs_2, c0_dqs_3, c0_dqs_4,
        c0_dqs_5, c0_dqs_6, c0_dqs_7, c0_dqsn_0, c0_dqsn_1,
        c0_dqsn_2, c0_dqsn_3, c0_dqsn_4, c0_dqsn_5, c0_dqsn_6,
        c0_dqsn_7, c0_odt, c0_ras, c0_rst, c0_we, c0_zq1, c0_zq2,
        c1_addr_0, c1_addr_1, c1_addr_10, c1_addr_11, c1_addr_12,
        c1_addr_13, c1_addr_2, c1_addr_3, c1_addr_4, c1_addr_5,
        c1_addr_6, c1_addr_7, c1_addr_8, c1_addr_9, c1_avdd_pll_c,
        c1_avddp_pll_c, c1_avddp_pll_p, c1_avss_pll_c,
        c1_avssp_pll_c, c1_avssp_pll_p, c1_ba_0, c1_ba_1, c1_ba_2,
        c1_cas, c1_ck_n0, c1_ck_n1, c1_ck_p0, c1_ck_p1, c1_cke,
        c1_cs_n0, c1_cs_n1, c1_dm_0, c1_dm_1, c1_dm_2, c1_dm_3,
        c1_dm_4, c1_dm_5, c1_dm_6, c1_dm_7, c1_dq_0, c1_dq_1,
        c1_dq_10, c1_dq_11, c1_dq_12, c1_dq_13, c1_dq_14, c1_dq_15,
        c1_dq_16, c1_dq_17, c1_dq_18, c1_dq_19, c1_dq_2, c1_dq_20,
        c1_dq_21, c1_dq_22, c1_dq_23, c1_dq_24, c1_dq_25, c1_dq_26,
        c1_dq_27, c1_dq_28, c1_dq_29, c1_dq_3, c1_dq_30, c1_dq_31,
        c1_dq_32, c1_dq_33, c1_dq_34, c1_dq_35, c1_dq_36, c1_dq_37,
        c1_dq_38, c1_dq_39, c1_dq_4, c1_dq_40, c1_dq_41, c1_dq_42,
        c1_dq_43, c1_dq_44, c1_dq_45, c1_dq_46, c1_dq_47, c1_dq_48,
        c1_dq_49, c1_dq_5, c1_dq_50, c1_dq_51, c1_dq_52, c1_dq_53,
        c1_dq_54, c1_dq_55, c1_dq_56, c1_dq_57, c1_dq_58, c1_dq_59,
        c1_dq_6, c1_dq_60, c1_dq_61, c1_dq_62, c1_dq_63, c1_dq_7,
        c1_dq_8, c1_dq_9, c1_dqs_0, c1_dqs_1, c1_dqs_2, c1_dqs_3,
        c1_dqs_4, c1_dqs_5, c1_dqs_6, c1_dqs_7, c1_dqsn_0,
        c1_dqsn_1, c1_dqsn_2, c1_dqsn_3, c1_dqsn_4, c1_dqsn_5,
        c1_dqsn_6, c1_dqsn_7, c1_odt, c1_ras, c1_rst, c1_we, c1_zq1,
        c1_zq2, clk_fp_n, clk_fp_p, cpu_addr0, cpu_addr1,
        cpu_addr10, cpu_addr11, cpu_addr12, cpu_addr13,
        cpu_addr14, cpu_addr15, cpu_addr2, cpu_addr3, cpu_addr4,
        cpu_addr5, cpu_addr6, cpu_addr7, cpu_addr8, cpu_addr9,
        cpu_cs_b, cpu_data0, cpu_data1, cpu_data10, cpu_data11,
        cpu_data12, cpu_data13, cpu_data14, cpu_data15, cpu_data2,
        cpu_data3, cpu_data4, cpu_data5, cpu_data6, cpu_data7,
        cpu_data8, cpu_data9, cpu_intb, cpu_rd_b, cpu_wr_b,
        ddr0_ref_clk, ddr1_ref_clk, ex_refclk_n0, ex_refclk_n1,
        ex_refclk_p0, ex_refclk_p1, ex_sd_rxn0, ex_sd_rxn1,
        ex_sd_rxn2, ex_sd_rxn3, ex_sd_rxn4, ex_sd_rxn5,
        ex_sd_rxn6, ex_sd_rxn7, ex_sd_rxp0, ex_sd_rxp1,
        ex_sd_rxp2, ex_sd_rxp3, ex_sd_rxp4, ex_sd_rxp5,
        ex_sd_rxp6, ex_sd_rxp7, ex_sd_txn0, ex_sd_txn1,
        ex_sd_txn2, ex_sd_txn3, ex_sd_txn4, ex_sd_txn5,
        ex_sd_txn6, ex_sd_txn7, ex_sd_txp0, ex_sd_txp1,
        ex_sd_txp2, ex_sd_txp3, ex_sd_txp4, ex_sd_txp5,
        ex_sd_txp6, ex_sd_txp7, gnd1_1, gnd1_10, gnd1_100,
        gnd1_101, gnd1_102, gnd1_103, gnd1_104, gnd1_105, gnd1_106,
        gnd1_107, gnd1_108, gnd1_109, gnd1_11, gnd1_110, gnd1_111,
        gnd1_112, gnd1_113, gnd1_114, gnd1_115, gnd1_116, gnd1_117,
        gnd1_12, gnd1_13, gnd1_14, gnd1_15, gnd1_16, gnd1_17,
        gnd1_18, gnd1_19, gnd1_2, gnd1_20, gnd1_21, gnd1_22,
        gnd1_23, gnd1_24, gnd1_25, gnd1_26, gnd1_27, gnd1_28,
        gnd1_29, gnd1_3, gnd1_30, gnd1_31, gnd1_32, gnd1_33,
        gnd1_34, gnd1_35, gnd1_36, gnd1_37, gnd1_38, gnd1_39,
        gnd1_4, gnd1_40, gnd1_41, gnd1_42, gnd1_43, gnd1_44,
        gnd1_45, gnd1_46, gnd1_47, gnd1_48, gnd1_49, gnd1_5,
        gnd1_50, gnd1_51, gnd1_52, gnd1_53, gnd1_54, gnd1_55,
        gnd1_56, gnd1_57, gnd1_58, gnd1_59, gnd1_6, gnd1_60,
        gnd1_61, gnd1_62, gnd1_63, gnd1_64, gnd1_65, gnd1_66,
        gnd1_67, gnd1_68, gnd1_69, gnd1_7, gnd1_70, gnd1_71,
        gnd1_72, gnd1_73, gnd1_74, gnd1_75, gnd1_76, gnd1_77,
        gnd1_78, gnd1_79, gnd1_8, gnd1_80, gnd1_81, gnd1_82,
        gnd1_83, gnd1_84, gnd1_85, gnd1_86, gnd1_87, gnd1_88,
        gnd1_89, gnd1_9, gnd1_90, gnd1_91, gnd1_92, gnd1_93,
        gnd1_94, gnd1_95, gnd1_96, gnd1_97, gnd1_98, gnd1_99,
        gnd2_1, gnd2_10, gnd2_11, gnd2_12, gnd2_13, gnd2_14,
        gnd2_15, gnd2_16, gnd2_17, gnd2_18, gnd2_19, gnd2_2,
        gnd2_20, gnd2_21, gnd2_22, gnd2_23, gnd2_24, gnd2_25,
        gnd2_26, gnd2_27, gnd2_28, gnd2_29, gnd2_3, gnd2_4, gnd2_5,
        gnd2_6, gnd2_7, gnd2_8, gnd2_9, gnd3_1, gnd3_10, gnd3_11,
        gnd3_12, gnd3_13, gnd3_14, gnd3_15, gnd3_16, gnd3_17,
        gnd3_18, gnd3_19, gnd3_2, gnd3_20, gnd3_21, gnd3_22,
        gnd3_23, gnd3_24, gnd3_25, gnd3_26, gnd3_27, gnd3_28,
        gnd3_29, gnd3_3, gnd3_30, gnd3_31, gnd3_32, gnd3_33,
        gnd3_34, gnd3_35, gnd3_36, gnd3_37, gnd3_38, gnd3_39,
        gnd3_4, gnd3_40, gnd3_41, gnd3_42, gnd3_43, gnd3_44,
        gnd3_45, gnd3_46, gnd3_47, gnd3_48, gnd3_49, gnd3_5,
        gnd3_50, gnd3_51, gnd3_52, gnd3_53, gnd3_54, gnd3_55,
        gnd3_56, gnd3_57, gnd3_58, gnd3_59, gnd3_6, gnd3_60,
        gnd3_61, gnd3_62, gnd3_63, gnd3_64, gnd3_65, gnd3_66,
        gnd3_67, gnd3_68, gnd3_69, gnd3_7, gnd3_70, gnd3_71,
        gnd3_72, gnd3_73, gnd3_74, gnd3_75, gnd3_76, gnd3_77,
        gnd3_78, gnd3_79, gnd3_8, gnd3_80, gnd3_9, gnd4_1, gnd4_10,
        gnd4_11, gnd4_12, gnd4_13, gnd4_14, gnd4_15, gnd4_16,
        gnd4_17, gnd4_18, gnd4_19, gnd4_2, gnd4_20, gnd4_21,
        gnd4_22, gnd4_23, gnd4_24, gnd4_25, gnd4_26, gnd4_27,
        gnd4_28, gnd4_29, gnd4_3, gnd4_30, gnd4_31, gnd4_32,
        gnd4_33, gnd4_34, gnd4_35, gnd4_36, gnd4_37, gnd4_38,
        gnd4_39, gnd4_4, gnd4_40, gnd4_41, gnd4_42, gnd4_43,
        gnd4_44, gnd4_45, gnd4_46, gnd4_47, gnd4_48, gnd4_49,
        gnd4_5, gnd4_50, gnd4_51, gnd4_52, gnd4_53, gnd4_54, gnd4_6,
        gnd4_7, gnd4_8, gnd4_9, gnd5_1, gnd5_2, gnd5_3, gnd5_4,
        gnd5_5, gnd5_6, gnd5_7, gnd6_1, gnd6_10, gnd6_11, gnd6_12,
        gnd6_13, gnd6_14, gnd6_15, gnd6_16, gnd6_17, gnd6_2, gnd6_3,
        gnd6_4, gnd6_5, gnd6_6, gnd6_7, gnd6_8, gnd6_9, gnd7_1,
        gnd7_10, gnd7_11, gnd7_12, gnd7_13, gnd7_14, gnd7_15,
        gnd7_16, gnd7_17, gnd7_18, gnd7_19, gnd7_2, gnd7_20,
        gnd7_21, gnd7_22, gnd7_23, gnd7_24, gnd7_25, gnd7_26,
        gnd7_27, gnd7_28, gnd7_3, gnd7_4, gnd7_5, gnd7_6, gnd7_7,
        gnd7_8, gnd7_9, gpon0_bcdr_rest, gpon0_opt_rst_o,
        gpon0_opt_sd_i, gpon0_otdr_trig_o, gpon0_otdr_vld_o,
        gpon0_pontxdis_o, gpon0_rssi_o, gpon0_rxclk_rxn,
        gpon0_rxclk_rxp, gpon0_tocpld_opt_rst_o,
        gpon0_tocpld_opt_sd_o, gpon1_bcdr_rest, gpon1_opt_rst_o,
        gpon1_opt_sd_i, gpon1_otdr_trig_o, gpon1_otdr_vld_o,
        gpon1_pontxdis_o, gpon1_rssi_o, gpon1_rxclk_rxn,
        gpon1_rxclk_rxp, gpon1_tocpld_opt_rst_o,
        gpon1_tocpld_opt_sd_o, gpon2_opt_rst_o, gpon2_opt_sd_i,
        gpon2_otdr_trig_o, gpon2_otdr_vld_o, gpon2_pontxdis_o,
        gpon2_rssi_o, gpon2_tocpld_opt_rst_o,
        gpon2_tocpld_opt_sd_o, gpon3_opt_rst_o, gpon3_opt_sd_i,
        gpon3_otdr_trig_o, gpon3_otdr_vld_o, gpon3_pontxdis_o,
        gpon3_rssi_o, gpon3_tocpld_opt_rst_o,
        gpon3_tocpld_opt_sd_o, gpon4_opt_rst_o, gpon4_opt_sd_i,
        gpon4_otdr_trig_o, gpon4_otdr_vld_o, gpon4_pontxdis_o,
        gpon4_rssi_o, gpon4_tocpld_opt_rst_o,
        gpon4_tocpld_opt_sd_o, gpon5_opt_rst_o, gpon5_opt_sd_i,
        gpon5_otdr_trig_o, gpon5_otdr_vld_o, gpon5_pontxdis_o,
        gpon5_rssi_o, gpon5_tocpld_opt_rst_o,
        gpon5_tocpld_opt_sd_o, gpon6_opt_rst_o, gpon6_opt_sd_i,
        gpon6_otdr_trig_o, gpon6_otdr_vld_o, gpon6_pontxdis_o,
        gpon6_rssi_o, gpon6_tocpld_opt_rst_o,
        gpon6_tocpld_opt_sd_o, gpon7_opt_rst_o, gpon7_opt_sd_i,
        gpon7_otdr_trig_o, gpon7_otdr_vld_o, gpon7_pontxdis_o,
        gpon7_rssi_o, gpon7_tocpld_opt_rst_o,
        gpon7_tocpld_opt_sd_o, gpon_refclk_n, gpon_refclk_p,
        gpon_rxd_n0, gpon_rxd_n1, gpon_rxd_n2, gpon_rxd_n5,
        gpon_rxd_n6, gpon_rxd_n7, gpon_rxd_p0, gpon_rxd_p1,
        gpon_rxd_p2, gpon_rxd_p5, gpon_rxd_p6, gpon_rxd_p7,
        gpon_txd_n0, gpon_txd_n1, gpon_txd_n2, gpon_txd_n5,
        gpon_txd_n6, gpon_txd_n7, gpon_txd_p0, gpon_txd_p1,
        gpon_txd_p2, gpon_txd_p5, gpon_txd_p6, gpon_txd_p7,
        hw_clk, hw_fp, hw_rx, hw_tx, jtag_tck, jtag_tdi, jtag_tdo,
        jtag_tms, jtag_trst, k_test, master_slave_select, ms_fp,
        pad_amon_pcie, pad_amon_xaui0, pad_amon_xaui1,
        pad_amon_xaui2, pad_amon_xaui3, pad_rbias_pcie,
        pad_rbias_xaui0, pad_rbias_xaui1, pad_rbias_xaui2,
        pad_rbias_xaui3, pcie_local_select, pcie_refclk_n,
        pcie_refclk_p, pcie_rxd_n0, pcie_rxd_p0, pcie_txd_n0,
        pcie_txd_p0, pll311_ahvdd, pll311_ahvss, pll311_dvdd,
        pll311_dvss, pll312_ahvdd, pll312_ahvss, pll312_dvdd,
        pll312_dvss, pll_vdd, ref_clk0, reset_b, rext_pmc, vdd115a,
        vdd115b, vdd115c, vdd115d, vdd115e, vdd115f, vdd15a, vdd15b,
        vdd25a, vdd25b, vdd33a, vdd33b, vref1_ag10, vref1_ag9,
        vref1_al7, vref1_w1, vref2_a16, vref2_g4, vref2_j8,
        vref2_k8, vref_atst_bgr, x10_fp, x11_fp, xgpon0_bcdr_rest,
        xgpon0_rxclk_rxn, xgpon0_rxclk_rxp, xgpon0_rxpd_n0,
        xgpon0_rxpd_n1, xgpon0_rxpd_n2, xgpon0_rxpd_n3,
        xgpon0_rxpd_n4, xgpon0_rxpd_n5, xgpon0_rxpd_n6,
        xgpon0_rxpd_n7, xgpon0_rxpd_p0, xgpon0_rxpd_p1,
        xgpon0_rxpd_p2, xgpon0_rxpd_p3, xgpon0_rxpd_p4,
        xgpon0_rxpd_p5, xgpon0_rxpd_p6, xgpon0_rxpd_p7,
        xgpon1_bcdr_rest, xgpon1_rxclk_rxn, xgpon1_rxclk_rxp,
        xgpon1_rxpd_n0, xgpon1_rxpd_n1, xgpon1_rxpd_n2,
        xgpon1_rxpd_n3, xgpon1_rxpd_n4, xgpon1_rxpd_n5,
        xgpon1_rxpd_n6, xgpon1_rxpd_n7, xgpon1_rxpd_p0,
        xgpon1_rxpd_p1, xgpon1_rxpd_p2, xgpon1_rxpd_p3,
        xgpon1_rxpd_p4, xgpon1_rxpd_p5, xgpon1_rxpd_p6,
        xgpon1_rxpd_p7, xgpon_rxd_n3, xgpon_rxd_n4, xgpon_rxd_p3,
        xgpon_rxd_p4, xgpon_txd_n3, xgpon_txd_n4, xgpon_txd_p3,
        xgpon_txd_p4);
    inout atst_pll;
    inout atst_pmc;
    inout atst_rext_vtoi0;
    inout atst_rext_vtoi1;
    inout bias_lvds_in_1;
    inout bias_lvds_in_2;
    inout bl_refclk_n0;
    inout bl_refclk_n1;
    inout bl_refclk_p0;
    inout bl_refclk_p1;
    inout bl_sd_rxn0;
    inout bl_sd_rxn1;
    inout bl_sd_rxn2;
    inout bl_sd_rxn3;
    inout bl_sd_rxn4;
    inout bl_sd_rxn5;
    inout bl_sd_rxn6;
    inout bl_sd_rxn7;
    inout bl_sd_rxp0;
    inout bl_sd_rxp1;
    inout bl_sd_rxp2;
    inout bl_sd_rxp3;
    inout bl_sd_rxp4;
    inout bl_sd_rxp5;
    inout bl_sd_rxp6;
    inout bl_sd_rxp7;
    inout bl_sd_txn0;
    inout bl_sd_txn1;
    inout bl_sd_txn2;
    inout bl_sd_txn3;
    inout bl_sd_txn4;
    inout bl_sd_txn5;
    inout bl_sd_txn6;
    inout bl_sd_txn7;
    inout bl_sd_txp0;
    inout bl_sd_txp1;
    inout bl_sd_txp2;
    inout bl_sd_txp3;
    inout bl_sd_txp4;
    inout bl_sd_txp5;
    inout bl_sd_txp6;
    inout bl_sd_txp7;
    inout c0_addr_0;
    inout c0_addr_1;
    inout c0_addr_10;
    inout c0_addr_11;
    inout c0_addr_12;
    inout c0_addr_13;
    inout c0_addr_2;
    inout c0_addr_3;
    inout c0_addr_4;
    inout c0_addr_5;
    inout c0_addr_6;
    inout c0_addr_7;
    inout c0_addr_8;
    inout c0_addr_9;
    inout c0_avdd_pll_c;
    inout c0_avddp_pll_c;
    inout c0_avddp_pll_p;
    inout c0_avss_pll_c;
    inout c0_avssp_pll_c;
    inout c0_avssp_pll_p;
    inout c0_ba_0;
    inout c0_ba_1;
    inout c0_ba_2;
    inout c0_cas;
    inout c0_ck_n0;
    inout c0_ck_n1;
    inout c0_ck_p0;
    inout c0_ck_p1;
    inout c0_cke;
    inout c0_cs_n0;
    inout c0_cs_n1;
    inout c0_dm_0;
    inout c0_dm_1;
    inout c0_dm_2;
    inout c0_dm_3;
    inout c0_dm_4;
    inout c0_dm_5;
    inout c0_dm_6;
    inout c0_dm_7;
    inout c0_dq_0;
    inout c0_dq_1;
    inout c0_dq_10;
    inout c0_dq_11;
    inout c0_dq_12;
    inout c0_dq_13;
    inout c0_dq_14;
    inout c0_dq_15;
    inout c0_dq_16;
    inout c0_dq_17;
    inout c0_dq_18;
    inout c0_dq_19;
    inout c0_dq_2;
    inout c0_dq_20;
    inout c0_dq_21;
    inout c0_dq_22;
    inout c0_dq_23;
    inout c0_dq_24;
    inout c0_dq_25;
    inout c0_dq_26;
    inout c0_dq_27;
    inout c0_dq_28;
    inout c0_dq_29;
    inout c0_dq_3;
    inout c0_dq_30;
    inout c0_dq_31;
    inout c0_dq_32;
    inout c0_dq_33;
    inout c0_dq_34;
    inout c0_dq_35;
    inout c0_dq_36;
    inout c0_dq_37;
    inout c0_dq_38;
    inout c0_dq_39;
    inout c0_dq_4;
    inout c0_dq_40;
    inout c0_dq_41;
    inout c0_dq_42;
    inout c0_dq_43;
    inout c0_dq_44;
    inout c0_dq_45;
    inout c0_dq_46;
    inout c0_dq_47;
    inout c0_dq_48;
    inout c0_dq_49;
    inout c0_dq_5;
    inout c0_dq_50;
    inout c0_dq_51;
    inout c0_dq_52;
    inout c0_dq_53;
    inout c0_dq_54;
    inout c0_dq_55;
    inout c0_dq_56;
    inout c0_dq_57;
    inout c0_dq_58;
    inout c0_dq_59;
    inout c0_dq_6;
    inout c0_dq_60;
    inout c0_dq_61;
    inout c0_dq_62;
    inout c0_dq_63;
    inout c0_dq_7;
    inout c0_dq_8;
    inout c0_dq_9;
    inout c0_dqs_0;
    inout c0_dqs_1;
    inout c0_dqs_2;
    inout c0_dqs_3;
    inout c0_dqs_4;
    inout c0_dqs_5;
    inout c0_dqs_6;
    inout c0_dqs_7;
    inout c0_dqsn_0;
    inout c0_dqsn_1;
    inout c0_dqsn_2;
    inout c0_dqsn_3;
    inout c0_dqsn_4;
    inout c0_dqsn_5;
    inout c0_dqsn_6;
    inout c0_dqsn_7;
    inout c0_odt;
    inout c0_ras;
    inout c0_rst;
    inout c0_we;
    inout c0_zq1;
    inout c0_zq2;
    inout c1_addr_0;
    inout c1_addr_1;
    inout c1_addr_10;
    inout c1_addr_11;
    inout c1_addr_12;
    inout c1_addr_13;
    inout c1_addr_2;
    inout c1_addr_3;
    inout c1_addr_4;
    inout c1_addr_5;
    inout c1_addr_6;
    inout c1_addr_7;
    inout c1_addr_8;
    inout c1_addr_9;
    inout c1_avdd_pll_c;
    inout c1_avddp_pll_c;
    inout c1_avddp_pll_p;
    inout c1_avss_pll_c;
    inout c1_avssp_pll_c;
    inout c1_avssp_pll_p;
    inout c1_ba_0;
    inout c1_ba_1;
    inout c1_ba_2;
    inout c1_cas;
    inout c1_ck_n0;
    inout c1_ck_n1;
    inout c1_ck_p0;
    inout c1_ck_p1;
    inout c1_cke;
    inout c1_cs_n0;
    inout c1_cs_n1;
    inout c1_dm_0;
    inout c1_dm_1;
    inout c1_dm_2;
    inout c1_dm_3;
    inout c1_dm_4;
    inout c1_dm_5;
    inout c1_dm_6;
    inout c1_dm_7;
    inout c1_dq_0;
    inout c1_dq_1;
    inout c1_dq_10;
    inout c1_dq_11;
    inout c1_dq_12;
    inout c1_dq_13;
    inout c1_dq_14;
    inout c1_dq_15;
    inout c1_dq_16;
    inout c1_dq_17;
    inout c1_dq_18;
    inout c1_dq_19;
    inout c1_dq_2;
    inout c1_dq_20;
    inout c1_dq_21;
    inout c1_dq_22;
    inout c1_dq_23;
    inout c1_dq_24;
    inout c1_dq_25;
    inout c1_dq_26;
    inout c1_dq_27;
    inout c1_dq_28;
    inout c1_dq_29;
    inout c1_dq_3;
    inout c1_dq_30;
    inout c1_dq_31;
    inout c1_dq_32;
    inout c1_dq_33;
    inout c1_dq_34;
    inout c1_dq_35;
    inout c1_dq_36;
    inout c1_dq_37;
    inout c1_dq_38;
    inout c1_dq_39;
    inout c1_dq_4;
    inout c1_dq_40;
    inout c1_dq_41;
    inout c1_dq_42;
    inout c1_dq_43;
    inout c1_dq_44;
    inout c1_dq_45;
    inout c1_dq_46;
    inout c1_dq_47;
    inout c1_dq_48;
    inout c1_dq_49;
    inout c1_dq_5;
    inout c1_dq_50;
    inout c1_dq_51;
    inout c1_dq_52;
    inout c1_dq_53;
    inout c1_dq_54;
    inout c1_dq_55;
    inout c1_dq_56;
    inout c1_dq_57;
    inout c1_dq_58;
    inout c1_dq_59;
    inout c1_dq_6;
    inout c1_dq_60;
    inout c1_dq_61;
    inout c1_dq_62;
    inout c1_dq_63;
    inout c1_dq_7;
    inout c1_dq_8;
    inout c1_dq_9;
    inout c1_dqs_0;
    inout c1_dqs_1;
    inout c1_dqs_2;
    inout c1_dqs_3;
    inout c1_dqs_4;
    inout c1_dqs_5;
    inout c1_dqs_6;
    inout c1_dqs_7;
    inout c1_dqsn_0;
    inout c1_dqsn_1;
    inout c1_dqsn_2;
    inout c1_dqsn_3;
    inout c1_dqsn_4;
    inout c1_dqsn_5;
    inout c1_dqsn_6;
    inout c1_dqsn_7;
    inout c1_odt;
    inout c1_ras;
    inout c1_rst;
    inout c1_we;
    inout c1_zq1;
    inout c1_zq2;
    inout clk_fp_n;
    inout clk_fp_p;
    inout cpu_addr0;
    inout cpu_addr1;
    inout cpu_addr10;
    inout cpu_addr11;
    inout cpu_addr12;
    inout cpu_addr13;
    inout cpu_addr14;
    inout cpu_addr15;
    inout cpu_addr2;
    inout cpu_addr3;
    inout cpu_addr4;
    inout cpu_addr5;
    inout cpu_addr6;
    inout cpu_addr7;
    inout cpu_addr8;
    inout cpu_addr9;
    inout cpu_cs_b;
    inout cpu_data0;
    inout cpu_data1;
    inout cpu_data10;
    inout cpu_data11;
    inout cpu_data12;
    inout cpu_data13;
    inout cpu_data14;
    inout cpu_data15;
    inout cpu_data2;
    inout cpu_data3;
    inout cpu_data4;
    inout cpu_data5;
    inout cpu_data6;
    inout cpu_data7;
    inout cpu_data8;
    inout cpu_data9;
    inout cpu_intb;
    inout cpu_rd_b;
    inout cpu_wr_b;
    inout ddr0_ref_clk;
    inout ddr1_ref_clk;
    inout ex_refclk_n0;
    inout ex_refclk_n1;
    inout ex_refclk_p0;
    inout ex_refclk_p1;
    inout ex_sd_rxn0;
    inout ex_sd_rxn1;
    inout ex_sd_rxn2;
    inout ex_sd_rxn3;
    inout ex_sd_rxn4;
    inout ex_sd_rxn5;
    inout ex_sd_rxn6;
    inout ex_sd_rxn7;
    inout ex_sd_rxp0;
    inout ex_sd_rxp1;
    inout ex_sd_rxp2;
    inout ex_sd_rxp3;
    inout ex_sd_rxp4;
    inout ex_sd_rxp5;
    inout ex_sd_rxp6;
    inout ex_sd_rxp7;
    inout ex_sd_txn0;
    inout ex_sd_txn1;
    inout ex_sd_txn2;
    inout ex_sd_txn3;
    inout ex_sd_txn4;
    inout ex_sd_txn5;
    inout ex_sd_txn6;
    inout ex_sd_txn7;
    inout ex_sd_txp0;
    inout ex_sd_txp1;
    inout ex_sd_txp2;
    inout ex_sd_txp3;
    inout ex_sd_txp4;
    inout ex_sd_txp5;
    inout ex_sd_txp6;
    inout ex_sd_txp7;
    input gnd1_1;
    input gnd1_10;
    input gnd1_100;
    input gnd1_101;
    input gnd1_102;
    input gnd1_103;
    input gnd1_104;
    input gnd1_105;
    input gnd1_106;
    input gnd1_107;
    input gnd1_108;
    input gnd1_109;
    input gnd1_11;
    input gnd1_110;
    input gnd1_111;
    input gnd1_112;
    input gnd1_113;
    input gnd1_114;
    input gnd1_115;
    input gnd1_116;
    input gnd1_117;
    input gnd1_12;
    input gnd1_13;
    input gnd1_14;
    input gnd1_15;
    input gnd1_16;
    input gnd1_17;
    input gnd1_18;
    input gnd1_19;
    input gnd1_2;
    input gnd1_20;
    input gnd1_21;
    input gnd1_22;
    input gnd1_23;
    input gnd1_24;
    input gnd1_25;
    input gnd1_26;
    input gnd1_27;
    input gnd1_28;
    input gnd1_29;
    input gnd1_3;
    input gnd1_30;
    input gnd1_31;
    input gnd1_32;
    input gnd1_33;
    input gnd1_34;
    input gnd1_35;
    input gnd1_36;
    input gnd1_37;
    input gnd1_38;
    input gnd1_39;
    input gnd1_4;
    input gnd1_40;
    input gnd1_41;
    input gnd1_42;
    input gnd1_43;
    input gnd1_44;
    input gnd1_45;
    input gnd1_46;
    input gnd1_47;
    input gnd1_48;
    input gnd1_49;
    input gnd1_5;
    input gnd1_50;
    input gnd1_51;
    input gnd1_52;
    input gnd1_53;
    input gnd1_54;
    input gnd1_55;
    input gnd1_56;
    input gnd1_57;
    input gnd1_58;
    input gnd1_59;
    input gnd1_6;
    input gnd1_60;
    input gnd1_61;
    input gnd1_62;
    input gnd1_63;
    input gnd1_64;
    input gnd1_65;
    input gnd1_66;
    input gnd1_67;
    input gnd1_68;
    input gnd1_69;
    input gnd1_7;
    input gnd1_70;
    input gnd1_71;
    input gnd1_72;
    input gnd1_73;
    input gnd1_74;
    input gnd1_75;
    input gnd1_76;
    input gnd1_77;
    input gnd1_78;
    input gnd1_79;
    input gnd1_8;
    input gnd1_80;
    input gnd1_81;
    input gnd1_82;
    input gnd1_83;
    input gnd1_84;
    input gnd1_85;
    input gnd1_86;
    input gnd1_87;
    input gnd1_88;
    input gnd1_89;
    input gnd1_9;
    input gnd1_90;
    input gnd1_91;
    input gnd1_92;
    input gnd1_93;
    input gnd1_94;
    input gnd1_95;
    input gnd1_96;
    input gnd1_97;
    input gnd1_98;
    input gnd1_99;
    input gnd2_1;
    input gnd2_10;
    input gnd2_11;
    input gnd2_12;
    input gnd2_13;
    input gnd2_14;
    input gnd2_15;
    input gnd2_16;
    input gnd2_17;
    input gnd2_18;
    input gnd2_19;
    input gnd2_2;
    input gnd2_20;
    input gnd2_21;
    input gnd2_22;
    input gnd2_23;
    input gnd2_24;
    input gnd2_25;
    input gnd2_26;
    input gnd2_27;
    input gnd2_28;
    input gnd2_29;
    input gnd2_3;
    input gnd2_4;
    input gnd2_5;
    input gnd2_6;
    input gnd2_7;
    input gnd2_8;
    input gnd2_9;
    input gnd3_1;
    input gnd3_10;
    input gnd3_11;
    input gnd3_12;
    input gnd3_13;
    input gnd3_14;
    input gnd3_15;
    input gnd3_16;
    input gnd3_17;
    input gnd3_18;
    input gnd3_19;
    input gnd3_2;
    input gnd3_20;
    input gnd3_21;
    input gnd3_22;
    input gnd3_23;
    input gnd3_24;
    input gnd3_25;
    input gnd3_26;
    input gnd3_27;
    input gnd3_28;
    input gnd3_29;
    input gnd3_3;
    input gnd3_30;
    input gnd3_31;
    input gnd3_32;
    input gnd3_33;
    input gnd3_34;
    input gnd3_35;
    input gnd3_36;
    input gnd3_37;
    input gnd3_38;
    input gnd3_39;
    input gnd3_4;
    input gnd3_40;
    input gnd3_41;
    input gnd3_42;
    input gnd3_43;
    input gnd3_44;
    input gnd3_45;
    input gnd3_46;
    input gnd3_47;
    input gnd3_48;
    input gnd3_49;
    input gnd3_5;
    input gnd3_50;
    input gnd3_51;
    input gnd3_52;
    input gnd3_53;
    input gnd3_54;
    input gnd3_55;
    input gnd3_56;
    input gnd3_57;
    input gnd3_58;
    input gnd3_59;
    input gnd3_6;
    input gnd3_60;
    input gnd3_61;
    input gnd3_62;
    input gnd3_63;
    input gnd3_64;
    input gnd3_65;
    input gnd3_66;
    input gnd3_67;
    input gnd3_68;
    input gnd3_69;
    input gnd3_7;
    input gnd3_70;
    input gnd3_71;
    input gnd3_72;
    input gnd3_73;
    input gnd3_74;
    input gnd3_75;
    input gnd3_76;
    input gnd3_77;
    input gnd3_78;
    input gnd3_79;
    input gnd3_8;
    input gnd3_80;
    input gnd3_9;
    input gnd4_1;
    input gnd4_10;
    input gnd4_11;
    input gnd4_12;
    input gnd4_13;
    input gnd4_14;
    input gnd4_15;
    input gnd4_16;
    input gnd4_17;
    input gnd4_18;
    input gnd4_19;
    input gnd4_2;
    input gnd4_20;
    input gnd4_21;
    input gnd4_22;
    input gnd4_23;
    input gnd4_24;
    input gnd4_25;
    input gnd4_26;
    input gnd4_27;
    input gnd4_28;
    input gnd4_29;
    input gnd4_3;
    input gnd4_30;
    input gnd4_31;
    input gnd4_32;
    input gnd4_33;
    input gnd4_34;
    input gnd4_35;
    input gnd4_36;
    input gnd4_37;
    input gnd4_38;
    input gnd4_39;
    input gnd4_4;
    input gnd4_40;
    input gnd4_41;
    input gnd4_42;
    input gnd4_43;
    input gnd4_44;
    input gnd4_45;
    input gnd4_46;
    input gnd4_47;
    input gnd4_48;
    input gnd4_49;
    input gnd4_5;
    input gnd4_50;
    input gnd4_51;
    input gnd4_52;
    input gnd4_53;
    input gnd4_54;
    input gnd4_6;
    input gnd4_7;
    input gnd4_8;
    input gnd4_9;
    input gnd5_1;
    input gnd5_2;
    input gnd5_3;
    input gnd5_4;
    input gnd5_5;
    input gnd5_6;
    input gnd5_7;
    input gnd6_1;
    input gnd6_10;
    input gnd6_11;
    input gnd6_12;
    input gnd6_13;
    input gnd6_14;
    input gnd6_15;
    input gnd6_16;
    input gnd6_17;
    input gnd6_2;
    input gnd6_3;
    input gnd6_4;
    input gnd6_5;
    input gnd6_6;
    input gnd6_7;
    input gnd6_8;
    input gnd6_9;
    input gnd7_1;
    input gnd7_10;
    input gnd7_11;
    input gnd7_12;
    input gnd7_13;
    input gnd7_14;
    input gnd7_15;
    input gnd7_16;
    input gnd7_17;
    input gnd7_18;
    input gnd7_19;
    input gnd7_2;
    input gnd7_20;
    input gnd7_21;
    input gnd7_22;
    input gnd7_23;
    input gnd7_24;
    input gnd7_25;
    input gnd7_26;
    input gnd7_27;
    input gnd7_28;
    input gnd7_3;
    input gnd7_4;
    input gnd7_5;
    input gnd7_6;
    input gnd7_7;
    input gnd7_8;
    input gnd7_9;
    inout gpon0_bcdr_rest;
    inout gpon0_opt_rst_o;
    inout gpon0_opt_sd_i;
    inout gpon0_otdr_trig_o;
    inout gpon0_otdr_vld_o;
    inout gpon0_pontxdis_o;
    inout gpon0_rssi_o;
    inout gpon0_rxclk_rxn;
    inout gpon0_rxclk_rxp;
    inout gpon0_tocpld_opt_rst_o;
    inout gpon0_tocpld_opt_sd_o;
    inout gpon1_bcdr_rest;
    inout gpon1_opt_rst_o;
    inout gpon1_opt_sd_i;
    inout gpon1_otdr_trig_o;
    inout gpon1_otdr_vld_o;
    inout gpon1_pontxdis_o;
    inout gpon1_rssi_o;
    inout gpon1_rxclk_rxn;
    inout gpon1_rxclk_rxp;
    inout gpon1_tocpld_opt_rst_o;
    inout gpon1_tocpld_opt_sd_o;
    inout gpon2_opt_rst_o;
    inout gpon2_opt_sd_i;
    inout gpon2_otdr_trig_o;
    inout gpon2_otdr_vld_o;
    inout gpon2_pontxdis_o;
    inout gpon2_rssi_o;
    inout gpon2_tocpld_opt_rst_o;
    inout gpon2_tocpld_opt_sd_o;
    inout gpon3_opt_rst_o;
    inout gpon3_opt_sd_i;
    inout gpon3_otdr_trig_o;
    inout gpon3_otdr_vld_o;
    inout gpon3_pontxdis_o;
    inout gpon3_rssi_o;
    inout gpon3_tocpld_opt_rst_o;
    inout gpon3_tocpld_opt_sd_o;
    inout gpon4_opt_rst_o;
    inout gpon4_opt_sd_i;
    inout gpon4_otdr_trig_o;
    inout gpon4_otdr_vld_o;
    inout gpon4_pontxdis_o;
    inout gpon4_rssi_o;
    inout gpon4_tocpld_opt_rst_o;
    inout gpon4_tocpld_opt_sd_o;
    inout gpon5_opt_rst_o;
    inout gpon5_opt_sd_i;
    inout gpon5_otdr_trig_o;
    inout gpon5_otdr_vld_o;
    inout gpon5_pontxdis_o;
    inout gpon5_rssi_o;
    inout gpon5_tocpld_opt_rst_o;
    inout gpon5_tocpld_opt_sd_o;
    inout gpon6_opt_rst_o;
    inout gpon6_opt_sd_i;
    inout gpon6_otdr_trig_o;
    inout gpon6_otdr_vld_o;
    inout gpon6_pontxdis_o;
    inout gpon6_rssi_o;
    inout gpon6_tocpld_opt_rst_o;
    inout gpon6_tocpld_opt_sd_o;
    inout gpon7_opt_rst_o;
    inout gpon7_opt_sd_i;
    inout gpon7_otdr_trig_o;
    inout gpon7_otdr_vld_o;
    inout gpon7_pontxdis_o;
    inout gpon7_rssi_o;
    inout gpon7_tocpld_opt_rst_o;
    inout gpon7_tocpld_opt_sd_o;
    inout gpon_refclk_n;
    inout gpon_refclk_p;
    inout gpon_rxd_n0;
    inout gpon_rxd_n1;
    inout gpon_rxd_n2;
    inout gpon_rxd_n5;
    inout gpon_rxd_n6;
    inout gpon_rxd_n7;
    inout gpon_rxd_p0;
    inout gpon_rxd_p1;
    inout gpon_rxd_p2;
    inout gpon_rxd_p5;
    inout gpon_rxd_p6;
    inout gpon_rxd_p7;
    inout gpon_txd_n0;
    inout gpon_txd_n1;
    inout gpon_txd_n2;
    inout gpon_txd_n5;
    inout gpon_txd_n6;
    inout gpon_txd_n7;
    inout gpon_txd_p0;
    inout gpon_txd_p1;
    inout gpon_txd_p2;
    inout gpon_txd_p5;
    inout gpon_txd_p6;
    inout gpon_txd_p7;
    inout hw_clk;
    inout hw_fp;
    inout hw_rx;
    inout hw_tx;
    inout jtag_tck;
    inout jtag_tdi;
    inout jtag_tdo;
    inout jtag_tms;
    inout jtag_trst;
    inout k_test;
    inout master_slave_select;
    inout ms_fp;
    inout pad_amon_pcie;
    inout pad_amon_xaui0;
    inout pad_amon_xaui1;
    inout pad_amon_xaui2;
    inout pad_amon_xaui3;
    inout pad_rbias_pcie;
    inout pad_rbias_xaui0;
    inout pad_rbias_xaui1;
    inout pad_rbias_xaui2;
    inout pad_rbias_xaui3;
    inout pcie_local_select;
    inout pcie_refclk_n;
    inout pcie_refclk_p;
    inout pcie_rxd_n0;
    inout pcie_rxd_p0;
    inout pcie_txd_n0;
    inout pcie_txd_p0;
    input pll311_ahvdd;
    input pll311_ahvss;
    input pll311_dvdd;
    input pll311_dvss;
    input pll312_ahvdd;
    input pll312_ahvss;
    input pll312_dvdd;
    input pll312_dvss;
    input [1:0] pll_vdd;
    inout ref_clk0;
    inout reset_b;
    inout rext_pmc;
    input [100:0] vdd115a;
    input [31:0] vdd115b;
    input [11:0] vdd115c;
    input [31:0] vdd115d;
    input [1:0] vdd115e;
    input [1:0] vdd115f;
    input [27:0] vdd15a;
    input [26:0] vdd15b;
    input [3:0] vdd25a;
    input vdd25b;
    input [13:0] vdd33a;
    input [5:0] vdd33b;
    inout vref1_ag10;
    inout vref1_ag9;
    inout vref1_al7;
    inout vref1_w1;
    inout vref2_a16;
    inout vref2_g4;
    inout vref2_j8;
    inout vref2_k8;
    inout vref_atst_bgr;
    inout x10_fp;
    inout x11_fp;
    inout xgpon0_bcdr_rest;
    inout xgpon0_rxclk_rxn;
    inout xgpon0_rxclk_rxp;
    inout xgpon0_rxpd_n0;
    inout xgpon0_rxpd_n1;
    inout xgpon0_rxpd_n2;
    inout xgpon0_rxpd_n3;
    inout xgpon0_rxpd_n4;
    inout xgpon0_rxpd_n5;
    inout xgpon0_rxpd_n6;
    inout xgpon0_rxpd_n7;
    inout xgpon0_rxpd_p0;
    inout xgpon0_rxpd_p1;
    inout xgpon0_rxpd_p2;
    inout xgpon0_rxpd_p3;
    inout xgpon0_rxpd_p4;
    inout xgpon0_rxpd_p5;
    inout xgpon0_rxpd_p6;
    inout xgpon0_rxpd_p7;
    inout xgpon1_bcdr_rest;
    inout xgpon1_rxclk_rxn;
    inout xgpon1_rxclk_rxp;
    inout xgpon1_rxpd_n0;
    inout xgpon1_rxpd_n1;
    inout xgpon1_rxpd_n2;
    inout xgpon1_rxpd_n3;
    inout xgpon1_rxpd_n4;
    inout xgpon1_rxpd_n5;
    inout xgpon1_rxpd_n6;
    inout xgpon1_rxpd_n7;
    inout xgpon1_rxpd_p0;
    inout xgpon1_rxpd_p1;
    inout xgpon1_rxpd_p2;
    inout xgpon1_rxpd_p3;
    inout xgpon1_rxpd_p4;
    inout xgpon1_rxpd_p5;
    inout xgpon1_rxpd_p6;
    inout xgpon1_rxpd_p7;
    inout xgpon_rxd_n3;
    inout xgpon_rxd_n4;
    inout xgpon_rxd_p3;
    inout xgpon_rxd_p4;
    inout xgpon_txd_n3;
    inout xgpon_txd_n4;
    inout xgpon_txd_p3;
    inout xgpon_txd_p4;


    initial
        begin
        end

endmodule
