// generated by newgenasym  Mon Mar 25 15:23:03 2024


module \ss05-4r  (gnd, \i/o1 , \i/o2 , \i/o3 , \i/o4 , vdd);
    inout gnd;
    inout \i/o1 ;
    inout \i/o2 ;
    inout \i/o3 ;
    inout \i/o4 ;
    inout vdd;


    initial
        begin
        end

endmodule
