-- generated by newgenasym Mon Mar 25 15:23:03 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ss05-4r\ is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\i/o1\:    INOUT  STD_LOGIC;    
	\i/o2\:    INOUT  STD_LOGIC;    
	\i/o3\:    INOUT  STD_LOGIC;    
	\i/o4\:    INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end \ss05-4r\;
