// generated by newgenasym  Fri Dec 18 11:06:51 2020


module pef3100x (cdcn, cdcp, cin, cout, cref, csq, dclk, din, dout, epad_gnd,
        fcs, fss, gpio0, gpio1, int, isense, mr, mt, nc1, nc2, nc3, pclk,
        reg_mode, reg_out, resetq, ring, rxd, sel, swd, test, tip, txd,
        vdd15_1, vdd15_2, vdd15p, vdd1v5_1, vdd1v5_2, vdd33_1,
        vdd33_2, vdd3v3, vddp33_1, vddp33_2, vddswd, vn, vsense);
    input cdcn;
    input cdcp;
    output cin;
    output cout;
    input cref;
    input csq;
    input dclk;
    input din;
    input dout;
    inout epad_gnd;
    input fcs;
    input fss;
    input gpio0;
    input gpio1;
    input int;
    output isense;
    input mr;
    input mt;
    inout nc1;
    inout nc2;
    inout nc3;
    output pclk;
    input reg_mode;
    input reg_out;
    output resetq;
    output ring;
    output rxd;
    input sel;
    input swd;
    input test;
    output tip;
    input txd;
    input vdd15_1;
    input vdd15_2;
    output vdd15p;
    input vdd1v5_1;
    input vdd1v5_2;
    input vdd33_1;
    input vdd33_2;
    input vdd3v3;
    input vddp33_1;
    input vddp33_2;
    output vddswd;
    input vn;
    input vsense;


    initial
        begin
        end

endmodule
