-- generated by newgenasym Sun Sep 26 15:30:05 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fm15l023uk6 is
    port (    
	\adc_in0/beeper1_1/gpt0_etr0/wkup6/pc5\: INOUT  STD_LOGIC;    
	\adc_in1/spi1_miso1/gpt0_ch3_0/pc7\: INOUT  STD_LOGIC;    
	\adc_in7/spi1_mosi1/gpt0_ch4_0/pc6\: INOUT  STD_LOGIC;    
	\adc_in8/spi1_sck_1/gpt0_ch2_0/pc8\: INOUT  STD_LOGIC;    
	\anatst/fout0_0/wkup7/pc10\: INOUT  STD_LOGIC;    
	EPAD:      IN     STD_LOGIC;    
	NRST:      INOUT  STD_LOGIC;    
	\pa10/i2c_scl0\: INOUT  STD_LOGIC;    
	\pa11/i2c_sda0/fout1_1\: INOUT  STD_LOGIC;    
	\pa12/uart1_rx0/lpuart0_rx1\: INOUT  STD_LOGIC;    
	\pa13/uart1_tx0/lpuart0_tx1\: INOUT  STD_LOGIC;    
	\pb0/spi1_ssn0/gpt0_ch1_1\: INOUT  STD_LOGIC;    
	\pb1/spi1_sck0/gpt0_ch2_1\: INOUT  STD_LOGIC;    
	\pb2/spi1_miso0/gpt0_ch3_1\: INOUT  STD_LOGIC;    
	\pb3/spi1_mosi0/gpt0_ch4_1\: INOUT  STD_LOGIC;    
	\pb7/uart5_tx0/lpt32_etr1\: INOUT  STD_LOGIC;    
	\pb8/xthin/uart1_tx1\: INOUT  STD_LOGIC;    
	\pb9/xthout/uart1_rx1\: INOUT  STD_LOGIC;    
	\pc0/wkup5/debug_4_1/adc_in13\: INOUT  STD_LOGIC;    
	\pc1/uart4_tx0/lpt32_ch2_1/adc_in11\: INOUT  STD_LOGIC;    
	\pc2/uart4_rx0/lpt32_ch1_1/adc_in4\: INOUT  STD_LOGIC;    
	\pc3/xt32ko\: INOUT  STD_LOGIC;    
	\pc4/xt32ki\: INOUT  STD_LOGIC;    
	\spi2_miso1/lpt32_ch1_0/pa7\: INOUT  STD_LOGIC;    
	\spi2_mosi1/beeper2_0/pa4\: INOUT  STD_LOGIC;    
	\spi2_sck1/7816io0/pa3\: INOUT  STD_LOGIC;    
	\spi2_ssn1/7816clk0/wkup0/pa2\: INOUT  STD_LOGIC;    
	\uart0_rx1/lpuart0_rx0/pa5\: INOUT  STD_LOGIC;    
	\uart0_tx1/lpuart0_tx0/pa6\: INOUT  STD_LOGIC;    
	\uart5_rx1/swclk0/pc11\: INOUT  STD_LOGIC;    
	\uart5_tx1/swio0/pc12\: INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VDD15:     INOUT  STD_LOGIC);
end fm15l023uk6;
