// generated by newgenasym  Tue Dec 15 09:37:25 2020


module rtl8192xar (chip_en, clkreqn, eecs, eesk, epad, gnd_hci, gnd_sps,
        gnd_sps_ana, gpio0, gpio1, gpio11, gpio14, gpio2, gpio3,
        gpio4, gpio5, gpio6, gpio7, \gpio_12/host_wake_wl ,
        \gpio_9/wl_dis , hsin, hsip, hson, hsop, ldo_v13_phy_i,
        lx_sps_ana, lx_sps_v10, lx_sps_v10_o_1, nc_1, nc_2, nc_3,
        nc_4, nc_5, nc_6, nc_7, nc_8, nc_9, perstn, refclk_n,
        refclk_p, rfi_wl2g_s0, rfi_wl2g_s1, rfio_wl2g_s0,
        rfio_wl2g_s1, rref, tssi_s0, tssi_s1, vd10_hci, vd10_vddtx,
        vd10d_wl, vd10d_wlbb_right, vd10d_wlbb_top, vd13_afe,
        vd13_pwr, vd13_syn_p0, vd13_trx_s0, vd13_trx_s1, vd33_io,
        vd33_ldo_wl, vd33_pa_s0, vd33_pa_s1, vd33_pwr,
        vd33_syn_p0, vd33_syn_p1, vd33_tx2g_s0, vd33_tx2g_s1,
        vd33_tx_s0, vd33_tx_s1, vd33sps, vd33sps_ana, vd33x,
        vdd_io, vfb, waken, \wl_led/gpio_8 , xi, xo);
    input chip_en;
    inout clkreqn;
    input eecs;
    input eesk;
    input epad;
    input gnd_hci;
    input gnd_sps;
    input gnd_sps_ana;
    inout gpio0;
    inout gpio1;
    inout gpio11;
    inout gpio14;
    inout gpio2;
    inout gpio3;
    inout gpio4;
    inout gpio5;
    inout gpio6;
    inout gpio7;
    inout \gpio_12/host_wake_wl ;
    inout \gpio_9/wl_dis ;
    input hsin;
    input hsip;
    output hson;
    output hsop;
    input ldo_v13_phy_i;
    input lx_sps_ana;
    input lx_sps_v10;
    input lx_sps_v10_o_1;
    inout nc_1;
    inout nc_2;
    inout nc_3;
    inout nc_4;
    inout nc_5;
    inout nc_6;
    inout nc_7;
    inout nc_8;
    inout nc_9;
    input perstn;
    input refclk_n;
    input refclk_p;
    inout rfi_wl2g_s0;
    inout rfi_wl2g_s1;
    inout rfio_wl2g_s0;
    inout rfio_wl2g_s1;
    inout rref;
    input tssi_s0;
    input tssi_s1;
    input vd10_hci;
    input vd10_vddtx;
    input vd10d_wl;
    input vd10d_wlbb_right;
    input vd10d_wlbb_top;
    input vd13_afe;
    input vd13_pwr;
    input vd13_syn_p0;
    input vd13_trx_s0;
    input vd13_trx_s1;
    input vd33_io;
    input vd33_ldo_wl;
    input vd33_pa_s0;
    input vd33_pa_s1;
    input vd33_pwr;
    input vd33_syn_p0;
    input vd33_syn_p1;
    input vd33_tx2g_s0;
    input vd33_tx2g_s1;
    input vd33_tx_s0;
    input vd33_tx_s1;
    input vd33sps;
    input vd33sps_ana;
    input vd33x;
    input vdd_io;
    input vfb;
    output waken;
    inout \wl_led/gpio_8 ;
    input xi;
    output xo;


    initial
        begin
        end

endmodule
