-- generated by newgenasym Thu Sep 08 13:42:15 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fem_2g is
    port (    
	ANT:       INOUT  STD_LOGIC;    
	BT:        INOUT  STD_LOGIC;    
	C_RX:      INOUT  STD_LOGIC;    
	CBT:       INOUT  STD_LOGIC;    
	EPAD:      INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	LNA_EN:    INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       IN     STD_LOGIC;    
	NC4:       IN     STD_LOGIC;    
	PA_EN:     INOUT  STD_LOGIC;    
	RX:        INOUT  STD_LOGIC;    
	TX:        INOUT  STD_LOGIC;    
	VBT:       OUT    STD_LOGIC;    
	VCC1:      INOUT  STD_LOGIC;    
	VCC2:      INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VDET:      INOUT  STD_LOGIC;    
	VRX:       OUT    STD_LOGIC;    
	VTX:       OUT    STD_LOGIC);
end fem_2g;
