// generated by newgenasym  Mon Aug 31 14:15:14 2020


module pcf8591 (a0, a1, a2, agnd, ain0, ain1, ain2, ain3, aout, ext, osc, scl,
        sda, vdd, vref, vss);
    input a0;
    input a1;
    input a2;
    input agnd;
    input ain0;
    input ain1;
    input ain2;
    input ain3;
    output aout;
    input ext;
    inout osc;
    input scl;
    inout sda;
    input vdd;
    input vref;
    input vss;


    initial
        begin
        end

endmodule
