-- generated by newgenasym Mon Aug 31 14:15:14 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pcf8591 is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	AGND:      IN     STD_LOGIC;    
	AIN0:      IN     STD_LOGIC;    
	AIN1:      IN     STD_LOGIC;    
	AIN2:      IN     STD_LOGIC;    
	AIN3:      IN     STD_LOGIC;    
	AOUT:      OUT    STD_LOGIC;    
	EXT:       IN     STD_LOGIC;    
	OSC:       INOUT  STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VREF:      IN     STD_LOGIC;    
	VSS:       IN     STD_LOGIC);
end pcf8591;
