// generated by newgenasym  Mon Dec 19 13:38:22 2022


module rtc7646 (ant, c0, c1, gnd, gnd_1, gnd_2, gnd_3, gnd_4, gnd_5, pa_en,
        pgnd, rx, tx, vcc1, vcc2, vdd, vdet);
    inout ant;
    inout c0;
    inout c1;
    inout gnd;
    inout gnd_1;
    inout gnd_2;
    inout gnd_3;
    inout gnd_4;
    inout gnd_5;
    input pa_en;
    inout pgnd;
    inout rx;
    inout tx;
    inout vcc1;
    input vcc2;
    inout vdd;
    inout vdet;


    initial
        begin
        end

endmodule
