// generated by newgenasym  Wed Nov 10 18:51:42 2021


module rtl8290b (avddh_apc, avddh_rx, avddh_tx, benp, biasp, cl_1, cl_2,
        comp, epad, fault, ibref, lasern, laserp, \loss/rx_sd , mpd,
        pwm, rssi, rxinn, rxinp, rxon, rxop, \sck_m/int , sck_s,
        \sda_m/rx_sleep , sda_s, txdis, txin, txip, txsd, vdd_ldi,
        vdd_ldx, vddh, vfb);
    input avddh_apc;
    input avddh_rx;
    input avddh_tx;
    input benp;
    output biasp;
    input cl_1;
    input cl_2;
    input comp;
    input epad;
    output fault;
    input ibref;
    output lasern;
    output laserp;
    output \loss/rx_sd ;
    input mpd;
    output pwm;
    input rssi;
    input rxinn;
    input rxinp;
    output rxon;
    output rxop;
    output \sck_m/int ;
    input sck_s;
    inout \sda_m/rx_sleep ;
    inout sda_s;
    input txdis;
    input txin;
    input txip;
    output txsd;
    input vdd_ldi;
    input vdd_ldx;
    input vddh;
    input vfb;


    initial
        begin
        end

endmodule
