-- generated by newgenasym Mon Aug 31 13:54:31 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fem_5g is
    port (    
	ANT:       INOUT  STD_LOGIC;    
	C_RX:      INOUT  STD_LOGIC;    
	EPAD:      INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	LNA_EN:    INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	PA_EN:     INOUT  STD_LOGIC;    
	PDET:      INOUT  STD_LOGIC;    
	RX:        INOUT  STD_LOGIC;    
	TX:        INOUT  STD_LOGIC;    
	VCC1:      INOUT  STD_LOGIC;    
	VCC2:      INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end fem_5g;
