// generated by newgenasym  Wed Nov 29 16:26:17 2023


module prx126a1bi (clk_md, ddr_a0, ddr_a1, ddr_a10, ddr_a11, ddr_a12, ddr_a13,
        ddr_a14, ddr_a15, ddr_a16, ddr_a2, ddr_a3, ddr_a4, ddr_a5,
        ddr_a6, ddr_a7, ddr_a8, ddr_a9, ddr_act_n, ddr_alert_n,
        ddr_ato, ddr_ba0, ddr_ba1, ddr_bg0, ddr_bg1, ddr_ck_c,
        ddr_ck_t, ddr_cke0, ddr_cke1, ddr_cs0_n, ddr_cs1_n,
        ddr_dm0_n, ddr_dm1_n, ddr_dm2_n, ddr_dm3_n, ddr_dq0,
        ddr_dq1, ddr_dq10, ddr_dq11, ddr_dq12, ddr_dq13, ddr_dq14,
        ddr_dq15, ddr_dq16, ddr_dq17, ddr_dq18, ddr_dq19, ddr_dq2,
        ddr_dq20, ddr_dq21, ddr_dq22, ddr_dq23, ddr_dq24, ddr_dq25,
        ddr_dq26, ddr_dq27, ddr_dq28, ddr_dq29, ddr_dq3, ddr_dq30,
        ddr_dq31, ddr_dq4, ddr_dq5, ddr_dq6, ddr_dq7, ddr_dq8,
        ddr_dq9, ddr_dqs0_c, ddr_dqs0_t, ddr_dqs1_c, ddr_dqs1_t,
        ddr_dqs2_c, ddr_dqs2_t, ddr_dqs3_c, ddr_dqs3_t, ddr_dto0,
        ddr_dto1, ddr_odt0, ddr_odt1, ddr_par, ddr_rst, ddr_vrefca,
        ddr_vrefdq0, ddr_vrefdq1, ddr_zq, gpio0, gpio1, gpio10,
        gpio11, gpio13, gpio15, gpio16, gpio2, gpio20, gpio21,
        gpio22, gpio23, gpio24, gpio25, gpio26, gpio27, gpio28,
        gpio29, gpio3, gpio30, gpio31, gpio4, gpio5, gpio8, hrst_n,
        opt_txen, p1_resref, p1_rxn, p1_rxp, p1_txn, p1_txp,
        p2_resref, p2_rxn, p2_rxp, p2_txn, p2_txp, por_n, reserved,
        tck, tdi, tdo, tms, trst_n, urxd0, utxd0, vaa0v9_pll,
        vaa0v9_pll5, vaa0v9_sphy1_0, vaa0v9_sphy1_1,
        vaa0v9_sphy2, vaa1v8_ddrpll_0, vaa1v8_ddrpll_1,
        vaa1v8_ddrpll_2, vaa1v8_otp, vaa1v8_pll, vaa1v8_pll5,
        vaa1v8_pvt_l, vaa1v8_pvt_r, vaa1v8_sphy1_0,
        vaa1v8_sphy1_1, vaa1v8_sphy2, vaa1v8_xo, vdd0v9_0,
        vdd0v9_1, vdd0v9_10, vdd0v9_11, vdd0v9_12, vdd0v9_13,
        vdd0v9_14, vdd0v9_15, vdd0v9_16, vdd0v9_17, vdd0v9_18,
        vdd0v9_19, vdd0v9_2, vdd0v9_20, vdd0v9_3, vdd0v9_4,
        vdd0v9_5, vdd0v9_6, vdd0v9_7, vdd0v9_8, vdd0v9_9, vdd_dg,
        vdd_io_0_0, vdd_io_0_1, vdd_io_1_0, vdd_io_1_1, vdd_io_2,
        vdd_io_3, vddq_0, vddq_1, vddq_10, vddq_11, vddq_2, vddq_3,
        vddq_4, vddq_5, vddq_6, vddq_7, vddq_8, vddq_9, vss_0, vss_1,
        vss_10, vss_11, vss_12, vss_13, vss_14, vss_15, vss_16,
        vss_17, vss_18, vss_19, vss_2, vss_20, vss_21, vss_22,
        vss_23, vss_24, vss_25, vss_26, vss_27, vss_28, vss_29,
        vss_3, vss_30, vss_31, vss_32, vss_33, vss_34, vss_35,
        vss_36, vss_37, vss_38, vss_39, vss_4, vss_40, vss_41,
        vss_42, vss_43, vss_44, vss_45, vss_46, vss_47, vss_48,
        vss_49, vss_5, vss_50, vss_51, vss_52, vss_53, vss_54,
        vss_55, vss_56, vss_57, vss_58, vss_59, vss_6, vss_60,
        vss_61, vss_62, vss_63, vss_64, vss_65, vss_66, vss_67,
        vss_68, vss_69, vss_7, vss_70, vss_71, vss_72, vss_73,
        vss_74, vss_75, vss_8, vss_9, vssa_sphy1_0, vssa_sphy1_1,
        vssa_sphy1_10, vssa_sphy1_11, vssa_sphy1_12,
        vssa_sphy1_2, vssa_sphy1_3, vssa_sphy1_4, vssa_sphy1_5,
        vssa_sphy1_6, vssa_sphy1_7, vssa_sphy1_8, vssa_sphy1_9,
        vssa_sphy2_0, vssa_sphy2_1, vssa_sphy2_2, vssa_sphy2_3,
        vssa_sphy2_4, vssa_sphy2_5, vssa_sphy2_6, vssa_xo_0,
        vssa_xo_1, xtal1, xtal2);
    input clk_md;
    output ddr_a0;
    output ddr_a1;
    output ddr_a10;
    output ddr_a11;
    output ddr_a12;
    output ddr_a13;
    output ddr_a14;
    output ddr_a15;
    output ddr_a16;
    output ddr_a2;
    output ddr_a3;
    output ddr_a4;
    output ddr_a5;
    output ddr_a6;
    output ddr_a7;
    output ddr_a8;
    output ddr_a9;
    output ddr_act_n;
    output ddr_alert_n;
    output ddr_ato;
    output ddr_ba0;
    output ddr_ba1;
    output ddr_bg0;
    output ddr_bg1;
    output ddr_ck_c;
    output ddr_ck_t;
    output ddr_cke0;
    output ddr_cke1;
    output ddr_cs0_n;
    output ddr_cs1_n;
    inout ddr_dm0_n;
    inout ddr_dm1_n;
    inout ddr_dm2_n;
    inout ddr_dm3_n;
    inout ddr_dq0;
    inout ddr_dq1;
    inout ddr_dq10;
    inout ddr_dq11;
    inout ddr_dq12;
    inout ddr_dq13;
    inout ddr_dq14;
    inout ddr_dq15;
    inout ddr_dq16;
    inout ddr_dq17;
    inout ddr_dq18;
    inout ddr_dq19;
    inout ddr_dq2;
    inout ddr_dq20;
    inout ddr_dq21;
    inout ddr_dq22;
    inout ddr_dq23;
    inout ddr_dq24;
    inout ddr_dq25;
    inout ddr_dq26;
    inout ddr_dq27;
    inout ddr_dq28;
    inout ddr_dq29;
    inout ddr_dq3;
    inout ddr_dq30;
    inout ddr_dq31;
    inout ddr_dq4;
    inout ddr_dq5;
    inout ddr_dq6;
    inout ddr_dq7;
    inout ddr_dq8;
    inout ddr_dq9;
    inout ddr_dqs0_c;
    inout ddr_dqs0_t;
    inout ddr_dqs1_c;
    inout ddr_dqs1_t;
    inout ddr_dqs2_c;
    inout ddr_dqs2_t;
    inout ddr_dqs3_c;
    inout ddr_dqs3_t;
    output ddr_dto0;
    output ddr_dto1;
    output ddr_odt0;
    output ddr_odt1;
    output ddr_par;
    output ddr_rst;
    output ddr_vrefca;
    output ddr_vrefdq0;
    output ddr_vrefdq1;
    input ddr_zq;
    inout gpio0;
    output gpio1;
    inout gpio10;
    inout gpio11;
    output gpio13;
    output gpio15;
    output gpio16;
    inout gpio2;
    inout gpio20;
    inout gpio21;
    inout gpio22;
    inout gpio23;
    inout gpio24;
    inout gpio25;
    inout gpio26;
    output gpio27;
    inout gpio28;
    inout gpio29;
    inout gpio3;
    inout gpio30;
    output gpio31;
    inout gpio4;
    inout gpio5;
    inout gpio8;
    output hrst_n;
    inout opt_txen;
    inout p1_resref;
    input p1_rxn;
    input p1_rxp;
    output p1_txn;
    output p1_txp;
    inout p2_resref;
    input p2_rxn;
    input p2_rxp;
    output p2_txn;
    output p2_txp;
    input por_n;
    inout reserved;
    input tck;
    input tdi;
    output tdo;
    input tms;
    input trst_n;
    input urxd0;
    output utxd0;
    input vaa0v9_pll;
    input vaa0v9_pll5;
    input vaa0v9_sphy1_0;
    input vaa0v9_sphy1_1;
    input vaa0v9_sphy2;
    input vaa1v8_ddrpll_0;
    input vaa1v8_ddrpll_1;
    input vaa1v8_ddrpll_2;
    input vaa1v8_otp;
    input vaa1v8_pll;
    input vaa1v8_pll5;
    input vaa1v8_pvt_l;
    input vaa1v8_pvt_r;
    input vaa1v8_sphy1_0;
    input vaa1v8_sphy1_1;
    input vaa1v8_sphy2;
    input vaa1v8_xo;
    input vdd0v9_0;
    input vdd0v9_1;
    input vdd0v9_10;
    input vdd0v9_11;
    input vdd0v9_12;
    input vdd0v9_13;
    input vdd0v9_14;
    input vdd0v9_15;
    input vdd0v9_16;
    input vdd0v9_17;
    input vdd0v9_18;
    input vdd0v9_19;
    input vdd0v9_2;
    input vdd0v9_20;
    input vdd0v9_3;
    input vdd0v9_4;
    input vdd0v9_5;
    input vdd0v9_6;
    input vdd0v9_7;
    input vdd0v9_8;
    input vdd0v9_9;
    input vdd_dg;
    input vdd_io_0_0;
    input vdd_io_0_1;
    input vdd_io_1_0;
    input vdd_io_1_1;
    input vdd_io_2;
    input vdd_io_3;
    input vddq_0;
    input vddq_1;
    input vddq_10;
    input vddq_11;
    input vddq_2;
    input vddq_3;
    input vddq_4;
    input vddq_5;
    input vddq_6;
    input vddq_7;
    input vddq_8;
    input vddq_9;
    input vss_0;
    input vss_1;
    input vss_10;
    input vss_11;
    input vss_12;
    input vss_13;
    input vss_14;
    input vss_15;
    input vss_16;
    input vss_17;
    input vss_18;
    input vss_19;
    input vss_2;
    input vss_20;
    input vss_21;
    input vss_22;
    input vss_23;
    input vss_24;
    input vss_25;
    input vss_26;
    input vss_27;
    input vss_28;
    input vss_29;
    input vss_3;
    input vss_30;
    input vss_31;
    input vss_32;
    input vss_33;
    input vss_34;
    input vss_35;
    input vss_36;
    input vss_37;
    input vss_38;
    input vss_39;
    input vss_4;
    input vss_40;
    input vss_41;
    input vss_42;
    input vss_43;
    input vss_44;
    input vss_45;
    input vss_46;
    input vss_47;
    input vss_48;
    input vss_49;
    input vss_5;
    input vss_50;
    input vss_51;
    input vss_52;
    input vss_53;
    input vss_54;
    input vss_55;
    input vss_56;
    input vss_57;
    input vss_58;
    input vss_59;
    input vss_6;
    input vss_60;
    input vss_61;
    input vss_62;
    input vss_63;
    input vss_64;
    input vss_65;
    input vss_66;
    input vss_67;
    input vss_68;
    input vss_69;
    input vss_7;
    input vss_70;
    input vss_71;
    input vss_72;
    input vss_73;
    input vss_74;
    input vss_75;
    input vss_8;
    input vss_9;
    input vssa_sphy1_0;
    input vssa_sphy1_1;
    input vssa_sphy1_10;
    input vssa_sphy1_11;
    input vssa_sphy1_12;
    input vssa_sphy1_2;
    input vssa_sphy1_3;
    input vssa_sphy1_4;
    input vssa_sphy1_5;
    input vssa_sphy1_6;
    input vssa_sphy1_7;
    input vssa_sphy1_8;
    input vssa_sphy1_9;
    input vssa_sphy2_0;
    input vssa_sphy2_1;
    input vssa_sphy2_2;
    input vssa_sphy2_3;
    input vssa_sphy2_4;
    input vssa_sphy2_5;
    input vssa_sphy2_6;
    input vssa_xo_0;
    input vssa_xo_1;
    input xtal1;
    output xtal2;


    initial
        begin
        end

endmodule
