// generated by newgenasym  Fri Dec 10 09:14:40 2021


module c_transformer (k1, k2, l1, l2);
    inout k1;
    inout k2;
    inout l1;
    inout l2;


    initial
        begin
        end

endmodule
