-- generated by newgenasym Fri Jan 15 17:36:26 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity diode is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	B3:        INOUT  STD_LOGIC;    
	C1:        INOUT  STD_LOGIC;    
	C2:        INOUT  STD_LOGIC;    
	C3:        INOUT  STD_LOGIC;    
	D1:        INOUT  STD_LOGIC;    
	D2:        INOUT  STD_LOGIC;    
	D3:        INOUT  STD_LOGIC;    
	E1:        INOUT  STD_LOGIC;    
	E2:        INOUT  STD_LOGIC);
end diode;
