-- generated by newgenasym Wed Nov 10 18:51:42 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rtl8290b is
    port (    
	AVDDH_APC: IN     STD_LOGIC;    
	AVDDH_RX:  IN     STD_LOGIC;    
	AVDDH_TX:  IN     STD_LOGIC;    
	BENP:      IN     STD_LOGIC;    
	BIASP:     OUT    STD_LOGIC;    
	CL_1:      IN     STD_LOGIC;    
	CL_2:      IN     STD_LOGIC;    
	COMP:      IN     STD_LOGIC;    
	EPAD:      IN     STD_LOGIC;    
	FAULT:     OUT    STD_LOGIC;    
	IBREF:     IN     STD_LOGIC;    
	LASERN:    OUT    STD_LOGIC;    
	LASERP:    OUT    STD_LOGIC;    
	\loss/rx_sd\: OUT    STD_LOGIC;    
	MPD:       IN     STD_LOGIC;    
	PWM:       OUT    STD_LOGIC;    
	RSSI:      IN     STD_LOGIC;    
	RXINN:     IN     STD_LOGIC;    
	RXINP:     IN     STD_LOGIC;    
	RXON:      OUT    STD_LOGIC;    
	RXOP:      OUT    STD_LOGIC;    
	\sck_m/int\: OUT    STD_LOGIC;    
	SCK_S:     IN     STD_LOGIC;    
	\sda_m/rx_sleep\: INOUT  STD_LOGIC;    
	SDA_S:     INOUT  STD_LOGIC;    
	TXDIS:     IN     STD_LOGIC;    
	TXIN:      IN     STD_LOGIC;    
	TXIP:      IN     STD_LOGIC;    
	TXSD:      OUT    STD_LOGIC;    
	VDD_LDI:   IN     STD_LOGIC;    
	VDD_LDX:   IN     STD_LOGIC;    
	VDDH:      IN     STD_LOGIC;    
	VFB:       IN     STD_LOGIC);
end rtl8290b;
