// generated by newgenasym  Tue Oct 08 11:29:48 2024


module tmi7608r (\2-event , \24v_en , ad0, ad1, ad2, agnd1, agnd10, agnd11, agnd2,
        agnd3, agnd4, agnd5, agnd6, agnd7, agnd8, agnd9, \alt_a/b ,
        auto, dgnd, dv3p3, \en_cl4+ , enb_reg, epad, intb, led_clk,
        led_dat, nc1, nc2, nc3, nc4, nc5, nc6, pmax, portn0, portn1,
        portn2, portn3, portn4, portn5, portn6, portn7, rstn,
        scan_mode, \scl/ee_clk , \sdai/ee_dat , sdao, v3p3, v54, vpp);
    input \2-event ;
    input \24v_en ;
    inout ad0;
    inout ad1;
    inout ad2;
    input agnd1;
    input agnd10;
    input agnd11;
    input agnd2;
    input agnd3;
    input agnd4;
    input agnd5;
    input agnd6;
    input agnd7;
    input agnd8;
    input agnd9;
    input \alt_a/b ;
    input auto;
    input dgnd;
    input dv3p3;
    input \en_cl4+ ;
    input enb_reg;
    input epad;
    output intb;
    output led_clk;
    output led_dat;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    input pmax;
    input portn0;
    input portn1;
    input portn2;
    input portn3;
    input portn4;
    input portn5;
    input portn6;
    input portn7;
    input rstn;
    input scan_mode;
    input \scl/ee_clk ;
    input \sdai/ee_dat ;
    output sdao;
    input v3p3;
    input v54;
    input vpp;


    initial
        begin
        end

endmodule
