-- generated by newgenasym Fri Aug 21 17:10:41 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity power_dip4 is
    port (    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	\vcc+\:    INOUT  STD_LOGIC;    
	\vcc-\:    INOUT  STD_LOGIC);
end power_dip4;
