// generated by newgenasym  Wed Nov 18 17:46:46 2020


module diplexer (g1, g2, g3, hf, lf, rf);
    inout g1;
    inout g2;
    inout g3;
    inout hf;
    inout lf;
    inout rf;


    initial
        begin
        end

endmodule
