// generated by newgenasym  Mon May 24 10:23:00 2021


module filter (gnd1, gnd2, gnd3, in, \input , out, \output );
    input gnd1;
    input gnd2;
    output gnd3;
    input in;
    inout \input ;
    output out;
    inout \output ;


    initial
        begin
        end

endmodule
