-- generated by newgenasym Mon May 24 10:23:00 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity filter is
    port (    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      OUT    STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	INPUT:     INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	OUTPUT:    INOUT  STD_LOGIC);
end filter;
