// generated by newgenasym  Fri Nov 12 15:21:17 2021


module rtl9601d (avddh1, avddh2, avddh3, avddl1, avddl2, avddl3, benp,
        \btup_typ/sled_ck/led16/gpio33 , cpupllvddl,
        \ddr_type/msi_clk24m/zpapck/gpio23 , ddrpllvddh,
        ddrpllvddl, \dis_jtag0/jtag0_tdo/gpio38 , \dis_tx/gpio02 ,
        dvddio1, dvddio2, dvddio3, dvddio4, dvddl1, dvddl2, dvddl3,
        dvddl4, dvddl5, dvddl6, dvddl7, dvddl8,
        \en_cpu/msif0_psdo/z0mosi/gpio24 , epad, ge_mdin0,
        ge_mdin1, ge_mdin2, ge_mdin3, ge_mdip0, ge_mdip1, ge_mdip2,
        ge_mdip3, ge_rset, \gpio03/tx_sd , \gpio04/tod ,
        \gpio05/gponpps , hsin, hsip, hson, hsop, hssd,
        \jtag0_ck/gpio36 , \jtag0_nrst/gpio40 , \jtag0_tdi/gpio39 ,
        \jtag0_tms/gpio37 , ldo_vddh, ldo_vout,
        \msif0_psdi/z0miso/gpio25 , nc, pe0_hsin, pe0_hsip,
        pe0_hson, pe0_hsop, pe0_refclk_m, pe0_refclk_p, pe0vddl,
        \sck1/led3/gpio09 , \sda1/led2/gpio08 ,
        \sled_da/led17/gpio35 , \spif_clk/rst_cmd_dis , spif_d0,
        spif_d1, spif_ncs, \spif_nrst/gpio57 , svddh, svddl,
        \sw_mdc/led5/gpio12 , \sw_mdio/led4/gpio10 , u0hsdm, u0hsdp,
        u0vddh, u0vddl, \urxd0/gpio42 , \urxd1/led13/gpio20 ,
        \utxd0/gpio41 , \utxd1/led14/gpio21 , vddq1, vddq2, vddq3,
        vddq4, vddq5, vref, xi, xo, \z0sync/gpio30 );
    input avddh1;
    input avddh2;
    input avddh3;
    input avddl1;
    input avddl2;
    input avddl3;
    input benp;
    inout \btup_typ/sled_ck/led16/gpio33 ;
    input cpupllvddl;
    output \ddr_type/msi_clk24m/zpapck/gpio23 ;
    input ddrpllvddh;
    input ddrpllvddl;
    inout \dis_jtag0/jtag0_tdo/gpio38 ;
    inout \dis_tx/gpio02 ;
    input dvddio1;
    input dvddio2;
    input dvddio3;
    input dvddio4;
    input dvddl1;
    input dvddl2;
    input dvddl3;
    input dvddl4;
    input dvddl5;
    input dvddl6;
    input dvddl7;
    input dvddl8;
    inout \en_cpu/msif0_psdo/z0mosi/gpio24 ;
    input epad;
    inout ge_mdin0;
    inout ge_mdin1;
    inout ge_mdin2;
    inout ge_mdin3;
    inout ge_mdip0;
    inout ge_mdip1;
    inout ge_mdip2;
    inout ge_mdip3;
    output ge_rset;
    inout \gpio03/tx_sd ;
    inout \gpio04/tod ;
    inout \gpio05/gponpps ;
    input hsin;
    input hsip;
    output hson;
    output hsop;
    output hssd;
    inout \jtag0_ck/gpio36 ;
    inout \jtag0_nrst/gpio40 ;
    inout \jtag0_tdi/gpio39 ;
    inout \jtag0_tms/gpio37 ;
    input ldo_vddh;
    input ldo_vout;
    input \msif0_psdi/z0miso/gpio25 ;
    inout nc;
    input pe0_hsin;
    input pe0_hsip;
    output pe0_hson;
    output pe0_hsop;
    inout pe0_refclk_m;
    inout pe0_refclk_p;
    input pe0vddl;
    inout \sck1/led3/gpio09 ;
    inout \sda1/led2/gpio08 ;
    inout \sled_da/led17/gpio35 ;
    output \spif_clk/rst_cmd_dis ;
    output spif_d0;
    output spif_d1;
    output spif_ncs;
    output \spif_nrst/gpio57 ;
    input svddh;
    input svddl;
    inout \sw_mdc/led5/gpio12 ;
    inout \sw_mdio/led4/gpio10 ;
    output u0hsdm;
    output u0hsdp;
    input u0vddh;
    input u0vddl;
    inout \urxd0/gpio42 ;
    output \urxd1/led13/gpio20 ;
    inout \utxd0/gpio41 ;
    inout \utxd1/led14/gpio21 ;
    input vddq1;
    input vddq2;
    input vddq3;
    input vddq4;
    input vddq5;
    input vref;
    input xi;
    output xo;
    inout \z0sync/gpio30 ;


    initial
        begin
        end

endmodule
