// generated by newgenasym  Mon Aug 23 13:19:29 2021


module si3402 (ct1, ct2, erout, fb, hso, isossft, ploss, rcl, rdet, sp1, sp2,
        ssft, swo, vdd, vneg, vneg_pad, vposf, vposs, vss1, vss2, vssa);
    input ct1;
    input ct2;
    inout erout;
    input fb;
    output hso;
    inout isossft;
    output ploss;
    input rcl;
    input rdet;
    input sp1;
    input sp2;
    inout ssft;
    output swo;
    input vdd;
    input vneg;
    input vneg_pad;
    input vposf;
    input vposs;
    input vss1;
    input vss2;
    input vssa;


    initial
        begin
        end

endmodule
