// generated by newgenasym  Wed Dec 14 17:55:40 2022


module ch347 (\cts/gpio6 , \d+ , \d- , \dcd0/gpio4/act , dtr1, gnd, \gpio3/scl ,
        \rst# , \rts1/gpio7 , \rxd0/sda , rxd1, tck, tdi, tdo, tms, trst,
        txd1, vcc, xi, xo);
    inout \cts/gpio6 ;
    inout \d+ ;
    inout \d- ;
    inout \dcd0/gpio4/act ;
    inout dtr1;
    inout gnd;
    inout \gpio3/scl ;
    inout \rst# ;
    inout \rts1/gpio7 ;
    inout \rxd0/sda ;
    inout rxd1;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    inout trst;
    inout txd1;
    inout vcc;
    inout xi;
    inout xo;


    initial
        begin
        end

endmodule
