-- generated by newgenasym Wed Dec 14 17:55:40 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ch347 is
    port (    
	\cts/gpio6\: INOUT  STD_LOGIC;    
	\d+\:      INOUT  STD_LOGIC;    
	\d-\:      INOUT  STD_LOGIC;    
	\dcd0/gpio4/act\: INOUT  STD_LOGIC;    
	DTR1:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\gpio3/scl\: INOUT  STD_LOGIC;    
	\rst#\:    INOUT  STD_LOGIC;    
	\rts1/gpio7\: INOUT  STD_LOGIC;    
	\rxd0/sda\: INOUT  STD_LOGIC;    
	RXD1:      INOUT  STD_LOGIC;    
	TCK:       INOUT  STD_LOGIC;    
	TDI:       INOUT  STD_LOGIC;    
	TDO:       INOUT  STD_LOGIC;    
	TMS:       INOUT  STD_LOGIC;    
	TRST:      INOUT  STD_LOGIC;    
	TXD1:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	XI:        INOUT  STD_LOGIC;    
	XO:        INOUT  STD_LOGIC);
end ch347;
