// generated by newgenasym  Wed Nov 29 15:53:27 2023


module sfp_2x10 (los, mod_abs, mod_def0, mod_def1, mod_def2, rate_select,
        rd_m, rd_p, rs0, rs1, rx_los, scl, sda, td_m, td_p, tx_disable,
        tx_fault, vccr, vcct, veer_1, veer_2, veer_3, veer_4, veet_1,
        veet_2, veet_3);
    inout los;
    inout mod_abs;
    inout mod_def0;
    inout mod_def1;
    inout mod_def2;
    inout rate_select;
    inout rd_m;
    inout rd_p;
    inout rs0;
    inout rs1;
    inout rx_los;
    inout scl;
    inout sda;
    inout td_m;
    inout td_p;
    inout tx_disable;
    inout tx_fault;
    inout vccr;
    inout vcct;
    inout veer_1;
    inout veer_2;
    inout veer_3;
    inout veer_4;
    inout veet_1;
    inout veet_2;
    inout veet_3;


    initial
        begin
        end

endmodule
