// generated by newgenasym  Mon Dec 19 09:43:16 2022


module mt7531ae (agnd, avdd10_sgmii, avdd33_buck_1, avdd33_buck_2,
        avdd33_misc, avdd33_pllgp, avdd33_sgmii, avdd33_xtal,
        avddh_1, avddh_2, avddh_3, avddh_4, avddh_5, avddh_6,
        avddh_7, avddl_1, avddl_2, avddl_3, avddl_4, avddl_5,
        avss10_sgmii, avss33, avss33_buck_1, avss33_pllgp,
        avss33_xtal, dvddio, dvddio_2, dvddl_1, dvddl_2, dvddl_3,
        dvddl_4, dvddl_5, gnd_1, gnd_10, gnd_11, gnd_12, gnd_13,
        gnd_14, gnd_15, gnd_2, gnd_3, gnd_4, gnd_5, gnd_6, gnd_7,
        gnd_8, gnd_9, pad_ana_tstn, pad_ana_tstp, pad_gpio10,
        pad_gpio11, pad_gpio12, pad_gpio6, pad_gpio7, pad_gpio8,
        pad_gpio9, pad_gpio_0, pad_gpio_16, pad_gpio_19,
        pad_lan0_led0, pad_lan0_led1, pad_lan1_led0,
        pad_lan1_led1, pad_lan2_led0, pad_lan2_led1,
        pad_lan3_led0, pad_lan3_led1, pad_lan4_led0,
        pad_lan4_led1, pad_lx_1, pad_lx_2, pad_rext,
        pad_sgmii_rxn_p5, pad_sgmii_rxn_p6, pad_sgmii_rxp_p5,
        pad_sgmii_rxp_p6, pad_sgmii_txn_p5, pad_sgmii_txn_p6,
        pad_sgmii_txp_p5, pad_sgmii_txp_p6, pad_smi_mdc,
        pad_smi_mdio, pad_sys_rstb, pad_txvn_a_p0, pad_txvn_a_p1,
        pad_txvn_a_p2, pad_txvn_a_p3, pad_txvn_a_p4,
        pad_txvn_b_p0, pad_txvn_b_p1, pad_txvn_b_p2,
        pad_txvn_b_p3, pad_txvn_b_p4, pad_txvn_c_p0,
        pad_txvn_c_p1, pad_txvn_c_p2, pad_txvn_c_p3,
        pad_txvn_c_p4, pad_txvn_d_p0, pad_txvn_d_p1,
        pad_txvn_d_p2, pad_txvn_d_p3, pad_txvn_d_p4,
        pad_txvp_a_p0, pad_txvp_a_p1, pad_txvp_a_p2,
        pad_txvp_a_p3, pad_txvp_a_p4, pad_txvp_b_p0,
        pad_txvp_b_p1, pad_txvp_b_p2, pad_txvp_b_p3,
        pad_txvp_b_p4, pad_txvp_c_p0, pad_txvp_c_p1,
        pad_txvp_c_p2, pad_txvp_c_p3, pad_txvp_c_p4,
        pad_txvp_d_p0, pad_txvp_d_p1, pad_txvp_d_p2,
        pad_txvp_d_p3, pad_txvp_d_p4, pad_vcore_r, pad_xtali,
        pad_xtalo);
    inout agnd;
    input [1:0] avdd10_sgmii;
    inout avdd33_buck_1;
    inout avdd33_buck_2;
    inout avdd33_misc;
    inout avdd33_pllgp;
    input avdd33_sgmii;
    inout avdd33_xtal;
    inout avddh_1;
    inout avddh_2;
    inout avddh_3;
    inout avddh_4;
    inout avddh_5;
    inout avddh_6;
    inout avddh_7;
    inout avddl_1;
    inout avddl_2;
    inout avddl_3;
    inout avddl_4;
    inout avddl_5;
    input [1:0] avss10_sgmii;
    inout avss33;
    inout avss33_buck_1;
    inout avss33_pllgp;
    inout avss33_xtal;
    inout dvddio;
    input dvddio_2;
    inout dvddl_1;
    inout dvddl_2;
    input dvddl_3;
    inout dvddl_4;
    inout dvddl_5;
    inout gnd_1;
    input gnd_10;
    input gnd_11;
    inout gnd_12;
    inout gnd_13;
    inout gnd_14;
    inout gnd_15;
    inout gnd_2;
    input gnd_3;
    input gnd_4;
    input gnd_5;
    input gnd_6;
    input gnd_7;
    input gnd_8;
    input gnd_9;
    inout pad_ana_tstn;
    inout pad_ana_tstp;
    inout pad_gpio10;
    inout pad_gpio11;
    inout pad_gpio12;
    inout pad_gpio6;
    inout pad_gpio7;
    inout pad_gpio8;
    inout pad_gpio9;
    inout pad_gpio_0;
    inout pad_gpio_16;
    inout pad_gpio_19;
    inout pad_lan0_led0;
    inout pad_lan0_led1;
    inout pad_lan1_led0;
    inout pad_lan1_led1;
    inout pad_lan2_led0;
    inout pad_lan2_led1;
    inout pad_lan3_led0;
    inout pad_lan3_led1;
    inout pad_lan4_led0;
    output pad_lan4_led1;
    inout pad_lx_1;
    inout pad_lx_2;
    inout pad_rext;
    inout pad_sgmii_rxn_p5;
    inout pad_sgmii_rxn_p6;
    inout pad_sgmii_rxp_p5;
    inout pad_sgmii_rxp_p6;
    inout pad_sgmii_txn_p5;
    inout pad_sgmii_txn_p6;
    inout pad_sgmii_txp_p5;
    inout pad_sgmii_txp_p6;
    inout pad_smi_mdc;
    inout pad_smi_mdio;
    inout pad_sys_rstb;
    inout pad_txvn_a_p0;
    inout pad_txvn_a_p1;
    inout pad_txvn_a_p2;
    inout pad_txvn_a_p3;
    inout pad_txvn_a_p4;
    inout pad_txvn_b_p0;
    inout pad_txvn_b_p1;
    inout pad_txvn_b_p2;
    inout pad_txvn_b_p3;
    inout pad_txvn_b_p4;
    inout pad_txvn_c_p0;
    inout pad_txvn_c_p1;
    inout pad_txvn_c_p2;
    inout pad_txvn_c_p3;
    inout pad_txvn_c_p4;
    inout pad_txvn_d_p0;
    inout pad_txvn_d_p1;
    inout pad_txvn_d_p2;
    inout pad_txvn_d_p3;
    inout pad_txvn_d_p4;
    inout pad_txvp_a_p0;
    inout pad_txvp_a_p1;
    inout pad_txvp_a_p2;
    inout pad_txvp_a_p3;
    inout pad_txvp_a_p4;
    inout pad_txvp_b_p0;
    inout pad_txvp_b_p1;
    inout pad_txvp_b_p2;
    inout pad_txvp_b_p3;
    inout pad_txvp_b_p4;
    inout pad_txvp_c_p0;
    inout pad_txvp_c_p1;
    inout pad_txvp_c_p2;
    inout pad_txvp_c_p3;
    inout pad_txvp_c_p4;
    inout pad_txvp_d_p0;
    inout pad_txvp_d_p1;
    inout pad_txvp_d_p2;
    inout pad_txvp_d_p3;
    inout pad_txvp_d_p4;
    input pad_vcore_r;
    inout pad_xtali;
    inout pad_xtalo;


    initial
        begin
        end

endmodule
