-- generated by newgenasym Mon Nov 06 16:34:28 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity en7571n is
    port (    
	APD_COMP:  INOUT  STD_LOGIC;    
	APD_DRV:   INOUT  STD_LOGIC;    
	AVDD10_RX: IN     STD_LOGIC;    
	AVDD33_TX: IN     STD_LOGIC;    
	AVDD33_TX_TO: IN     STD_LOGIC;    
	BENN:      INOUT  STD_LOGIC;    
	BENP:      INOUT  STD_LOGIC;    
	DVDD10:    IN     STD_LOGIC;    
	DVDD33:    IN     STD_LOGIC;    
	EPAD:      IN     STD_LOGIC;    
	IBOUT:     OUT    STD_LOGIC;    
	IPIN:      IN     STD_LOGIC;    
	IREF:      INOUT  STD_LOGIC;    
	LOS:       OUT    STD_LOGIC;    
	MPXOUT:    OUT    STD_LOGIC;    
	RSSI:      IN     STD_LOGIC;    
	RXINN:     IN     STD_LOGIC;    
	RXINP:     IN     STD_LOGIC;    
	RXOUTN:    OUT    STD_LOGIC;    
	RXOUTP:    OUT    STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	TX_DIS:    IN     STD_LOGIC;    
	TX_FAULT:  OUT    STD_LOGIC;    
	TX_SD:     OUT    STD_LOGIC;    
	TXINN:     IN     STD_LOGIC;    
	TXINP:     IN     STD_LOGIC;    
	TXOUTN:    OUT    STD_LOGIC;    
	TXOUTP:    OUT    STD_LOGIC);
end en7571n;
