// generated by newgenasym  Fri Oct 16 10:46:03 2020


module lcmxo3 (b0_pt10a, b0_pt10b, b0_pt11a, b0_pt11b, b0_pt11c,
        b0_pt11d, b0_pt12a, b0_pt12b, \b0_pt12c/tdo , \b0_pt12d/tdi ,
        b0_pt13a, b0_pt13b, b0_pt13c, b0_pt13d, b0_pt16a, b0_pt16b,
        \b0_pt16c/tck , \b0_pt16d/tms , \b0_pt17a/pclkt0_1 ,
        \b0_pt17b/pclkc0_1 , b0_pt17c, b0_pt17d, b0_pt18a, b0_pt18b,
        \b0_pt18c/scl/pclkt0_0 , \b0_pt18d/sda/pclkc0_0 , b0_pt19a,
        b0_pt19b, b0_pt19c, b0_pt19d, b0_pt20a, b0_pt20b,
        \b0_pt20c/jtagenb , \b0_pt20d/b1_programn , b0_pt21a,
        b0_pt21b, b0_pt21c, b0_pt21d, b0_pt22a, b0_pt22b, b0_pt22c,
        b0_pt22d, b0_pt23a, b0_pt23b, b0_pt24a, b0_pt24b,
        \b0_pt24c/initn , \b0_pt24d/done , b0_pt9a, b0_pt9b, b0_pt9c,
        b1_pr10a, b1_pr10b, b1_pr10c, b1_pr10d, b1_pr11a, b1_pr11b,
        b1_pr11c, b1_pr11d, b1_pr12a, b1_pr12b, b1_pr12c, b1_pr12d,
        b1_pr13a, b1_pr13b, b1_pr13c, b1_pr13d, b1_pr14a, b1_pr14b,
        b1_pr14c, b1_pr14d, b1_pr1a, b1_pr1b, b1_pr1c, b1_pr1d,
        b1_pr2a, b1_pr2b, b1_pr2c, b1_pr2d, b1_pr3a, b1_pr3b,
        b1_pr3c, b1_pr3d, b1_pr4a, b1_pr4b, b1_pr4c, b1_pr4d,
        b1_pr5a, b1_pr5b, b1_pr5c, b1_pr5d, b1_pr6a, b1_pr6b,
        b1_pr6c, b1_pr6d, \b1_pr7a/pclkt1_0 , \b1_pr7b/pclkc1_0 ,
        b1_pr7c, b1_pr7d, b1_pr9a, b1_pr9b, b1_pr9c, b1_pr9d,
        \b2_pb11a/pclkt2_0 , \b2_pb11b/pclkc2_0 , b2_pb11c, b2_pb11d,
        b2_pb12a, b2_pb12b, b2_pb12c, b2_pb12d, \b2_pb16a/pclkt2_1 ,
        \b2_pb16b/pclkc2_1 , b2_pb16c, b2_pb16d, b2_pb18a, b2_pb18b,
        b2_pb18c, b2_pb18d, b2_pb19a, b2_pb19b, b2_pb19c, b2_pb19d,
        b2_pb21a, b2_pb21b, b2_pb21c, b2_pb21d, b2_pb22a, b2_pb22b,
        b2_pb22c, b2_pb22d, b2_pb24a, b2_pb24b, \b2_pb25a/sn ,
        \b2_pb25b/si/sispi , b2_pb25c, b2_pb25d, b2_pb3a, b2_pb3b,
        b2_pb3c, b2_pb3d, \b2_pb5a/csspin , b2_pb5b, b2_pb6a,
        b2_pb6b, b2_pb6c, b2_pb6d, \b2_pb8a/mclk/cclk ,
        \b2_pb8b/so/spiso , b2_pb8c, b2_pb8d, b2_pb9a, b2_pb9b,
        b2_pb9c, b2_pb9d, b3_pl11a, b3_pl11b, b3_pl11c, b3_pl11d,
        \b3_pl12a/pclkt3_0 , \b3_pl12b/pclkc3_0 , b3_pl12c, b3_pl12d,
        b3_pl13a, b3_pl13b, b3_pl13c, b3_pl13d, b3_pl14a, b3_pl14b,
        b3_pl14c, b3_pl14d, b4_pl10a, b4_pl10b, b4_pl10c, b4_pl10d,
        b4_pl6a, b4_pl6b, b4_pl6c, b4_pl6d, b4_pl7a, b4_pl7b,
        \b4_pl7c/pclkt4_0 , \b4_pl7d/pclkc4_0 , b4_pl9a, b4_pl9b,
        b4_pl9c, b4_pl9d, \b5_pl1a/l_gb3_pllt_fb ,
        \b5_pl1b/l_gb3_pllc_fb , b5_pl1c, b5_pl1d,
        \b5_pl2a/l_gb3_pllt_in , \b5_pl2b/l_gb3_pllc_in , b5_pl2c,
        b5_pl2d, \b5_pl3a/pclkt5_0 , \b5_pl3b/pclkc5_0 , b5_pl3c,
        b5_pl3d, b5_pl4a, b5_pl4b, b5_pl4c, b5_pl4d, b5_pl5a,
        b5_pl5b, b5_pl5c, b5_pl5d, gnd_1, gnd_10, gnd_11, gnd_12,
        gnd_13, gnd_14, gnd_15, gnd_16, gnd_17, gnd_18, gnd_19,
        gnd_2, gnd_20, gnd_21, gnd_22, gnd_23, gnd_24, gnd_3, gnd_4,
        gnd_5, gnd_6, gnd_7, gnd_8, gnd_9, nc1, vcc_1, vcc_2, vcc_3,
        vcc_4, vcc_5, vcc_6, vcc_7, vcc_8, vccio0_1, vccio0_2,
        vccio0_3, vccio0_4, vccio1_1, vccio1_2, vccio1_3, vccio1_4,
        vccio2_2, vccio2_3, vccio2_4, vccio2_5, vccio3, vccio4_1,
        vccio4_2, vccio5);
    inout b0_pt10a;
    inout b0_pt10b;
    inout b0_pt11a;
    inout b0_pt11b;
    inout b0_pt11c;
    inout b0_pt11d;
    inout b0_pt12a;
    inout b0_pt12b;
    inout \b0_pt12c/tdo ;
    inout \b0_pt12d/tdi ;
    inout b0_pt13a;
    inout b0_pt13b;
    inout b0_pt13c;
    inout b0_pt13d;
    inout b0_pt16a;
    inout b0_pt16b;
    inout \b0_pt16c/tck ;
    inout \b0_pt16d/tms ;
    inout \b0_pt17a/pclkt0_1 ;
    inout \b0_pt17b/pclkc0_1 ;
    inout b0_pt17c;
    inout b0_pt17d;
    inout b0_pt18a;
    inout b0_pt18b;
    inout \b0_pt18c/scl/pclkt0_0 ;
    inout \b0_pt18d/sda/pclkc0_0 ;
    inout b0_pt19a;
    inout b0_pt19b;
    inout b0_pt19c;
    inout b0_pt19d;
    inout b0_pt20a;
    inout b0_pt20b;
    inout \b0_pt20c/jtagenb ;
    inout \b0_pt20d/b1_programn ;
    inout b0_pt21a;
    inout b0_pt21b;
    inout b0_pt21c;
    inout b0_pt21d;
    inout b0_pt22a;
    inout b0_pt22b;
    inout b0_pt22c;
    inout b0_pt22d;
    inout b0_pt23a;
    inout b0_pt23b;
    inout b0_pt24a;
    inout b0_pt24b;
    inout \b0_pt24c/initn ;
    inout \b0_pt24d/done ;
    inout b0_pt9a;
    inout b0_pt9b;
    inout b0_pt9c;
    inout b1_pr10a;
    inout b1_pr10b;
    inout b1_pr10c;
    inout b1_pr10d;
    inout b1_pr11a;
    inout b1_pr11b;
    inout b1_pr11c;
    inout b1_pr11d;
    inout b1_pr12a;
    inout b1_pr12b;
    inout b1_pr12c;
    inout b1_pr12d;
    inout b1_pr13a;
    inout b1_pr13b;
    inout b1_pr13c;
    inout b1_pr13d;
    inout b1_pr14a;
    inout b1_pr14b;
    inout b1_pr14c;
    inout b1_pr14d;
    inout b1_pr1a;
    inout b1_pr1b;
    inout b1_pr1c;
    inout b1_pr1d;
    inout b1_pr2a;
    inout b1_pr2b;
    inout b1_pr2c;
    inout b1_pr2d;
    inout b1_pr3a;
    inout b1_pr3b;
    inout b1_pr3c;
    inout b1_pr3d;
    inout b1_pr4a;
    inout b1_pr4b;
    inout b1_pr4c;
    inout b1_pr4d;
    inout b1_pr5a;
    inout b1_pr5b;
    inout b1_pr5c;
    inout b1_pr5d;
    inout b1_pr6a;
    inout b1_pr6b;
    inout b1_pr6c;
    inout b1_pr6d;
    inout \b1_pr7a/pclkt1_0 ;
    inout \b1_pr7b/pclkc1_0 ;
    inout b1_pr7c;
    inout b1_pr7d;
    inout b1_pr9a;
    inout b1_pr9b;
    inout b1_pr9c;
    inout b1_pr9d;
    inout \b2_pb11a/pclkt2_0 ;
    inout \b2_pb11b/pclkc2_0 ;
    inout b2_pb11c;
    inout b2_pb11d;
    inout b2_pb12a;
    inout b2_pb12b;
    inout b2_pb12c;
    inout b2_pb12d;
    inout \b2_pb16a/pclkt2_1 ;
    inout \b2_pb16b/pclkc2_1 ;
    inout b2_pb16c;
    inout b2_pb16d;
    inout b2_pb18a;
    inout b2_pb18b;
    inout b2_pb18c;
    inout b2_pb18d;
    inout b2_pb19a;
    inout b2_pb19b;
    inout b2_pb19c;
    inout b2_pb19d;
    inout b2_pb21a;
    inout b2_pb21b;
    inout b2_pb21c;
    inout b2_pb21d;
    inout b2_pb22a;
    inout b2_pb22b;
    inout b2_pb22c;
    inout b2_pb22d;
    inout b2_pb24a;
    inout b2_pb24b;
    inout \b2_pb25a/sn ;
    inout \b2_pb25b/si/sispi ;
    inout b2_pb25c;
    inout b2_pb25d;
    inout b2_pb3a;
    inout b2_pb3b;
    inout b2_pb3c;
    inout b2_pb3d;
    inout \b2_pb5a/csspin ;
    inout b2_pb5b;
    inout b2_pb6a;
    inout b2_pb6b;
    inout b2_pb6c;
    inout b2_pb6d;
    inout \b2_pb8a/mclk/cclk ;
    inout \b2_pb8b/so/spiso ;
    inout b2_pb8c;
    inout b2_pb8d;
    inout b2_pb9a;
    inout b2_pb9b;
    inout b2_pb9c;
    inout b2_pb9d;
    inout b3_pl11a;
    inout b3_pl11b;
    inout b3_pl11c;
    inout b3_pl11d;
    inout \b3_pl12a/pclkt3_0 ;
    inout \b3_pl12b/pclkc3_0 ;
    inout b3_pl12c;
    inout b3_pl12d;
    inout b3_pl13a;
    inout b3_pl13b;
    inout b3_pl13c;
    inout b3_pl13d;
    inout b3_pl14a;
    inout b3_pl14b;
    inout b3_pl14c;
    inout b3_pl14d;
    inout b4_pl10a;
    inout b4_pl10b;
    inout b4_pl10c;
    inout b4_pl10d;
    inout b4_pl6a;
    inout b4_pl6b;
    inout b4_pl6c;
    inout b4_pl6d;
    inout b4_pl7a;
    inout b4_pl7b;
    inout \b4_pl7c/pclkt4_0 ;
    inout \b4_pl7d/pclkc4_0 ;
    inout b4_pl9a;
    inout b4_pl9b;
    inout b4_pl9c;
    inout b4_pl9d;
    inout \b5_pl1a/l_gb3_pllt_fb ;
    inout \b5_pl1b/l_gb3_pllc_fb ;
    inout b5_pl1c;
    inout b5_pl1d;
    inout \b5_pl2a/l_gb3_pllt_in ;
    inout \b5_pl2b/l_gb3_pllc_in ;
    inout b5_pl2c;
    inout b5_pl2d;
    inout \b5_pl3a/pclkt5_0 ;
    inout \b5_pl3b/pclkc5_0 ;
    inout b5_pl3c;
    inout b5_pl3d;
    inout b5_pl4a;
    inout b5_pl4b;
    inout b5_pl4c;
    inout b5_pl4d;
    inout b5_pl5a;
    inout b5_pl5b;
    inout b5_pl5c;
    inout b5_pl5d;
    input gnd_1;
    input gnd_10;
    input gnd_11;
    input gnd_12;
    input gnd_13;
    input gnd_14;
    input gnd_15;
    input gnd_16;
    input gnd_17;
    input gnd_18;
    input gnd_19;
    input gnd_2;
    input gnd_20;
    input gnd_21;
    input gnd_22;
    input gnd_23;
    input gnd_24;
    input gnd_3;
    input gnd_4;
    input gnd_5;
    input gnd_6;
    input gnd_7;
    input gnd_8;
    input gnd_9;
    inout nc1;
    input vcc_1;
    input vcc_2;
    input vcc_3;
    input vcc_4;
    input vcc_5;
    input vcc_6;
    input vcc_7;
    input vcc_8;
    input vccio0_1;
    input vccio0_2;
    input vccio0_3;
    input vccio0_4;
    input vccio1_1;
    input vccio1_2;
    input vccio1_3;
    input vccio1_4;
    input vccio2_2;
    input vccio2_3;
    input vccio2_4;
    input vccio2_5;
    input vccio3;
    input vccio4_1;
    input vccio4_2;
    input vccio5;


    initial
        begin
        end

endmodule
