// generated by newgenasym  Wed Oct 21 09:51:03 2020


module n_mos (d, d1, d2, d3, d4, g, s, s1, s2, s3);
    inout d;
    inout d1;
    output d2;
    output d3;
    output d4;
    input g;
    inout s;
    input s1;
    input s2;
    input s3;


    initial
        begin
        end

endmodule
