// generated by newgenasym  Fri Dec 17 10:00:32 2021


module ldo (\4 , adj, en, gnd, vin, vout);
    input \4 ;
    output adj;
    input en;
    input gnd;
    input vin;
    input vout;


    initial
        begin
        end

endmodule
