-- generated by newgenasym Mon Aug 31 14:11:00 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity n_mos is
    port (    
	D:         INOUT  STD_LOGIC;    
	D1:        INOUT  STD_LOGIC;    
	D2:        OUT    STD_LOGIC;    
	D3:        OUT    STD_LOGIC;    
	D4:        OUT    STD_LOGIC;    
	G:         IN     STD_LOGIC;    
	S:         INOUT  STD_LOGIC;    
	S1:        IN     STD_LOGIC;    
	S2:        IN     STD_LOGIC;    
	S3:        IN     STD_LOGIC);
end n_mos;
