// generated by newgenasym  Mon Aug 31 14:05:50 2020


module le9622 (avdd1, avdd2, cs, dclk, din, dout, \dra/zmosi , dvdd1, dvdd1v2,
        dvdd2, \dxa/zmiso , epad, \fs/zsync , \i/o11 , \i/o12 , \i/o21/vs1 ,
        \i/o22/vs2 , ihl1, ihl2, int, iref, lfc1, \pclk/zclk , rac1, rac2,
        rdc1, rdc2, ringd1, ringd2, rsn1, rsn2, rst, rtv1, rtv2,
        swcmpy, swcmpz, swisy, swisz, swouty, swoutz, swvsy, swvsz,
        tac1, tac2, tdc1, tdc2, tipd1, tipd2, vbh, vbl1, vbl2, vddhpi,
        vddsw, vref);
    input avdd1;
    input avdd2;
    input cs;
    input dclk;
    input din;
    output dout;
    input \dra/zmosi ;
    input dvdd1;
    output dvdd1v2;
    input dvdd2;
    output \dxa/zmiso ;
    input epad;
    input \fs/zsync ;
    inout \i/o11 ;
    inout \i/o12 ;
    inout \i/o21/vs1 ;
    inout \i/o22/vs2 ;
    output ihl1;
    output ihl2;
    output int;
    input iref;
    output lfc1;
    input \pclk/zclk ;
    input rac1;
    input rac2;
    input rdc1;
    input rdc2;
    output ringd1;
    output ringd2;
    input rsn1;
    input rsn2;
    input rst;
    output rtv1;
    output rtv2;
    output swcmpy;
    output swcmpz;
    input swisy;
    input swisz;
    output swouty;
    output swoutz;
    input swvsy;
    input swvsz;
    input tac1;
    input tac2;
    input tdc1;
    input tdc2;
    output tipd1;
    output tipd2;
    input vbh;
    input vbl1;
    input vbl2;
    input vddhpi;
    input vddsw;
    output vref;


    initial
        begin
        end

endmodule
