// generated by newgenasym  Wed Sep 16 11:07:26 2020


module bosa (gnd_r, gnd_t, \ld+/pd- , \ld- , \pd+ , rxn, rxp, vapd, vcc);
    inout gnd_r;
    inout gnd_t;
    inout \ld+/pd- ;
    inout \ld- ;
    inout \pd+ ;
    inout rxn;
    inout rxp;
    inout vapd;
    inout vcc;


    initial
        begin
        end

endmodule
