-- generated by newgenasym Wed Sep 16 11:07:26 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bosa is
    port (    
	GND_R:     INOUT  STD_LOGIC;    
	GND_T:     INOUT  STD_LOGIC;    
	\ld+/pd-\: INOUT  STD_LOGIC;    
	\ld-\:     INOUT  STD_LOGIC;    
	\pd+\:     INOUT  STD_LOGIC;    
	RXN:       INOUT  STD_LOGIC;    
	RXP:       INOUT  STD_LOGIC;    
	VAPD:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end bosa;
