-- generated by newgenasym Mon Aug 31 13:53:27 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity eeprom is
    port (    
	A0:        INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	WP:        INOUT  STD_LOGIC);
end eeprom;
