// generated by newgenasym  Thu Oct 21 15:11:13 2021


module key (\1 , \2 , \3 , \4 , \5 , \6 , \7 , ina, inb, ms1, ms2, out1a, out1b, out2a,
        out2b);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    input \5 ;
    output \6 ;
    output \7 ;
    input ina;
    input inb;
    input ms1;
    input ms2;
    output out1a;
    output out1b;
    output out2a;
    output out2b;


    initial
        begin
        end

endmodule
