"""EDIF 2.0.0 S-expression parser — extracts logic netlist from OrCAD EDIF export.

Parses .edf files generated by OrCAD cap2edi into the unified DesignIR,
covering component definitions, instances, nets, and net classification.

Phase XI P0-A1/A4: EDIF **does** contain coordinates — ``(figure WIRE
(path (pointList (pt x y) ...)))`` polylines (verified on
HG5015-BE36_V10.EDF: 2516 wire figures / 4257 points / 836 of 862 nets
with geometry).  These are now extracted into ``NetIR.wires`` /
``PageIR.wires`` to drive CSA ``WIRE 16 -1`` generation.  Instance
coordinates are approximated from ``(designator (display (origin (pt x y))))``
labels.  The historical claim "Coordinates absent in EDIF" was incorrect.

Phase XI P0-A2: OrCAD cap2edi exports multi-sheet schematics as 24
``(page (rename &NN_NAME "NN-Name") (pageSize ...) (instance ...)
(net ...) ...)`` blocks that are direct children of the top cell's view
contents.  ``_parse_page`` now detects these blocks and splits them into
separate PageIRs (previously every sheet collapsed into ``PageIR[0]``),
reading ``pageSize``/``boundingBox`` for page width/height.  When a cell
has no page blocks the legacy ``_cell_is_page`` heuristic is used as a
fallback for other EDIF variants.

References:
    ORCAD_SOURCE_ANALYSIS.md §12 for the 12 structural rules
    BACKEND_DESIGN.md §3.0a for the EDIFParser interface
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from sexpdata import Symbol, loads

from .base import ParserBase
from ..config import config as cfg
from ..db.component_db import ComponentDB
from ..ir.component import (
    ComponentDef,
    ComponentInstanceIR,
    ElectricalType,
    PinDef,
)
from ..ir.design import DesignIR, NetCategory, NetConnection, NetIR, PageIR, WireSegment

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
#  ISCF net-classification — sourced from central config
# ---------------------------------------------------------------------------

GROUND_NAMES: set[str] = cfg.net.ground_names
POWER_PREFIXES: tuple[str, ...] = cfg.net.power_prefixes

# EDIF direction → ElectricalType mapping
_DIRECTION_MAP: dict[str, ElectricalType] = {
    "INPUT": ElectricalType.INPUT,
    "OUTPUT": ElectricalType.OUTPUT,
    "BIDIR": ElectricalType.BIDIR,
    "BIDIRECTIONAL": ElectricalType.BIDIR,
    "INOUT": ElectricalType.BIDIR,
    "POWER": ElectricalType.POWER,
    "GROUND": ElectricalType.GROUND,
    "PASSIVE": ElectricalType.PASSIVE,
    "TRISTATE": ElectricalType.TRI_STATE,
}


# ====================================================================
#  Helper utilities
# ====================================================================

def _sym_str(obj) -> str:
    """Safely convert an sexp Symbol | str → str."""
    if isinstance(obj, Symbol):
        return obj.value()
    if isinstance(obj, str):
        return obj
    if isinstance(obj, (int, float)):
        return str(obj)
    return ""


def _edif_name(obj) -> str:
    """Extract a name from an EDIF expression, handling (rename ...) syntax.
    
    EDIF uses (rename internal "external") to alias names.
    The external name (second string arg) is preferred.
    Falls back to _sym_str for plain names.
    """
    if isinstance(obj, list) and obj and _sym_str(obj[0]).lower() == "rename":
        # (rename INTERNAL "EXTERNAL") → prefer external
        if len(obj) >= 3:
            return _sym_str(obj[2]) or _sym_str(obj[1])
        return _sym_str(obj[1]) if len(obj) >= 2 else ""
    return _sym_str(obj)


def _net_name(obj) -> str:
    """Extract a net name from ``net[1]``, handling all EDIF name forms.

    OrCAD EDIF encodes net names three ways:
      * plain:      ``(net GND (joined ...))``
      * name-wrap:  ``(net (name PFI_DYING_GASP (display ...)) ...)``
      * rename:     ``(net (rename INTERNAL "EXTERNAL") ...)``

    Using ``_sym_str`` directly on the wrapped forms returns "" (the name
    is a sub-list, not a symbol), silently dropping the net name.

    Args:
        obj: The second element of a ``(net ...)`` S-expression.

    Returns:
        The net name string (empty only if truly absent).
    """
    name = ""
    if isinstance(obj, list) and obj:
        tag = _sym_str(obj[0]).lower()
        if tag == "name" and len(obj) >= 2:
            name = _sym_str(obj[1])
        elif tag == "rename":
            name = _edif_name(obj)
    else:
        name = _sym_str(obj)
    # Phase XI P0-A5: OrCAD EDIF escapes special characters with a leading
    # '&' (e.g. '&3V3_SOC', '&1V8_BUCK').  Strip the escape so the net name
    # matches the CIS/pstxnet spelling used downstream.
    if name.startswith("&"):
        name = name[1:]
    return name


def _find_first(items: list, tag: str, flatten: bool = False) -> list | None:
    """Return the first sub-list whose first element matches *tag*.

    Args:
        items: A list of S-expressions.
        tag: Tag name to search for (compared case-insensitively).
        flatten: If True, only descend one level into sub-lists for broader search.

    Returns:
        The matched list, or None.
    """
    for item in items:
        if isinstance(item, list) and item and _sym_str(item[0]).lower() == tag.lower():
            return item
    if flatten:
        for item in items:
            if isinstance(item, list):
                result = _find_first(item, tag, flatten=False)
                if result is not None:
                    return result
    return None


def _find_all(items: list, tag: str, recursive: bool = False) -> list[list]:
    """Return all sub-lists whose first element matches *tag*.

    Args:
        items: A list of S-expressions.
        tag: Tag name to search for (compared case-insensitively).
        recursive: If True, recursively search all nested sub-lists
                   (e.g. for deeply nested EDIF structures like
                   cell→view→contents→figure→instance).

    Returns:
        List of matched sub-lists.

    Note:
        Recursive mode is essential for Type B EDIF files (e.g. RTL8367RB.edf)
        where instances/nets are nested inside intermediate elements beyond
        the immediate children of ``contents``.
    """
    result: list[list] = []
    _find_all_impl(items, tag, recursive, 0, result)
    return result


def _find_all_impl(
    items: list, tag: str, recursive: bool, depth: int, result: list[list]
) -> None:
    """Recursive implementation helper for _find_all."""
    if depth > 12:  # safety limit — prevents stack overflow on malformed data
        return
    for item in items:
        if isinstance(item, list) and item:
            if _sym_str(item[0]).lower() == tag.lower():
                result.append(item)
            if recursive:
                _find_all_impl(item, tag, recursive, depth + 1, result)


def _get_named(items: list, tag: str) -> str:
    """Return the value of the first attribute-like sub-item `(tag value)`.

    Example: Given `(cell FOO (cellType GENERIC))`, `_get_named(items, 'cellType')` → `'GENERIC'`.
    """
    for item in items:
        if isinstance(item, list) and len(item) >= 2:
            if _sym_str(item[0]).lower() == tag.lower():
                return _sym_str(item[1])
    return ""


def _is_cell(items: list) -> bool:
    """Predicate: does the list start with Symbol('cell')?"""
    return bool(items) and _sym_str(items[0]) == "cell"


def _is_instance(items: list) -> bool:
    return bool(items) and _sym_str(items[0]) == "instance"


def _is_net(items: list) -> bool:
    return bool(items) and _sym_str(items[0]) == "net"


def _is_port(items: list) -> bool:
    return bool(items) and _sym_str(items[0]) == "port"


def _is_property(items: list) -> bool:
    return bool(items) and _sym_str(items[0]) == "property"


# ====================================================================
#  Property parsing utilities
# ====================================================================

def _parse_property_kv(prop: list) -> tuple[str, str]:
    """Extract (name, value) from an EDIF property expression.

    Handles both single-token and multi-token names:
        (property VALUE (string "10K"))          → ("VALUE", "10K")
        (property PCB Footprint (string "0603")) → ("PCB Footprint", "0603")

    Returns:
        A (name, value) pair; both may be empty strings on failure.
    """
    if len(prop) < 3:
        return ("", "")

    # The last element is the value spec: (TYPE VALUE)
    val_spec = prop[-1]
    value = ""
    if isinstance(val_spec, list) and len(val_spec) >= 2:
        value = _sym_str(val_spec[1])
    elif isinstance(val_spec, (str, int, float)):
        value = str(val_spec)

    # Everything between index 1 and len-2 forms the property name
    name_tokens = prop[1:-1]
    name = " ".join(_sym_str(t) for t in name_tokens)

    return (name, value)


def _parse_property_value(prop: list) -> str:
    """Extract only the string value from an EDIF property expression.

    Args:
        prop: Property sub-list, e.g. ``(property REFDES (string "C122"))``.

    Returns:
        The string value, or empty string if not found.
    """
    if len(prop) < 3:
        return ""
    val_spec = prop[-1]
    if isinstance(val_spec, list) and len(val_spec) >= 2:
        return _sym_str(val_spec[1])
    if isinstance(val_spec, (str, int, float)):
        return str(val_spec)
    return ""


class EDIFParser(ParserBase):
    """Parse an EDIF 2.0.0 file into DesignIR + ComponentDB.

    Handles:
    * Multiple libraries (work + vendor)
    * Hierarchical / nested cells
    * Properties on instances (value, footprint, MPN, PCB Footprint)
    * Port references in nets (portRef + instanceRef)
    * Array / member bus syntax
    * ISCF 4-class net classification (FLAT/GROUND/POWER/BUS)
    """

    FORMAT_NAME = "CIS_EDIF"
    FILE_EXTENSIONS = [".edf"]

    # ------------------------------------------------------------------
    #  Public entry point
    # ------------------------------------------------------------------

    def parse(self, path: Path) -> DesignIR:
        """Parse an .edf file into a DesignIR."""
        if not path.exists():
            raise FileNotFoundError(f"EDIF file not found: {path}")

        raw_text = path.read_text(encoding="utf-8", errors="replace")

        # Fix: Windows paths like C:\USERS\... break sexpdata's string parser
        # because backslash is treated as escape char. Replace with forward slash.
        raw_text = raw_text.replace('\\\\', '/').replace('\\', '/')

        try:
            tree = loads(raw_text)
        except Exception as e:
            logger.error("EDIF parse failed: %s", e)
            raise

        if not isinstance(tree, list) or not tree:
            raise ValueError("EDIF: top-level expression is not a valid list")

        tag = _sym_str(tree[0])
        if tag != "edif":
            raise ValueError(f"EDIF: expected '(edif ...)' at top level, got '{tag}'")

        project_name = _edif_name(tree[1]) if len(tree) > 1 else "UNNAMED"
        logger.info("Parsing EDIF project: %s", project_name)

        # ── extract libraries ──────────────────────────────────────────
        libraries = _find_all(tree, "library")
        logger.info("Found %d library(s)", len(libraries))

        # ── build ComponentDB from component-definition cells ───────────
        component_db = ComponentDB()
        component_cell_names: set[str] = set()

        for lib in libraries:
            cells = _find_all(lib, "cell")
            for cell in cells:
                # Page cells / page-container cells are not components
                if self._get_page_blocks(cell) or self._cell_is_page(cell):
                    continue
                comp = self._parse_cell_as_component(cell, component_db)
                if comp is not None:
                    component_cell_names.add(comp.library_id)

        # ── build pages from page cells ─────────────────────────────────
        # Phase XI P0-A2: a cell may contain (page ...) blocks (OrCAD
        # multi-sheet schematic); each block is parsed into its own PageIR.
        # Without page blocks, fall back to the _cell_is_page heuristic.
        pages: list[PageIR] = []
        page_counter = 0

        for lib in libraries:
            cells = _find_all(lib, "cell")
            for cell in cells:
                parsed = self._parse_page(
                    cell, component_db, component_cell_names, page_counter
                )
                if not parsed:
                    continue
                page_counter += len(parsed)
                pages.extend(parsed)

        # ── determine top page from (design ...) ────────────────────────
        design_block = _find_first(tree, "design")
        if design_block:
            top_cell = _get_named(design_block, "cellRef")
            if top_cell:
                top_lib = _get_named(design_block, "libraryRef")
                logger.info("Top-level cell: %s (library: %s)", top_cell, top_lib)
                for page in pages:
                    if page.page_name == top_cell:
                        page.page_id = "1.1"
                        # move to front
                        pages.remove(page)
                        pages.insert(0, page)
                        break

        # renumber pages
        for idx, page in enumerate(pages):
            page.page_id = f"1.{idx + 1}"

        # ── Phase XI P0-A3: design-level off-page ports ──────────────
        # EDIF declares off-page connectors on the top-level cell's port
        # list: ``(contents (offPageConnector <name>_OFF_PAGE_CONNECTOR))``.
        # HG5015 has 243 such declarations (212 named + 31 auto "&..."),
        # complementing the 522 page-level off_pages — 765 total matches
        # the raw OFF_PAGE_CONNECTOR occurrences in the file.
        design_off_pages: list[dict] = []
        for lib in libraries:
            for cell in _find_all(lib, "cell"):
                # offPageConnector lives under a view's contents:
                # library → cell → view → contents → (offPageConnector ...)
                for view in _find_all(cell, "view"):
                    contents = _find_first(view, "contents")
                    if contents is None:
                        continue
                    for offref in _find_all(contents, "offPageConnector"):
                        if len(offref) >= 2:
                            _nm = _sym_str(offref[1])
                            design_off_pages.append({
                                "name": _nm,
                                "net_name": _nm.replace(
                                    "_OFF_PAGE_CONNECTOR", ""
                                ),
                            })
        # dedupe
        _seen_dop: set[tuple[str, str]] = set()
        _uniq_dop: list[dict] = []
        for op in design_off_pages:
            key = (op["name"], op["net_name"])
            if key not in _seen_dop:
                _seen_dop.add(key)
                _uniq_dop.append(op)
        design_off_pages = _uniq_dop
        logger.info(
            "P0-A3: %d design-level off-page port(s) (page-level: %d)",
            len(design_off_pages),
            sum(len(p.off_pages) for p in pages),
        )

        design_ir = DesignIR(
            project_name=project_name,
            source_format=self.FORMAT_NAME,
            pages=pages,
            component_db=component_db,
            global_nets=[],
            metadata={
                "edif_version": "2.0.0",
                "design_off_pages": design_off_pages,
            },
        )

        logger.info(
            "Parsed: %d page(s), %d component(s), %d instance(s), %d net(s)",
            len(pages),
            component_db.count,
            len(design_ir.all_instances),
            len(design_ir.all_nets),
        )

        return design_ir

    # ------------------------------------------------------------------
    #  Cell classification
    # ------------------------------------------------------------------

    @staticmethod
    def _cell_is_page(cell: list) -> bool:
        """Heuristic: a cell is a schematic page if it contains instance or net elements
        anywhere in its subtree."""
        view = _find_first(cell, "view", flatten=False)
        if view is None:
            return False

        # Recursively check for instance/net elements
        def _has_tag(items: list, tags: set[str], depth: int = 0) -> bool:
            if depth > 12:
                return False
            for item in items:
                if isinstance(item, list) and item:
                    if _sym_str(item[0]) in tags:
                        return True
                    if _has_tag(item, tags, depth + 1):
                        return True
            return False

        return _has_tag(view, {"instance", "net"})


    # ------------------------------------------------------------------
    #  Cell → ComponentDef  (library components)
    # ------------------------------------------------------------------

    def _parse_cell_as_component(
        self, cell: list, existing_db: ComponentDB
    ) -> ComponentDef | None:
        """Interpret a cell as a component definition."""
        cell_name = _sym_str(cell[1]) if len(cell) > 1 else ""

        if not cell_name:
            return None

        # skip if already registered
        if existing_db.contains(cell_name):
            return existing_db.get_by_library_id(cell_name)

        view = _find_first(cell, "view", flatten=True)
        interface: list | None = None
        if view is not None:
            interface = _find_first(view, "interface")

        # extract ports
        pins: list[PinDef] = []
        if interface:
            ports = _find_all(interface, "port")
            for port in ports:
                pin = self._parse_port(port)
                if pin:
                    pins.append(pin)

        comp = ComponentDef(
            library_id=cell_name,
            part_name=cell_name,
            pins=pins,
            pin_count=len(pins),
            source_format=self.FORMAT_NAME,
        )

        # try to extract properties from a (property ...) at the cell level
        self._attach_properties_to_component(comp, cell)

        existing_db.add(comp)
        return comp

    def _parse_port(self, port: list) -> PinDef | None:
        """(port NAME (direction DIR)) → PinDef."""
        if len(port) < 2:
            return None
        pin_name = _sym_str(port[1])
        direction_str = ""
        for item in port[2:]:
            if isinstance(item, list) and item and _sym_str(item[0]) == "direction":
                direction_str = _sym_str(item[1])
                break
        etype = _DIRECTION_MAP.get(direction_str.upper(), ElectricalType.PASSIVE)
        return PinDef(number=pin_name, name=pin_name, type=etype)

    def _attach_properties_to_component(self, comp: ComponentDef, items: list) -> None:
        """Walk items to find (property ...) expressions, apply to comp."""
        for item in items:
            if not _is_property(item):
                continue
            self._apply_property(comp, item)

    def _apply_property(self, comp: ComponentDef, prop: list) -> None:
        """Map a single (property NAME (TYPE VALUE)) to ComponentDef fields."""
        name, value = _parse_property_kv(prop)
        if not name:
            return

        name_upper = name.upper()
        if name_upper == "VALUE":
            comp.value = value
        elif name_upper in ("PCB FOOTPRINT", "FOOTPRINT"):
            comp.footprint = value
        elif name_upper == "MPN" or name_upper == "PART_NUMBER":
            comp.mpn = value
        elif name_upper == "DESCRIPTION":
            comp.description = value
        elif name_upper == "TOLERANCE":
            comp.tolerance = value

    # ------------------------------------------------------------------
    #  Cell → PageIR  (schematic pages)
    # ------------------------------------------------------------------

    def _get_page_blocks(self, cell: list) -> list[list]:
        """Return ``(page ...)`` blocks nested in cell → view → contents.

        OrCAD cap2edi exports multi-sheet schematics with every sheet as a
        ``(page (rename &NN_NAME "NN-Name") (pageSize ...) (instance ...)
        (net ...) ...)`` block that is a **direct child** of the top cell's
        view contents.  Priority is the direct children; a recursive
        fallback covers variants that wrap pages in an intermediate block.

        Args:
            cell: A ``(cell ...)`` S-expression.

        Returns:
            List of ``(page ...)`` sub-lists; empty if the cell has none.
        """
        view = _find_first(cell, "view", flatten=False)
        if view is None:
            return []
        contents = _find_first(view, "contents")
        if contents is None:
            return []
        direct = [
            item
            for item in contents
            if isinstance(item, list) and item and _sym_str(item[0]).lower() == "page"
        ]
        if direct:
            return direct
        return _find_all(contents, "page", recursive=True)

    @staticmethod
    def _page_block_name(page_block: list, page_index: int) -> str:
        """Extract the display name from ``(page (rename INTERNAL "DISPLAY") ...)``.

        OrCAD pages are named ``(page (rename &01_COVER_PAGE "01-Cover_Page")
        ...)``; the external display name (second string) is preferred.

        Args:
            page_block: A ``(page ...)`` S-expression.
            page_index: 1-based page number used as fallback name.

        Returns:
            The display name string (never empty).
        """
        if len(page_block) > 1:
            name = _edif_name(page_block[1])
            if name:
                return name
        return f"PAGE_{page_index}"

    @staticmethod
    def _page_block_size(page_block: list) -> tuple[int, int]:
        """Parse ``(pageSize (rectangle (pt x1 y1) (pt x2 y2)))`` → (width, height).

        The rectangle spans the schematic sheet; width/height are the
        absolute x/y extents.  Falls back to the legacy PageIR default
        (3520 × 2720) when the attribute is missing or malformed.

        Args:
            page_block: A ``(page ...)`` S-expression.

        Returns:
            (width, height) integer tuple.
        """
        default = (3520, 2720)
        page_size = _find_first(page_block, "pageSize")
        if not isinstance(page_size, list):
            return default
        rect = _find_first(page_size, "rectangle")
        if not isinstance(rect, list) or len(rect) < 3:
            return default
        corners: list[tuple[int, int]] = []
        for corner in rect[1:3]:
            if not (
                isinstance(corner, list)
                and len(corner) >= 3
                and _sym_str(corner[0]).lower() == "pt"
            ):
                return default
            try:
                x = int(float(_sym_str(corner[1])))
                y = int(float(_sym_str(corner[2])))
            except (TypeError, ValueError):
                return default
            corners.append((x, y))
        (x1, y1), (x2, y2) = corners
        return (abs(x2 - x1), abs(y2 - y1))

    def _parse_page(
        self,
        cell: list,
        component_db: ComponentDB,
        component_cell_names: set[str],
        page_index: int,
    ) -> list[PageIR]:
        """Parse a cell into one or more PageIR.

        Priority 1 (P0-A2): if the cell's view/contents contains
        ``(page ...)`` blocks (OrCAD multi-sheet schematic), each block is
        parsed into its own PageIR — fixing the historical "all sheets
        collapse into PageIR[0]" bug.
        Priority 2: fall back to the legacy ``_cell_is_page`` heuristic
        (single-sheet / other EDIF variants).

        Args:
            cell: A ``(cell ...)`` S-expression.
            component_db: Shared component definitions.
            component_cell_names: Registered component library ids.
            page_index: Number of pages already parsed *before* this cell
                        (0-based running counter; display ids are 1-based).

        Returns:
            List of parsed pages (empty if the cell is not a page).
        """
        page_blocks = self._get_page_blocks(cell)
        if page_blocks:
            return [
                self._parse_page_block(
                    block, component_db, component_cell_names, page_index + idx + 1
                )
                for idx, block in enumerate(page_blocks)
            ]
        if not self._cell_is_page(cell):
            return []
        return [
            self._parse_page_legacy(
                cell, component_db, component_cell_names, page_index + 1
            )
        ]

    def _parse_page_block(
        self,
        page_block: list,
        component_db: ComponentDB,
        component_cell_names: set[str],
        page_index: int,
    ) -> PageIR:
        """Parse a single ``(page ...)`` block into a PageIR (P0-A2).

        Args:
            page_block: A ``(page ...)`` S-expression.
            component_db: Shared component definitions.
            component_cell_names: Registered component library ids.
            page_index: 1-based page number for this block.

        Returns:
            A populated PageIR (instances / nets / wires / off_pages).
        """
        page_name = self._page_block_name(page_block, page_index)
        width, height = self._page_block_size(page_block)
        page = PageIR(
            page_id=f"1.{page_index}",
            page_name=page_name,
            width=width,
            height=height,
        )

        # Page blocks may carry an interface (ports) in some variants.
        interface = _find_first(page_block, "interface")
        if interface is not None:
            self._collect_page_ports(page, interface)

        # Parse instances — recursive search covers deeply nested EDIF
        # (Type B: page→[figure]→instance, depth 3+).
        inst_items = _find_all(page_block, "instance", recursive=True)
        for inst_raw in inst_items:
            inst = self._parse_instance(inst_raw, component_db, component_cell_names)
            if inst is not None:
                page.add_instance(inst)

        # Parse nets — use recursive search (same deep-nesting scenario).
        net_items = _find_all(page_block, "net", recursive=True)
        for net_raw in net_items:
            net = self._parse_net(net_raw, page_id=page.page_id)
            if net is not None:
                page.add_net(net)
                # ── Phase XI P0-A1: collect wires at page level ──
                page.wires.extend(net.wires)

        # ── Phase XI P0-A3: off-page connectors ──────────────────────
        self._collect_off_pages(page, net_items)

        return page

    def _parse_page_legacy(
        self,
        cell: list,
        component_db: ComponentDB,
        component_cell_names: set[str],
        page_index: int,
    ) -> PageIR:
        """Legacy single-cell page parse (no ``(page ...)`` blocks).

        Used as the fallback path when a page cell has no nested page
        blocks (e.g. single-sheet EDIF variants).  Behaviour is identical
        to the pre-P0-A2 ``_parse_page``.
        """
        cell_name = _sym_str(cell[1]) if len(cell) > 1 else f"PAGE_{page_index}"

        page = PageIR(
            page_id=f"1.{page_index}",
            page_name=cell_name,
        )

        view = _find_first(cell, "view", flatten=True)
        if view is None:
            logger.warning("Page cell '%s' has no view; returning empty page", cell_name)
            return page

        # interface / ports of this page (hierarchical ports)
        interface = _find_first(view, "interface")
        if interface is not None:
            self._collect_page_ports(page, interface)

        # contents → instances + nets
        contents = _find_first(view, "contents")
        if contents is None:
            logger.warning("Page cell '%s' has no contents", cell_name)
            return page

        # Parse instances — use recursive search for deeply nested EDIF
        # (Type B: cell→view→contents→[figure]→instance, depth 5+)
        inst_items = _find_all(contents, "instance", recursive=True)
        for inst_raw in inst_items:
            inst = self._parse_instance(inst_raw, component_db, component_cell_names)
            if inst is not None:
                page.add_instance(inst)

        # Parse nets — use recursive search (same deep-nesting scenario)
        net_items = _find_all(contents, "net", recursive=True)
        for net_raw in net_items:
            net = self._parse_net(net_raw, page_id=page.page_id)
            if net is not None:
                page.add_net(net)
                # ── Phase XI P0-A1: also collect wires at page level ──
                page.wires.extend(net.wires)

        # ── Phase XI P0-A3: off-page connectors ──────────────────────
        self._collect_off_pages(page, net_items)

        return page

    def _collect_page_ports(self, page: PageIR, interface: list) -> None:
        """Extract ``(port NAME (direction DIR))`` items into ``page.ports``."""
        for port in _find_all(interface, "port"):
            port_name = _sym_str(port[1]) if len(port) > 1 else ""
            direction = ""
            for sub in port[2:]:
                if isinstance(sub, list) and sub and _sym_str(sub[0]) == "direction":
                    direction = _sym_str(sub[1])
                    break
            page.ports.append({"name": port_name, "direction": direction})

    def _collect_off_pages(self, page: PageIR, net_items: list[list]) -> None:
        """Scan nets for OFF_PAGE_CONNECTOR refs → ``page.off_pages``.

        Two EDIF representations of a cross-page connector are merged
        (Phase XI P0-A3):
          1. ``(joined (portRef XXX_OFF_PAGE_CONNECTOR))`` — a net pin
             reference with no instanceRef (named networks).
          2. ``(contents (offPageConnector &_N..._OFF_PAGE_CONNECTOR))`` —
             an explicit off-page connector object inside the net's
             contents (auto-named networks, e.g. ``&_31N396766``).

        HG5015: 522 portRef + 243 offPageConnector = 765 total.
        """
        seen: set[tuple[str, str]] = {
            (op["name"], op["net_name"]) for op in page.off_pages
        }

        def _add(name: str, net_name: str) -> None:
            key = (name, net_name)
            if key not in seen:
                seen.add(key)
                page.off_pages.append({"name": name, "net_name": net_name})

        for net_raw in net_items:
            net_name = _net_name(net_raw[1]) if len(net_raw) > 1 else ""
            # 1) joined → portRef without instanceRef (named off-page pins)
            joined = _find_first(net_raw, "joined")
            if joined is not None:
                for pref in _find_all(joined, "portRef"):
                    if len(pref) < 2:
                        continue
                    pin_label = _sym_str(pref[1])
                    if (
                        "OFF_PAGE_CONNECTOR" in pin_label.upper()
                        and _find_first(pref, "instanceRef") is None
                    ):
                        _add(pin_label, net_name)
            # 2) contents → offPageConnector objects (auto-named nets)
            contents = _find_first(net_raw, "contents")
            if contents is not None:
                for offref in _find_all(contents, "offPageConnector"):
                    if len(offref) >= 2:
                        _add(_sym_str(offref[1]), net_name)

    # ------------------------------------------------------------------
    #  Instance parsing
    # ------------------------------------------------------------------

    def _parse_instance(
        self,
        inst: list,
        component_db: ComponentDB,
        component_cell_names: set[str],
    ) -> ComponentInstanceIR | None:
        """(instance REFDES (viewRef VW (cellRef CELL (libraryRef LIB))) ...) → ComponentInstanceIR."""
        if len(inst) < 2:
            return None

        # Phase XI P0-遗留#2 (2026-08-10): power symbols appear inside
        # ``(portImplementation ... (instance (rename &3V3_SOC_0 "3V3_SOC") ...))``
        # blocks.  ``_edif_name`` resolves the rename external name so the
        # VCC_CIRCLE instance keeps its net name as refdes (OrCAD stores the
        # net name as the instance name).  Plain ``(instance INS265 ...)``
        # placeholders are unaffected.
        refdes = _edif_name(inst[1])

        # extract cellRef / libraryRef from viewRef
        library_id = ""
        view_ref = _find_first(inst, "viewRef")
        if view_ref:
            cell_ref = _find_first(view_ref, "cellRef")
            if cell_ref and len(cell_ref) >= 2:
                library_id = _sym_str(cell_ref[1])

        # Look up the component definition
        comp_def = component_db.get_by_library_id(library_id) if library_id else None

        # Build the instance
        instance = ComponentInstanceIR(
            refdes=refdes,
            library_id=library_id,
        )

        # Phase XI P0-遗留#2: extract the placement origin from
        # ``(transform (origin (pt x y)))`` — power symbols carry their real
        # placement here (e.g. GND at (1020,-610)); regular components rely
        # on the CrossRef catalog coordinates, so this is a no-op for them.
        _transform = _find_first(inst, "transform")
        if _transform is not None:
            _origin = _find_first(_transform, "origin")
            if _origin is not None:
                _pt = _find_first(_origin, "pt")
                if _pt is not None and len(_pt) >= 3:
                    try:
                        instance.loc_x = int(_pt[1])
                        instance.loc_y = int(_pt[2])
                    except (TypeError, ValueError):
                        pass
            # Phase XI P1-4: extract rotation / mirror from the EDIF
            # orientation.  EDIF uses ``(orientation R90)`` / ``R180`` /
            # ``R270`` for rotation and ``MY`` / ``MX`` / ``MYR90`` for
            # mirrors — captured so writers can place components with the
            # correct orientation.
            _orient = _find_first(_transform, "orientation")
            if _orient is not None and len(_orient) >= 2:
                orient = str(_orient[1]).upper()
                # Rotation: R90 → 90, R180 → 180, R270 → 270
                m_rot = re.match(r"R(\d+)$", orient)
                if m_rot:
                    instance.rotation = int(m_rot.group(1))
                elif "R90" in orient:
                    instance.rotation = 90
                # Mirror: MY / MX (optionally combined with rotation)
                if orient.startswith("MY"):
                    instance.mirror = 2
                elif orient.startswith("MX"):
                    instance.mirror = 1

        # Extract properties
        for item in inst:
            if not _is_property(item):
                continue
            name, value = _parse_property_kv(item)
            if not name:
                continue

            instance.properties[name] = value

            name_upper = name.upper()
            if name_upper == "VALUE" and not instance.value_override:
                instance.value_override = value

        # Inherit pin info from component definition for pin_connections initialization
        if comp_def is not None:
            for pin in comp_def.pins:
                instance.pin_connections[pin.number] = ""  # unconnected by default

        return instance

    # ------------------------------------------------------------------
    #  Net parsing
    # ------------------------------------------------------------------

    def _parse_net(self, net: list, page_id: str = "") -> NetIR | None:
        """(net NAME (joined (portRef N (instanceRef R)) ...)) → NetIR.

        Phase XI P0-A1: also extracts ``(figure WIRE (path (pointList
        (pt x y) ...)))`` polylines owned by this net and stores them on
        ``net_ir.wires`` (list[WireSegment]), so the connectivity layer can
        emit ``WIRE 16 -1 (x1 y1)(x2 y2);`` CSA commands.
        """
        if len(net) < 2:
            return None

        net_name = _net_name(net[1])

        connections: list[NetConnection] = []
        joined = _find_first(net, "joined")
        if joined:
            port_refs = _find_all(joined, "portRef")
            for pref in port_refs:
                if len(pref) < 2:
                    continue
                pin_number = _sym_str(pref[1])

                refdes = ""
                inst_ref = _find_first(pref, "instanceRef")
                if inst_ref and len(inst_ref) >= 2:
                    refdes = _sym_str(inst_ref[1])

                connections.append(NetConnection(refdes=refdes, pin_number=pin_number))

        category = self._classify_net(net_name)

        # ── Phase XI P0-A1: extract figure WIRE polylines ─────────────
        wires: list[WireSegment] = []
        figure_items = _find_all(net, "figure", recursive=False)
        for fig in figure_items:
            if len(fig) < 2 or _sym_str(fig[1]) != "WIRE":
                continue
            pts = self._extract_wire_points(fig)
            if len(pts) >= 2:
                wires.append(WireSegment(points=pts, net_name=net_name, page_id=page_id))

        net_ir = NetIR(
            name=net_name,
            category=category,
            connections=connections,
            is_bus=(category == NetCategory.BUS),
            wires=wires,
        )

        return net_ir

    @staticmethod
    def _extract_wire_points(figure: list) -> list[tuple[int, int]]:
        """Extract polyline vertices from ``(figure WIRE (path (pointList
        (pt x y) ...)))``.

        Args:
            figure: The (figure WIRE ...) sublist.

        Returns:
            Ordered list of (x, y) integer points; empty if no valid path.
        """
        path = _find_first(figure, "path")
        if path is None:
            return []
        point_list = _find_first(path, "pointList")
        if point_list is None:
            return []
        pts: list[tuple[int, int]] = []
        for sub in point_list[1:]:
            if isinstance(sub, list) and sub and _sym_str(sub[0]) == "pt" and len(sub) >= 3:
                try:
                    x = int(float(_sym_str(sub[1])))
                    y = int(float(_sym_str(sub[2])))
                except (TypeError, ValueError):
                    continue
                pts.append((x, y))
        return pts

    # ------------------------------------------------------------------
    #  Net classification (ISCF)
    # ------------------------------------------------------------------

    @staticmethod
    def _classify_net(name: str) -> NetCategory:
        """ISCF 4-class classification.

        - GROUND if name matches known ground synonyms
        - POWER  if name starts with a power prefix
        - BUS    if name contains `[` / `(` (bus notation)
        - FLAT   otherwise
        """
        upper = name.upper().strip()

        if upper in GROUND_NAMES:
            return NetCategory.GROUND

        if any(upper.startswith(prefix) for prefix in POWER_PREFIXES):
            return NetCategory.POWER

        if "[" in name or "(" in name:
            return NetCategory.BUS

        return NetCategory.FLAT

    # ------------------------------------------------------------------
    #  Pin→Net mapping extraction (v0.6.0 — for CSA pin connection injection)
    # ------------------------------------------------------------------

    @staticmethod
    def extract_pin_net_map(edf_path: Path) -> dict[str, dict[str, str]]:
        """Extract {refdes: {pin_number: net_name}} from EDIF netlist.

        This is a lightweight extraction that reads only net definitions,
        skipping component and page construction for speed.  Used to
        inject pin_connections into ComponentInstanceIR before CSA generation.

        Args:
            edf_path: Path to the EDIF file.

        Returns:
            Dict mapping ``refdes → {pin_number: net_name}``.
        """
        if not edf_path.exists():
            logger.debug("EDIF not found at %s — skipping pin map", edf_path)
            return {}

        raw_text = edf_path.read_text(encoding="utf-8", errors="replace")
        raw_text = raw_text.replace('\\\\', '/').replace('\\', '/')

        try:
            tree = loads(raw_text)
        except Exception as exc:
            logger.warning("EDIF pin map: parse failed — %s", exc)
            return {}

        if not isinstance(tree, list) or not tree:
            return {}

        pin_map: dict[str, dict[str, str]] = {}

        # Recursively find all (net ...) blocks anywhere in the tree.
        # Nets may be deeply nested: cell → view → contents → page → contents → net
        def _find_all_nets(node, depth: int = 0) -> list[list]:
            """Recursively find all (net ...) sublists within *node*."""
            results: list[list] = []
            if not isinstance(node, list) or depth > 20:
                return results
            for child in node:
                if isinstance(child, list) and child:
                    tag = _sym_str(child[0])
                    if tag == "net":
                        results.append(child)
                    else:
                        results.extend(_find_all_nets(child, depth + 1))
            return results

        all_nets = _find_all_nets(tree)
        logger.info("EDIF pin map: scanning %d net(s) from tree", len(all_nets))

        for net_item in all_nets:
            net_ir = EDIFParser._parse_net_raw(net_item)
            if net_ir is not None:
                net_name = net_ir["name"]
                for conn in net_ir["connections"]:
                    refdes = conn.get("refdes", "")
                    pin = conn.get("pin_number", "")
                    if refdes and pin:
                        if refdes not in pin_map:
                            pin_map[refdes] = {}
                        if pin not in pin_map[refdes]:
                            pin_map[refdes][pin] = net_name

        # ── Build INSxxx → real_refdes mapping from (instance ...) blocks ──
        ins_to_refdes: dict[str, str] = {}
        def _find_all_instances(node, depth: int = 0) -> list[list]:
            results: list[list] = []
            if not isinstance(node, list) or depth > 20:
                return results
            for child in node:
                if isinstance(child, list) and child:
                    tag = _sym_str(child[0])
                    if tag == "instance":
                        results.append(child)
                    else:
                        results.extend(_find_all_instances(child, depth + 1))
            return results

        # ── Helper: check if a string looks like a real refdes ──
        # Refdes patterns: C122, R42, L3, U6G, D18, J26, TP12, M5, Z1, X2, etc.
        _RE_REFDES = re.compile(r"^[CRLDUTJTPMZX]\w*\d")

        for inst_item in _find_all_instances(tree):
            if len(inst_item) < 2:
                continue
            ins_id = _sym_str(inst_item[1])

            # Strategy 1: Find PART_REFERENCE or REFDES property.
            # EDIF from OrCAD uses (property (rename PART_REFERENCE "Part Reference") (string "C106"))
            # Other EDIF variants may use (property REFDES (string "C122"))
            for prop in inst_item:
                if not isinstance(prop, list) or len(prop) < 3:
                    continue
                if _sym_str(prop[0]) != "property":
                    continue

                # Handle (rename PART_REFERENCE "Part Reference") syntax
                prop_name = ""
                if isinstance(prop[1], list) and _sym_str(prop[1][0]) == "rename":
                    # (property (rename INTERNAL "External") ...)
                    if len(prop[1]) >= 2:
                        prop_name = _sym_str(prop[1][1])
                else:
                    prop_name = _sym_str(prop[1])

                if prop_name.upper() in ("REFDES", "PART_REFERENCE"):
                    val = _parse_property_value(prop)
                    if val:
                        ins_to_refdes[ins_id] = val
                        break

            # Strategy 2: Fallback to designator stringDisplay
            # (designator (stringDisplay "C106" (display ...)))
            if ins_id not in ins_to_refdes:
                for item in inst_item:
                    if not isinstance(item, list) or not item:
                        continue
                    if _sym_str(item[0]) == "designator":
                        if len(item) >= 2 and isinstance(item[1], list):
                            display = item[1]
                            if (_sym_str(display[0]) == "stringDisplay"
                                    and len(display) >= 2):
                                val = _sym_str(display[1])
                                if val and _RE_REFDES.match(val):
                                    ins_to_refdes[ins_id] = val
                        break

        # ── Remap pin_map keys from INSxxx → real refdes ──
        if ins_to_refdes:
            remapped: dict[str, dict[str, str]] = {}
            unmapped_count = 0
            for ins_id, pins in pin_map.items():
                real_refdes = ins_to_refdes.get(ins_id, ins_id)
                if real_refdes == ins_id:
                    unmapped_count += 1
                if real_refdes not in remapped:
                    remapped[real_refdes] = {}
                for pin, net in pins.items():
                    if pin not in remapped[real_refdes]:
                        remapped[real_refdes][pin] = net
            pin_map = remapped
            logger.info(
                "EDIF pin map: remapped %d INSxxx IDs → %d real refdes "
                "(%d remaining unmapped)",
                len(ins_to_refdes), len(pin_map), unmapped_count,
            )
        else:
            # No INSxxx→real_refdes mapping found — pin_map keys remain
            # as EDIF internal IDs.  The HG5015 EDIF stores real refdes
            # only as display strings, not structured properties.
            # Pin injection will skip these since they don't match
            # CrossRef CSV refdes keys.
            logger.debug(
                "EDIF pin map: no INSxxx→real_refdes mapping available "
                "(real refdes stored as display strings only)"
            )

        logger.info(
            "EDIF pin map: %d refdes → %d total pin connections",
            len(pin_map),
            sum(len(pins) for pins in pin_map.values()),
        )
        return pin_map

    @staticmethod
    def _parse_net_raw(net: list) -> dict | None:
        """Parse (net NAME (joined ...)) → {name, connections} without NetIR.

        Returns:
            Dict with 'name' and 'connections' keys, or None.
        """
        if len(net) < 2:
            return None
        net_name = _net_name(net[1])
        connections: list[dict] = []
        joined = _find_first(net, "joined")
        if joined:
            port_refs = _find_all(joined, "portRef")
            for pref in port_refs:
                if len(pref) < 2:
                    continue
                pin_number = _sym_str(pref[1])
                refdes = ""
                inst_ref = _find_first(pref, "instanceRef")
                if inst_ref and len(inst_ref) >= 2:
                    refdes = _sym_str(inst_ref[1])
                connections.append({"refdes": refdes, "pin_number": pin_number})
        return {"name": net_name, "connections": connections}

    # ------------------------------------------------------------------
    #  Registration helper
    # ------------------------------------------------------------------

    @classmethod
    def register(cls) -> None:
        """Register this parser in the global ParserRegistry."""
        from .base import ParserRegistry

        ParserRegistry.register(cls())
