"""PstchipParser — parse OrCAD pstchip.dat LIBRARY_PARTS files.

The pstchip.dat file is generated by OrCAD Capture's PSTWRITER and contains
the LIBRARY_PARTS section with primitive definitions.  Each primitive maps
a symbolic name (e.g. ``C_HSC0201-HDTA_8.2PF``) to its electrical attributes
(PART_NAME, JEDEC_TYPE, VALUE) and pin numbers.

This data is used to enrich component matching with precise package size
(JEDEC_TYPE) and electrical value (VALUE) information from the PCB netlist.

Format reference:
    tests/fixtures/pstchip_sample.dat (if available)

Usage::

    from cis2hdl.core.parser.pstchip_parser import PstchipParser
    parser = PstchipParser()
    pstchip_map = parser.parse(Path("pstchip.dat"))
    entry = pstchip_map.get("C_HSC0201-HDTA_8.2PF")
    print(entry.jedec_type)   # → "HSC0201-HDTA"
    print(entry.value)        # → "8.2pF"
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)


# ============================================================
#  PstchipEntry — parsed primitive from pstchip.dat
# ============================================================


@dataclass
class PstchipEntry:
    """A single primitive entry from the LIBRARY_PARTS section.

    Attributes:
        primitive_name: Symbolic name in single quotes (e.g. "C_HSC0201-HDTA_8.2PF").
        part_name: Component category — "C" (capacitor), "R" (resistor), etc.
        jedec_type: JEDEC package type (e.g. "HSC0201-HDTA", "RSC0402").
        value: Electrical value string (e.g. "8.2pF", "10K", "NC").
        pins: Mapping of pin name → pin number (e.g. {"A": "1", "B": "2"}).
        pin_sections: For multi-section parts (e.g. a 9-section SoC), maps a
            BGA pin value → list of section letters that pin belongs to.
            Derived from the multi-position PIN_NUMBER tuple
            ``'(BGA,secA,secB,...)'`` (position 1 = section A, ...).
    """

    primitive_name: str = ""
    part_name: str = ""
    jedec_type: str = ""
    value: str = ""
    pins: dict[str, str] = field(default_factory=dict)
    pin_sections: dict[str, list[str]] = field(default_factory=dict)


# ============================================================
#  Regex patterns (compiled once at module level)
# ============================================================

# Parsing states
_IDLE = 0
_IN_PRIMITIVE = 1
_IN_PIN = 2
_IN_BODY = 3

# Matches: primitive 'C_HSC0201-HDTA_8.2PF*';
_RE_PRIMITIVE_HEADER = re.compile(r"^\s*primitive\s+'([^']+)'\s*;?\s*$")

# Matches pin definitions split across lines:
# Line 1: 'A':
# Line 2: PIN_NUMBER='(1)';
# Or on one line: 'A': PIN_NUMBER='(1)';
_RE_PIN_NAME = re.compile(r"^\s*'([^']+)'\s*:\s*$")
_RE_PIN_NUM = re.compile(r"^\s*PIN_NUMBER\s*=\s*'\((\d+)\)'\s*;?\s*$")
# Combined form (single line)
_RE_PIN_DEF = re.compile(r"'([^']+)'\s*:\s*PIN_NUMBER\s*=\s*'\((\d+)\)'\s*;?")
# v2.1: multi-position PIN_NUMBER tuple for sectioned parts:
#   PIN_NUMBER='(N3,0,0,0,0,0,0,0,0)'  → 9 positions = sections A..I
_RE_PIN_NUM_TUPLE = re.compile(r"^\s*PIN_NUMBER\s*=\s*'\(([^)]*)\)'\s*;?\s*$")

# Matches body attribute lines:
#   body PART_NAME='C'; JEDEC_TYPE='HSC0201-HDTA'; VALUE='8.2pF*';
_RE_BODY_ATTR = re.compile(r"(\w+)\s*=\s*'([^']*)'")

# Matches end_primitive marker
_RE_END_PRIMITIVE = re.compile(r"^\s*end_primitive\s*;?\s*$")


def _tuple_to_sections(pin_number_tuple: str) -> dict[str, list[str]]:
    """Map BGA pin values → section letters from a multi-position tuple.

    OrCAD encodes a multi-section part (e.g. a 9-section SoC) as a single
    primitive whose ``PIN_NUMBER`` is a comma-separated tuple with one
    position per section::

        PIN_NUMBER='(N3,0,0,0,0,0,0,0,0)'   # N3 → section A only
        PIN_NUMBER='(0,AG23,0,0,0,0,0,0,0)' # AG23 → section B only

    Position 1 = section A, position 2 = section B, ... up to position 26.
    A non-zero value at a position means that BGA pin exists in that section.

    Args:
        pin_number_tuple: Raw inner text of a PIN_NUMBER tuple (no parens).

    Returns:
        Mapping of BGA pin value → sorted list of section letters.  Empty
        dict if the tuple is not multi-position (single-pin primitives).
    """
    parts = [p.strip() for p in pin_number_tuple.split(",")]
    if len(parts) <= 1:
        return {}
    result: dict[str, list[str]] = {}
    for idx, val in enumerate(parts, 1):
        if not val or val == "0" or idx > 26:
            continue
        letter = chr(64 + idx)
        result.setdefault(val, []).append(letter)
    for letters in result.values():
        letters.sort()
    return result


# ============================================================
#  PstchipParser
# ============================================================


class PstchipParser:
    """Parser for OrCAD pstchip.dat LIBRARY_PARTS files.

    Uses a state-machine approach to parse primitive blocks with their
    pin definitions and body attributes.

    State flow: IDLE → IN_PRIMITIVE → (IN_PIN | IN_BODY) → IDLE

    Attributes:
        ENCODING: "latin-1" — consistent with other PST parsers.
    """

    ENCODING: str = "latin-1"

    def parse(self, file_path: Path) -> dict[str, PstchipEntry]:
        """Parse a pstchip.dat file into a primitive_name → PstchipEntry map.

        If the file does not exist or cannot be parsed, returns an empty
        dict (no exception raised — pstchip is an optional data source).

        Args:
            file_path: Path to the pstchip.dat file.

        Returns:
            dict mapping primitive_name → PstchipEntry.
        """
        if not file_path.exists():
            logger.debug("pstchip file not found: %s — skipping", file_path)
            return {}

        try:
            with open(file_path, "r", encoding=self.ENCODING, errors="replace") as fh:
                content: str = fh.read()
        except (OSError, UnicodeDecodeError) as exc:
            logger.warning(
                "Failed to read pstchip file %s: %s — returning empty",
                file_path, exc,
            )
            return {}

        result: dict[str, PstchipEntry] = self._parse_content(content)
        logger.info(
            "PstchipParser: %d primitive(s) parsed from %s",
            len(result), file_path.name,
        )
        return result

    # ------------------------------------------------------------------
    #  Internal parsing
    # ------------------------------------------------------------------

    @staticmethod
    def _parse_content(content: str) -> dict[str, PstchipEntry]:
        """Parse pstchip.dat content using a state machine.

        Args:
            content: Raw file content as a string.

        Returns:
            dict of primitive_name → PstchipEntry.
        """
        result: dict[str, PstchipEntry] = {}
        state: int = _IDLE
        current_entry: PstchipEntry | None = None
        _pin_name_pending: str = ""  # v0.8.1: multi-line pin support

        for line in content.splitlines():
            stripped: str = line.strip()

            # Skip empty lines and comments
            if not stripped or stripped.startswith("{") or stripped.startswith("--"):
                continue

            # ── Detect end_primitive ──
            if _RE_END_PRIMITIVE.match(stripped):
                if current_entry is not None and current_entry.primitive_name:
                    result[current_entry.primitive_name] = current_entry
                current_entry = None
                state = _IDLE
                continue

            # ── Detect primitive header ──
            m_prim = _RE_PRIMITIVE_HEADER.match(stripped)
            if m_prim:
                current_entry = PstchipEntry(primitive_name=m_prim.group(1))
                state = _IN_PRIMITIVE
                continue

            # ── Inside a primitive block ──
            if state in (_IN_PRIMITIVE, _IN_PIN, _IN_BODY) and current_entry is not None:
                # Detect pin name line — can appear in _IN_PRIMITIVE state
                m_pname = _RE_PIN_NAME.match(stripped)
                if m_pname and "PIN_NUMBER" not in stripped:
                    _pin_name_pending = m_pname.group(1)
                    state = _IN_PIN
                    continue

                # Detect pin number line
                if "PIN_NUMBER" in stripped or state == _IN_PIN:
                    # Try combined form first: 'A': PIN_NUMBER='(1)';
                    combined = _RE_PIN_DEF.findall(stripped)
                    if combined:
                        for pn, pnum in combined:
                            current_entry.pins[pn] = pnum
                        state = _IN_PIN
                        _pin_name_pending = ""
                        continue

                    # Multi-line: PIN_NUMBER — pair with pending pin name.
                    # Handles both single-pin '(1)' and multi-section
                    # tuples '(BGA,secA,secB,...)' for sectioned parts.
                    m_pnum = _RE_PIN_NUM_TUPLE.match(stripped)
                    if m_pnum and _pin_name_pending:
                        sections = _tuple_to_sections(m_pnum.group(1))
                        if sections:
                            for bga_pin, letters in sections.items():
                                existing = current_entry.pin_sections.setdefault(bga_pin, [])
                                for letter in letters:
                                    if letter not in existing:
                                        existing.append(letter)
                                existing.sort()
                        else:
                            current_entry.pins[_pin_name_pending] = m_pnum.group(1)
                        _pin_name_pending = ""
                        state = _IN_PIN
                        continue

                    # PIN_NUMBER without pending name or other — skip

                # Detect body line
                if "PART_NAME" in stripped or "JEDEC_TYPE" in stripped or "VALUE" in stripped:
                    for m_attr in _RE_BODY_ATTR.finditer(stripped):
                        attr_name: str = m_attr.group(1)
                        attr_value: str = m_attr.group(2)
                        if attr_name == "PART_NAME":
                            current_entry.part_name = attr_value
                        elif attr_name == "JEDEC_TYPE":
                            current_entry.jedec_type = attr_value
                        elif attr_name == "VALUE":
                            current_entry.value = attr_value
                    state = _IN_BODY
                    continue

        # ── Handle unclosed primitive at EOF ──
        if current_entry is not None and current_entry.primitive_name:
            result[current_entry.primitive_name] = current_entry

        return result
