"""PstxnetParser — parse OrCAD pstxprt.dat files for refdes→primitive mapping.

The pstxprt.dat file is generated by OrCAD Capture's PSTWRITER (EXPANDEDPARTLIST
format) and maps reference designators to part names, hierarchical sections,
and internal instance IDs (INSxxx).

v0.8.1: Rewritten to handle multi-line PART_NAME format.  Also extracts
INSxxx identifiers from C_PATH/P_PATH for bridging with pstxnet.dat
and EDIF files.

Format::

    PART_NAME
     C1 'C_SC0603-TD_10UF':;
    SECTION_NUMBER 1
     '@HG5015-BE36_V10...INS32276@LIBRARY1.C.NORMAL(CHIPS)':
     C_PATH='@\\...ins32276@...',
     PRIM_FILE='.\\pstchip.dat',
     SECTION='';

Usage::

    from cis2hdl.core.parser.pstxnet_parser import PstxnetParser
    parser = PstxnetParser()
    ir = parser.parse(Path("project_pstxprt.dat"))
    entries = ir.metadata.get("pstxnet_entries", [])
    ins_map = ir.metadata.get("ins_to_refdes", {})
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path

from .base import ParserBase, ParserRegistry
from ..ir.design import DesignIR

logger = logging.getLogger(__name__)


# ============================================================
#  PstxprtEntry — parsed entry from pstxprt.dat
# ============================================================


@dataclass
class PstxprtEntry:
    """A single part-section entry from pstxprt.dat.

    Attributes:
        refdes: Reference designator (e.g. "C1", "R5", "LED2").
        part_name: CIS primitive name (e.g. "C_SC0603-TD_10UF").
        ins_id: Internal OrCAD instance ID from C_PATH (e.g. "INS32276").
        section: Section letter (e.g. "1", "A").
        prim_file: PRIM_FILE reference (e.g. ".\\\\pstchip.dat").
        signal_model: SIGNAL_MODEL value if present.
    """

    refdes: str = ""
    part_name: str = ""
    ins_id: str = ""
    section: str = ""
    prim_file: str = ""
    signal_model: str = ""


# ============================================================
#  State machine constants
# ============================================================

_S_IDLE = 0
_S_PART_NAME_LINE = 1   # Saw "PART_NAME", expecting refdes line
_S_IN_SECTION = 2       # Inside SECTION_NUMBER block
_S_END = 3


# ============================================================
#  Regex patterns
# ============================================================

# PART_NAME header line (keyword alone)
_RE_PART_NAME_HDR = re.compile(r"^\s*PART_NAME\s*$")

# Refdes + primitive line: " C1 'C_SC0603-TD_10UF':;"
# or: " C100 'C_HSC0201-HDTA_100NF':"  (SIGNAL_MODEL follows on same line)
_RE_PART_BODY = re.compile(
    r"^\s*(\S+)\s+'([^']+)'\s*:?;?\s*$"
)

# Matches SIGNAL_MODEL='VALUE' on the same or next line
_RE_SIGNAL_MODEL = re.compile(r"SIGNAL_MODEL\s*=\s*'([^']*)'")

# Matches SECTION_NUMBER N
_RE_SECTION_NUM = re.compile(r"^\s*SECTION_NUMBER\s+(\S+)")

# Matches INSxxx from paths:
# '@...INS32276@...' or '...:ins32276@...'
_RE_INS_ID = re.compile(r"[Ii][Nn][Ss](\d+)")

# Matches C_PATH line
_RE_C_PATH = re.compile(r"C_PATH\s*=\s*'([^']*)'")

# Matches PRIM_FILE line
_RE_PRIM_FILE = re.compile(r"PRIM_FILE\s*=\s*'([^']*)'")

# Matches SECTION line
_RE_SECTION_VAL = re.compile(r"SECTION\s*=\s*'([^']*)'")

# Lines to skip
_RE_SKIP = re.compile(
    r"^\s*(?:FILE_TYPE|DIRECTIVES|END_DIRECTIVES|END\.|\{)"
)


# ============================================================
#  PstxnetParser (pstxprt.dat parser)
# ============================================================


class PstxnetParser(ParserBase):
    """Parser for OrCAD pstxprt.dat files (EXPANDEDPARTLIST format).

    Extracts refdes → part_name → INSxxx → section mappings.
    Also builds an INSxxx → refdes lookup table for bridging
    with pstxnet.dat and EDIF netlist files.

    Attributes:
        FORMAT_NAME: "PSTXPRT" (registered format name).
        FILE_EXTENSIONS: [".dat"].
    """

    FORMAT_NAME: str = "PSTXPRT"
    FILE_EXTENSIONS: list[str] = [".dat"]

    # ------------------------------------------------------------------
    #  Core parse interface
    # ------------------------------------------------------------------

    def parse(self, file_path: Path) -> DesignIR:
        """Parse a pstxprt.dat file.

        Returns:
            DesignIR with metadata keys:
            - "pstxnet_entries": list of PstxprtEntry
            - "ins_to_refdes": dict mapping INSxxx → refdes
        """
        ir = DesignIR(
            project_name=file_path.stem,
            source_format="PSTXPRT",
        )

        if not file_path.exists():
            logger.debug("pstxprt file not found: %s — skipping", file_path)
            ir.metadata["pstxnet_entries"] = []
            ir.metadata["ins_to_refdes"] = {}
            return ir

        try:
            with open(file_path, "r", encoding="latin-1", errors="replace") as f:
                content = f.read()
        except (OSError, UnicodeDecodeError) as exc:
            logger.warning(
                "Failed to read pstxprt file %s: %s",
                file_path, exc,
            )
            ir.metadata["pstxnet_entries"] = []
            ir.metadata["ins_to_refdes"] = {}
            return ir

        entries, ins_to_refdes = self._parse_content(content)

        logger.info(
            "PstxnetParser: %d entries, %d INSxxx→refdes from %s",
            len(entries), len(ins_to_refdes), file_path.name,
        )
        ir.metadata["pstxnet_entries"] = entries
        ir.metadata["ins_to_refdes"] = ins_to_refdes
        return ir

    # ------------------------------------------------------------------
    #  Internal parsing — state machine for multi-line format
    # ------------------------------------------------------------------

    @staticmethod
    def _parse_content(
        content: str,
    ) -> tuple[list[PstxprtEntry], dict[str, str]]:
        """Parse pstxprt.dat using a multi-line-aware state machine.

        State flow:
            IDLE → (PART_NAME keyword) → PART_NAME_LINE
            → (refdes line) → IN_SECTION → (SECTION='') → IDLE

        Also builds INSxxx → refdes lookup from C_PATH identifiers.

        Returns:
            (entries list, ins_to_refdes dict).
        """
        entries: list[PstxprtEntry] = []
        ins_to_refdes: dict[str, str] = {}
        state: int = _S_IDLE
        current: PstxprtEntry | None = None
        last_refdes: str = ""      # v2.1: for multi-section continuation
        last_part_name: str = ""

        for line in content.splitlines():
            stripped = line.strip()

            # Skip empty lines, comments, headers
            if not stripped or _RE_SKIP.match(stripped):
                continue

            # ── State: IDLE — look for "PART_NAME" header ──
            if state == _S_IDLE:
                if _RE_PART_NAME_HDR.match(stripped):
                    state = _S_PART_NAME_LINE
                    continue
                # v2.1: Multi-section part continuation — after the previous
                # section's SECTION='X' completes, a new SECTION_NUMBER N
                # block for the SAME refdes appears.  Resume it with the
                # same refdes/part_name instead of dropping every line.
                if _RE_SECTION_NUM.match(stripped) and last_refdes:
                    current = PstxprtEntry(
                        refdes=last_refdes,
                        part_name=last_part_name,
                    )
                    state = _S_IN_SECTION
                    continue
                continue

            # ── State: PART_NAME_LINE — look for refdes line ──
            if state == _S_PART_NAME_LINE:
                m_body = _RE_PART_BODY.match(stripped)
                if m_body:
                    refdes = m_body.group(1)
                    part_name = m_body.group(2)

                    # Check for SIGNAL_MODEL on same line (comma-separated)
                    sm_match = _RE_SIGNAL_MODEL.search(stripped)
                    signal_model = sm_match.group(1) if sm_match else ""

                    current = PstxprtEntry(
                        refdes=refdes,
                        part_name=part_name,
                        signal_model=signal_model,
                    )
                    state = _S_IN_SECTION
                    continue
                # Not a refdes line — reset
                state = _S_IDLE
                continue

            # ── State: IN_SECTION — collect section-level data ──
            if state == _S_IN_SECTION and current is not None:
                # Extract INSxxx from @HG5015...INS32276@...
                for m_ins in _RE_INS_ID.finditer(stripped):
                    ins_key = f"INS{m_ins.group(1)}"
                    ins_to_refdes[ins_key.upper()] = current.refdes.upper()

                # C_PATH
                m_cp = _RE_C_PATH.search(stripped)
                if m_cp:
                    # Also extract from C_PATH for redundancy
                    for m_ins2 in _RE_INS_ID.finditer(m_cp.group(1)):
                        ins_key2 = f"INS{m_ins2.group(1)}"
                        ins_to_refdes[ins_key2.upper()] = current.refdes.upper()

                # SIGNAL_MODEL on a separate line
                m_sm = _RE_SIGNAL_MODEL.search(stripped)
                if m_sm and not current.signal_model:
                    current.signal_model = m_sm.group(1)

                # PRIM_FILE
                m_pf = _RE_PRIM_FILE.search(stripped)
                if m_pf:
                    current.prim_file = m_pf.group(1)

                # SECTION value
                m_sv = _RE_SECTION_VAL.search(stripped)
                if m_sv:
                    current.section = m_sv.group(1)
                    entries.append(current)
                    # Remember for multi-section continuation (v2.1)
                    last_refdes = current.refdes
                    last_part_name = current.part_name
                    current = None
                    state = _S_IDLE
                continue

        # Handle unclosed entry at EOF
        if current is not None:
            entries.append(current)

        return entries, ins_to_refdes

    # ------------------------------------------------------------------
    #  pstchip lookup builder (Phase IX)
    # ------------------------------------------------------------------

    @staticmethod
    def build_pstchip_lookup(
        pstxprt_entries: list[PstxprtEntry],
        pstchip_map: dict,
    ) -> dict[str, object]:
        """Build refdes → pstchip entry lookup from pstxprt + pstchip data.

        For each pstxprt entry (refdes → primitive name), look up the
        corresponding primitive definition in pstchip_map to enrich
        component matching with JEDEC_TYPE and precise VALUE.

        Args:
            pstxprt_entries: Parsed entries from pstxprt.dat.
            pstchip_map: Primitive name → PstchipEntry from pstchip_parser.

        Returns:
            dict mapping refdes → PstchipEntry (or empty dict if no data).
        """
        if not pstxprt_entries or not pstchip_map:
            return {}

        result: dict[str, object] = {}
        for entry in pstxprt_entries:
            if entry.part_name and entry.part_name in pstchip_map:
                result[entry.refdes.upper()] = pstchip_map[entry.part_name]
            else:
                clean_name = entry.part_name.replace("*", "").replace("_", "_")
                if clean_name in pstchip_map:
                    result[entry.refdes.upper()] = pstchip_map[clean_name]
                else:
                    # Try without value suffix: "C_SC0603-TD_10UF" → "C_SC0603-TD"
                    base = re.sub(r"_\d+\.?\d*[A-Za-z]*\**$", "", entry.part_name)
                    if base and base in pstchip_map:
                        result[entry.refdes.upper()] = pstchip_map[base]

        logger.info(
            "build_pstchip_lookup: %d refdes → pstchip entries resolved "
            "from %d pstxprt entries",
            len(result), len(pstxprt_entries),
        )
        return result

    # ------------------------------------------------------------------
    #  Registration
    # ------------------------------------------------------------------

    @classmethod
    def register(cls) -> None:
        """Register this parser in the global ParserRegistry."""
        ParserRegistry.register(cls())


# ── Auto-register at import time ──────────────────────────────────────────
PstxnetParser.register()
