// generated by newgenasym  Mon Mar 25 14:11:18 2024


module rtxm169 (ms1, ms2, ms3, ms4, ms5, ms6, nc1, nc2, nc3, \rd+ , \rd- , scl, sd,
        sda, \td+ , \td- , tx_brst, unknow, vccr, vcct, veer, veet, vss1,
        vss2, vss3, vss4);
    input ms1;
    input ms2;
    inout ms3;
    inout ms4;
    inout ms5;
    inout ms6;
    inout nc1;
    inout nc2;
    inout nc3;
    output \rd+ ;
    output \rd- ;
    input scl;
    output sd;
    inout sda;
    input \td+ ;
    input \td- ;
    input tx_brst;
    inout unknow;
    input vccr;
    input vcct;
    inout veer;
    input veet;
    input vss1;
    input vss2;
    input vss3;
    input vss4;


    initial
        begin
        end

endmodule
