// generated by newgenasym  Mon Aug 31 11:13:46 2020


module ad7170 (ain_n, ain_p, \dout/rdy , epad, gnd_1, gnd_2, pdrst, refin_n,
        refin_p, sclk, vdd);
    input ain_n;
    input ain_p;
    output \dout/rdy ;
    input epad;
    input gnd_1;
    input gnd_2;
    input pdrst;
    input refin_n;
    input refin_p;
    input sclk;
    input vdd;


    initial
        begin
        end

endmodule
