-- generated by newgenasym Mon Aug 31 11:13:46 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad7170 is
    port (    
	AIN_N:     IN     STD_LOGIC;    
	AIN_P:     IN     STD_LOGIC;    
	\dout/rdy\: OUT    STD_LOGIC;    
	EPAD:      IN     STD_LOGIC;    
	GND_1:     IN     STD_LOGIC;    
	GND_2:     IN     STD_LOGIC;    
	PDRST:     IN     STD_LOGIC;    
	REFIN_N:   IN     STD_LOGIC;    
	REFIN_P:   IN     STD_LOGIC;    
	SCLK:      IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end ad7170;
