// generated by newgenasym  Mon Aug 31 14:16:48 2020


module reset (gnd, \mr# , pfi, \pfo# , reset, vcc, wdi, \wdo# );
    input gnd;
    input \mr# ;
    input pfi;
    output \pfo# ;
    output reset;
    input vcc;
    input wdi;
    output \wdo# ;


    initial
        begin
        end

endmodule
