// generated by newgenasym  Mon Aug 31 14:16:05 2020


module pq2016 (\-28v , \-56v , \-80v , gnd, in1, in2, in3, in4, nc1, nc2, nc3, nc4,
        nc5, nc6);
    output \-28v ;
    output \-56v ;
    output \-80v ;
    output gnd;
    input in1;
    input in2;
    input in3;
    input in4;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;


    initial
        begin
        end

endmodule
