// generated by newgenasym  Tue Nov 02 15:16:21 2021


module ux3328 (benn, benp, biasn, biasp, dao, epad, gnd_rx1, gnd_rx2,
        gnd_tx1, gnd_tx2, irop, lain, laip, laon, laop, ldin, ldip,
        ldon, ldop, los_sd, md, rref, scl, scl_e, sda, sda_e,
        tx_disable, tx_fault, tx_sdo, vdd_rx1, vdd_rx2, vdd_tx1,
        vdd_tx2);
    input benn;
    input benp;
    output biasn;
    output biasp;
    output dao;
    input epad;
    input gnd_rx1;
    input gnd_rx2;
    input gnd_tx1;
    input gnd_tx2;
    input irop;
    input lain;
    input laip;
    output laon;
    output laop;
    input ldin;
    input ldip;
    output ldon;
    output ldop;
    output los_sd;
    input md;
    input rref;
    inout scl;
    inout scl_e;
    inout sda;
    inout sda_e;
    inout tx_disable;
    inout tx_fault;
    output tx_sdo;
    input vdd_rx1;
    input vdd_rx2;
    input vdd_tx1;
    input vdd_tx2;


    initial
        begin
        end

endmodule
