// generated by newgenasym  Thu May 11 14:11:51 2023


module SFP_TOP (\rd+ , \rd- , \td+ , \td- , vccr, vcct, veer_1, veer_2, veet_1,
        veet_2);
    input \rd+ ;
    input \rd- ;
    output \td+ ;
    output \td- ;
    input vccr;
    input vcct;
    input veer_1;
    input veer_2;
    input veet_1;
    input veet_2;


    initial
        begin
        end

endmodule
