-- generated by newgenasym Mon Aug 31 14:12:29 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity network_tf is
    port (    
	MCT:       INOUT  STD_LOGIC;    
	MCT1:      INOUT  STD_LOGIC;    
	MCT2:      INOUT  STD_LOGIC;    
	MCT3:      OUT    STD_LOGIC;    
	MCT4:      OUT    STD_LOGIC;    
	\mx1+\:    INOUT  STD_LOGIC;    
	\mx1-\:    INOUT  STD_LOGIC;    
	\mx2+\:    INOUT  STD_LOGIC;    
	\mx2-\:    INOUT  STD_LOGIC;    
	\mx3+\:    INOUT  STD_LOGIC;    
	\mx3-\:    INOUT  STD_LOGIC;    
	\mx4+\:    INOUT  STD_LOGIC;    
	\mx4-\:    INOUT  STD_LOGIC;    
	NC1:       IN     STD_LOGIC;    
	NC2:       IN     STD_LOGIC;    
	NC3:       OUT    STD_LOGIC;    
	NC4:       OUT    STD_LOGIC;    
	NC5:       IN     STD_LOGIC;    
	NC6:       OUT    STD_LOGIC;    
	TCT:       IN     STD_LOGIC;    
	TCT1:      INOUT  STD_LOGIC;    
	TCT2:      INOUT  STD_LOGIC;    
	TCT3:      IN     STD_LOGIC;    
	TCT4:      IN     STD_LOGIC;    
	\td1+\:    INOUT  STD_LOGIC;    
	\td1-\:    INOUT  STD_LOGIC;    
	\td2+\:    INOUT  STD_LOGIC;    
	\td2-\:    INOUT  STD_LOGIC;    
	\td3+\:    INOUT  STD_LOGIC;    
	\td3-\:    INOUT  STD_LOGIC;    
	\td4+\:    INOUT  STD_LOGIC;    
	\td4-\:    INOUT  STD_LOGIC;    
	TDT:       IN     STD_LOGIC);
end network_tf;
