-- generated by newgenasym Mon Aug 31 14:13:53 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity osc is
    port (    
	GND:       IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end osc;
