// generated by newgenasym  Mon Dec 19 16:07:40 2022


module gpy211 (dcdc_rego_1, dcdc_rego_2, gnd_1, gnd_2, gphy_led0,
        gphy_led1, gphy_led2, gphy_led3, \gpio11/mint_pol ,
        \gpio12/maddr3 , gpio13, \gpio15/tdi , \gpio16/tms ,
        \gpio17/tdo/rj45_tap , \gpio18/maddr4 , hrstn, \mcs/maddr0 ,
        mdc, mdint, mdio, miso, \mosi/maddr2 , rcal, resref, rx0_n,
        rx0_p, \sclk/maddr1 , thpad, tpian, tpiap, tpibn, tpibp, tpicn,
        tpicp, tpidn, tpidp, trstn, tx0_n, tx0_p, vdd3v3dcdc, vdd_1,
        vdd_2, vdda0v9_1, vdda0v9_2, vdda0v9_3, vdda3v3_1,
        vdda3v3_2, vdda3v3aon, vdda3v3cdb, vdda3v3xo, vddp_1,
        vddp_2, vp, vph, vqps, xtal1, xtal2);
    input dcdc_rego_1;
    input dcdc_rego_2;
    input gnd_1;
    input gnd_2;
    output gphy_led0;
    output gphy_led1;
    output gphy_led2;
    output gphy_led3;
    inout \gpio11/mint_pol ;
    inout \gpio12/maddr3 ;
    inout gpio13;
    input \gpio15/tdi ;
    input \gpio16/tms ;
    output \gpio17/tdo/rj45_tap ;
    inout \gpio18/maddr4 ;
    input hrstn;
    output \mcs/maddr0 ;
    input mdc;
    output mdint;
    inout mdio;
    input miso;
    output \mosi/maddr2 ;
    inout rcal;
    inout resref;
    input rx0_n;
    input rx0_p;
    output \sclk/maddr1 ;
    input thpad;
    inout tpian;
    inout tpiap;
    inout tpibn;
    inout tpibp;
    inout tpicn;
    inout tpicp;
    inout tpidn;
    inout tpidp;
    input trstn;
    output tx0_n;
    output tx0_p;
    input vdd3v3dcdc;
    input vdd_1;
    input vdd_2;
    input vdda0v9_1;
    input vdda0v9_2;
    input vdda0v9_3;
    input vdda3v3_1;
    input vdda3v3_2;
    input vdda3v3aon;
    input vdda3v3cdb;
    input vdda3v3xo;
    input vddp_1;
    input vddp_2;
    input vp;
    input vph;
    input vqps;
    input xtal1;
    output xtal2;


    initial
        begin
        end

endmodule
