// generated by newgenasym  Mon Aug 31 13:59:18 2020


module inductor (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    output \3 ;
    output \4 ;


    initial
        begin
        end

endmodule
