-- generated by newgenasym Thu Oct 21 15:11:13 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity key is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       OUT    STD_LOGIC;    
	\7\:       OUT    STD_LOGIC;    
	INA:       IN     STD_LOGIC;    
	INB:       IN     STD_LOGIC;    
	MS1:       IN     STD_LOGIC;    
	MS2:       IN     STD_LOGIC;    
	OUT1A:     OUT    STD_LOGIC;    
	OUT1B:     OUT    STD_LOGIC;    
	OUT2A:     OUT    STD_LOGIC;    
	OUT2B:     OUT    STD_LOGIC);
end key;
