// generated by newgenasym  Wed Sep 02 15:22:05 2020


module b50210sb0 (avddh_1, avddh_2, avddh_clk, avddl, avddl_clk, biasvdd,
        dvdd_1, dvdd_2, epad, gnd_1, gnd_2, gtxclk, intrpt,
        \led1/phya0 , \led2/phya3 , led3, \lock_rec_clk/phya4 , mdc,
        mdio, nc_1, nc_2, ovdd, ovdd_led, ovdd_rgmii1, ovdd_rgmii2,
        pllvdd, rdac, rec_clk, refclkn, refclkp, reset, rx_dv, rxc,
        rxd0, rxd1, rxd2, rxd3, s_sginn, s_sginp, s_sgoutn, s_sgoutp,
        savdd_1, savdd_2, sginn, sginp, sgoutn, sgoutp, spllvdd,
        td0n, td0p, td1n, td1p, td2n, td2p, td3n, td3p, test, tvcoi,
        tx_en, txd0, txd1, txd2, txd3, vreg_cntl, vreg_sense);
    input avddh_1;
    input avddh_2;
    input avddh_clk;
    input avddl;
    input avddl_clk;
    input biasvdd;
    input dvdd_1;
    input dvdd_2;
    input epad;
    input gnd_1;
    input gnd_2;
    input gtxclk;
    output intrpt;
    inout \led1/phya0 ;
    inout \led2/phya3 ;
    inout led3;
    inout \lock_rec_clk/phya4 ;
    input mdc;
    inout mdio;
    inout nc_1;
    inout nc_2;
    input ovdd;
    input ovdd_led;
    input ovdd_rgmii1;
    input ovdd_rgmii2;
    input pllvdd;
    output rdac;
    output rec_clk;
    input refclkn;
    input refclkp;
    input reset;
    output rx_dv;
    output rxc;
    output rxd0;
    output rxd1;
    output rxd2;
    output rxd3;
    input s_sginn;
    input s_sginp;
    output s_sgoutn;
    output s_sgoutp;
    input savdd_1;
    input savdd_2;
    input sginn;
    input sginp;
    output sgoutn;
    output sgoutp;
    input spllvdd;
    inout td0n;
    inout td0p;
    inout td1n;
    inout td1p;
    inout td2n;
    inout td2p;
    inout td3n;
    inout td3p;
    input test;
    inout tvcoi;
    input tx_en;
    input txd0;
    input txd1;
    input txd2;
    input txd3;
    output vreg_cntl;
    output vreg_sense;


    initial
        begin
        end

endmodule
