-- generated by newgenasym Tue Nov 02 15:16:21 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ux3328 is
    port (    
	BENN:      IN     STD_LOGIC;    
	BENP:      IN     STD_LOGIC;    
	BIASN:     OUT    STD_LOGIC;    
	BIASP:     OUT    STD_LOGIC;    
	DAO:       OUT    STD_LOGIC;    
	EPAD:      IN     STD_LOGIC;    
	GND_RX1:   IN     STD_LOGIC;    
	GND_RX2:   IN     STD_LOGIC;    
	GND_TX1:   IN     STD_LOGIC;    
	GND_TX2:   IN     STD_LOGIC;    
	IROP:      IN     STD_LOGIC;    
	LAIN:      IN     STD_LOGIC;    
	LAIP:      IN     STD_LOGIC;    
	LAON:      OUT    STD_LOGIC;    
	LAOP:      OUT    STD_LOGIC;    
	LDIN:      IN     STD_LOGIC;    
	LDIP:      IN     STD_LOGIC;    
	LDON:      OUT    STD_LOGIC;    
	LDOP:      OUT    STD_LOGIC;    
	LOS_SD:    OUT    STD_LOGIC;    
	MD:        IN     STD_LOGIC;    
	RREF:      IN     STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SCL_E:     INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	SDA_E:     INOUT  STD_LOGIC;    
	TX_DISABLE: INOUT  STD_LOGIC;    
	TX_FAULT:  INOUT  STD_LOGIC;    
	TX_SDO:    OUT    STD_LOGIC;    
	VDD_RX1:   IN     STD_LOGIC;    
	VDD_RX2:   IN     STD_LOGIC;    
	VDD_TX1:   IN     STD_LOGIC;    
	VDD_TX2:   IN     STD_LOGIC);
end ux3328;
