// generated by newgenasym  Mon Nov 02 09:20:42 2020


module gn28l95 (\adc_in/rx_slp , apd_fb, apd_pwn, ben, \bias+ , \bias- , ee_scl,
        ee_sda, epad, \laser+ , \laser- , mpd, rssi_in, \rxin+ , \rxin- ,
        \rxo+ , \rxo- , scl, \sd/los , sda, \tx_dis/tx_slp , tx_fault, tx_sd,
        \txin+ , \txin- , vdd_dig, vdd_rx, vdd_tx_1, vdd_tx_2, vss_rx_1,
        vss_rx_2, vss_tx_1, vss_tx_2);
    inout \adc_in/rx_slp ;
    inout apd_fb;
    inout apd_pwn;
    input ben;
    inout \bias+ ;
    inout \bias- ;
    inout ee_scl;
    inout ee_sda;
    inout epad;
    inout \laser+ ;
    inout \laser- ;
    inout mpd;
    inout rssi_in;
    inout \rxin+ ;
    inout \rxin- ;
    inout \rxo+ ;
    inout \rxo- ;
    inout scl;
    inout \sd/los ;
    inout sda;
    inout \tx_dis/tx_slp ;
    inout tx_fault;
    inout tx_sd;
    inout \txin+ ;
    inout \txin- ;
    input vdd_dig;
    input vdd_rx;
    input vdd_tx_1;
    input vdd_tx_2;
    input vss_rx_1;
    input vss_rx_2;
    input vss_tx_1;
    input vss_tx_2;


    initial
        begin
        end

endmodule
