-- generated by newgenasym Mon Nov 02 09:20:42 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity gn28l95 is
    port (    
	\adc_in/rx_slp\: INOUT  STD_LOGIC;    
	APD_FB:    INOUT  STD_LOGIC;    
	APD_PWN:   INOUT  STD_LOGIC;    
	BEN:       IN     STD_LOGIC;    
	\bias+\:   INOUT  STD_LOGIC;    
	\bias-\:   INOUT  STD_LOGIC;    
	EE_SCL:    INOUT  STD_LOGIC;    
	EE_SDA:    INOUT  STD_LOGIC;    
	EPAD:      INOUT  STD_LOGIC;    
	\laser+\:  INOUT  STD_LOGIC;    
	\laser-\:  INOUT  STD_LOGIC;    
	MPD:       INOUT  STD_LOGIC;    
	RSSI_IN:   INOUT  STD_LOGIC;    
	\rxin+\:   INOUT  STD_LOGIC;    
	\rxin-\:   INOUT  STD_LOGIC;    
	\rxo+\:    INOUT  STD_LOGIC;    
	\rxo-\:    INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	\sd/los\:  INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	\tx_dis/tx_slp\: INOUT  STD_LOGIC;    
	TX_FAULT:  INOUT  STD_LOGIC;    
	TX_SD:     INOUT  STD_LOGIC;    
	\txin+\:   INOUT  STD_LOGIC;    
	\txin-\:   INOUT  STD_LOGIC;    
	VDD_DIG:   IN     STD_LOGIC;    
	VDD_RX:    IN     STD_LOGIC;    
	VDD_TX_1:  IN     STD_LOGIC;    
	VDD_TX_2:  IN     STD_LOGIC;    
	VSS_RX_1:  IN     STD_LOGIC;    
	VSS_RX_2:  IN     STD_LOGIC;    
	VSS_TX_1:  IN     STD_LOGIC;    
	VSS_TX_2:  IN     STD_LOGIC);
end gn28l95;
