// generated by newgenasym  Wed Dec 21 10:16:24 2022


module mt7981b (auxin0, auxin1, auxin2, avdd09_pcie, avdd09_sgmii,
        avdd12_cksq, avdd12_wbg, avdd15_por, avdd18_auxadc,
        avdd18_cksq, avdd18_com, avdd18_pcie, avdd18_pllgp,
        avdd18_por, avdd18_rddr, avdd18_sgmii, avdd18_usb,
        avdd18_wbg, avdd33_ld_p0, avdd33_usb, avss18,
        avss18_wbg_1, avss18_wbg_10, avss18_wbg_11,
        avss18_wbg_12, avss18_wbg_13, avss18_wbg_14,
        avss18_wbg_15, avss18_wbg_16, avss18_wbg_17,
        avss18_wbg_2, avss18_wbg_3, avss18_wbg_4, avss18_wbg_5,
        avss18_wbg_6, avss18_wbg_7, avss18_wbg_8, avss18_wbg_9,
        dvdd18_vqps, dvdd18io_bl, dvdd18io_lb, dvdd18io_lt,
        dvdd18io_rb, dvdd18io_rtc0, dvdd18io_rtc1, dvdd18io_tl,
        dvdd33io_bl, dvdd33io_lb, dvdd33io_rb, dvdd33io_rtc0,
        dvdd33io_rtc1, dvdd_ddr_rx, dvdd_ddr_tx, emi0_a0, emi0_a1,
        emi0_a10, emi0_a11, emi0_a12, emi0_a13, emi0_a14, emi0_a2,
        emi0_a3, emi0_a4, emi0_a5, emi0_a6, emi0_a7, emi0_a8,
        emi0_a9, emi0_ba0, emi0_ba1, emi0_ba2, emi0_cas_n,
        emi0_ck_c, emi0_ck_t, emi0_cke0, emi0_cs0_n, emi0_dm0,
        emi0_dm1, emi0_dq0, emi0_dq1, emi0_dq10, emi0_dq11,
        emi0_dq12, emi0_dq13, emi0_dq14, emi0_dq15, emi0_dq2,
        emi0_dq3, emi0_dq4, emi0_dq5, emi0_dq6, emi0_dq7, emi0_dq8,
        emi0_dq9, emi0_dqs0_c, emi0_dqs0_t, emi0_dqs1_c,
        emi0_dqs1_t, emi0_odt, emi0_ras_n, emi0_we_n, emi_extr,
        emi_reset_n, gbe_int, gbe_reset, gbe_txvn_a_p0,
        gbe_txvn_b_p0, gbe_txvn_c_p0, gbe_txvn_d_p0,
        gbe_txvp_a_p0, gbe_txvp_b_p0, gbe_txvp_c_p0,
        gbe_txvp_d_p0, gndk, gpio_reset, gpio_wps, jtag_jtclk,
        jtag_jtdi, jtag_jtdo, jtag_jtms, jtag_jtrst_n,
        main_x40m_in, nc_a1, nc_a20, nc_v1, nc_v20, pcie_ckn,
        pcie_ckp, pcie_ln0_rxn, pcie_ln0_rxp, pcie_ln0_txn,
        pcie_ln0_txp, pcie_pereset_n, pllgp_tn, pllgp_tp,
        por_bg_out, por_rstb, pwm0, rext, sgmii_ln0_rxn,
        sgmii_ln0_rxp, sgmii_ln0_txn, sgmii_ln0_txp, smi_mdc,
        smi_mdio, spi0_clk, spi0_cs, spi0_hold, spi0_miso,
        spi0_mosi, spi0_wp, spi1_clk, spi1_cs, spi1_miso,
        spi1_mosi, spi2_clk, spi2_cs, spi2_hold, spi2_miso,
        spi2_mosi, spi2_wp, sys_watchdog, sysrstb, testmode,
        tsaux_md, tsaux_refp, uart0_rxd, uart0_txd, usb_dm, usb_dp,
        usb_vbus, vcck, vcck_1, vcck_10, vcck_11, vcck_12, vcck_13,
        vcck_14, vcck_15, vcck_16, vcck_17, vcck_18, vcck_19,
        vcck_2, vcck_3, vcck_4, vcck_5, vcck_6, vcck_7, vcck_8,
        vcck_9, vddio_ddr_ca, vddio_ddr_dq_1, vddio_ddr_dq_2,
        vddio_ddr_mclk, vddio_ddr_r, wf0_in, wf0_ip, wf0_qn,
        wf0_qp, wf1_in, wf1_ip, wf1_qn, wf1_qp, wf2_in, wf2_ip,
        wf2_qn, wf2_qp, wf2g_led, wf3_in, wf3_ip, wf3_qn, wf3_qp,
        wf4_in, wf4_ip, wf4_qn, wf4_qp, wf5g_led, wf_cba_resetb,
        wf_dig_resetb, wf_hb0, wf_hb0_b, wf_hb1, wf_hb10, wf_hb2,
        wf_hb3, wf_hb4, wf_hb5, wf_hb6, wf_hb7, wf_hb8, wf_hb9,
        wf_top_clk, wf_top_data, wf_xo_req, wo_jtag_jtclk,
        wo_jtag_jtdi, wo_jtag_jtdo, wo_jtag_jtms,
        wo_jtag_jtrst_n);
    inout auxin0;
    inout auxin1;
    inout auxin2;
    inout avdd09_pcie;
    inout avdd09_sgmii;
    input avdd12_cksq;
    inout avdd12_wbg;
    input avdd15_por;
    input avdd18_auxadc;
    input avdd18_cksq;
    inout avdd18_com;
    inout avdd18_pcie;
    input avdd18_pllgp;
    input avdd18_por;
    inout avdd18_rddr;
    inout avdd18_sgmii;
    inout avdd18_usb;
    inout avdd18_wbg;
    inout avdd33_ld_p0;
    inout avdd33_usb;
    inout avss18;
    inout avss18_wbg_1;
    inout avss18_wbg_10;
    inout avss18_wbg_11;
    inout avss18_wbg_12;
    inout avss18_wbg_13;
    inout avss18_wbg_14;
    inout avss18_wbg_15;
    inout avss18_wbg_16;
    inout avss18_wbg_17;
    inout avss18_wbg_2;
    inout avss18_wbg_3;
    inout avss18_wbg_4;
    inout avss18_wbg_5;
    inout avss18_wbg_6;
    inout avss18_wbg_7;
    inout avss18_wbg_8;
    inout avss18_wbg_9;
    inout dvdd18_vqps;
    inout dvdd18io_bl;
    input dvdd18io_lb;
    input dvdd18io_lt;
    input dvdd18io_rb;
    input dvdd18io_rtc0;
    input dvdd18io_rtc1;
    inout dvdd18io_tl;
    input dvdd33io_bl;
    input dvdd33io_lb;
    input dvdd33io_rb;
    input dvdd33io_rtc0;
    input dvdd33io_rtc1;
    inout dvdd_ddr_rx;
    inout dvdd_ddr_tx;
    input emi0_a0;
    input emi0_a1;
    input emi0_a10;
    input emi0_a11;
    inout emi0_a12;
    inout emi0_a13;
    inout emi0_a14;
    inout emi0_a2;
    inout emi0_a3;
    inout emi0_a4;
    inout emi0_a5;
    inout emi0_a6;
    inout emi0_a7;
    inout emi0_a8;
    inout emi0_a9;
    inout emi0_ba0;
    inout emi0_ba1;
    inout emi0_ba2;
    inout emi0_cas_n;
    inout emi0_ck_c;
    inout emi0_ck_t;
    inout emi0_cke0;
    inout emi0_cs0_n;
    inout emi0_dm0;
    inout emi0_dm1;
    inout emi0_dq0;
    inout emi0_dq1;
    inout emi0_dq10;
    inout emi0_dq11;
    inout emi0_dq12;
    inout emi0_dq13;
    inout emi0_dq14;
    inout emi0_dq15;
    inout emi0_dq2;
    inout emi0_dq3;
    inout emi0_dq4;
    inout emi0_dq5;
    inout emi0_dq6;
    inout emi0_dq7;
    inout emi0_dq8;
    inout emi0_dq9;
    inout emi0_dqs0_c;
    inout emi0_dqs0_t;
    inout emi0_dqs1_c;
    inout emi0_dqs1_t;
    inout emi0_odt;
    inout emi0_ras_n;
    inout emi0_we_n;
    inout emi_extr;
    input emi_reset_n;
    inout gbe_int;
    inout gbe_reset;
    inout gbe_txvn_a_p0;
    inout gbe_txvn_b_p0;
    inout gbe_txvn_c_p0;
    inout gbe_txvn_d_p0;
    inout gbe_txvp_a_p0;
    inout gbe_txvp_b_p0;
    inout gbe_txvp_c_p0;
    inout gbe_txvp_d_p0;
    input [98:0] gndk;
    inout gpio_reset;
    inout gpio_wps;
    inout jtag_jtclk;
    inout jtag_jtdi;
    inout jtag_jtdo;
    inout jtag_jtms;
    inout jtag_jtrst_n;
    inout main_x40m_in;
    inout nc_a1;
    inout nc_a20;
    inout nc_v1;
    inout nc_v20;
    inout pcie_ckn;
    inout pcie_ckp;
    inout pcie_ln0_rxn;
    inout pcie_ln0_rxp;
    inout pcie_ln0_txn;
    inout pcie_ln0_txp;
    inout pcie_pereset_n;
    input pllgp_tn;
    input pllgp_tp;
    inout por_bg_out;
    inout por_rstb;
    inout pwm0;
    inout rext;
    inout sgmii_ln0_rxn;
    inout sgmii_ln0_rxp;
    inout sgmii_ln0_txn;
    inout sgmii_ln0_txp;
    inout smi_mdc;
    inout smi_mdio;
    inout spi0_clk;
    inout spi0_cs;
    inout spi0_hold;
    inout spi0_miso;
    inout spi0_mosi;
    inout spi0_wp;
    inout spi1_clk;
    inout spi1_cs;
    inout spi1_miso;
    inout spi1_mosi;
    inout spi2_clk;
    inout spi2_cs;
    inout spi2_hold;
    inout spi2_miso;
    inout spi2_mosi;
    inout spi2_wp;
    inout sys_watchdog;
    inout sysrstb;
    inout testmode;
    inout tsaux_md;
    inout tsaux_refp;
    inout uart0_rxd;
    inout uart0_txd;
    inout usb_dm;
    inout usb_dp;
    inout usb_vbus;
    inout vcck;
    inout vcck_1;
    inout vcck_10;
    inout vcck_11;
    inout vcck_12;
    inout vcck_13;
    inout vcck_14;
    inout vcck_15;
    inout vcck_16;
    inout vcck_17;
    inout vcck_18;
    inout vcck_19;
    inout vcck_2;
    inout vcck_3;
    inout vcck_4;
    inout vcck_5;
    inout vcck_6;
    inout vcck_7;
    inout vcck_8;
    inout vcck_9;
    inout vddio_ddr_ca;
    inout vddio_ddr_dq_1;
    inout vddio_ddr_dq_2;
    inout vddio_ddr_mclk;
    inout vddio_ddr_r;
    inout wf0_in;
    inout wf0_ip;
    inout wf0_qn;
    inout wf0_qp;
    inout wf1_in;
    inout wf1_ip;
    inout wf1_qn;
    inout wf1_qp;
    inout wf2_in;
    inout wf2_ip;
    inout wf2_qn;
    inout wf2_qp;
    inout wf2g_led;
    inout wf3_in;
    inout wf3_ip;
    inout wf3_qn;
    inout wf3_qp;
    inout wf4_in;
    inout wf4_ip;
    inout wf4_qn;
    inout wf4_qp;
    inout wf5g_led;
    inout wf_cba_resetb;
    inout wf_dig_resetb;
    inout wf_hb0;
    inout wf_hb0_b;
    inout wf_hb1;
    inout wf_hb10;
    input wf_hb2;
    input wf_hb3;
    inout wf_hb4;
    inout wf_hb5;
    inout wf_hb6;
    inout wf_hb7;
    inout wf_hb8;
    inout wf_hb9;
    inout wf_top_clk;
    inout wf_top_data;
    inout wf_xo_req;
    inout wo_jtag_jtclk;
    inout wo_jtag_jtdi;
    inout wo_jtag_jtdo;
    inout wo_jtag_jtms;
    inout wo_jtag_jtrst_n;


    initial
        begin
        end

endmodule
