// generated by newgenasym  Mon Aug 31 14:13:35 2020


module optocoupler (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
