// generated by newgenasym  Tue Apr 08 14:27:23 2025


module tmi39610 (bs, en, epad, fb, gnd, lx, pg, ron, vin);
    inout bs;
    inout en;
    inout epad;
    inout fb;
    inout gnd;
    inout lx;
    inout pg;
    inout ron;
    inout vin;


    initial
        begin
        end

endmodule
