-- generated by newgenasym Tue Apr 08 14:27:23 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tmi39610 is
    port (    
	BS:        INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	EPAD:      INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	LX:        INOUT  STD_LOGIC;    
	PG:        INOUT  STD_LOGIC;    
	RON:       INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC);
end tmi39610;
