// generated by newgenasym  Wed Sep 29 16:44:00 2021


module le9643 (avdd1, dra_zmosi, dvdd1, dvdd1v2, dxa_zmiso, epad_gnd,
        fs_zsync, ihl1, iref, lfc1, pclk_zclk, rac1, rdc1, ringd1,
        rsn1, rsvd18, rsvd19, rsvd20, rsvd_cs_n, rsvd_dclk,
        rsvd_din, rsvd_dout, rsvd_int_n, \rsvd_vs/io , rsvd_zsi_n,
        rtv1, swcmpy, swisy, swouty, swvsy, tac1, tdc1, tipd1, vbat1,
        vddhpi, vddsw, vref);
    input avdd1;
    input dra_zmosi;
    input dvdd1;
    input dvdd1v2;
    output dxa_zmiso;
    inout epad_gnd;
    input fs_zsync;
    output ihl1;
    input iref;
    output lfc1;
    input pclk_zclk;
    input rac1;
    input rdc1;
    output ringd1;
    input rsn1;
    inout rsvd18;
    inout rsvd19;
    inout rsvd20;
    input rsvd_cs_n;
    input rsvd_dclk;
    output rsvd_din;
    input rsvd_dout;
    output rsvd_int_n;
    input \rsvd_vs/io ;
    input rsvd_zsi_n;
    output rtv1;
    output swcmpy;
    input swisy;
    output swouty;
    input swvsy;
    input tac1;
    input tdc1;
    output tipd1;
    input vbat1;
    input vddhpi;
    input vddsw;
    output vref;


    initial
        begin
        end

endmodule
