// generated by newgenasym  Mon Sep 14 16:45:20 2020


module zx279128s (ddr_a_0, ddr_a_1, ddr_a_10, ddr_a_11, ddr_a_12, ddr_a_13,
        ddr_a_14, ddr_a_15, ddr_a_16, ddr_a_17, ddr_a_2, ddr_a_3,
        ddr_a_4, ddr_a_5, ddr_a_6, ddr_a_7, ddr_a_8, ddr_a_9,
        ddr_act, ddr_ba_0, ddr_ba_1, ddr_bg_0, ddr_bg_1, ddr_cke,
        ddr_clk_n, ddr_clk_p, ddr_cs, ddr_dm_0, ddr_dm_1, ddr_dq_0,
        ddr_dq_1, ddr_dq_10, ddr_dq_11, ddr_dq_12, ddr_dq_13,
        ddr_dq_14, ddr_dq_15, ddr_dq_2, ddr_dq_3, ddr_dq_4,
        ddr_dq_5, ddr_dq_6, ddr_dq_7, ddr_dq_8, ddr_dq_9,
        ddr_dqs_n_0, ddr_dqs_n_1, ddr_dqs_p_0, ddr_dqs_p_1,
        ddr_odt, ddr_pll_vdd1p8_1, ddr_pll_vdd1p8_2, ddr_rst,
        ddr_zq, dyingin, dyingout, gephy_avdd1p8, gephy_tclk,
        gpio18, gpio20, gpio21, gpio60, gpio63, i2c0_scl, i2c0_sda,
        i2c1_scl, i2c1_sda, jtag_tck, jtag_tdi, jtag_tdo, jtag_tms,
        jtag_trstn, mdc0, mdio0, nand_adq0, nand_adq1, nand_adq2,
        nand_adq3, nand_adq4, nand_adq5, nand_adq6, nand_adq7,
        nand_ale, nand_cen, nand_cle, nand_rdy_busy, nand_ren,
        nand_wen, otp_avddq1p8, pcie0_nclkreq, pcie0_rstb,
        pcie0clk_avdd0p9, pcie1_nclkreq, pcie1_rstb,
        pcie1clk_avdd0p9, pcm_clk, pcm_fs, pcm_rxd, pcm_txd,
        pll_avdd0p9, pll_avdd1p8, pll_avss, pon_ben, por_avdd1p8,
        recclk_out, rgm_txclk, rgm_txctl, rgm_txd0, rgm_txd1,
        rgm_txd2, rgm_txd3, rst_out, rstn, rx_los, rx_pwrdown,
        ssp0_fs0, ssp0_fs1, ssp0_fs2, ssp0_fs3, ssp0_rxd,
        ssp0_sclk, ssp0_txd, synce_clk_in, test_mode, tx_pwrdown,
        tx_sd, uart0_rxd, uart0_txd, usb20_avdd1p8, usb20_avdd3p3,
        usb20_dm, usb20_dp, usb30_avdd0p9, usb30_avdd1p8,
        usb30_avdd3p3, usb30_dm, usb30_dp, usb30_ssrxa2,
        usb30_ssrxb2, usb30_sstxa2, usb30_sstxb2, vdd_dvdd1p8_1,
        vdd_dvdd1p8_2, vdd_dvdd1p8_3, vdd_dvdd1p8_4,
        vdd_dvdd1p8_5, vdd_dvdd3p3_1, vdd_dvdd3p3_2,
        vdd_dvdd3p3_3, vdd_dvdd3p3_4, vdd_dvdd3p3_5,
        vdd_dvdd3p3_6, vdd_soc_0p9_1, vdd_soc_0p9_10,
        vdd_soc_0p9_11, vdd_soc_0p9_12, vdd_soc_0p9_13,
        vdd_soc_0p9_14, vdd_soc_0p9_15, vdd_soc_0p9_16,
        vdd_soc_0p9_17, vdd_soc_0p9_18, vdd_soc_0p9_19,
        vdd_soc_0p9_2, vdd_soc_0p9_20, vdd_soc_0p9_21,
        vdd_soc_0p9_3, vdd_soc_0p9_4, vdd_soc_0p9_5,
        vdd_soc_0p9_6, vdd_soc_0p9_7, vdd_soc_0p9_8,
        vdd_soc_0p9_9, vddq_1, vddq_2, vddq_3, vddq_4, vddq_5,
        vddq_6, vddq_7, vin_vdt, vss_a23, vss_aa11, vss_aa13,
        vss_aa15, vss_aa17, vss_aa18, vss_aa9, vss_ab10, vss_ab14,
        vss_ab18, vss_ab21, vss_ab8, vss_ac1, vss_ac14, vss_ac23,
        vss_ac4, vss_b15, vss_c15, vss_c16, vss_c18, vss_c2,
        vss_d10, vss_d11, vss_d12, vss_d13, vss_d14, vss_d15,
        vss_d16, vss_d18, vss_d6, vss_d7, vss_d8, vss_d9, vss_g15,
        vss_g16, vss_g20, vss_g22, vss_g4, vss_h10, vss_h11,
        vss_h12, vss_h13, vss_h14, vss_h15, vss_h16, vss_h20,
        vss_h21, vss_h8, vss_h9, vss_j10, vss_j11, vss_j12, vss_j13,
        vss_j14, vss_j15, vss_j16, vss_j9, vss_k10, vss_k11,
        vss_k12, vss_k13, vss_k14, vss_k15, vss_k16, vss_k20,
        vss_k9, vss_l10, vss_l11, vss_l12, vss_l13, vss_l14,
        vss_l15, vss_l16, vss_l2, vss_l20, vss_l9, vss_m10, vss_m11,
        vss_m12, vss_m13, vss_m14, vss_m15, vss_m16, vss_m20,
        vss_m9, vss_n10, vss_n11, vss_n12, vss_n13, vss_n14,
        vss_n15, vss_n16, vss_n20, vss_n9, vss_p10, vss_p11,
        vss_p12, vss_p13, vss_p14, vss_p15, vss_p16, vss_p20,
        vss_p23, vss_p9, vss_r10, vss_r11, vss_r12, vss_r13,
        vss_r14, vss_r15, vss_r16, vss_r20, vss_r9, vss_t20,
        vss_u20, vss_v20, vss_w20, vss_w22, vss_w23, vss_y11,
        vss_y13, vss_y14, vss_y15, vss_y17, vss_y18, vss_y19,
        vss_y20, vss_y6, vss_y9, x25m_dvdd1p8, x_gphy_anatestdcn,
        x_gphy_anatestdcp, x_gphy_avdd15_com, x_gphy_avdd18_com,
        x_gphy_avdd33_com_1, x_gphy_avdd33_com_2,
        x_gphy_avdd33_com_3, x_gphy_avdd33_com_4,
        x_gphy_avdd33_com_5, x_gphy_led_l0, x_gphy_led_l1,
        x_gphy_led_l2, x_gphy_led_l3, x_gphy_mdin0_0,
        x_gphy_mdin0_1, x_gphy_mdin0_2, x_gphy_mdin0_3,
        x_gphy_mdin1_0, x_gphy_mdin1_1, x_gphy_mdin1_2,
        x_gphy_mdin1_3, x_gphy_mdin2_0, x_gphy_mdin2_1,
        x_gphy_mdin2_2, x_gphy_mdin2_3, x_gphy_mdin3_0,
        x_gphy_mdin3_1, x_gphy_mdin3_2, x_gphy_mdin3_3,
        x_gphy_mdip0_0, x_gphy_mdip0_1, x_gphy_mdip0_2,
        x_gphy_mdip0_3, x_gphy_mdip1_0, x_gphy_mdip1_1,
        x_gphy_mdip1_2, x_gphy_mdip1_3, x_gphy_mdip2_0,
        x_gphy_mdip2_1, x_gphy_mdip2_2, x_gphy_mdip2_3,
        x_gphy_mdip3_0, x_gphy_mdip3_1, x_gphy_mdip3_2,
        x_gphy_mdip3_3, x_gphy_rset, x_pcie0_clk_100m_n,
        x_pcie0_clk_100m_p, x_pcie0_resref, x_pcie0_rxm0,
        x_pcie0_rxp0, x_pcie0_txm0, x_pcie0_txp0, x_pcie0_vp0p9,
        x_pcie0_vph3p3, x_pcie1_clk_100m_n, x_pcie1_clk_100m_p,
        x_pcie1_resref, x_pcie1_rxm, x_pcie1_rxp, x_pcie1_txm,
        x_pcie1_txp, x_pcie1_vp0p9, x_pcie1_vph3p3, xpon_ats,
        xpon_avdd0p9, xpon_avddh3p3, xpon_avss_r1, xpon_avss_r2,
        xpon_avss_t3, xpon_avss_u1, xpon_avss_u2, xpon_avss_u3,
        xpon_avss_v3, xpon_avss_w1, xpon_avss_w2, xpon_dinn,
        xpon_dinp, xpon_doutn, xpon_doutp, xpon_exres, xtali,
        xtalo);
    output ddr_a_0;
    output ddr_a_1;
    output ddr_a_10;
    output ddr_a_11;
    output ddr_a_12;
    output ddr_a_13;
    output ddr_a_14;
    output ddr_a_15;
    output ddr_a_16;
    output ddr_a_17;
    output ddr_a_2;
    output ddr_a_3;
    output ddr_a_4;
    output ddr_a_5;
    output ddr_a_6;
    output ddr_a_7;
    output ddr_a_8;
    output ddr_a_9;
    output ddr_act;
    output ddr_ba_0;
    output ddr_ba_1;
    output ddr_bg_0;
    output ddr_bg_1;
    output ddr_cke;
    output ddr_clk_n;
    output ddr_clk_p;
    output ddr_cs;
    output ddr_dm_0;
    output ddr_dm_1;
    inout ddr_dq_0;
    inout ddr_dq_1;
    inout ddr_dq_10;
    inout ddr_dq_11;
    inout ddr_dq_12;
    inout ddr_dq_13;
    inout ddr_dq_14;
    inout ddr_dq_15;
    inout ddr_dq_2;
    inout ddr_dq_3;
    inout ddr_dq_4;
    inout ddr_dq_5;
    inout ddr_dq_6;
    inout ddr_dq_7;
    inout ddr_dq_8;
    inout ddr_dq_9;
    inout ddr_dqs_n_0;
    inout ddr_dqs_n_1;
    inout ddr_dqs_p_0;
    inout ddr_dqs_p_1;
    output ddr_odt;
    input ddr_pll_vdd1p8_1;
    input ddr_pll_vdd1p8_2;
    output ddr_rst;
    inout ddr_zq;
    inout dyingin;
    inout dyingout;
    input gephy_avdd1p8;
    inout gephy_tclk;
    inout gpio18;
    inout gpio20;
    inout gpio21;
    inout gpio60;
    inout gpio63;
    inout i2c0_scl;
    inout i2c0_sda;
    inout i2c1_scl;
    inout i2c1_sda;
    inout jtag_tck;
    inout jtag_tdi;
    inout jtag_tdo;
    inout jtag_tms;
    inout jtag_trstn;
    inout mdc0;
    inout mdio0;
    inout nand_adq0;
    inout nand_adq1;
    inout nand_adq2;
    inout nand_adq3;
    inout nand_adq4;
    inout nand_adq5;
    inout nand_adq6;
    inout nand_adq7;
    inout nand_ale;
    inout nand_cen;
    inout nand_cle;
    inout nand_rdy_busy;
    inout nand_ren;
    inout nand_wen;
    input otp_avddq1p8;
    inout pcie0_nclkreq;
    inout pcie0_rstb;
    input pcie0clk_avdd0p9;
    inout pcie1_nclkreq;
    inout pcie1_rstb;
    input pcie1clk_avdd0p9;
    inout pcm_clk;
    inout pcm_fs;
    inout pcm_rxd;
    inout pcm_txd;
    input pll_avdd0p9;
    input pll_avdd1p8;
    input pll_avss;
    inout pon_ben;
    input por_avdd1p8;
    inout recclk_out;
    inout rgm_txclk;
    inout rgm_txctl;
    inout rgm_txd0;
    inout rgm_txd1;
    inout rgm_txd2;
    inout rgm_txd3;
    inout rst_out;
    input rstn;
    inout rx_los;
    inout rx_pwrdown;
    inout ssp0_fs0;
    inout ssp0_fs1;
    inout ssp0_fs2;
    inout ssp0_fs3;
    inout ssp0_rxd;
    inout ssp0_sclk;
    inout ssp0_txd;
    inout synce_clk_in;
    input test_mode;
    inout tx_pwrdown;
    inout tx_sd;
    inout uart0_rxd;
    inout uart0_txd;
    input usb20_avdd1p8;
    input usb20_avdd3p3;
    inout usb20_dm;
    inout usb20_dp;
    input usb30_avdd0p9;
    input usb30_avdd1p8;
    input usb30_avdd3p3;
    inout usb30_dm;
    inout usb30_dp;
    output usb30_ssrxa2;
    output usb30_ssrxb2;
    input usb30_sstxa2;
    input usb30_sstxb2;
    input vdd_dvdd1p8_1;
    input vdd_dvdd1p8_2;
    input vdd_dvdd1p8_3;
    input vdd_dvdd1p8_4;
    input vdd_dvdd1p8_5;
    input vdd_dvdd3p3_1;
    input vdd_dvdd3p3_2;
    input vdd_dvdd3p3_3;
    input vdd_dvdd3p3_4;
    input vdd_dvdd3p3_5;
    input vdd_dvdd3p3_6;
    input vdd_soc_0p9_1;
    input vdd_soc_0p9_10;
    input vdd_soc_0p9_11;
    input vdd_soc_0p9_12;
    input vdd_soc_0p9_13;
    input vdd_soc_0p9_14;
    input vdd_soc_0p9_15;
    input vdd_soc_0p9_16;
    input vdd_soc_0p9_17;
    input vdd_soc_0p9_18;
    input vdd_soc_0p9_19;
    input vdd_soc_0p9_2;
    input vdd_soc_0p9_20;
    input vdd_soc_0p9_21;
    input vdd_soc_0p9_3;
    input vdd_soc_0p9_4;
    input vdd_soc_0p9_5;
    input vdd_soc_0p9_6;
    input vdd_soc_0p9_7;
    input vdd_soc_0p9_8;
    input vdd_soc_0p9_9;
    input vddq_1;
    input vddq_2;
    input vddq_3;
    input vddq_4;
    input vddq_5;
    input vddq_6;
    input vddq_7;
    input vin_vdt;
    input vss_a23;
    input vss_aa11;
    input vss_aa13;
    input vss_aa15;
    input vss_aa17;
    input vss_aa18;
    input vss_aa9;
    input vss_ab10;
    input vss_ab14;
    input vss_ab18;
    input vss_ab21;
    input vss_ab8;
    input vss_ac1;
    input vss_ac14;
    input vss_ac23;
    input vss_ac4;
    input vss_b15;
    input vss_c15;
    input vss_c16;
    input vss_c18;
    input vss_c2;
    input vss_d10;
    input vss_d11;
    input vss_d12;
    input vss_d13;
    input vss_d14;
    input vss_d15;
    input vss_d16;
    input vss_d18;
    input vss_d6;
    input vss_d7;
    input vss_d8;
    input vss_d9;
    input vss_g15;
    input vss_g16;
    input vss_g20;
    input vss_g22;
    input vss_g4;
    input vss_h10;
    input vss_h11;
    input vss_h12;
    input vss_h13;
    input vss_h14;
    input vss_h15;
    input vss_h16;
    input vss_h20;
    input vss_h21;
    input vss_h8;
    input vss_h9;
    input vss_j10;
    input vss_j11;
    input vss_j12;
    input vss_j13;
    input vss_j14;
    input vss_j15;
    input vss_j16;
    input vss_j9;
    input vss_k10;
    input vss_k11;
    input vss_k12;
    input vss_k13;
    input vss_k14;
    input vss_k15;
    input vss_k16;
    input vss_k20;
    input vss_k9;
    input vss_l10;
    input vss_l11;
    input vss_l12;
    input vss_l13;
    input vss_l14;
    input vss_l15;
    input vss_l16;
    input vss_l2;
    input vss_l20;
    input vss_l9;
    input vss_m10;
    input vss_m11;
    input vss_m12;
    input vss_m13;
    input vss_m14;
    input vss_m15;
    input vss_m16;
    input vss_m20;
    input vss_m9;
    input vss_n10;
    input vss_n11;
    input vss_n12;
    input vss_n13;
    input vss_n14;
    input vss_n15;
    input vss_n16;
    input vss_n20;
    input vss_n9;
    input vss_p10;
    input vss_p11;
    input vss_p12;
    input vss_p13;
    input vss_p14;
    input vss_p15;
    input vss_p16;
    input vss_p20;
    input vss_p23;
    input vss_p9;
    input vss_r10;
    input vss_r11;
    input vss_r12;
    input vss_r13;
    input vss_r14;
    input vss_r15;
    input vss_r16;
    input vss_r20;
    input vss_r9;
    input vss_t20;
    input vss_u20;
    input vss_v20;
    input vss_w20;
    input vss_w22;
    input vss_w23;
    input vss_y11;
    input vss_y13;
    input vss_y14;
    input vss_y15;
    input vss_y17;
    input vss_y18;
    input vss_y19;
    input vss_y20;
    input vss_y6;
    input vss_y9;
    input x25m_dvdd1p8;
    inout x_gphy_anatestdcn;
    inout x_gphy_anatestdcp;
    input x_gphy_avdd15_com;
    input x_gphy_avdd18_com;
    input x_gphy_avdd33_com_1;
    input x_gphy_avdd33_com_2;
    input x_gphy_avdd33_com_3;
    input x_gphy_avdd33_com_4;
    input x_gphy_avdd33_com_5;
    inout x_gphy_led_l0;
    inout x_gphy_led_l1;
    inout x_gphy_led_l2;
    inout x_gphy_led_l3;
    inout x_gphy_mdin0_0;
    inout x_gphy_mdin0_1;
    inout x_gphy_mdin0_2;
    inout x_gphy_mdin0_3;
    inout x_gphy_mdin1_0;
    inout x_gphy_mdin1_1;
    inout x_gphy_mdin1_2;
    inout x_gphy_mdin1_3;
    inout x_gphy_mdin2_0;
    inout x_gphy_mdin2_1;
    inout x_gphy_mdin2_2;
    inout x_gphy_mdin2_3;
    inout x_gphy_mdin3_0;
    inout x_gphy_mdin3_1;
    inout x_gphy_mdin3_2;
    inout x_gphy_mdin3_3;
    inout x_gphy_mdip0_0;
    inout x_gphy_mdip0_1;
    inout x_gphy_mdip0_2;
    inout x_gphy_mdip0_3;
    inout x_gphy_mdip1_0;
    inout x_gphy_mdip1_1;
    inout x_gphy_mdip1_2;
    inout x_gphy_mdip1_3;
    inout x_gphy_mdip2_0;
    inout x_gphy_mdip2_1;
    inout x_gphy_mdip2_2;
    inout x_gphy_mdip2_3;
    inout x_gphy_mdip3_0;
    inout x_gphy_mdip3_1;
    inout x_gphy_mdip3_2;
    inout x_gphy_mdip3_3;
    inout x_gphy_rset;
    output x_pcie0_clk_100m_n;
    output x_pcie0_clk_100m_p;
    inout x_pcie0_resref;
    input x_pcie0_rxm0;
    input x_pcie0_rxp0;
    output x_pcie0_txm0;
    output x_pcie0_txp0;
    input x_pcie0_vp0p9;
    input x_pcie0_vph3p3;
    output x_pcie1_clk_100m_n;
    output x_pcie1_clk_100m_p;
    inout x_pcie1_resref;
    input x_pcie1_rxm;
    input x_pcie1_rxp;
    output x_pcie1_txm;
    output x_pcie1_txp;
    input x_pcie1_vp0p9;
    input x_pcie1_vph3p3;
    inout xpon_ats;
    input xpon_avdd0p9;
    input xpon_avddh3p3;
    input xpon_avss_r1;
    input xpon_avss_r2;
    input xpon_avss_t3;
    input xpon_avss_u1;
    input xpon_avss_u2;
    input xpon_avss_u3;
    input xpon_avss_v3;
    input xpon_avss_w1;
    input xpon_avss_w2;
    input xpon_dinn;
    input xpon_dinp;
    output xpon_doutn;
    output xpon_doutp;
    inout xpon_exres;
    input xtali;
    output xtalo;


    initial
        begin
        end

endmodule
