// generated by newgenasym  Fri May 28 14:02:47 2021


module flash (a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20,
        a21, a22, a23, a24, a25, a3, a4, a5, a6, a7, a8, a9, ale, \byte# ,
        \ce# , \ce2#/nc , cle, clk, cs, \di/io0 , \do/io1 , dq0, dq1, dq10,
        dq11, dq12, dq13, dq14, \dq15/a-1 , dq2, dq3, dq4, dq5, dq6, dq7,
        dq8, dq9, epad, gnd, gnd1, gnd2, \h/r#/io3 , \i/o0 , \i/o1 , \i/o10 ,
        \i/o11 , \i/o12 , \i/o13 , \i/o14 , \i/o15 , \i/o2 , \i/o3 , \i/o4 , \i/o5 ,
        \i/o6 , \i/o7 , \i/o8 , \i/o9 , \nc/a20/a20 , \nc/byte# , \nc/nc/a21 ,
        \nc/ry/by# , \nc10/ce2# , \nc6/r/b2# , \oe# , \r/b# , \r/b2#/nc , \re# ,
        \reset# , rfu1, rfu2, \rfu3/a26 , \rst# , \ry/by# , vcc, vcc_0, vcc_1,
        vcc_2, vcc_3, vcc_4, vio, vss1, vss2, vss_0, vss_1, vss_2,
        vss_3, vss_4, \we# , \wp# , \wp#/acc , \wp#/nc , \wp/io2 );
    input a0;
    input a1;
    input a10;
    input a11;
    input a12;
    input a13;
    input a14;
    input a15;
    input a16;
    input a17;
    input a18;
    input a19;
    input a2;
    input a20;
    input a21;
    input a22;
    input [256:256] a23;
    input [512:512] a24;
    input [1:1] a25;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    input a9;
    output ale;
    output \byte# ;
    output \ce# ;
    output \ce2#/nc ;
    output cle;
    input clk;
    input cs;
    inout \di/io0 ;
    inout \do/io1 ;
    output dq0;
    output dq1;
    output dq10;
    output dq11;
    output dq12;
    output dq13;
    output dq14;
    output \dq15/a-1 ;
    output dq2;
    output dq3;
    output dq4;
    output dq5;
    output dq6;
    output dq7;
    output dq8;
    output dq9;
    output epad;
    input gnd;
    output gnd1;
    output gnd2;
    inout \h/r#/io3 ;
    output \i/o0 ;
    output \i/o1 ;
    output \i/o10 ;
    output \i/o11 ;
    output \i/o12 ;
    output \i/o13 ;
    output \i/o14 ;
    output \i/o15 ;
    output \i/o2 ;
    output \i/o3 ;
    output \i/o4 ;
    output \i/o5 ;
    output \i/o6 ;
    output \i/o7 ;
    output \i/o8 ;
    output \i/o9 ;
    input \nc/a20/a20 ;
    output \nc/byte# ;
    input \nc/nc/a21 ;
    output \nc/ry/by# ;
    output \nc10/ce2# ;
    output \nc6/r/b2# ;
    output \oe# ;
    output \r/b# ;
    output \r/b2#/nc ;
    output \re# ;
    input \reset# ;
    input rfu1;
    input rfu2;
    input \rfu3/a26 ;
    input \rst# ;
    output \ry/by# ;
    input vcc;
    input vcc_0;
    input vcc_1;
    input vcc_2;
    input vcc_3;
    input vcc_4;
    output vio;
    output vss1;
    output vss2;
    input vss_0;
    input vss_1;
    input vss_2;
    input vss_3;
    input vss_4;
    output \we# ;
    output \wp# ;
    output \wp#/acc ;
    output \wp#/nc ;
    inout \wp/io2 ;


    initial
        begin
        end

endmodule
