// generated by newgenasym  Fri May 27 18:10:12 2022


module sgm41282c (agnd, apd, en, gain, gnd, in, mb, pgnd1, pgnd2, rlim, sw1, sw2,
        th, thhxor, vmon, vref, vs);
    input agnd;
    output apd;
    input en;
    input gain;
    input gnd;
    input in;
    input mb;
    input pgnd1;
    input pgnd2;
    input rlim;
    output sw1;
    output sw2;
    input th;
    input thhxor;
    output vmon;
    output vref;
    input vs;


    initial
        begin
        end

endmodule
