// generated by newgenasym  Tue Jun 07 16:08:11 2022


module bcm68627 (bit_clk, bsc_scl, bsc_sda, cpu_ddr_a0, cpu_ddr_a1,
        cpu_ddr_a10, cpu_ddr_a11, cpu_ddr_a12, cpu_ddr_a13,
        cpu_ddr_a14, cpu_ddr_a15, cpu_ddr_a2, cpu_ddr_a3,
        cpu_ddr_a4, cpu_ddr_a5, cpu_ddr_a6, cpu_ddr_a7,
        cpu_ddr_a8, cpu_ddr_a9, cpu_ddr_ba0, cpu_ddr_ba1,
        cpu_ddr_ba2, cpu_ddr_cas_b, cpu_ddr_ck_n, cpu_ddr_ck_p,
        cpu_ddr_cke, cpu_ddr_cs0_b, cpu_ddr_cs1_b, cpu_ddr_dm0,
        cpu_ddr_dm1, cpu_ddr_dq0, cpu_ddr_dq1, cpu_ddr_dq10,
        cpu_ddr_dq11, cpu_ddr_dq12, cpu_ddr_dq13, cpu_ddr_dq14,
        cpu_ddr_dq15, cpu_ddr_dq2, cpu_ddr_dq3, cpu_ddr_dq4,
        cpu_ddr_dq5, cpu_ddr_dq6, cpu_ddr_dq7, cpu_ddr_dq8,
        cpu_ddr_dq9, cpu_ddr_dqs0_n, cpu_ddr_dqs0_p,
        cpu_ddr_dqs1_n, cpu_ddr_dqs1_p, cpu_ddr_ldo_vddo,
        cpu_ddr_odt, cpu_ddr_ras_b, cpu_ddr_rst_b,
        cpu_ddr_vddc_1, cpu_ddr_vddc_2, cpu_ddr_vddc_3,
        cpu_ddr_vddo_1, cpu_ddr_vddo_2, cpu_ddr_vddo_3,
        cpu_ddr_vddo_4, cpu_ddr_vddo_5, cpu_ddr_vddo_6,
        cpu_ddr_vddo_7, cpu_ddr_vddo_8, cpu_ddr_vddo_ck,
        cpu_ddr_vref, cpu_ddr_we_b, cpu_ddr_zq, dp_ddr0_a0,
        dp_ddr0_a1, dp_ddr0_a10, dp_ddr0_a11, dp_ddr0_a12,
        dp_ddr0_a13, dp_ddr0_a14, dp_ddr0_a15, dp_ddr0_a2,
        dp_ddr0_a3, dp_ddr0_a4, dp_ddr0_a5, dp_ddr0_a6,
        dp_ddr0_a7, dp_ddr0_a8, dp_ddr0_a9, dp_ddr0_ba0,
        dp_ddr0_ba1, dp_ddr0_ba2, dp_ddr0_cas_b, dp_ddr0_ck_n,
        dp_ddr0_ck_p, dp_ddr0_cke, dp_ddr0_cs0_b, dp_ddr0_cs1_b,
        dp_ddr0_dm0, dp_ddr0_dm1, dp_ddr0_dm2, dp_ddr0_dm3,
        dp_ddr0_dq0, dp_ddr0_dq1, dp_ddr0_dq10, dp_ddr0_dq11,
        dp_ddr0_dq12, dp_ddr0_dq13, dp_ddr0_dq14, dp_ddr0_dq15,
        dp_ddr0_dq16, dp_ddr0_dq17, dp_ddr0_dq18, dp_ddr0_dq19,
        dp_ddr0_dq2, dp_ddr0_dq20, dp_ddr0_dq21, dp_ddr0_dq22,
        dp_ddr0_dq23, dp_ddr0_dq24, dp_ddr0_dq25, dp_ddr0_dq26,
        dp_ddr0_dq27, dp_ddr0_dq28, dp_ddr0_dq29, dp_ddr0_dq3,
        dp_ddr0_dq30, dp_ddr0_dq31, dp_ddr0_dq4, dp_ddr0_dq5,
        dp_ddr0_dq6, dp_ddr0_dq7, dp_ddr0_dq8, dp_ddr0_dq9,
        dp_ddr0_dqs0_n, dp_ddr0_dqs0_p, dp_ddr0_dqs1_n,
        dp_ddr0_dqs1_p, dp_ddr0_dqs2_n, dp_ddr0_dqs2_p,
        dp_ddr0_dqs3_n, dp_ddr0_dqs3_p, dp_ddr0_ldo_vddo,
        dp_ddr0_odt, dp_ddr0_ras_b, dp_ddr0_rst_b,
        dp_ddr0_vddc_1, dp_ddr0_vddc_2, dp_ddr0_vddc_3,
        dp_ddr0_vddc_4, dp_ddr0_vddo_1, dp_ddr0_vddo_10,
        dp_ddr0_vddo_11, dp_ddr0_vddo_2, dp_ddr0_vddo_3,
        dp_ddr0_vddo_4, dp_ddr0_vddo_5, dp_ddr0_vddo_6,
        dp_ddr0_vddo_7, dp_ddr0_vddo_8, dp_ddr0_vddo_9,
        dp_ddr0_vddo_ck, dp_ddr0_vref, dp_ddr0_we_b, dp_ddr0_zq,
        dp_ddr1_a0, dp_ddr1_a1, dp_ddr1_a10, dp_ddr1_a11,
        dp_ddr1_a12, dp_ddr1_a13, dp_ddr1_a14, dp_ddr1_a15,
        dp_ddr1_a2, dp_ddr1_a3, dp_ddr1_a4, dp_ddr1_a5,
        dp_ddr1_a6, dp_ddr1_a7, dp_ddr1_a8, dp_ddr1_a9,
        dp_ddr1_ba0, dp_ddr1_ba1, dp_ddr1_ba2, dp_ddr1_cas_b,
        dp_ddr1_ck_n, dp_ddr1_ck_p, dp_ddr1_cke, dp_ddr1_cs0_b,
        dp_ddr1_cs1_b, dp_ddr1_dm0, dp_ddr1_dm1, dp_ddr1_dm2,
        dp_ddr1_dm3, dp_ddr1_dq0, dp_ddr1_dq1, dp_ddr1_dq10,
        dp_ddr1_dq11, dp_ddr1_dq12, dp_ddr1_dq13, dp_ddr1_dq14,
        dp_ddr1_dq15, dp_ddr1_dq16, dp_ddr1_dq17, dp_ddr1_dq18,
        dp_ddr1_dq19, dp_ddr1_dq2, dp_ddr1_dq20, dp_ddr1_dq21,
        dp_ddr1_dq22, dp_ddr1_dq23, dp_ddr1_dq24, dp_ddr1_dq25,
        dp_ddr1_dq26, dp_ddr1_dq27, dp_ddr1_dq28, dp_ddr1_dq29,
        dp_ddr1_dq3, dp_ddr1_dq30, dp_ddr1_dq31, dp_ddr1_dq4,
        dp_ddr1_dq5, dp_ddr1_dq6, dp_ddr1_dq7, dp_ddr1_dq8,
        dp_ddr1_dq9, dp_ddr1_dqs0_n, dp_ddr1_dqs0_p,
        dp_ddr1_dqs1_n, dp_ddr1_dqs1_p, dp_ddr1_dqs2_n,
        dp_ddr1_dqs2_p, dp_ddr1_dqs3_n, dp_ddr1_dqs3_p,
        dp_ddr1_ldo_vddo, dp_ddr1_odt, dp_ddr1_ras_b,
        dp_ddr1_rst_b, dp_ddr1_vddc_1, dp_ddr1_vddc_2,
        dp_ddr1_vddc_3, dp_ddr1_vddc_4, dp_ddr1_vddo_1,
        dp_ddr1_vddo_10, dp_ddr1_vddo_11, dp_ddr1_vddo_2,
        dp_ddr1_vddo_3, dp_ddr1_vddo_4, dp_ddr1_vddo_5,
        dp_ddr1_vddo_6, dp_ddr1_vddo_7, dp_ddr1_vddo_8,
        dp_ddr1_vddo_9, dp_ddr1_vddo_ck, dp_ddr1_vref,
        dp_ddr1_we_b, dp_ddr1_zq, ejtag_ce0, ejtag_ce1, ejtag_tck,
        ejtag_tdi, ejtag_tdo, ejtag_tms, ejtag_trst_b, gpio_00,
        gpio_01, gpio_02, gpio_03, gpio_04, gpio_05, gpio_06,
        gpio_07, gpio_08, gpio_09, gpio_10, gpio_11, gpio_12,
        gpio_13, gpio_14, gpio_15, gpio_16, gpio_17, gpio_18,
        gpio_19, gpio_20, gpio_21, gpio_22, gpio_23, gpio_24,
        gpio_25, gpio_26, gpio_27, gpio_28, gpio_29, gpio_30,
        gpio_31, gpio_32, gpio_33, gpio_34, gpio_35, gpio_36,
        gpio_37, gpio_38, gpio_39, gpio_40, heartbeat,
        main_refclk_avdd1p8, main_refclk_avss_1,
        main_refclk_avss_10, main_refclk_avss_11,
        main_refclk_avss_12, main_refclk_avss_2,
        main_refclk_avss_3, main_refclk_avss_4,
        main_refclk_avss_5, main_refclk_avss_6,
        main_refclk_avss_7, main_refclk_avss_8,
        main_refclk_avss_9, main_refclkn, main_refclkp, otp_vddo,
        pcie0_clkreq_b, pcie0_pvdd1p0, pcie0_rdn, pcie0_rdp,
        pcie0_refclkn, pcie0_refclkp, pcie0_rst_b, pcie0_rvdd1p0,
        pcie0_tdn, pcie0_tdp, pcie0_tvdd1p0, pm0_pvdd1p0,
        pm0_rd0_n, pm0_rd0_p, pm0_rd1_n, pm0_rd1_p, pm0_refclkn,
        pm0_refclkp, pm0_rescal_rext, pm0_rvdd1p0_1,
        pm0_rvdd1p0_2, pm0_td0_n, pm0_td0_p, pm0_td1_n, pm0_td1_p,
        pm0_tvdd1p0_1, pm0_tvdd1p0_2, pm1_rescal_rext,
        pm2_pvdd1p0, pm2_rd0_n, pm2_rd0_p, pm2_rd1_n, pm2_rd1_p,
        pm2_refclkn, pm2_refclkp, pm2_rvdd1p0_1, pm2_rvdd1p0_2,
        pm2_td0_n, pm2_td0_p, pm2_td1_n, pm2_td1_p, pm2_tvdd1p0_1,
        pm2_tvdd1p0_2, pm_agnd_1, pm_agnd_10, pm_agnd_11,
        pm_agnd_12, pm_agnd_13, pm_agnd_14, pm_agnd_15,
        pm_agnd_16, pm_agnd_17, pm_agnd_18, pm_agnd_19, pm_agnd_2,
        pm_agnd_20, pm_agnd_21, pm_agnd_22, pm_agnd_23,
        pm_agnd_24, pm_agnd_25, pm_agnd_26, pm_agnd_27,
        pm_agnd_28, pm_agnd_29, pm_agnd_3, pm_agnd_30, pm_agnd_31,
        pm_agnd_32, pm_agnd_33, pm_agnd_34, pm_agnd_35,
        pm_agnd_36, pm_agnd_37, pm_agnd_38, pm_agnd_39, pm_agnd_4,
        pm_agnd_40, pm_agnd_41, pm_agnd_42, pm_agnd_43,
        pm_agnd_44, pm_agnd_45, pm_agnd_46, pm_agnd_47,
        pm_agnd_48, pm_agnd_49, pm_agnd_5, pm_agnd_50, pm_agnd_51,
        pm_agnd_52, pm_agnd_53, pm_agnd_54, pm_agnd_55,
        pm_agnd_56, pm_agnd_57, pm_agnd_58, pm_agnd_59, pm_agnd_6,
        pm_agnd_60, pm_agnd_61, pm_agnd_62, pm_agnd_63,
        pm_agnd_64, pm_agnd_65, pm_agnd_66, pm_agnd_67,
        pm_agnd_68, pm_agnd_69, pm_agnd_7, pm_agnd_70, pm_agnd_71,
        pm_agnd_8, pm_agnd_9, pon00_ed_mpio_2, pon00_rssi_mpio_0,
        pon00_trx_rst_mpio_1, pon01_ed_mpio_2,
        pon01_rssi_mpio_0, pon01_trx_rst_mpio_1, pon0_3p3_a,
        pon0_pvdd1p0, pon0_rd0_n, pon0_rd0_p, pon0_rd1_n,
        pon0_rd1_p, pon0_refclkn, pon0_refclkp, pon0_rvdd1p0_1,
        pon0_rvdd1p0_2, pon0_td0_n, pon0_td0_p, pon0_td1_n,
        pon0_td1_p, pon0_tvdd1p0_1, pon0_tvdd1p0_2,
        pon20_ed_mpio_2, pon20_rssi_mpio_0,
        pon20_trx_rst_mpio_1, pon30_ed_mpio_2,
        pon30_rssi_mpio_0, pon30_trx_rst_mpio_1,
        pon31_ed_mpio_2, pon31_rssi_mpio_0,
        pon31_trx_rst_mpio_1, pon3_3p3_a, pon3_pvdd1p0,
        pon3_rd0_n, pon3_rd0_p, pon3_rd1_n, pon3_rd1_p,
        pon3_refclkn, pon3_refclkp, pon3_rvdd1p0_1,
        pon3_rvdd1p0_2, pon3_td0_n, pon3_td0_p, pon3_td1_n,
        pon3_td1_p, pon3_tvdd1p0_1, pon3_tvdd1p0_2, pon_agnd_1,
        pon_agnd_10, pon_agnd_11, pon_agnd_12, pon_agnd_13,
        pon_agnd_14, pon_agnd_15, pon_agnd_16, pon_agnd_17,
        pon_agnd_18, pon_agnd_19, pon_agnd_2, pon_agnd_20,
        pon_agnd_21, pon_agnd_22, pon_agnd_23, pon_agnd_24,
        pon_agnd_25, pon_agnd_26, pon_agnd_27, pon_agnd_28,
        pon_agnd_29, pon_agnd_3, pon_agnd_30, pon_agnd_31,
        pon_agnd_32, pon_agnd_33, pon_agnd_34, pon_agnd_35,
        pon_agnd_36, pon_agnd_37, pon_agnd_38, pon_agnd_39,
        pon_agnd_4, pon_agnd_40, pon_agnd_41, pon_agnd_42,
        pon_agnd_43, pon_agnd_44, pon_agnd_45, pon_agnd_46,
        pon_agnd_47, pon_agnd_48, pon_agnd_49, pon_agnd_5,
        pon_agnd_50, pon_agnd_51, pon_agnd_52, pon_agnd_53,
        pon_agnd_54, pon_agnd_55, pon_agnd_56, pon_agnd_57,
        pon_agnd_58, pon_agnd_59, pon_agnd_6, pon_agnd_60,
        pon_agnd_61, pon_agnd_62, pon_agnd_63, pon_agnd_64,
        pon_agnd_65, pon_agnd_66, pon_agnd_67, pon_agnd_68,
        pon_agnd_69, pon_agnd_7, pon_agnd_8, pon_agnd_9,
        pon_refclk_avdd1p8_1, pon_refclk_avdd1p8_2,
        pon_refclk_avss_1, pon_refclk_avss_2, pon_refclk_avss_3,
        pon_refclk_avss_4, pon_refclk_avss_5, pon_refclk_avss_6,
        pon_refclk_avss_7, pon_refclkn, pon_refclkp,
        pon_rescal_rext, pvtmon_adc, pvtmon_vdac, reserved_1,
        reserved_10, reserved_100, reserved_101, reserved_102,
        reserved_103, reserved_104, reserved_105, reserved_106,
        reserved_107, reserved_108, reserved_109, reserved_11,
        reserved_110, reserved_111, reserved_112, reserved_113,
        reserved_114, reserved_115, reserved_116, reserved_117,
        reserved_118, reserved_119, reserved_12, reserved_120,
        reserved_121, reserved_122, reserved_123, reserved_13,
        reserved_14, reserved_15, reserved_16, reserved_17,
        reserved_18, reserved_19, reserved_2, reserved_20,
        reserved_21, reserved_22, reserved_23, reserved_24,
        reserved_25, reserved_26, reserved_27, reserved_28,
        reserved_29, reserved_3, reserved_30, reserved_31,
        reserved_32, reserved_33, reserved_34, reserved_35,
        reserved_36, reserved_37, reserved_38, reserved_39,
        reserved_4, reserved_40, reserved_41, reserved_42,
        reserved_43, reserved_44, reserved_45, reserved_46,
        reserved_47, reserved_48, reserved_49, reserved_5,
        reserved_50, reserved_51, reserved_52, reserved_53,
        reserved_54, reserved_55, reserved_56, reserved_57,
        reserved_58, reserved_59, reserved_6, reserved_60,
        reserved_61, reserved_62, reserved_63, reserved_64,
        reserved_65, reserved_66, reserved_67, reserved_68,
        reserved_69, reserved_7, reserved_70, reserved_71,
        reserved_72, reserved_73, reserved_74, reserved_75,
        reserved_76, reserved_77, reserved_78, reserved_79,
        reserved_8, reserved_80, reserved_81, reserved_82,
        reserved_83, reserved_84, reserved_85, reserved_86,
        reserved_87, reserved_88, reserved_89, reserved_9,
        reserved_90, reserved_91, reserved_92, reserved_93,
        reserved_94, reserved_95, reserved_96, reserved_97,
        reserved_98, reserved_99, reset_out_b, spim_clk,
        spim_miso, spim_mosi, spim_ss0_b, spim_ss1_b, sys_reset_b,
        time_code, uart0_sin, uart0_sout, uart1_sin, uart1_sout,
        vdd1p8_pll0, vdd1p8_pll1, vddc_1, vddc_10, vddc_11,
        vddc_12, vddc_13, vddc_14, vddc_15, vddc_16, vddc_17,
        vddc_18, vddc_19, vddc_2, vddc_20, vddc_21, vddc_22,
        vddc_23, vddc_24, vddc_25, vddc_26, vddc_27, vddc_28,
        vddc_29, vddc_3, vddc_30, vddc_31, vddc_32, vddc_33,
        vddc_34, vddc_35, vddc_36, vddc_37, vddc_38, vddc_39,
        vddc_4, vddc_40, vddc_41, vddc_5, vddc_6, vddc_7, vddc_8,
        vddc_9, vddo_1, vddo_10, vddo_2, vddo_3, vddo_4, vddo_5,
        vddo_6, vddo_7, vddo_8, vddo_9, vddp1p8_1, vddp1p8_2,
        vddp1p8_3, vddp1p8_4, vss_1, vss_10, vss_100, vss_101,
        vss_102, vss_103, vss_104, vss_105, vss_106, vss_107,
        vss_108, vss_109, vss_11, vss_110, vss_111, vss_112,
        vss_113, vss_114, vss_115, vss_116, vss_117, vss_118,
        vss_119, vss_12, vss_120, vss_121, vss_122, vss_123,
        vss_124, vss_125, vss_126, vss_127, vss_128, vss_129,
        vss_13, vss_130, vss_131, vss_132, vss_133, vss_134,
        vss_135, vss_136, vss_137, vss_138, vss_139, vss_14,
        vss_140, vss_141, vss_142, vss_143, vss_144, vss_145,
        vss_146, vss_147, vss_148, vss_149, vss_15, vss_150,
        vss_151, vss_152, vss_153, vss_154, vss_155, vss_156,
        vss_157, vss_158, vss_159, vss_16, vss_160, vss_161,
        vss_162, vss_163, vss_164, vss_165, vss_166, vss_17, vss_18,
        vss_19, vss_2, vss_20, vss_21, vss_22, vss_23, vss_24,
        vss_25, vss_26, vss_27, vss_28, vss_29, vss_3, vss_30,
        vss_31, vss_32, vss_33, vss_34, vss_35, vss_36, vss_37,
        vss_38, vss_39, vss_4, vss_40, vss_41, vss_42, vss_43,
        vss_44, vss_45, vss_46, vss_47, vss_48, vss_49, vss_5,
        vss_50, vss_51, vss_52, vss_53, vss_54, vss_55, vss_56,
        vss_57, vss_58, vss_59, vss_6, vss_60, vss_61, vss_62,
        vss_63, vss_64, vss_65, vss_66, vss_67, vss_68, vss_69,
        vss_7, vss_70, vss_71, vss_72, vss_73, vss_74, vss_75,
        vss_76, vss_77, vss_78, vss_79, vss_8, vss_80, vss_81,
        vss_82, vss_83, vss_84, vss_85, vss_86, vss_87, vss_88,
        vss_89, vss_9, vss_90, vss_91, vss_92, vss_93, vss_94,
        vss_95, vss_96, vss_97, vss_98, vss_99);
    inout bit_clk;
    inout bsc_scl;
    inout bsc_sda;
    output cpu_ddr_a0;
    output cpu_ddr_a1;
    output cpu_ddr_a10;
    output cpu_ddr_a11;
    output cpu_ddr_a12;
    output cpu_ddr_a13;
    output cpu_ddr_a14;
    output cpu_ddr_a15;
    output cpu_ddr_a2;
    output cpu_ddr_a3;
    output cpu_ddr_a4;
    output cpu_ddr_a5;
    output cpu_ddr_a6;
    output cpu_ddr_a7;
    output cpu_ddr_a8;
    output cpu_ddr_a9;
    output cpu_ddr_ba0;
    output cpu_ddr_ba1;
    output cpu_ddr_ba2;
    output cpu_ddr_cas_b;
    output cpu_ddr_ck_n;
    output cpu_ddr_ck_p;
    output cpu_ddr_cke;
    output cpu_ddr_cs0_b;
    output cpu_ddr_cs1_b;
    output cpu_ddr_dm0;
    output cpu_ddr_dm1;
    inout cpu_ddr_dq0;
    inout cpu_ddr_dq1;
    inout cpu_ddr_dq10;
    inout cpu_ddr_dq11;
    inout cpu_ddr_dq12;
    inout cpu_ddr_dq13;
    inout cpu_ddr_dq14;
    inout cpu_ddr_dq15;
    inout cpu_ddr_dq2;
    inout cpu_ddr_dq3;
    inout cpu_ddr_dq4;
    inout cpu_ddr_dq5;
    inout cpu_ddr_dq6;
    inout cpu_ddr_dq7;
    inout cpu_ddr_dq8;
    inout cpu_ddr_dq9;
    inout cpu_ddr_dqs0_n;
    inout cpu_ddr_dqs0_p;
    inout cpu_ddr_dqs1_n;
    inout cpu_ddr_dqs1_p;
    input cpu_ddr_ldo_vddo;
    output cpu_ddr_odt;
    output cpu_ddr_ras_b;
    output cpu_ddr_rst_b;
    input cpu_ddr_vddc_1;
    input cpu_ddr_vddc_2;
    input cpu_ddr_vddc_3;
    input cpu_ddr_vddo_1;
    input cpu_ddr_vddo_2;
    input cpu_ddr_vddo_3;
    input cpu_ddr_vddo_4;
    input cpu_ddr_vddo_5;
    input cpu_ddr_vddo_6;
    input cpu_ddr_vddo_7;
    input cpu_ddr_vddo_8;
    input cpu_ddr_vddo_ck;
    output cpu_ddr_vref;
    output cpu_ddr_we_b;
    input cpu_ddr_zq;
    output dp_ddr0_a0;
    output dp_ddr0_a1;
    output dp_ddr0_a10;
    output dp_ddr0_a11;
    output dp_ddr0_a12;
    output dp_ddr0_a13;
    output dp_ddr0_a14;
    output dp_ddr0_a15;
    output dp_ddr0_a2;
    output dp_ddr0_a3;
    output dp_ddr0_a4;
    output dp_ddr0_a5;
    output dp_ddr0_a6;
    output dp_ddr0_a7;
    output dp_ddr0_a8;
    output dp_ddr0_a9;
    output dp_ddr0_ba0;
    output dp_ddr0_ba1;
    output dp_ddr0_ba2;
    output dp_ddr0_cas_b;
    output dp_ddr0_ck_n;
    output dp_ddr0_ck_p;
    output dp_ddr0_cke;
    output dp_ddr0_cs0_b;
    output dp_ddr0_cs1_b;
    output dp_ddr0_dm0;
    output dp_ddr0_dm1;
    output dp_ddr0_dm2;
    output dp_ddr0_dm3;
    inout dp_ddr0_dq0;
    inout dp_ddr0_dq1;
    inout dp_ddr0_dq10;
    inout dp_ddr0_dq11;
    inout dp_ddr0_dq12;
    inout dp_ddr0_dq13;
    inout dp_ddr0_dq14;
    inout dp_ddr0_dq15;
    inout dp_ddr0_dq16;
    inout dp_ddr0_dq17;
    inout dp_ddr0_dq18;
    inout dp_ddr0_dq19;
    inout dp_ddr0_dq2;
    inout dp_ddr0_dq20;
    inout dp_ddr0_dq21;
    inout dp_ddr0_dq22;
    inout dp_ddr0_dq23;
    inout dp_ddr0_dq24;
    inout dp_ddr0_dq25;
    inout dp_ddr0_dq26;
    inout dp_ddr0_dq27;
    inout dp_ddr0_dq28;
    inout dp_ddr0_dq29;
    inout dp_ddr0_dq3;
    inout dp_ddr0_dq30;
    inout dp_ddr0_dq31;
    inout dp_ddr0_dq4;
    inout dp_ddr0_dq5;
    inout dp_ddr0_dq6;
    inout dp_ddr0_dq7;
    inout dp_ddr0_dq8;
    inout dp_ddr0_dq9;
    inout dp_ddr0_dqs0_n;
    inout dp_ddr0_dqs0_p;
    inout dp_ddr0_dqs1_n;
    inout dp_ddr0_dqs1_p;
    inout dp_ddr0_dqs2_n;
    inout dp_ddr0_dqs2_p;
    inout dp_ddr0_dqs3_n;
    inout dp_ddr0_dqs3_p;
    input dp_ddr0_ldo_vddo;
    output dp_ddr0_odt;
    output dp_ddr0_ras_b;
    output dp_ddr0_rst_b;
    input dp_ddr0_vddc_1;
    input dp_ddr0_vddc_2;
    input dp_ddr0_vddc_3;
    input dp_ddr0_vddc_4;
    input dp_ddr0_vddo_1;
    input dp_ddr0_vddo_10;
    input dp_ddr0_vddo_11;
    input dp_ddr0_vddo_2;
    input dp_ddr0_vddo_3;
    input dp_ddr0_vddo_4;
    input dp_ddr0_vddo_5;
    input dp_ddr0_vddo_6;
    input dp_ddr0_vddo_7;
    input dp_ddr0_vddo_8;
    input dp_ddr0_vddo_9;
    input dp_ddr0_vddo_ck;
    output dp_ddr0_vref;
    output dp_ddr0_we_b;
    input dp_ddr0_zq;
    output dp_ddr1_a0;
    output dp_ddr1_a1;
    output dp_ddr1_a10;
    output dp_ddr1_a11;
    output dp_ddr1_a12;
    output dp_ddr1_a13;
    output dp_ddr1_a14;
    output dp_ddr1_a15;
    output dp_ddr1_a2;
    output dp_ddr1_a3;
    output dp_ddr1_a4;
    output dp_ddr1_a5;
    output dp_ddr1_a6;
    output dp_ddr1_a7;
    output dp_ddr1_a8;
    output dp_ddr1_a9;
    output dp_ddr1_ba0;
    output dp_ddr1_ba1;
    output dp_ddr1_ba2;
    output dp_ddr1_cas_b;
    output dp_ddr1_ck_n;
    output dp_ddr1_ck_p;
    output dp_ddr1_cke;
    output dp_ddr1_cs0_b;
    output dp_ddr1_cs1_b;
    output dp_ddr1_dm0;
    output dp_ddr1_dm1;
    output dp_ddr1_dm2;
    output dp_ddr1_dm3;
    inout dp_ddr1_dq0;
    inout dp_ddr1_dq1;
    inout dp_ddr1_dq10;
    inout dp_ddr1_dq11;
    inout dp_ddr1_dq12;
    inout dp_ddr1_dq13;
    inout dp_ddr1_dq14;
    inout dp_ddr1_dq15;
    inout dp_ddr1_dq16;
    inout dp_ddr1_dq17;
    inout dp_ddr1_dq18;
    inout dp_ddr1_dq19;
    inout dp_ddr1_dq2;
    inout dp_ddr1_dq20;
    inout dp_ddr1_dq21;
    inout dp_ddr1_dq22;
    inout dp_ddr1_dq23;
    inout dp_ddr1_dq24;
    inout dp_ddr1_dq25;
    inout dp_ddr1_dq26;
    inout dp_ddr1_dq27;
    inout dp_ddr1_dq28;
    inout dp_ddr1_dq29;
    inout dp_ddr1_dq3;
    inout dp_ddr1_dq30;
    inout dp_ddr1_dq31;
    inout dp_ddr1_dq4;
    inout dp_ddr1_dq5;
    inout dp_ddr1_dq6;
    inout dp_ddr1_dq7;
    inout dp_ddr1_dq8;
    inout dp_ddr1_dq9;
    inout dp_ddr1_dqs0_n;
    inout dp_ddr1_dqs0_p;
    inout dp_ddr1_dqs1_n;
    inout dp_ddr1_dqs1_p;
    inout dp_ddr1_dqs2_n;
    inout dp_ddr1_dqs2_p;
    inout dp_ddr1_dqs3_n;
    inout dp_ddr1_dqs3_p;
    input dp_ddr1_ldo_vddo;
    output dp_ddr1_odt;
    output dp_ddr1_ras_b;
    output dp_ddr1_rst_b;
    input dp_ddr1_vddc_1;
    input dp_ddr1_vddc_2;
    input dp_ddr1_vddc_3;
    input dp_ddr1_vddc_4;
    input dp_ddr1_vddo_1;
    input dp_ddr1_vddo_10;
    input dp_ddr1_vddo_11;
    input dp_ddr1_vddo_2;
    input dp_ddr1_vddo_3;
    input dp_ddr1_vddo_4;
    input dp_ddr1_vddo_5;
    input dp_ddr1_vddo_6;
    input dp_ddr1_vddo_7;
    input dp_ddr1_vddo_8;
    input dp_ddr1_vddo_9;
    input dp_ddr1_vddo_ck;
    output dp_ddr1_vref;
    output dp_ddr1_we_b;
    input dp_ddr1_zq;
    input ejtag_ce0;
    input ejtag_ce1;
    input ejtag_tck;
    input ejtag_tdi;
    output ejtag_tdo;
    input ejtag_tms;
    input ejtag_trst_b;
    inout gpio_00;
    inout gpio_01;
    inout gpio_02;
    inout gpio_03;
    inout gpio_04;
    inout gpio_05;
    inout gpio_06;
    inout gpio_07;
    inout gpio_08;
    inout gpio_09;
    inout gpio_10;
    inout gpio_11;
    inout gpio_12;
    inout gpio_13;
    inout gpio_14;
    inout gpio_15;
    inout gpio_16;
    inout gpio_17;
    inout gpio_18;
    inout gpio_19;
    inout gpio_20;
    inout gpio_21;
    inout gpio_22;
    inout gpio_23;
    inout gpio_24;
    inout gpio_25;
    inout gpio_26;
    inout gpio_27;
    inout gpio_28;
    inout gpio_29;
    inout gpio_30;
    inout gpio_31;
    inout gpio_32;
    inout gpio_33;
    inout gpio_34;
    inout gpio_35;
    inout gpio_36;
    inout gpio_37;
    inout gpio_38;
    inout gpio_39;
    inout gpio_40;
    input heartbeat;
    input main_refclk_avdd1p8;
    input main_refclk_avss_1;
    input main_refclk_avss_10;
    input main_refclk_avss_11;
    input main_refclk_avss_12;
    input main_refclk_avss_2;
    input main_refclk_avss_3;
    input main_refclk_avss_4;
    input main_refclk_avss_5;
    input main_refclk_avss_6;
    input main_refclk_avss_7;
    input main_refclk_avss_8;
    input main_refclk_avss_9;
    input main_refclkn;
    input main_refclkp;
    input otp_vddo;
    output pcie0_clkreq_b;
    input pcie0_pvdd1p0;
    input pcie0_rdn;
    input pcie0_rdp;
    input pcie0_refclkn;
    input pcie0_refclkp;
    input pcie0_rst_b;
    input pcie0_rvdd1p0;
    output pcie0_tdn;
    output pcie0_tdp;
    input pcie0_tvdd1p0;
    input pm0_pvdd1p0;
    input pm0_rd0_n;
    input pm0_rd0_p;
    input pm0_rd1_n;
    input pm0_rd1_p;
    input pm0_refclkn;
    input pm0_refclkp;
    input pm0_rescal_rext;
    input pm0_rvdd1p0_1;
    input pm0_rvdd1p0_2;
    output pm0_td0_n;
    output pm0_td0_p;
    output pm0_td1_n;
    output pm0_td1_p;
    input pm0_tvdd1p0_1;
    input pm0_tvdd1p0_2;
    input pm1_rescal_rext;
    input pm2_pvdd1p0;
    input pm2_rd0_n;
    input pm2_rd0_p;
    input pm2_rd1_n;
    input pm2_rd1_p;
    input pm2_refclkn;
    input pm2_refclkp;
    input pm2_rvdd1p0_1;
    input pm2_rvdd1p0_2;
    output pm2_td0_n;
    output pm2_td0_p;
    output pm2_td1_n;
    output pm2_td1_p;
    input pm2_tvdd1p0_1;
    input pm2_tvdd1p0_2;
    input pm_agnd_1;
    input pm_agnd_10;
    input pm_agnd_11;
    input pm_agnd_12;
    input pm_agnd_13;
    input pm_agnd_14;
    input pm_agnd_15;
    input pm_agnd_16;
    input pm_agnd_17;
    input pm_agnd_18;
    input pm_agnd_19;
    input pm_agnd_2;
    input pm_agnd_20;
    input pm_agnd_21;
    input pm_agnd_22;
    input pm_agnd_23;
    input pm_agnd_24;
    input pm_agnd_25;
    input pm_agnd_26;
    input pm_agnd_27;
    input pm_agnd_28;
    input pm_agnd_29;
    input pm_agnd_3;
    input pm_agnd_30;
    input pm_agnd_31;
    input pm_agnd_32;
    input pm_agnd_33;
    input pm_agnd_34;
    input pm_agnd_35;
    input pm_agnd_36;
    input pm_agnd_37;
    input pm_agnd_38;
    input pm_agnd_39;
    input pm_agnd_4;
    input pm_agnd_40;
    input pm_agnd_41;
    input pm_agnd_42;
    input pm_agnd_43;
    input pm_agnd_44;
    input pm_agnd_45;
    input pm_agnd_46;
    input pm_agnd_47;
    input pm_agnd_48;
    input pm_agnd_49;
    input pm_agnd_5;
    input pm_agnd_50;
    input pm_agnd_51;
    input pm_agnd_52;
    input pm_agnd_53;
    input pm_agnd_54;
    input pm_agnd_55;
    input pm_agnd_56;
    input pm_agnd_57;
    input pm_agnd_58;
    input pm_agnd_59;
    input pm_agnd_6;
    input pm_agnd_60;
    input pm_agnd_61;
    input pm_agnd_62;
    input pm_agnd_63;
    input pm_agnd_64;
    input pm_agnd_65;
    input pm_agnd_66;
    input pm_agnd_67;
    input pm_agnd_68;
    input pm_agnd_69;
    input pm_agnd_7;
    input pm_agnd_70;
    input pm_agnd_71;
    input pm_agnd_8;
    input pm_agnd_9;
    inout pon00_ed_mpio_2;
    inout pon00_rssi_mpio_0;
    inout pon00_trx_rst_mpio_1;
    inout pon01_ed_mpio_2;
    inout pon01_rssi_mpio_0;
    inout pon01_trx_rst_mpio_1;
    input pon0_3p3_a;
    input pon0_pvdd1p0;
    input pon0_rd0_n;
    input pon0_rd0_p;
    input pon0_rd1_n;
    input pon0_rd1_p;
    input pon0_refclkn;
    input pon0_refclkp;
    input pon0_rvdd1p0_1;
    input pon0_rvdd1p0_2;
    output pon0_td0_n;
    output pon0_td0_p;
    output pon0_td1_n;
    output pon0_td1_p;
    input pon0_tvdd1p0_1;
    input pon0_tvdd1p0_2;
    inout pon20_ed_mpio_2;
    inout pon20_rssi_mpio_0;
    inout pon20_trx_rst_mpio_1;
    inout pon30_ed_mpio_2;
    inout pon30_rssi_mpio_0;
    inout pon30_trx_rst_mpio_1;
    inout pon31_ed_mpio_2;
    inout pon31_rssi_mpio_0;
    inout pon31_trx_rst_mpio_1;
    input pon3_3p3_a;
    input pon3_pvdd1p0;
    input pon3_rd0_n;
    input pon3_rd0_p;
    input pon3_rd1_n;
    input pon3_rd1_p;
    input pon3_refclkn;
    input pon3_refclkp;
    input pon3_rvdd1p0_1;
    input pon3_rvdd1p0_2;
    output pon3_td0_n;
    output pon3_td0_p;
    output pon3_td1_n;
    output pon3_td1_p;
    input pon3_tvdd1p0_1;
    input pon3_tvdd1p0_2;
    input pon_agnd_1;
    input pon_agnd_10;
    input pon_agnd_11;
    input pon_agnd_12;
    input pon_agnd_13;
    input pon_agnd_14;
    input pon_agnd_15;
    input pon_agnd_16;
    input pon_agnd_17;
    input pon_agnd_18;
    input pon_agnd_19;
    input pon_agnd_2;
    input pon_agnd_20;
    input pon_agnd_21;
    input pon_agnd_22;
    input pon_agnd_23;
    input pon_agnd_24;
    input pon_agnd_25;
    input pon_agnd_26;
    input pon_agnd_27;
    input pon_agnd_28;
    input pon_agnd_29;
    input pon_agnd_3;
    input pon_agnd_30;
    input pon_agnd_31;
    input pon_agnd_32;
    input pon_agnd_33;
    input pon_agnd_34;
    input pon_agnd_35;
    input pon_agnd_36;
    input pon_agnd_37;
    input pon_agnd_38;
    input pon_agnd_39;
    input pon_agnd_4;
    input pon_agnd_40;
    input pon_agnd_41;
    input pon_agnd_42;
    input pon_agnd_43;
    input pon_agnd_44;
    input pon_agnd_45;
    input pon_agnd_46;
    input pon_agnd_47;
    input pon_agnd_48;
    input pon_agnd_49;
    input pon_agnd_5;
    input pon_agnd_50;
    input pon_agnd_51;
    input pon_agnd_52;
    input pon_agnd_53;
    input pon_agnd_54;
    input pon_agnd_55;
    input pon_agnd_56;
    input pon_agnd_57;
    input pon_agnd_58;
    input pon_agnd_59;
    input pon_agnd_6;
    input pon_agnd_60;
    input pon_agnd_61;
    input pon_agnd_62;
    input pon_agnd_63;
    input pon_agnd_64;
    input pon_agnd_65;
    input pon_agnd_66;
    input pon_agnd_67;
    input pon_agnd_68;
    input pon_agnd_69;
    input pon_agnd_7;
    input pon_agnd_8;
    input pon_agnd_9;
    input pon_refclk_avdd1p8_1;
    input pon_refclk_avdd1p8_2;
    input pon_refclk_avss_1;
    input pon_refclk_avss_2;
    input pon_refclk_avss_3;
    input pon_refclk_avss_4;
    input pon_refclk_avss_5;
    input pon_refclk_avss_6;
    input pon_refclk_avss_7;
    input pon_refclkn;
    input pon_refclkp;
    input pon_rescal_rext;
    inout pvtmon_adc;
    inout pvtmon_vdac;
    inout reserved_1;
    inout reserved_10;
    inout reserved_100;
    inout reserved_101;
    inout reserved_102;
    inout reserved_103;
    inout reserved_104;
    inout reserved_105;
    inout reserved_106;
    inout reserved_107;
    inout reserved_108;
    inout reserved_109;
    inout reserved_11;
    inout reserved_110;
    inout reserved_111;
    inout reserved_112;
    inout reserved_113;
    inout reserved_114;
    inout reserved_115;
    inout reserved_116;
    inout reserved_117;
    inout reserved_118;
    inout reserved_119;
    inout reserved_12;
    inout reserved_120;
    inout reserved_121;
    inout reserved_122;
    inout reserved_123;
    inout reserved_13;
    inout reserved_14;
    inout reserved_15;
    inout reserved_16;
    inout reserved_17;
    inout reserved_18;
    inout reserved_19;
    inout reserved_2;
    inout reserved_20;
    inout reserved_21;
    inout reserved_22;
    inout reserved_23;
    inout reserved_24;
    inout reserved_25;
    inout reserved_26;
    inout reserved_27;
    inout reserved_28;
    inout reserved_29;
    inout reserved_3;
    inout reserved_30;
    inout reserved_31;
    inout reserved_32;
    inout reserved_33;
    inout reserved_34;
    inout reserved_35;
    inout reserved_36;
    inout reserved_37;
    inout reserved_38;
    inout reserved_39;
    inout reserved_4;
    inout reserved_40;
    inout reserved_41;
    inout reserved_42;
    inout reserved_43;
    inout reserved_44;
    inout reserved_45;
    inout reserved_46;
    inout reserved_47;
    inout reserved_48;
    inout reserved_49;
    inout reserved_5;
    inout reserved_50;
    inout reserved_51;
    inout reserved_52;
    inout reserved_53;
    inout reserved_54;
    inout reserved_55;
    inout reserved_56;
    inout reserved_57;
    inout reserved_58;
    inout reserved_59;
    inout reserved_6;
    inout reserved_60;
    inout reserved_61;
    inout reserved_62;
    inout reserved_63;
    inout reserved_64;
    inout reserved_65;
    inout reserved_66;
    inout reserved_67;
    inout reserved_68;
    inout reserved_69;
    inout reserved_7;
    inout reserved_70;
    inout reserved_71;
    inout reserved_72;
    inout reserved_73;
    inout reserved_74;
    inout reserved_75;
    inout reserved_76;
    inout reserved_77;
    inout reserved_78;
    inout reserved_79;
    inout reserved_8;
    inout reserved_80;
    inout reserved_81;
    inout reserved_82;
    inout reserved_83;
    inout reserved_84;
    inout reserved_85;
    inout reserved_86;
    inout reserved_87;
    inout reserved_88;
    inout reserved_89;
    inout reserved_9;
    inout reserved_90;
    inout reserved_91;
    inout reserved_92;
    inout reserved_93;
    inout reserved_94;
    inout reserved_95;
    inout reserved_96;
    inout reserved_97;
    inout reserved_98;
    inout reserved_99;
    inout reset_out_b;
    inout spim_clk;
    inout spim_miso;
    inout spim_mosi;
    inout spim_ss0_b;
    inout spim_ss1_b;
    inout sys_reset_b;
    input time_code;
    inout uart0_sin;
    inout uart0_sout;
    inout uart1_sin;
    inout uart1_sout;
    input vdd1p8_pll0;
    input vdd1p8_pll1;
    input vddc_1;
    input vddc_10;
    input vddc_11;
    input vddc_12;
    input vddc_13;
    input vddc_14;
    input vddc_15;
    input vddc_16;
    input vddc_17;
    input vddc_18;
    input vddc_19;
    input vddc_2;
    input vddc_20;
    input vddc_21;
    input vddc_22;
    input vddc_23;
    input vddc_24;
    input vddc_25;
    input vddc_26;
    input vddc_27;
    input vddc_28;
    input vddc_29;
    input vddc_3;
    input vddc_30;
    input vddc_31;
    input vddc_32;
    input vddc_33;
    input vddc_34;
    input vddc_35;
    input vddc_36;
    input vddc_37;
    input vddc_38;
    input vddc_39;
    input vddc_4;
    input vddc_40;
    input vddc_41;
    input vddc_5;
    input vddc_6;
    input vddc_7;
    input vddc_8;
    input vddc_9;
    input vddo_1;
    input vddo_10;
    input vddo_2;
    input vddo_3;
    input vddo_4;
    input vddo_5;
    input vddo_6;
    input vddo_7;
    input vddo_8;
    input vddo_9;
    input vddp1p8_1;
    input vddp1p8_2;
    input vddp1p8_3;
    input vddp1p8_4;
    input vss_1;
    input vss_10;
    input vss_100;
    input vss_101;
    input vss_102;
    input vss_103;
    input vss_104;
    input vss_105;
    input vss_106;
    input vss_107;
    input vss_108;
    input vss_109;
    input vss_11;
    input vss_110;
    input vss_111;
    input vss_112;
    input vss_113;
    input vss_114;
    input vss_115;
    input vss_116;
    input vss_117;
    input vss_118;
    input vss_119;
    input vss_12;
    input vss_120;
    input vss_121;
    input vss_122;
    input vss_123;
    input vss_124;
    input vss_125;
    input vss_126;
    input vss_127;
    input vss_128;
    input vss_129;
    input vss_13;
    input vss_130;
    input vss_131;
    input vss_132;
    input vss_133;
    input vss_134;
    input vss_135;
    input vss_136;
    input vss_137;
    input vss_138;
    input vss_139;
    input vss_14;
    input vss_140;
    input vss_141;
    input vss_142;
    input vss_143;
    input vss_144;
    input vss_145;
    input vss_146;
    input vss_147;
    input vss_148;
    input vss_149;
    input vss_15;
    input vss_150;
    input vss_151;
    input vss_152;
    input vss_153;
    input vss_154;
    input vss_155;
    input vss_156;
    input vss_157;
    input vss_158;
    input vss_159;
    input vss_16;
    input vss_160;
    input vss_161;
    input vss_162;
    input vss_163;
    input vss_164;
    input vss_165;
    input vss_166;
    input vss_17;
    input vss_18;
    input vss_19;
    input vss_2;
    input vss_20;
    input vss_21;
    input vss_22;
    input vss_23;
    input vss_24;
    input vss_25;
    input vss_26;
    input vss_27;
    input vss_28;
    input vss_29;
    input vss_3;
    input vss_30;
    input vss_31;
    input vss_32;
    input vss_33;
    input vss_34;
    input vss_35;
    input vss_36;
    input vss_37;
    input vss_38;
    input vss_39;
    input vss_4;
    input vss_40;
    input vss_41;
    input vss_42;
    input vss_43;
    input vss_44;
    input vss_45;
    input vss_46;
    input vss_47;
    input vss_48;
    input vss_49;
    input vss_5;
    input vss_50;
    input vss_51;
    input vss_52;
    input vss_53;
    input vss_54;
    input vss_55;
    input vss_56;
    input vss_57;
    input vss_58;
    input vss_59;
    input vss_6;
    input vss_60;
    input vss_61;
    input vss_62;
    input vss_63;
    input vss_64;
    input vss_65;
    input vss_66;
    input vss_67;
    input vss_68;
    input vss_69;
    input vss_7;
    input vss_70;
    input vss_71;
    input vss_72;
    input vss_73;
    input vss_74;
    input vss_75;
    input vss_76;
    input vss_77;
    input vss_78;
    input vss_79;
    input vss_8;
    input vss_80;
    input vss_81;
    input vss_82;
    input vss_83;
    input vss_84;
    input vss_85;
    input vss_86;
    input vss_87;
    input vss_88;
    input vss_89;
    input vss_9;
    input vss_90;
    input vss_91;
    input vss_92;
    input vss_93;
    input vss_94;
    input vss_95;
    input vss_96;
    input vss_97;
    input vss_98;
    input vss_99;


    initial
        begin
        end

endmodule
