// generated by newgenasym  Mon Aug 31 11:34:06 2020


module bcm53125 (avddh_0, avddh_1, avddh_2, avddh_3, avddh_4, avddh_5,
        avddh_6, avddh_7, avddl_0, avddl_1, dvdd_0, dvdd_1, dvdd_2,
        dvdd_3, dvdd_4, dvdd_5, dvdd_6, egphy_bvdd, egphy_pllvdd,
        egphy_rdac, fclk, fcs, fsi, fso, \gmii_gtxclk/nc ,
        gmii_led_sel, gmii_rxclk, \gmii_rxd0/led10 ,
        \gmii_rxd1/led11 , \gmii_rxd2/led12 , \gmii_rxd3/led13 ,
        \gmii_rxd4/led14 , \gmii_rxd5/led15 , \gmii_rxd6/led16 ,
        \gmii_rxd7/led17 , \gmii_rxdv/led18 , \gmii_rxer/led19 ,
        \gmii_txclk/nc , \gmii_txd0/nc , \gmii_txd1/nc , \gmii_txd2/nc ,
        \gmii_txd3/nc , \gmii_txd4/nc , \gmii_txd5/nc , \gmii_txd6/nc ,
        \gmii_txd7/nc , \gmii_txen/nc , \gmii_txer/nc , gmii_vol_ref,
        gmii_vol_sel1, imp_gtxclk, imp_rxclk, imp_rxd0, imp_rxd1,
        imp_rxd2, imp_rxd3, imp_rxd4, imp_rxd5, imp_rxd6, imp_rxd7,
        imp_rxdv, imp_rxer, imp_txclk, imp_txd0, imp_txd1,
        imp_txd2, imp_txd3, imp_txd4, imp_txd5, imp_txd6, imp_txd7,
        imp_txen, imp_txer, imp_vol_ref, imp_vol_sel1, int,
        \led0/mii_dumb_fwdg_en , led1, \led2/led_mode1 ,
        \led3/sys_freq1 , \led4/gmii_mode0 , \led5/gmii_mode1 ,
        \led6/imp_mode0 , \led7/imp_mode1 , \led8/cpu_eeprom_sel ,
        \led9/hw_fwdg_en , \ledclk/led_mode0 , \leddata/sys_freq0 ,
        mdc, mdio, \miso/en_eee , mosi, nc1, nc10, nc11, nc12, nc13,
        nc14, nc15, nc16, nc17, nc18, nc19, nc2, nc20, nc21, nc22, nc23,
        nc24, nc25, nc26, nc27, nc28, nc29, nc3, nc30, nc31, nc32, nc4,
        nc5, nc6, nc7, nc8, nc9, ndrive, otp_vdd, ovdd2_io, ovdd3_wan,
        ovdd_imp, pdrive, pll_avdd, qgphy1_bvdd, qgphy1_pllvdd,
        qgphy1_rdac, qgphy2_bvdd, qgphy2_pllvdd, qgphy2_rdac,
        reset, sck, ss, swreg_vddo, tck, tdi, tdn_0_0, tdn_0_1,
        tdn_0_2, tdn_0_3, tdn_0_4, tdn_1_0, tdn_1_1, tdn_1_2,
        tdn_1_3, tdn_1_4, tdn_2_0, tdn_2_1, tdn_2_2, tdn_2_3,
        tdn_2_4, tdn_3_0, tdn_3_1, tdn_3_2, tdn_3_3, tdn_3_4,
        \tdo/en_8051 , tdp_0_0, tdp_0_1, tdp_0_2, tdp_0_3, tdp_0_4,
        tdp_1_0, tdp_1_1, tdp_1_2, tdp_1_3, tdp_1_4, tdp_2_0,
        tdp_2_1, tdp_2_2, tdp_2_3, tdp_2_4, tdp_3_0, tdp_3_1,
        tdp_3_2, tdp_3_3, tdp_3_4, tms, trst, vfb, vss_0, vss_1,
        xtal_avdd, xtal_i, xtal_o);
    input avddh_0;
    input avddh_1;
    input avddh_2;
    input avddh_3;
    input avddh_4;
    input avddh_5;
    input avddh_6;
    input avddh_7;
    input avddl_0;
    input avddl_1;
    input dvdd_0;
    input dvdd_1;
    input dvdd_2;
    input dvdd_3;
    input dvdd_4;
    input dvdd_5;
    input dvdd_6;
    input egphy_bvdd;
    input egphy_pllvdd;
    input egphy_rdac;
    output fclk;
    output fcs;
    input fsi;
    output fso;
    output \gmii_gtxclk/nc ;
    input gmii_led_sel;
    input gmii_rxclk;
    input \gmii_rxd0/led10 ;
    input \gmii_rxd1/led11 ;
    input \gmii_rxd2/led12 ;
    input \gmii_rxd3/led13 ;
    input \gmii_rxd4/led14 ;
    input \gmii_rxd5/led15 ;
    input \gmii_rxd6/led16 ;
    input \gmii_rxd7/led17 ;
    input \gmii_rxdv/led18 ;
    input \gmii_rxer/led19 ;
    output \gmii_txclk/nc ;
    output \gmii_txd0/nc ;
    output \gmii_txd1/nc ;
    output \gmii_txd2/nc ;
    output \gmii_txd3/nc ;
    output \gmii_txd4/nc ;
    output \gmii_txd5/nc ;
    output \gmii_txd6/nc ;
    output \gmii_txd7/nc ;
    output \gmii_txen/nc ;
    output \gmii_txer/nc ;
    input gmii_vol_ref;
    input gmii_vol_sel1;
    output imp_gtxclk;
    inout imp_rxclk;
    input imp_rxd0;
    input imp_rxd1;
    input imp_rxd2;
    input imp_rxd3;
    input imp_rxd4;
    input imp_rxd5;
    input imp_rxd6;
    input imp_rxd7;
    input imp_rxdv;
    input imp_rxer;
    inout imp_txclk;
    output imp_txd0;
    output imp_txd1;
    output imp_txd2;
    output imp_txd3;
    output imp_txd4;
    output imp_txd5;
    output imp_txd6;
    output imp_txd7;
    output imp_txen;
    output imp_txer;
    input imp_vol_ref;
    input imp_vol_sel1;
    output int;
    output \led0/mii_dumb_fwdg_en ;
    output led1;
    output \led2/led_mode1 ;
    output \led3/sys_freq1 ;
    output \led4/gmii_mode0 ;
    output \led5/gmii_mode1 ;
    output \led6/imp_mode0 ;
    output \led7/imp_mode1 ;
    output \led8/cpu_eeprom_sel ;
    output \led9/hw_fwdg_en ;
    output \ledclk/led_mode0 ;
    output \leddata/sys_freq0 ;
    inout mdc;
    inout mdio;
    inout \miso/en_eee ;
    inout mosi;
    inout nc1;
    inout nc10;
    inout nc11;
    inout nc12;
    inout nc13;
    inout nc14;
    inout nc15;
    inout nc16;
    inout nc17;
    inout nc18;
    inout nc19;
    inout nc2;
    inout nc20;
    inout nc21;
    inout nc22;
    inout nc23;
    inout nc24;
    inout nc25;
    inout nc26;
    inout nc27;
    inout nc28;
    inout nc29;
    inout nc3;
    inout nc30;
    inout nc31;
    inout nc32;
    inout nc4;
    inout nc5;
    inout nc6;
    inout nc7;
    inout nc8;
    inout nc9;
    output ndrive;
    input otp_vdd;
    input ovdd2_io;
    input ovdd3_wan;
    input ovdd_imp;
    output pdrive;
    input pll_avdd;
    input qgphy1_bvdd;
    input qgphy1_pllvdd;
    input qgphy1_rdac;
    input qgphy2_bvdd;
    input qgphy2_pllvdd;
    input qgphy2_rdac;
    input reset;
    inout sck;
    inout ss;
    input swreg_vddo;
    input tck;
    input tdi;
    inout tdn_0_0;
    inout tdn_0_1;
    inout tdn_0_2;
    inout tdn_0_3;
    inout tdn_0_4;
    inout tdn_1_0;
    inout tdn_1_1;
    inout tdn_1_2;
    inout tdn_1_3;
    inout tdn_1_4;
    inout tdn_2_0;
    inout tdn_2_1;
    inout tdn_2_2;
    inout tdn_2_3;
    inout tdn_2_4;
    inout tdn_3_0;
    inout tdn_3_1;
    inout tdn_3_2;
    inout tdn_3_3;
    inout tdn_3_4;
    output \tdo/en_8051 ;
    inout tdp_0_0;
    inout tdp_0_1;
    inout tdp_0_2;
    inout tdp_0_3;
    inout tdp_0_4;
    inout tdp_1_0;
    inout tdp_1_1;
    inout tdp_1_2;
    inout tdp_1_3;
    inout tdp_1_4;
    inout tdp_2_0;
    inout tdp_2_1;
    inout tdp_2_2;
    inout tdp_2_3;
    inout tdp_2_4;
    inout tdp_3_0;
    inout tdp_3_1;
    inout tdp_3_2;
    inout tdp_3_3;
    inout tdp_3_4;
    input tms;
    input trst;
    output vfb;
    input vss_0;
    input vss_1;
    input xtal_avdd;
    input xtal_i;
    output xtal_o;


    initial
        begin
        end

endmodule
