// generated by newgenasym  Mon Aug 31 14:23:01 2020


module rtl8367 (agnd, atestck, avddh_1, avddh_10, avddh_2, avddh_3,
        avddh_4, avddh_5, avddh_6, avddh_7, avddh_8, avddh_9,
        avddl_1, avddl_2, avddl_3, avddl_4, avddl_5, avddl_6,
        avddl_7, \disautoload/p2led0/gpio45 , dvddio_1, dvddio_1_1,
        dvddio_1_2, dvddio_2, dvddio_2_1, dvddio_2_2, dvddl_1,
        dvddl_2, dvddl_3, \eeprom_mod/p4led0/gpio39 ,
        \en_phy/p0led2/gpio50 , \en_pwrlight/p3led2/gpio42 , epad,
        \gpio57/interrupt , \gpio58/dis_lpd , \led_da/p0led1/gpio51 ,
        \m1m_crs/gpio13 , \m1p_rxclk/m1m_txclk/rg1_txclk/gpio24 ,
        \m1p_rxd0/m1m_txd0/rg1_txd0/gpio22 ,
        \m1p_rxd1/m1m_txd1/rg1_txd1/gpio21 ,
        \m1p_rxd2/m1m_txd2/rg1_txd2/gpio20 ,
        \m1p_rxd3/m1m_txd3/rg1_txd3/gpio19 ,
        \m1p_rxdv/m1m_txen/rg1_txctl/gpio23 ,
        \m1p_txclk/m1m_rxclk/rg1_rxclk/gpio28 ,
        \m1p_txd0/m1m_rxd0/rg1_rxd0/gpio30 ,
        \m1p_txd1/m1m_rxd1/rg1_rxd1/gpio31 ,
        \m1p_txd2/m1m_rxd2/rg1_rxd2/gpio32 ,
        \m1p_txd3/m1m_rxd3/rg1_rxd3/gpio33 ,
        \m1p_txen/m1m_rxdv/rg1_rxctl/gpio29 , \m2m_crs/gpio00 ,
        \m2p_rxclk/m2m_txclk/rg2_txclk/gpio06 ,
        \m2p_rxd0/m2m_txd0/rg2_txd0/gpio04 ,
        \m2p_rxd1/m2m_txd1/rg2_txd1/gpio03 ,
        \m2p_rxd2/m2m_txd2/rg2_txd2/gpio02 ,
        \m2p_rxd3/m2m_txd3/rg2_txd3/gpio01 ,
        \m2p_rxdv/m2m_txen/rg2_txctl/gpio05 ,
        \m2p_txclk/m2m_rxclk/rg2_rxclk/gpio07 ,
        \m2p_txd0/m2m_rxd0/rg2_rxd0/gpio09 ,
        \m2p_txd1/m2m_rxd1/rg2_rxd1/gpio10 ,
        \m2p_txd2/m2m_rxd2/rg2_rxd2/gpio11 ,
        \m2p_txd3/m2m_rxd3/rg2_rxd3/gpio12 ,
        \m2p_txen/m2m_rxdv/rg2_rxctl/gpio08 , mdiref,
        \mid29/p1led0/gpio48 , nc_1, nc_2, nc_3, nreset, p0mdian,
        p0mdiap, p0mdibn, p0mdibp, p0mdicn, p0mdicp, p0mdidn,
        p0mdidp, \p1led1/gpio49 , p1mdian, p1mdiap, p1mdibn, p1mdibp,
        p1mdicn, p1mdicp, p1mdidn, p1mdidp, \p2led1/gpio46 , p2mdian,
        p2mdiap, p2mdibn, p2mdibp, p2mdicn, p2mdicp, p2mdidn,
        p2mdidp, \p3led1/gpio41 , p3mdian, p3mdiap, p3mdibn, p3mdibp,
        p3mdicn, p3mdicp, p3mdidn, p3mdidp, \p4led1/gpio40 , p4mdian,
        p4mdiap, p4mdibn, p4mdibp, p4mdicn, p4mdicp, p4mdidn,
        p4mdidp, pllgnd, pllvddl, \reserved/p1led2/gpio47 ,
        \reserved/p2led2/gpio44 , \reserved/p3led0/gpio43 ,
        \reserved/p4led2/gpio38 , reserved_1, reserved_2, rtt1,
        rtt2, \sck/spis_ck/gpio54 , \sda/spis_di/gpio55 ,
        \smi_sel/led_ck/p0led0/gpio52 , \spis_do/gpio56 ,
        \spis_ncsi/gpio53 , xtali, xtalo);
    input agnd;
    input atestck;
    input avddh_1;
    input avddh_10;
    input avddh_2;
    input avddh_3;
    input avddh_4;
    input avddh_5;
    input avddh_6;
    input avddh_7;
    input avddh_8;
    input avddh_9;
    input avddl_1;
    input avddl_2;
    input avddl_3;
    input avddl_4;
    input avddl_5;
    input avddl_6;
    input avddl_7;
    output \disautoload/p2led0/gpio45 ;
    input dvddio_1;
    input dvddio_1_1;
    input dvddio_1_2;
    input dvddio_2;
    input dvddio_2_1;
    input dvddio_2_2;
    input dvddl_1;
    input dvddl_2;
    input dvddl_3;
    output \eeprom_mod/p4led0/gpio39 ;
    output \en_phy/p0led2/gpio50 ;
    output \en_pwrlight/p3led2/gpio42 ;
    inout epad;
    output \gpio57/interrupt ;
    inout \gpio58/dis_lpd ;
    output \led_da/p0led1/gpio51 ;
    input \m1m_crs/gpio13 ;
    output \m1p_rxclk/m1m_txclk/rg1_txclk/gpio24 ;
    output \m1p_rxd0/m1m_txd0/rg1_txd0/gpio22 ;
    output \m1p_rxd1/m1m_txd1/rg1_txd1/gpio21 ;
    output \m1p_rxd2/m1m_txd2/rg1_txd2/gpio20 ;
    output \m1p_rxd3/m1m_txd3/rg1_txd3/gpio19 ;
    output \m1p_rxdv/m1m_txen/rg1_txctl/gpio23 ;
    input \m1p_txclk/m1m_rxclk/rg1_rxclk/gpio28 ;
    input \m1p_txd0/m1m_rxd0/rg1_rxd0/gpio30 ;
    input \m1p_txd1/m1m_rxd1/rg1_rxd1/gpio31 ;
    input \m1p_txd2/m1m_rxd2/rg1_rxd2/gpio32 ;
    input \m1p_txd3/m1m_rxd3/rg1_rxd3/gpio33 ;
    input \m1p_txen/m1m_rxdv/rg1_rxctl/gpio29 ;
    input \m2m_crs/gpio00 ;
    output \m2p_rxclk/m2m_txclk/rg2_txclk/gpio06 ;
    output \m2p_rxd0/m2m_txd0/rg2_txd0/gpio04 ;
    output \m2p_rxd1/m2m_txd1/rg2_txd1/gpio03 ;
    output \m2p_rxd2/m2m_txd2/rg2_txd2/gpio02 ;
    output \m2p_rxd3/m2m_txd3/rg2_txd3/gpio01 ;
    output \m2p_rxdv/m2m_txen/rg2_txctl/gpio05 ;
    inout \m2p_txclk/m2m_rxclk/rg2_rxclk/gpio07 ;
    input \m2p_txd0/m2m_rxd0/rg2_rxd0/gpio09 ;
    input \m2p_txd1/m2m_rxd1/rg2_rxd1/gpio10 ;
    input \m2p_txd2/m2m_rxd2/rg2_rxd2/gpio11 ;
    input \m2p_txd3/m2m_rxd3/rg2_rxd3/gpio12 ;
    input \m2p_txen/m2m_rxdv/rg2_rxctl/gpio08 ;
    output mdiref;
    output \mid29/p1led0/gpio48 ;
    inout nc_1;
    inout nc_2;
    inout nc_3;
    input nreset;
    inout p0mdian;
    inout p0mdiap;
    inout p0mdibn;
    inout p0mdibp;
    inout p0mdicn;
    inout p0mdicp;
    inout p0mdidn;
    inout p0mdidp;
    output \p1led1/gpio49 ;
    inout p1mdian;
    inout p1mdiap;
    inout p1mdibn;
    inout p1mdibp;
    inout p1mdicn;
    inout p1mdicp;
    inout p1mdidn;
    inout p1mdidp;
    output \p2led1/gpio46 ;
    inout p2mdian;
    inout p2mdiap;
    inout p2mdibn;
    inout p2mdibp;
    inout p2mdicn;
    inout p2mdicp;
    inout p2mdidn;
    inout p2mdidp;
    output \p3led1/gpio41 ;
    inout p3mdian;
    inout p3mdiap;
    inout p3mdibn;
    inout p3mdibp;
    inout p3mdicn;
    inout p3mdicp;
    inout p3mdidn;
    inout p3mdidp;
    output \p4led1/gpio40 ;
    inout p4mdian;
    inout p4mdiap;
    inout p4mdibn;
    inout p4mdibp;
    inout p4mdicn;
    inout p4mdicp;
    inout p4mdidn;
    inout p4mdidp;
    input pllgnd;
    input pllvddl;
    output \reserved/p1led2/gpio47 ;
    output \reserved/p2led2/gpio44 ;
    output \reserved/p3led0/gpio43 ;
    output \reserved/p4led2/gpio38 ;
    output reserved_1;
    input reserved_2;
    output rtt1;
    output rtt2;
    inout \sck/spis_ck/gpio54 ;
    inout \sda/spis_di/gpio55 ;
    output \smi_sel/led_ck/p0led0/gpio52 ;
    input \spis_do/gpio56 ;
    input \spis_ncsi/gpio53 ;
    input xtali;
    output xtalo;


    initial
        begin
        end

endmodule
