// generated by newgenasym  Thu Oct 21 09:53:19 2021


module bosa (gnd1, gnd2, gnd3, gnd_r, gnd_t, gnd_t1, gnd_t2, gnd_t3,
        \ld+/pd- , \ld- , \pd+ , rxn, rxp, vapd, vcc);
    output gnd1;
    output gnd2;
    output gnd3;
    inout gnd_r;
    inout gnd_t;
    output gnd_t1;
    output gnd_t2;
    output gnd_t3;
    inout \ld+/pd- ;
    inout \ld- ;
    inout \pd+ ;
    inout rxn;
    inout rxp;
    inout vapd;
    inout vcc;


    initial
        begin
        end

endmodule
