// generated by newgenasym  Mon Aug 31 13:58:47 2020


module hdc1080 (epad, gnd, nc1, nc2, scl, sda, vdd);
    inout epad;
    input gnd;
    inout nc1;
    inout nc2;
    inout scl;
    inout sda;
    inout vdd;


    initial
        begin
        end

endmodule
