-- generated by newgenasym Mon Aug 31 13:58:47 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hdc1080 is
    port (    
	EPAD:      INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end hdc1080;
