// generated by newgenasym  Fri Feb 24 15:22:28 2023


module mt7976cn (antsel_10, antsel_11, antsel_12, antsel_13, antsel_14,
        antsel_15, antsel_5, antsel_6, antsel_7, antsel_8,
        antsel_9, avdd18_wf0_dig, avdd18_wf0_io, avdd18_wf0_sx,
        avdd18_wf0_top, avdd18_wf0_tx, avdd18_wf0_tx_ga,
        avdd18_wf1_tx, avdd18_wf3_dig, avdd18_wf3_sx,
        avdd18_wf3_top, avdd18_wf3_tx_ga, avdd33_esd,
        avdd33_wf0_pa_g, avdd33_wf0_top, avdd33_wf0_tx_ga,
        avdd33_wf1_pa_g, avdd33_wf2_pa_a, avdd33_wf2_pad_a,
        avdd33_wf3_pa_a, avdd33_wf3_pad_a, avdd33_wf3_top,
        avdd33_wf3_tx_ga, avdd33_wf4_pa_a, avdd33_wf4_pad_a,
        avdd33_wf_sx, avdd33_xo, avdd33_xobuf, epad, gnd1, gnd10,
        gnd11, gnd12, gnd13, gnd14, gnd15, gnd16, gnd17, gnd18, gnd19,
        gnd2, gnd20, gnd21, gnd22, gnd23, gnd24, gnd25, gnd26, gnd27,
        gnd28, gnd29, gnd3, gnd30, gnd31, gnd4, gnd5, gnd6, gnd7, gnd8,
        gnd9, nc1, nc10, nc11, nc12, nc13, nc14, nc15, nc16, nc17, nc18,
        nc19, nc2, nc20, nc21, nc3, nc4, nc5, nc6, nc7, nc8, nc9,
        pad_cba_resetb, pad_dig_resetb, pad_pmu_por_b_v18,
        pad_slp_clk, pad_top_clk, pad_top_data, pad_wf_hb0,
        pad_wf_hb0_b, pad_wf_hb1, pad_wf_hb10, pad_wf_hb2,
        pad_wf_hb3, pad_wf_hb4, pad_wf_hb5, pad_wf_hb6,
        pad_wf_hb7, pad_wf_hb8, pad_wf_hb9, pad_xo_req, pdet0,
        pdet1, pdet2, pdet3, pdet4, wf0_g_rfio, wf0_in, wf0_ip,
        wf0_qn, wf0_qp, wf1_g_rfio, wf1_in, wf1_ip, wf1_qn, wf1_qp,
        wf2_a_rfio, wf2_in, wf2_ip, wf2_qn, wf2_qp, wf3_a_rfio,
        wf3_in, wf3_ip, wf3_qn, wf3_qp, wf4_a_rfio, wf4_in, wf4_ip,
        wf4_qn, wf4_qp, xo_buf_in, xo_coclk, xo_in, xo_inb, xo_out);
    inout antsel_10;
    inout antsel_11;
    inout antsel_12;
    inout antsel_13;
    inout antsel_14;
    inout antsel_15;
    inout antsel_5;
    inout antsel_6;
    inout antsel_7;
    inout antsel_8;
    inout antsel_9;
    input avdd18_wf0_dig;
    input avdd18_wf0_io;
    input avdd18_wf0_sx;
    input avdd18_wf0_top;
    input avdd18_wf0_tx;
    input avdd18_wf0_tx_ga;
    input avdd18_wf1_tx;
    input avdd18_wf3_dig;
    input avdd18_wf3_sx;
    input avdd18_wf3_top;
    input avdd18_wf3_tx_ga;
    input avdd33_esd;
    input avdd33_wf0_pa_g;
    input avdd33_wf0_top;
    input avdd33_wf0_tx_ga;
    input avdd33_wf1_pa_g;
    input avdd33_wf2_pa_a;
    input avdd33_wf2_pad_a;
    input avdd33_wf3_pa_a;
    input avdd33_wf3_pad_a;
    input avdd33_wf3_top;
    input avdd33_wf3_tx_ga;
    input avdd33_wf4_pa_a;
    input avdd33_wf4_pad_a;
    input avdd33_wf_sx;
    input avdd33_xo;
    input avdd33_xobuf;
    input epad;
    input gnd1;
    input gnd10;
    input gnd11;
    input gnd12;
    input gnd13;
    input gnd14;
    input gnd15;
    input gnd16;
    input gnd17;
    input gnd18;
    input gnd19;
    input gnd2;
    input gnd20;
    input gnd21;
    input gnd22;
    input gnd23;
    input gnd24;
    input gnd25;
    input gnd26;
    input gnd27;
    input gnd28;
    input gnd29;
    input gnd3;
    input gnd30;
    input gnd31;
    input gnd4;
    input gnd5;
    input gnd6;
    input gnd7;
    input gnd8;
    input gnd9;
    inout nc1;
    inout nc10;
    inout nc11;
    inout nc12;
    inout nc13;
    inout nc14;
    inout nc15;
    inout nc16;
    inout nc17;
    inout nc18;
    inout nc19;
    inout nc2;
    inout nc20;
    inout nc21;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout nc7;
    inout nc8;
    inout nc9;
    inout pad_cba_resetb;
    inout pad_dig_resetb;
    inout pad_pmu_por_b_v18;
    inout pad_slp_clk;
    inout pad_top_clk;
    inout pad_top_data;
    inout pad_wf_hb0;
    inout pad_wf_hb0_b;
    inout pad_wf_hb1;
    inout pad_wf_hb10;
    inout pad_wf_hb2;
    inout pad_wf_hb3;
    inout pad_wf_hb4;
    inout pad_wf_hb5;
    inout pad_wf_hb6;
    inout pad_wf_hb7;
    inout pad_wf_hb8;
    inout pad_wf_hb9;
    inout pad_xo_req;
    input pdet0;
    input pdet1;
    input pdet2;
    input pdet3;
    input pdet4;
    inout wf0_g_rfio;
    inout wf0_in;
    inout wf0_ip;
    inout wf0_qn;
    inout wf0_qp;
    inout wf1_g_rfio;
    inout wf1_in;
    inout wf1_ip;
    inout wf1_qn;
    inout wf1_qp;
    inout wf2_a_rfio;
    inout wf2_in;
    inout wf2_ip;
    inout wf2_qn;
    inout wf2_qp;
    inout wf3_a_rfio;
    inout wf3_in;
    inout wf3_ip;
    inout wf3_qn;
    inout wf3_qp;
    inout wf4_a_rfio;
    inout wf4_in;
    inout wf4_ip;
    inout wf4_qn;
    inout wf4_qp;
    input xo_buf_in;
    output xo_coclk;
    input xo_in;
    input xo_inb;
    output xo_out;


    initial
        begin
        end

endmodule
