-- generated by newgenasym Wed Sep 29 16:44:00 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity le9643 is
    port (    
	AVDD1:     IN     STD_LOGIC;    
	DRA_ZMOSI: IN     STD_LOGIC;    
	DVDD1:     IN     STD_LOGIC;    
	DVDD1V2:   IN     STD_LOGIC;    
	DXA_ZMISO: OUT    STD_LOGIC;    
	EPAD_GND:  INOUT  STD_LOGIC;    
	FS_ZSYNC:  IN     STD_LOGIC;    
	IHL1:      OUT    STD_LOGIC;    
	IREF:      IN     STD_LOGIC;    
	LFC1:      OUT    STD_LOGIC;    
	PCLK_ZCLK: IN     STD_LOGIC;    
	RAC1:      IN     STD_LOGIC;    
	RDC1:      IN     STD_LOGIC;    
	RINGD1:    OUT    STD_LOGIC;    
	RSN1:      IN     STD_LOGIC;    
	RSVD18:    INOUT  STD_LOGIC;    
	RSVD19:    INOUT  STD_LOGIC;    
	RSVD20:    INOUT  STD_LOGIC;    
	RSVD_CS_N: IN     STD_LOGIC;    
	RSVD_DCLK: IN     STD_LOGIC;    
	RSVD_DIN:  OUT    STD_LOGIC;    
	RSVD_DOUT: IN     STD_LOGIC;    
	RSVD_INT_N: OUT    STD_LOGIC;    
	\rsvd_vs/io\: IN     STD_LOGIC;    
	RSVD_ZSI_N: IN     STD_LOGIC;    
	RTV1:      OUT    STD_LOGIC;    
	SWCMPY:    OUT    STD_LOGIC;    
	SWISY:     IN     STD_LOGIC;    
	SWOUTY:    OUT    STD_LOGIC;    
	SWVSY:     IN     STD_LOGIC;    
	TAC1:      IN     STD_LOGIC;    
	TDC1:      IN     STD_LOGIC;    
	TIPD1:     OUT    STD_LOGIC;    
	VBAT1:     IN     STD_LOGIC;    
	VDDHPI:    IN     STD_LOGIC;    
	VDDSW:     IN     STD_LOGIC;    
	VREF:      OUT    STD_LOGIC);
end le9643;
