// generated by newgenasym  Wed Sep 15 17:19:24 2021


module mald_02101c (\auxadcv/auxadci , auxdac, benp, epad, gdrv, ipin, iref,
        rxinn, rxinp, rxoutn, rxoutp, scl_m, scl_s, \sd/los , sda_m,
        sda_s, \svcc/tsense , tx_sd, txbias, \txdis/sleep , txfault,
        txinn, txinp, txoutn, txoutp, vccd, vccr, vcct, vccto);
    input \auxadcv/auxadci ;
    inout auxdac;
    input benp;
    input epad;
    output gdrv;
    input ipin;
    output iref;
    input rxinn;
    input rxinp;
    output rxoutn;
    output rxoutp;
    output scl_m;
    input scl_s;
    output \sd/los ;
    inout sda_m;
    inout sda_s;
    output \svcc/tsense ;
    output tx_sd;
    output txbias;
    input \txdis/sleep ;
    output txfault;
    input txinn;
    input txinp;
    input txoutn;
    input txoutp;
    input vccd;
    input vccr;
    input vcct;
    input vccto;


    initial
        begin
        end

endmodule
