-- generated by newgenasym Mon Aug 31 13:59:18 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity inductor is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       OUT    STD_LOGIC;    
	\4\:       OUT    STD_LOGIC);
end inductor;
