// generated by newgenasym  Thu May 20 10:57:24 2021


module mod (adc0, adc1, ant_div, ant_gnss, ant_main, ap_ready, bt_cts,
        bt_en, bt_rts, bt_rxd, bt_txd, coex_rxd, coex_txd,
        coex_uart_rx, coex_uart_tx, config0, config1, config2,
        config3, cts, dbg_rxd, dbg_txd, dcd, dpr, dtr, ephy_int_n,
        ephy_rst_n, \full_card_power_off# , gnd, gnd_1, gnd_10,
        gnd_11, gnd_12, gnd_13, gnd_14, gnd_15, gnd_16, gnd_17,
        gnd_18, gnd_19, gnd_2, gnd_20, gnd_21, gnd_22, gnd_23,
        gnd_24, gnd_25, gnd_26, gnd_27, gnd_28, gnd_29, gnd_3,
        gnd_30, gnd_31, gnd_32, gnd_33, gnd_34, gnd_35, gnd_36,
        gnd_37, gnd_38, gnd_39, gnd_4, gnd_40, gnd_41, gnd_42, gnd_5,
        gnd_6, gnd_7, gnd_8, gnd_9, i2c_scl, i2c_sda, laa_tx_en,
        nc_1, nc_2, net_mode, net_status, \pcie_clkreq# ,
        pcie_refclk_m, pcie_refclk_p, \pcie_rst# , pcie_rx_m,
        pcie_rx_p, pcie_tx_m, pcie_tx_p, \pcie_wake# , pcm_clk,
        pcm_in, pcm_out, pcm_sync, pm_enable, pwrkey, rem,
        reserved_1, reserved_10, reserved_11, reserved_12,
        reserved_13, reserved_14, reserved_15, reserved_16,
        reserved_17, reserved_18, reserved_19, reserved_2,
        reserved_20, reserved_21, reserved_22, reserved_23,
        reserved_24, reserved_25, reserved_26, reserved_27,
        reserved_28, reserved_29, reserved_3, reserved_30,
        reserved_31, reserved_32, reserved_33, reserved_34,
        reserved_35, reserved_36, reserved_37, reserved_38,
        reserved_39, reserved_4, reserved_40, reserved_5,
        reserved_6, reserved_7, reserved_8, reserved_9, \reset# ,
        reset_n, rffe1_clk, rffe1_data, rffe_clk, rffe_data,
        rffe_vio_1p8, ri, rts, rxd, \s+ , \s- , sd_det, sd_ins_det,
        sdc1_clk, sdc1_cmd, sdc1_data0, sdc1_data1, sdc1_data2,
        sdc1_data3, sdc2_clk, sdc2_cmd, sdc2_data0, sdc2_data1,
        sdc2_data2, sdc2_data3, sgmii_mclk, sgmii_mdata,
        sgmii_rx_m, sgmii_rx_p, sgmii_tx_m, sgmii_tx_p, status,
        trim, txd, \usb3.0_rx_m , \usb3.0_rx_p , \usb3.0_tx_m ,
        \usb3.0_tx_p , usb_boot, usb_dm, usb_dp, usb_vbus, usim1_clk,
        usim1_data, usim1_det, usim1_reset, usim1_vdd, usim2_clk,
        usim2_data, usim2_det, usim2_reset, usim2_vdd, usim_clk,
        usim_data, usim_gnd, usim_presence, usim_rst, usim_vdd,
        vbat_bb_1, vbat_bb_2, vbat_rf_1, vbat_rf_2, vcc_1, vcc_2,
        vcc_3, vcc_4, vcc_5, vdd_ext, vdd_sdio, \vin+ , \vin- , vout,
        \w_disable# , \w_disable1# , \w_disable2# , \wake_on_wan# ,
        wake_on_wireless, wakeup_in, wlan_en, wlan_slp_clk,
        wlan_tx_en, \wwan_led# );
    input adc0;
    input adc1;
    output ant_div;
    output ant_gnss;
    output ant_main;
    input ap_ready;
    input bt_cts;
    input bt_en;
    input bt_rts;
    input bt_rxd;
    input bt_txd;
    input coex_rxd;
    input coex_txd;
    input coex_uart_rx;
    input coex_uart_tx;
    output config0;
    output config1;
    output config2;
    output config3;
    input cts;
    input dbg_rxd;
    input dbg_txd;
    input dcd;
    output dpr;
    input dtr;
    input ephy_int_n;
    input ephy_rst_n;
    output \full_card_power_off# ;
    inout gnd;
    output gnd_1;
    output gnd_10;
    output gnd_11;
    output gnd_12;
    output gnd_13;
    output gnd_14;
    output gnd_15;
    output gnd_16;
    output gnd_17;
    output gnd_18;
    output gnd_19;
    output gnd_2;
    output gnd_20;
    output gnd_21;
    output gnd_22;
    output gnd_23;
    output gnd_24;
    output gnd_25;
    output gnd_26;
    output gnd_27;
    output gnd_28;
    output gnd_29;
    output gnd_3;
    output gnd_30;
    output gnd_31;
    output gnd_32;
    output gnd_33;
    output gnd_34;
    output gnd_35;
    output gnd_36;
    output gnd_37;
    output gnd_38;
    output gnd_39;
    output gnd_4;
    output gnd_40;
    output gnd_41;
    output gnd_42;
    output gnd_5;
    output gnd_6;
    output gnd_7;
    output gnd_8;
    output gnd_9;
    input i2c_scl;
    input i2c_sda;
    input laa_tx_en;
    output nc_1;
    output nc_2;
    input net_mode;
    input net_status;
    input \pcie_clkreq# ;
    input pcie_refclk_m;
    input pcie_refclk_p;
    input \pcie_rst# ;
    input pcie_rx_m;
    input pcie_rx_p;
    input pcie_tx_m;
    input pcie_tx_p;
    input \pcie_wake# ;
    input pcm_clk;
    input pcm_in;
    input pcm_out;
    input pcm_sync;
    input pm_enable;
    input pwrkey;
    inout rem;
    output reserved_1;
    output reserved_10;
    output reserved_11;
    output reserved_12;
    output reserved_13;
    input reserved_14;
    input reserved_15;
    input reserved_16;
    input reserved_17;
    output reserved_18;
    input reserved_19;
    output reserved_2;
    input reserved_20;
    input reserved_21;
    input reserved_22;
    input reserved_23;
    input reserved_24;
    input reserved_25;
    input reserved_26;
    input reserved_27;
    input reserved_28;
    output reserved_29;
    output reserved_3;
    input reserved_30;
    input reserved_31;
    input reserved_32;
    input reserved_33;
    input reserved_34;
    input reserved_35;
    input reserved_36;
    input reserved_37;
    input reserved_38;
    input reserved_39;
    output reserved_4;
    input reserved_40;
    output reserved_5;
    output reserved_6;
    output reserved_7;
    output reserved_8;
    output reserved_9;
    output \reset# ;
    input reset_n;
    input rffe1_clk;
    input rffe1_data;
    input rffe_clk;
    input rffe_data;
    output rffe_vio_1p8;
    input ri;
    input rts;
    input rxd;
    inout \s+ ;
    inout \s- ;
    input sd_det;
    input sd_ins_det;
    input sdc1_clk;
    input sdc1_cmd;
    input sdc1_data0;
    input sdc1_data1;
    input sdc1_data2;
    input sdc1_data3;
    input sdc2_clk;
    input sdc2_cmd;
    input sdc2_data0;
    input sdc2_data1;
    input sdc2_data2;
    input sdc2_data3;
    input sgmii_mclk;
    input sgmii_mdata;
    input sgmii_rx_m;
    input sgmii_rx_p;
    input sgmii_tx_m;
    input sgmii_tx_p;
    input status;
    inout trim;
    input txd;
    input \usb3.0_rx_m ;
    input \usb3.0_rx_p ;
    input \usb3.0_tx_m ;
    input \usb3.0_tx_p ;
    input usb_boot;
    input usb_dm;
    input usb_dp;
    output usb_vbus;
    input usim1_clk;
    input usim1_data;
    input usim1_det;
    input usim1_reset;
    output usim1_vdd;
    input usim2_clk;
    input usim2_data;
    input usim2_det;
    input usim2_reset;
    output usim2_vdd;
    input usim_clk;
    input usim_data;
    output usim_gnd;
    input usim_presence;
    input usim_rst;
    output usim_vdd;
    output vbat_bb_1;
    output vbat_bb_2;
    output vbat_rf_1;
    output vbat_rf_2;
    output vcc_1;
    output vcc_2;
    output vcc_3;
    output vcc_4;
    output vcc_5;
    output vdd_ext;
    output vdd_sdio;
    inout \vin+ ;
    inout \vin- ;
    inout vout;
    input \w_disable# ;
    output \w_disable1# ;
    output \w_disable2# ;
    output \wake_on_wan# ;
    input wake_on_wireless;
    input wakeup_in;
    input wlan_en;
    input wlan_slp_clk;
    output wlan_tx_en;
    output \wwan_led# ;


    initial
        begin
        end

endmodule
