// generated by newgenasym  Wed Dec 21 17:39:48 2022


module rtc7676e (ant, c0, c1, gnd, gnd_1, gnd_2, gnd_3, gnd_4, gnd_5, pa_en,
        pgnd, rx, tx, vcc1, vcc2, vdd, vdet);
    output ant;
    input c0;
    inout c1;
    inout gnd;
    inout gnd_1;
    inout gnd_2;
    inout gnd_3;
    inout gnd_4;
    inout gnd_5;
    inout pa_en;
    inout pgnd;
    inout rx;
    inout tx;
    inout vcc1;
    inout vcc2;
    input vdd;
    inout vdet;


    initial
        begin
        end

endmodule
