-- generated by newgenasym Wed Dec 21 17:39:48 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rtc7676e is
    port (    
	ANT:       OUT    STD_LOGIC;    
	C0:        IN     STD_LOGIC;    
	C1:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	GND_1:     INOUT  STD_LOGIC;    
	GND_2:     INOUT  STD_LOGIC;    
	GND_3:     INOUT  STD_LOGIC;    
	GND_4:     INOUT  STD_LOGIC;    
	GND_5:     INOUT  STD_LOGIC;    
	PA_EN:     INOUT  STD_LOGIC;    
	PGND:      INOUT  STD_LOGIC;    
	RX:        INOUT  STD_LOGIC;    
	TX:        INOUT  STD_LOGIC;    
	VCC1:      INOUT  STD_LOGIC;    
	VCC2:      INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VDET:      INOUT  STD_LOGIC);
end rtc7676e;
