-- generated by newgenasym Sat Oct 12 09:02:50 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cw30p10d is
    port (    
	D:         INOUT  STD_LOGIC;    
	G:         IN     STD_LOGIC;    
	S:         INOUT  STD_LOGIC);
end cw30p10d;
