// generated by newgenasym  Thu Nov 02 17:19:02 2023


module network_tf (\1 , \2 , \3 , \4 , mct, mct1, mct2, mct3, mct4, \mx+ , \mx- , \mx1+ , \mx1- ,
        \mx2+ , \mx2- , \mx3+ , \mx3- , \mx4+ , \mx4- , nc1, nc2, nc3, nc4, nc5, nc6,
        tct, tct1, tct2, tct3, tct4, \td+ , \td- , \td1+ , \td1- , \td2+ , \td2- ,
        \td3+ , \td3- , \td4+ , \td4- , tdt);
    input \1 ;
    input \2 ;
    output \3 ;
    output \4 ;
    inout mct;
    inout mct1;
    inout mct2;
    output mct3;
    output mct4;
    output \mx+ ;
    output \mx- ;
    inout \mx1+ ;
    inout \mx1- ;
    inout \mx2+ ;
    inout \mx2- ;
    inout \mx3+ ;
    inout \mx3- ;
    inout \mx4+ ;
    inout \mx4- ;
    input nc1;
    input nc2;
    output nc3;
    output nc4;
    input nc5;
    output nc6;
    input tct;
    inout tct1;
    inout tct2;
    input tct3;
    input tct4;
    input \td+ ;
    input \td- ;
    inout \td1+ ;
    inout \td1- ;
    inout \td2+ ;
    inout \td2- ;
    inout \td3+ ;
    inout \td3- ;
    inout \td4+ ;
    inout \td4- ;
    input tdt;


    initial
        begin
        end

endmodule
