-- generated by newgenasym Fri May 27 10:12:39 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity gn25l99 is
    port (    
	A0:        INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	ADC_IN:    IN     STD_LOGIC;    
	BIAS:      INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\laser+\:  INOUT  STD_LOGIC;    
	\laser-\:  INOUT  STD_LOGIC;    
	MPD:       INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	RESET:     INOUT  STD_LOGIC;    
	\rxin+\:   INOUT  STD_LOGIC;    
	\rxin-\:   INOUT  STD_LOGIC;    
	\rxout+\:  INOUT  STD_LOGIC;    
	\rxout-\:  INOUT  STD_LOGIC;    
	RXREF:     INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SD:        OUT    STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	TX_DISABLE: INOUT  STD_LOGIC;    
	TX_FAULT:  INOUT  STD_LOGIC;    
	\txin+\:   INOUT  STD_LOGIC;    
	\txin-\:   INOUT  STD_LOGIC;    
	VCAP:      IN     STD_LOGIC;    
	VDD_DIG:   IN     STD_LOGIC;    
	VDD_RX1:   IN     STD_LOGIC;    
	VDD_RX2:   IN     STD_LOGIC;    
	VDD_RX3:   IN     STD_LOGIC;    
	VDD_TX:    IN     STD_LOGIC);
end gn25l99;
