-- generated by newgenasym Fri May 27 18:10:12 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sgm41282c is
    port (    
	AGND:      IN     STD_LOGIC;    
	APD:       OUT    STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	GAIN:      IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	MB:        IN     STD_LOGIC;    
	PGND1:     IN     STD_LOGIC;    
	PGND2:     IN     STD_LOGIC;    
	RLIM:      IN     STD_LOGIC;    
	SW1:       OUT    STD_LOGIC;    
	SW2:       OUT    STD_LOGIC;    
	TH:        IN     STD_LOGIC;    
	THHXOR:    IN     STD_LOGIC;    
	VMON:      OUT    STD_LOGIC;    
	VREF:      OUT    STD_LOGIC;    
	VS:        IN     STD_LOGIC);
end sgm41282c;
