-- generated by newgenasym Mon Aug 31 13:53:47 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fb is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end fb;
