// generated by newgenasym  Mon Aug 31 14:16:29 2020


module pusb3f96 (ch1, ch2, ch3, ch4, gnd1, gnd2, nc1, nc2, nc3, nc4);
    inout ch1;
    inout ch2;
    inout ch3;
    inout ch4;
    inout gnd1;
    inout gnd2;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;


    initial
        begin
        end

endmodule
