// generated by newgenasym  Fri Jun 16 11:32:28 2023


module rtl9607dq (\biw_c/gpio_2_5 , \biw_d/gpio_2_4 , \ddr3_a/ddr4__1_13 ,
        \ddr3_a/ddr4_a/casn_4_15 , \ddr3_a/ddr4_a_0_0 ,
        \ddr3_a/ddr4_a_11_7 , \ddr3_a/ddr4_a_12_3 ,
        \ddr3_a/ddr4_a_14_9 , \ddr3_a/ddr4_a_15_1 ,
        \ddr3_a/ddr4_a_2_8 , \ddr3_a/ddr4_a_3_4 , \ddr3_a/ddr4_a_5_6 ,
        \ddr3_a/ddr4_a_6_5 , \ddr3_a/ddr4_a_7_2 ,
        \ddr3_a/ddr4_a_9_11 , \ddr3_a/ddr4_bg0_10 ,
        \ddr3_a/ddr4_par_13 , \ddr3_a/ddr4_ten_8 ,
        \ddr3_ba/ddr4_a_0_10 , \ddr3_ba/ddr4_ba_1_1 ,
        \ddr3_ba/ddr4_ba_2_0 , \ddr3_casn/ddr4_act ,
        \ddr3_odt/ddr4_a_12 , \ddr3_odt_1/ddr4_rasn ,
        \ddr3_rasn/ddr4_odt , \ddr3_wen/ddr4_a/wen_14 , ddr4_alertn,
        \debug_mode/gpio_4_13 , dram_ck, dram_ck_b, dram_cke,
        dram_csn_0, dram_csn_1, dram_dm_0, dram_dm_1, dram_dq_0,
        dram_dq_1, dram_dq_10, dram_dq_11, dram_dq_12, dram_dq_13,
        dram_dq_14, dram_dq_15, dram_dq_2, dram_dq_3, dram_dq_4,
        dram_dq_5, dram_dq_6, dram_dq_7, dram_dq_8, dram_dq_9,
        dram_dqs_0, dram_dqs_1, dram_dqs_b_0, dram_dqs_b_1,
        dram_rstn, dram_vdd33, dram_vdd_ck, dram_vss_ck, dy_gasp,
        \ext_reset_n/gpio_4_0 , \gmac_rxc/gpio_3_24 ,
        \gmac_rxd/gpio_3_0_19 , \gmac_rxd/gpio_3_1_20 ,
        \gmac_rxd/gpio_3_2_21 , \gmac_rxd/gpio_3_3_22 ,
        \gmac_rxdv/gpio_3_23 , \gmac_txc/gpio_3_18 ,
        \gmac_txd/gpio_3_0_13 , \gmac_txd/gpio_3_1_14 ,
        \gmac_txd/gpio_3_2_15 , \gmac_txd/gpio_3_3_16 ,
        \gmac_txen/gpio_3_17 , gphy_avdd10_0, gphy_avdd10_1,
        gphy_avdd10_2, gphy_avdd10_3, gphy_hg_cen, gphy_hv_cen,
        gphy_hv_giga_0, gphy_hv_giga_1, gphy_hv_giga_2,
        gphy_hv_giga_3, gphy_hv_giga_4, gphy_hv_giga_5,
        gphy_hv_giga_6, gphy_hv_giga_7, gphy_hv_giga_8,
        gphy_lv_cen, gphy_mdin0_0, gphy_mdin0_1, gphy_mdin0_2,
        gphy_mdin0_3, gphy_mdin1_0, gphy_mdin1_1, gphy_mdin1_2,
        gphy_mdin1_3, gphy_mdin2_0, gphy_mdin2_1, gphy_mdin2_2,
        gphy_mdin2_3, gphy_mdin3_0, gphy_mdin3_1, gphy_mdin3_2,
        gphy_mdin3_3, gphy_mdip0_0, gphy_mdip0_1, gphy_mdip0_2,
        gphy_mdip0_3, gphy_mdip1_0, gphy_mdip1_1, gphy_mdip1_2,
        gphy_mdip1_3, gphy_mdip2_0, gphy_mdip2_1, gphy_mdip2_2,
        gphy_mdip2_3, gphy_mdip3_0, gphy_mdip3_1, gphy_mdip3_2,
        gphy_mdip3_3, gphy_pgnd, gphy_pvdd, gphy_rset,
        \gpio/led_10_10 , \gpio/opt_rx_los/led_13_13 ,
        \gpio/opt_tx_fault/pwm_timer0/led_15_15 ,
        \gpio/opt_tx_sd/led_14_14 , \gpio/spi_cs4/boot_sd/led_7_7 ,
        \gpio/uart_cts3/led_9_9 , \gpio/uart_rts3/led_8_8 ,
        \gpio/uart_rx2/uart_rts0/led_0_0 , \gpio/uart_rx3/led_2_2 ,
        \gpio/uart_tx2/uart_cts/led_1_1 , \gpio/uart_tx3/led_3_3 ,
        \gpio_11/led_clk/flashsize/led_0_11 ,
        \gpio_12/led_val/flashsize/led_1_12 , gpio_3_0, gpio_3_1,
        gpio_3_10, gpio_3_11, gpio_3_12, gpio_3_2, gpio_3_3,
        gpio_3_4, gpio_3_5, gpio_3_6, gpio_3_7, gpio_3_8, gpio_3_9,
        \gpio_4/spi_cs1/speed/led_0_4 ,
        \gpio_5/spi_cs2/speed/led_1_5 ,
        \gpio_6/spi_cs3/speed/led_2_6 , internal_use_1,
        internal_use_2, internal_use_3, internal_use_4,
        internal_use_5, \mdc/gpio_4/flashtype_2_0 , \mdio/gpio_4_3 ,
        nc, nc_1, \onu_mpcp_ts/gpio_4_15 , \onu_pps/gpio_4_14 ,
        \pll_bypass/gpio_4_16 , psds_avdd, psds_ben_out,
        psds_ck_avdd, psds_gnd_xtal, psds_hsin, psds_hsip,
        psds_hson, psds_hsop, psds_hv, psds_hv_xtal, psds_xi_25m,
        psds_xo_25m, ref_clk, reset_n, s0_hsim_0, s0_hsim_1,
        s0_hsip_0, s0_hsip_1, s0_hsom_0, s0_hsom_1, s0_hsop_0,
        s0_hsop_1, s0_refclk_n, s0_refclk_p, s1_hsim_0, s1_hsip_0,
        s1_hsom_0, s1_hsop_0, s1_refclk_n, s1_refclk_p, s2_hsim,
        s2_hsip, s2_hsom, s2_hsop, s2_refclk_n, s2_refclk_p,
        s3_hsim, s3_hsip, s3_hsom, s3_hsop, s_agnd0, s_agnd1,
        s_agnd10, s_agnd11, s_agnd12, s_agnd13, s_agnd14, s_agnd15,
        s_agnd16, s_agnd17, s_agnd18, s_agnd19, s_agnd2, s_agnd20,
        s_agnd21, s_agnd3, s_agnd4, s_agnd5, s_agnd6, s_agnd7,
        s_agnd8, s_agnd9, s_agnd_0, s_agnd_1, s_agnd_10, s_agnd_11,
        s_agnd_2, s_agnd_3, s_agnd_4, s_agnd_5, s_agnd_6, s_agnd_7,
        s_agnd_8, s_agnd_9, s_avdd_0, s_avdd_1, s_avdd_2, s_avdd_3,
        s_avdd_4, sfi_avdd, sfi_ck_avdd, sfi_hsin, sfi_hsip,
        sfi_hson, sfi_hsop, sfi_hv, \spi_clk/gpio_2/flashtype_0_1 ,
        \spi_csn0/gpio_2_3 , \spi_rx/gpio_2_2 ,
        \spi_tx/gpio_2/flashpin_1 , \spif_clk/gpio_1_10 ,
        \spif_csn/gpio_1_0_15 , \spif_csn/gpio_1_1_16 ,
        \spif_d/gpio_1_0_0 , \spif_d/gpio_1_1_1 , \spif_d/gpio_1_3_3 ,
        \spif_d/gpio__1_2_2 , \ssp_extclk/gpio_2_7 ,
        \ssp_extsclk/gpio_2_6 , \ssp_fsc/gpio_2_8 ,
        \ssp_rxd/gpio_2_10 , \ssp_sclk/gpio_2_11 , \ssp_txd/gpio_2_9 ,
        \tck/gpio_4_9 , \tdi/gpio_4_11 , \tdo/gpio_4_8 , \tms/gpio_4_10 ,
        \trst_n/gpio_4_12 , \uart0_rx/gpio_4_4 ,
        \uart0_tx/gpio_4/umsg_5 , \uart1_rx/gpio_4_6 ,
        \uart1_tx/gpio_4_7 , usb0_dm, usb0_dp, usb1_dm, usb1_dp,
        usb_av33_0, usb_av33_1, vdd_3p3_0, vdd_3p3_1, vdd_3p3_2,
        vdd_3p3_3, vdd_3p3_4, vdd_3p3_6, vdd_core_0, vdd_core_1,
        vdd_core_10, vdd_core_11, vdd_core_12, vdd_core_13,
        vdd_core_14, vdd_core_15, vdd_core_16, vdd_core_17,
        vdd_core_18, vdd_core_19, vdd_core_2, vdd_core_20,
        vdd_core_21, vdd_core_22, vdd_core_23, vdd_core_24,
        vdd_core_25, vdd_core_26, vdd_core_27, vdd_core_28,
        vdd_core_29, vdd_core_3, vdd_core_30, vdd_core_31,
        vdd_core_32, vdd_core_33, vdd_core_34, vdd_core_35,
        vdd_core_36, vdd_core_37, vdd_core_38, vdd_core_39,
        vdd_core_4, vdd_core_40, vdd_core_41, vdd_core_42,
        vdd_core_43, vdd_core_44, vdd_core_45, vdd_core_46,
        vdd_core_47, vdd_core_48, vdd_core_49, vdd_core_5,
        vdd_core_6, vdd_core_7, vdd_core_8, vdd_core_9, vdd_cpu_0,
        vdd_cpu_1, vdd_cpu_10, vdd_cpu_11, vdd_cpu_12, vdd_cpu_13,
        vdd_cpu_14, vdd_cpu_15, vdd_cpu_16, vdd_cpu_17,
        vdd_cpu_18, vdd_cpu_19, vdd_cpu_2, vdd_cpu_3, vdd_cpu_4,
        vdd_cpu_5, vdd_cpu_6, vdd_cpu_7, vdd_cpu_8, vdd_cpu_9,
        vdd_io_rgmii_0, vdd_io_rgmii_1, vddq_0, vddq_1, vddq_10,
        vddq_11, vddq_2, vddq_3, vddq_4, vddq_5, vddq_6, vddq_7,
        vddq_8, vddq_9, vss_ring_0, vss_ring_1, vss_ring_10,
        vss_ring_100, vss_ring_101, vss_ring_102, vss_ring_103,
        vss_ring_104, vss_ring_105, vss_ring_106, vss_ring_11,
        vss_ring_12, vss_ring_13, vss_ring_14, vss_ring_15,
        vss_ring_16, vss_ring_17, vss_ring_18, vss_ring_19,
        vss_ring_2, vss_ring_20, vss_ring_21, vss_ring_22,
        vss_ring_23, vss_ring_24, vss_ring_25, vss_ring_26,
        vss_ring_27, vss_ring_28, vss_ring_29, vss_ring_3,
        vss_ring_30, vss_ring_31, vss_ring_32, vss_ring_33,
        vss_ring_34, vss_ring_35, vss_ring_36, vss_ring_37,
        vss_ring_38, vss_ring_39, vss_ring_4, vss_ring_40,
        vss_ring_41, vss_ring_42, vss_ring_43, vss_ring_44,
        vss_ring_45, vss_ring_46, vss_ring_47, vss_ring_48,
        vss_ring_49, vss_ring_5, vss_ring_50, vss_ring_51,
        vss_ring_52, vss_ring_53, vss_ring_54, vss_ring_55,
        vss_ring_56, vss_ring_57, vss_ring_58, vss_ring_59,
        vss_ring_6, vss_ring_60, vss_ring_61, vss_ring_62,
        vss_ring_63, vss_ring_64, vss_ring_65, vss_ring_66,
        vss_ring_67, vss_ring_68, vss_ring_69, vss_ring_7,
        vss_ring_70, vss_ring_71, vss_ring_72, vss_ring_73,
        vss_ring_74, vss_ring_75, vss_ring_76, vss_ring_77,
        vss_ring_78, vss_ring_79, vss_ring_8, vss_ring_80,
        vss_ring_81, vss_ring_82, vss_ring_83, vss_ring_84,
        vss_ring_85, vss_ring_86, vss_ring_87, vss_ring_88,
        vss_ring_89, vss_ring_9, vss_ring_90, vss_ring_91,
        vss_ring_92, vss_ring_93, vss_ring_94, vss_ring_95,
        vss_ring_96, vss_ring_97, vss_ring_98, vss_ring_99,
        vss_shld_0, vss_shld_1, vss_shld_2, vss_shld_3);
    inout \biw_c/gpio_2_5 ;
    inout \biw_d/gpio_2_4 ;
    output \ddr3_a/ddr4__1_13 ;
    output \ddr3_a/ddr4_a/casn_4_15 ;
    output \ddr3_a/ddr4_a_0_0 ;
    output \ddr3_a/ddr4_a_11_7 ;
    output \ddr3_a/ddr4_a_12_3 ;
    output \ddr3_a/ddr4_a_14_9 ;
    output \ddr3_a/ddr4_a_15_1 ;
    output \ddr3_a/ddr4_a_2_8 ;
    output \ddr3_a/ddr4_a_3_4 ;
    output \ddr3_a/ddr4_a_5_6 ;
    output \ddr3_a/ddr4_a_6_5 ;
    output \ddr3_a/ddr4_a_7_2 ;
    output \ddr3_a/ddr4_a_9_11 ;
    output \ddr3_a/ddr4_bg0_10 ;
    output \ddr3_a/ddr4_par_13 ;
    output \ddr3_a/ddr4_ten_8 ;
    output \ddr3_ba/ddr4_a_0_10 ;
    output \ddr3_ba/ddr4_ba_1_1 ;
    output \ddr3_ba/ddr4_ba_2_0 ;
    output \ddr3_casn/ddr4_act ;
    output \ddr3_odt/ddr4_a_12 ;
    output \ddr3_odt_1/ddr4_rasn ;
    output \ddr3_rasn/ddr4_odt ;
    output \ddr3_wen/ddr4_a/wen_14 ;
    output ddr4_alertn;
    inout \debug_mode/gpio_4_13 ;
    inout dram_ck;
    inout dram_ck_b;
    inout dram_cke;
    output dram_csn_0;
    output dram_csn_1;
    inout dram_dm_0;
    inout dram_dm_1;
    inout dram_dq_0;
    inout dram_dq_1;
    inout dram_dq_10;
    inout dram_dq_11;
    inout dram_dq_12;
    inout dram_dq_13;
    inout dram_dq_14;
    inout dram_dq_15;
    inout dram_dq_2;
    inout dram_dq_3;
    inout dram_dq_4;
    inout dram_dq_5;
    inout dram_dq_6;
    inout dram_dq_7;
    inout dram_dq_8;
    inout dram_dq_9;
    inout dram_dqs_0;
    inout dram_dqs_1;
    inout dram_dqs_b_0;
    inout dram_dqs_b_1;
    output dram_rstn;
    input dram_vdd33;
    input dram_vdd_ck;
    input dram_vss_ck;
    inout dy_gasp;
    inout \ext_reset_n/gpio_4_0 ;
    inout \gmac_rxc/gpio_3_24 ;
    inout \gmac_rxd/gpio_3_0_19 ;
    inout \gmac_rxd/gpio_3_1_20 ;
    inout \gmac_rxd/gpio_3_2_21 ;
    inout \gmac_rxd/gpio_3_3_22 ;
    inout \gmac_rxdv/gpio_3_23 ;
    inout \gmac_txc/gpio_3_18 ;
    inout \gmac_txd/gpio_3_0_13 ;
    inout \gmac_txd/gpio_3_1_14 ;
    inout \gmac_txd/gpio_3_2_15 ;
    inout \gmac_txd/gpio_3_3_16 ;
    inout \gmac_txen/gpio_3_17 ;
    input gphy_avdd10_0;
    input gphy_avdd10_1;
    input gphy_avdd10_2;
    input gphy_avdd10_3;
    input gphy_hg_cen;
    input gphy_hv_cen;
    input gphy_hv_giga_0;
    input gphy_hv_giga_1;
    input gphy_hv_giga_2;
    input gphy_hv_giga_3;
    input gphy_hv_giga_4;
    input gphy_hv_giga_5;
    input gphy_hv_giga_6;
    input gphy_hv_giga_7;
    input gphy_hv_giga_8;
    input gphy_lv_cen;
    inout gphy_mdin0_0;
    inout gphy_mdin0_1;
    inout gphy_mdin0_2;
    inout gphy_mdin0_3;
    inout gphy_mdin1_0;
    inout gphy_mdin1_1;
    inout gphy_mdin1_2;
    inout gphy_mdin1_3;
    inout gphy_mdin2_0;
    inout gphy_mdin2_1;
    inout gphy_mdin2_2;
    inout gphy_mdin2_3;
    inout gphy_mdin3_0;
    inout gphy_mdin3_1;
    inout gphy_mdin3_2;
    inout gphy_mdin3_3;
    inout gphy_mdip0_0;
    inout gphy_mdip0_1;
    inout gphy_mdip0_2;
    inout gphy_mdip0_3;
    inout gphy_mdip1_0;
    inout gphy_mdip1_1;
    inout gphy_mdip1_2;
    inout gphy_mdip1_3;
    inout gphy_mdip2_0;
    inout gphy_mdip2_1;
    inout gphy_mdip2_2;
    inout gphy_mdip2_3;
    inout gphy_mdip3_0;
    inout gphy_mdip3_1;
    inout gphy_mdip3_2;
    inout gphy_mdip3_3;
    input gphy_pgnd;
    input gphy_pvdd;
    inout gphy_rset;
    inout \gpio/led_10_10 ;
    inout \gpio/opt_rx_los/led_13_13 ;
    inout \gpio/opt_tx_fault/pwm_timer0/led_15_15 ;
    inout \gpio/opt_tx_sd/led_14_14 ;
    inout \gpio/spi_cs4/boot_sd/led_7_7 ;
    inout \gpio/uart_cts3/led_9_9 ;
    inout \gpio/uart_rts3/led_8_8 ;
    inout \gpio/uart_rx2/uart_rts0/led_0_0 ;
    inout \gpio/uart_rx3/led_2_2 ;
    inout \gpio/uart_tx2/uart_cts/led_1_1 ;
    inout \gpio/uart_tx3/led_3_3 ;
    inout \gpio_11/led_clk/flashsize/led_0_11 ;
    inout \gpio_12/led_val/flashsize/led_1_12 ;
    inout gpio_3_0;
    inout gpio_3_1;
    inout gpio_3_10;
    inout gpio_3_11;
    inout gpio_3_12;
    inout gpio_3_2;
    inout gpio_3_3;
    inout gpio_3_4;
    inout gpio_3_5;
    inout gpio_3_6;
    inout gpio_3_7;
    inout gpio_3_8;
    inout gpio_3_9;
    inout \gpio_4/spi_cs1/speed/led_0_4 ;
    inout \gpio_5/spi_cs2/speed/led_1_5 ;
    inout \gpio_6/spi_cs3/speed/led_2_6 ;
    inout internal_use_1;
    inout internal_use_2;
    inout internal_use_3;
    inout internal_use_4;
    inout internal_use_5;
    inout \mdc/gpio_4/flashtype_2_0 ;
    inout \mdio/gpio_4_3 ;
    inout nc;
    inout nc_1;
    inout \onu_mpcp_ts/gpio_4_15 ;
    inout \onu_pps/gpio_4_14 ;
    inout \pll_bypass/gpio_4_16 ;
    input psds_avdd;
    inout psds_ben_out;
    input psds_ck_avdd;
    input psds_gnd_xtal;
    inout psds_hsin;
    inout psds_hsip;
    inout psds_hson;
    inout psds_hsop;
    input psds_hv;
    input psds_hv_xtal;
    inout psds_xi_25m;
    inout psds_xo_25m;
    inout ref_clk;
    inout reset_n;
    inout s0_hsim_0;
    inout s0_hsim_1;
    inout s0_hsip_0;
    inout s0_hsip_1;
    inout s0_hsom_0;
    inout s0_hsom_1;
    inout s0_hsop_0;
    inout s0_hsop_1;
    inout s0_refclk_n;
    inout s0_refclk_p;
    inout s1_hsim_0;
    inout s1_hsip_0;
    inout s1_hsom_0;
    inout s1_hsop_0;
    inout s1_refclk_n;
    inout s1_refclk_p;
    inout s2_hsim;
    inout s2_hsip;
    inout s2_hsom;
    inout s2_hsop;
    inout s2_refclk_n;
    inout s2_refclk_p;
    inout s3_hsim;
    inout s3_hsip;
    inout s3_hsom;
    inout s3_hsop;
    input s_agnd0;
    input s_agnd1;
    input s_agnd10;
    input s_agnd11;
    input s_agnd12;
    input s_agnd13;
    input s_agnd14;
    input s_agnd15;
    input s_agnd16;
    input s_agnd17;
    input s_agnd18;
    input s_agnd19;
    input s_agnd2;
    input s_agnd20;
    input s_agnd21;
    input s_agnd3;
    input s_agnd4;
    input s_agnd5;
    input s_agnd6;
    input s_agnd7;
    input s_agnd8;
    input s_agnd9;
    input s_agnd_0;
    input s_agnd_1;
    inout s_agnd_10;
    inout s_agnd_11;
    input s_agnd_2;
    input s_agnd_3;
    input s_agnd_4;
    input s_agnd_5;
    input s_agnd_6;
    input s_agnd_7;
    inout s_agnd_8;
    inout s_agnd_9;
    input s_avdd_0;
    input s_avdd_1;
    input s_avdd_2;
    input s_avdd_3;
    input s_avdd_4;
    inout sfi_avdd;
    inout sfi_ck_avdd;
    inout sfi_hsin;
    inout sfi_hsip;
    inout sfi_hson;
    inout sfi_hsop;
    inout sfi_hv;
    inout \spi_clk/gpio_2/flashtype_0_1 ;
    inout \spi_csn0/gpio_2_3 ;
    inout \spi_rx/gpio_2_2 ;
    inout \spi_tx/gpio_2/flashpin_1 ;
    inout \spif_clk/gpio_1_10 ;
    inout \spif_csn/gpio_1_0_15 ;
    inout \spif_csn/gpio_1_1_16 ;
    inout \spif_d/gpio_1_0_0 ;
    inout \spif_d/gpio_1_1_1 ;
    inout \spif_d/gpio_1_3_3 ;
    inout \spif_d/gpio__1_2_2 ;
    inout \ssp_extclk/gpio_2_7 ;
    inout \ssp_extsclk/gpio_2_6 ;
    inout \ssp_fsc/gpio_2_8 ;
    inout \ssp_rxd/gpio_2_10 ;
    inout \ssp_sclk/gpio_2_11 ;
    inout \ssp_txd/gpio_2_9 ;
    inout \tck/gpio_4_9 ;
    inout \tdi/gpio_4_11 ;
    inout \tdo/gpio_4_8 ;
    inout \tms/gpio_4_10 ;
    inout \trst_n/gpio_4_12 ;
    inout \uart0_rx/gpio_4_4 ;
    inout \uart0_tx/gpio_4/umsg_5 ;
    inout \uart1_rx/gpio_4_6 ;
    inout \uart1_tx/gpio_4_7 ;
    inout usb0_dm;
    inout usb0_dp;
    inout usb1_dm;
    inout usb1_dp;
    input usb_av33_0;
    input usb_av33_1;
    input vdd_3p3_0;
    input vdd_3p3_1;
    input vdd_3p3_2;
    input vdd_3p3_3;
    input vdd_3p3_4;
    input vdd_3p3_6;
    input vdd_core_0;
    input vdd_core_1;
    input vdd_core_10;
    input vdd_core_11;
    input vdd_core_12;
    input vdd_core_13;
    input vdd_core_14;
    input vdd_core_15;
    input vdd_core_16;
    input vdd_core_17;
    input vdd_core_18;
    input vdd_core_19;
    input vdd_core_2;
    input vdd_core_20;
    input vdd_core_21;
    input vdd_core_22;
    input vdd_core_23;
    input vdd_core_24;
    input vdd_core_25;
    input vdd_core_26;
    input vdd_core_27;
    input vdd_core_28;
    input vdd_core_29;
    input vdd_core_3;
    input vdd_core_30;
    input vdd_core_31;
    input vdd_core_32;
    input vdd_core_33;
    input vdd_core_34;
    input vdd_core_35;
    input vdd_core_36;
    input vdd_core_37;
    input vdd_core_38;
    input vdd_core_39;
    input vdd_core_4;
    input vdd_core_40;
    input vdd_core_41;
    input vdd_core_42;
    input vdd_core_43;
    input vdd_core_44;
    input vdd_core_45;
    input vdd_core_46;
    input vdd_core_47;
    input vdd_core_48;
    input vdd_core_49;
    input vdd_core_5;
    input vdd_core_6;
    input vdd_core_7;
    input vdd_core_8;
    input vdd_core_9;
    input vdd_cpu_0;
    input vdd_cpu_1;
    input vdd_cpu_10;
    input vdd_cpu_11;
    input vdd_cpu_12;
    input vdd_cpu_13;
    input vdd_cpu_14;
    input vdd_cpu_15;
    input vdd_cpu_16;
    input vdd_cpu_17;
    input vdd_cpu_18;
    input vdd_cpu_19;
    input vdd_cpu_2;
    input vdd_cpu_3;
    input vdd_cpu_4;
    input vdd_cpu_5;
    input vdd_cpu_6;
    input vdd_cpu_7;
    input vdd_cpu_8;
    input vdd_cpu_9;
    input vdd_io_rgmii_0;
    input vdd_io_rgmii_1;
    input vddq_0;
    input vddq_1;
    input vddq_10;
    input vddq_11;
    input vddq_2;
    input vddq_3;
    input vddq_4;
    input vddq_5;
    input vddq_6;
    input vddq_7;
    input vddq_8;
    input vddq_9;
    input vss_ring_0;
    input vss_ring_1;
    input vss_ring_10;
    input vss_ring_100;
    input vss_ring_101;
    input vss_ring_102;
    input vss_ring_103;
    input vss_ring_104;
    input vss_ring_105;
    input vss_ring_106;
    input vss_ring_11;
    input vss_ring_12;
    input vss_ring_13;
    input vss_ring_14;
    input vss_ring_15;
    input vss_ring_16;
    input vss_ring_17;
    input vss_ring_18;
    input vss_ring_19;
    input vss_ring_2;
    input vss_ring_20;
    input vss_ring_21;
    input vss_ring_22;
    input vss_ring_23;
    input vss_ring_24;
    input vss_ring_25;
    input vss_ring_26;
    input vss_ring_27;
    input vss_ring_28;
    input vss_ring_29;
    input vss_ring_3;
    input vss_ring_30;
    input vss_ring_31;
    input vss_ring_32;
    input vss_ring_33;
    input vss_ring_34;
    input vss_ring_35;
    input vss_ring_36;
    input vss_ring_37;
    input vss_ring_38;
    input vss_ring_39;
    input vss_ring_4;
    input vss_ring_40;
    input vss_ring_41;
    input vss_ring_42;
    input vss_ring_43;
    input vss_ring_44;
    input vss_ring_45;
    input vss_ring_46;
    input vss_ring_47;
    input vss_ring_48;
    input vss_ring_49;
    input vss_ring_5;
    input vss_ring_50;
    input vss_ring_51;
    input vss_ring_52;
    input vss_ring_53;
    input vss_ring_54;
    input vss_ring_55;
    input vss_ring_56;
    input vss_ring_57;
    input vss_ring_58;
    input vss_ring_59;
    input vss_ring_6;
    input vss_ring_60;
    input vss_ring_61;
    input vss_ring_62;
    input vss_ring_63;
    input vss_ring_64;
    input vss_ring_65;
    input vss_ring_66;
    input vss_ring_67;
    input vss_ring_68;
    input vss_ring_69;
    input vss_ring_7;
    input vss_ring_70;
    input vss_ring_71;
    input vss_ring_72;
    input vss_ring_73;
    input vss_ring_74;
    input vss_ring_75;
    input vss_ring_76;
    input vss_ring_77;
    input vss_ring_78;
    input vss_ring_79;
    input vss_ring_8;
    input vss_ring_80;
    input vss_ring_81;
    input vss_ring_82;
    input vss_ring_83;
    input vss_ring_84;
    input vss_ring_85;
    input vss_ring_86;
    input vss_ring_87;
    input vss_ring_88;
    input vss_ring_89;
    input vss_ring_9;
    input vss_ring_90;
    input vss_ring_91;
    input vss_ring_92;
    input vss_ring_93;
    input vss_ring_94;
    input vss_ring_95;
    input vss_ring_96;
    input vss_ring_97;
    input vss_ring_98;
    input vss_ring_99;
    input vss_shld_0;
    input vss_shld_1;
    input vss_shld_2;
    input vss_shld_3;


    initial
        begin
        end

endmodule
