// generated by newgenasym  Fri Jan 15 17:36:26 2021


module diode (\1 , \2 , \3 , a1, a2, a3, b1, b2, b3, c1, c2, c3, d1, d2, d3, e1, e2);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout a1;
    inout a2;
    inout a3;
    inout b1;
    inout b2;
    inout b3;
    inout c1;
    inout c2;
    inout c3;
    inout d1;
    inout d2;
    inout d3;
    inout e1;
    inout e2;


    initial
        begin
        end

endmodule
