// generated by newgenasym  Tue Sep 15 11:13:11 2020


module lpc176x (\p0_0/rd1/txd3/sda1 , \p0_1/td1/rxd3/scl1 ,
        \p0_10/txd2/sda2/mat3_0 , \p0_11/rxd2/scl2/mat3_1 ,
        \p0_15txd1/sck0/sck , \p0_16/rxd1/ssel0/ssel ,
        \p0_17/cts1/miso0/miso , \p0_18/dcd1/mosi0/mosi ,
        \p0_19/dsr1/sda1 , \p0_2/txd0/ad0_7 , \p0_20/dtr1/scl1 ,
        \p0_21/ri1/rd1 , \p0_22/rts1/td1 ,
        \p0_23/ad0_0/i2srx_clk/cap3_0 ,
        \p0_24/ad0_1/i2srx_ws/cap3_1 ,
        \p0_25/ad0_2/i2srx_sda/txd3 , \p0_26/ad0_3/aout/rxd3 ,
        \p0_27/sda0/usb_sda , \p0_28/scl0/usb_scl , \p0_29/usb_d+ ,
        \p0_3/rxd0/ad0_6 , \p0_30/usb_d- ,
        \p0_4/i2srx_clk/rd2/cap2_0 , \p0_5/i2srx_ws/td2/cap2_1 ,
        \p0_6/i2srx_sda/ssel1/mat2_0 ,
        \p0_7/i2stx_clk/sck1/mat2_1 , \p0_8/i2stx_ws/miso1/mat2_2 ,
        \p0_9/i2stx_sda/mosi1/mat2_3 , \p1_0/enet_txd0 ,
        \p1_1/enet_txd1 , \p1_10/enet_rxd1 , \p1_14/enet_rx_er ,
        \p1_15/enet_ref_clk , \p1_16/enet_mdc , \p1_17/enet_mdio ,
        \p1_18/usb_up_led/pwm1_1/cap1_0 ,
        \p1_19/mcoa0/usb_ppwr/cap1_1 , \p1_20/mic0/pwm1_2/sck0 ,
        \p1_21/pwm1_3/ssel0/mcabort ,
        \p1_22/mcob0/usb_pwrd/mat1_0 , \p1_23/mci1/pwm1_4/miso0 ,
        \p1_24/mci2/pwm1_5/mosi0 , \p1_25/mcoa1/mat1_1 ,
        \p1_26/mcb1/pwm1_6/cap0_0 ,
        \p1_27/clkout/cap0_1/usb_ovrcr ,
        \p1_28/mcoa2/pcap1_0/mat0_0 , \p1_29/mcob2/pcap1_1/mat0_1 ,
        \p1_30/vbus/ad0_4 , \p1_31/sck1/ad0_5 , \p1_4/enet_tx_en ,
        \p1_8/enet_crs , \p1_9/enet_rxd0 , \p2_0/pwm1_1/txd1 ,
        \p2_1/pwm1_2/rxd1 , \p2_10/nmi/eint0 ,
        \p2_11/i2stx_clk/eint1 , \p2_12/i2stx_ws/eint2 ,
        \p2_13/i2stx_sda/eint3 , \p2_2/pwm1_3/cts1/tracedata_3 ,
        \p2_3/pwm1_4/dcd1/tracedata_2 ,
        \p2_4/pwm1_15/dsr1/tracedata_1 ,
        \p2_5/pwm1_6/dtr1/tracedata_0 ,
        \p2_6/pcap1_0/ri1/traceclk , \p2_7/rd2/rts1 , \p2_8/td2/txd2 ,
        \p2_9/usb_connect/rxd2 , \p3_25/mat0_0/pwm1_2 ,
        \p3_26/stclk/mat0_1/pwm1_3 , \p4_28/rx_mclk/mat2_0/txd3 ,
        \p4_29/tx_mclk/mat2_1/rxd3 , reset, rstout, rtck, rtcx1,
        rtcx2, \tck/swdclk , tdi, \tdo/swo , \tms/swdio , trst, vbat, vdd1,
        vdd2, vdd3, vdd4, vdda, vddreg, vddreg1, vrefn, vrefp, vss1,
        vss2, vss3, vss4, vss5, vss6, vssa, xtal1, xtal2);
    inout \p0_0/rd1/txd3/sda1 ;
    inout \p0_1/td1/rxd3/scl1 ;
    inout \p0_10/txd2/sda2/mat3_0 ;
    inout \p0_11/rxd2/scl2/mat3_1 ;
    inout \p0_15txd1/sck0/sck ;
    inout \p0_16/rxd1/ssel0/ssel ;
    inout \p0_17/cts1/miso0/miso ;
    inout \p0_18/dcd1/mosi0/mosi ;
    inout \p0_19/dsr1/sda1 ;
    inout \p0_2/txd0/ad0_7 ;
    inout \p0_20/dtr1/scl1 ;
    inout \p0_21/ri1/rd1 ;
    inout \p0_22/rts1/td1 ;
    inout \p0_23/ad0_0/i2srx_clk/cap3_0 ;
    inout \p0_24/ad0_1/i2srx_ws/cap3_1 ;
    inout \p0_25/ad0_2/i2srx_sda/txd3 ;
    inout \p0_26/ad0_3/aout/rxd3 ;
    inout \p0_27/sda0/usb_sda ;
    inout \p0_28/scl0/usb_scl ;
    inout \p0_29/usb_d+ ;
    inout \p0_3/rxd0/ad0_6 ;
    inout \p0_30/usb_d- ;
    inout \p0_4/i2srx_clk/rd2/cap2_0 ;
    inout \p0_5/i2srx_ws/td2/cap2_1 ;
    inout \p0_6/i2srx_sda/ssel1/mat2_0 ;
    inout \p0_7/i2stx_clk/sck1/mat2_1 ;
    inout \p0_8/i2stx_ws/miso1/mat2_2 ;
    inout \p0_9/i2stx_sda/mosi1/mat2_3 ;
    inout \p1_0/enet_txd0 ;
    inout \p1_1/enet_txd1 ;
    inout \p1_10/enet_rxd1 ;
    inout \p1_14/enet_rx_er ;
    inout \p1_15/enet_ref_clk ;
    inout \p1_16/enet_mdc ;
    inout \p1_17/enet_mdio ;
    inout \p1_18/usb_up_led/pwm1_1/cap1_0 ;
    inout \p1_19/mcoa0/usb_ppwr/cap1_1 ;
    inout \p1_20/mic0/pwm1_2/sck0 ;
    inout \p1_21/pwm1_3/ssel0/mcabort ;
    inout \p1_22/mcob0/usb_pwrd/mat1_0 ;
    inout \p1_23/mci1/pwm1_4/miso0 ;
    inout \p1_24/mci2/pwm1_5/mosi0 ;
    inout \p1_25/mcoa1/mat1_1 ;
    inout \p1_26/mcb1/pwm1_6/cap0_0 ;
    inout \p1_27/clkout/cap0_1/usb_ovrcr ;
    inout \p1_28/mcoa2/pcap1_0/mat0_0 ;
    inout \p1_29/mcob2/pcap1_1/mat0_1 ;
    inout \p1_30/vbus/ad0_4 ;
    inout \p1_31/sck1/ad0_5 ;
    inout \p1_4/enet_tx_en ;
    inout \p1_8/enet_crs ;
    inout \p1_9/enet_rxd0 ;
    inout \p2_0/pwm1_1/txd1 ;
    inout \p2_1/pwm1_2/rxd1 ;
    inout \p2_10/nmi/eint0 ;
    inout \p2_11/i2stx_clk/eint1 ;
    inout \p2_12/i2stx_ws/eint2 ;
    inout \p2_13/i2stx_sda/eint3 ;
    inout \p2_2/pwm1_3/cts1/tracedata_3 ;
    inout \p2_3/pwm1_4/dcd1/tracedata_2 ;
    inout \p2_4/pwm1_15/dsr1/tracedata_1 ;
    inout \p2_5/pwm1_6/dtr1/tracedata_0 ;
    inout \p2_6/pcap1_0/ri1/traceclk ;
    inout \p2_7/rd2/rts1 ;
    inout \p2_8/td2/txd2 ;
    inout \p2_9/usb_connect/rxd2 ;
    inout \p3_25/mat0_0/pwm1_2 ;
    inout \p3_26/stclk/mat0_1/pwm1_3 ;
    inout \p4_28/rx_mclk/mat2_0/txd3 ;
    inout \p4_29/tx_mclk/mat2_1/rxd3 ;
    input reset;
    output rstout;
    output rtck;
    input rtcx1;
    output rtcx2;
    input \tck/swdclk ;
    input tdi;
    output \tdo/swo ;
    inout \tms/swdio ;
    input trst;
    input vbat;
    input vdd1;
    input vdd2;
    input vdd3;
    input vdd4;
    input vdda;
    input vddreg;
    input vddreg1;
    input vrefn;
    input vrefp;
    input vss1;
    input vss2;
    input vss3;
    input vss4;
    input vss5;
    input vss6;
    input vssa;
    input xtal1;
    output xtal2;


    initial
        begin
        end

endmodule
