-- generated by newgenasym Thu Sep 03 17:59:24 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hc32f005c6ua is
    port (    
	\avcc/dvcc\: IN     STD_LOGIC;    
	\avss/dvss\: IN     STD_LOGIC;    
	EPAD:      INOUT  STD_LOGIC;    
	\lvdin1/p03\: INOUT  STD_LOGIC;    
	\lvdin2/vcin0/p23\: INOUT  STD_LOGIC;    
	P14:       INOUT  STD_LOGIC;    
	P15:       INOUT  STD_LOGIC;    
	\p24/vin0\: INOUT  STD_LOGIC;    
	\p25/lvdin3/vc1\: INOUT  STD_LOGIC;    
	\p26/ain1\: INOUT  STD_LOGIC;    
	\p27/swdio\: INOUT  STD_LOGIC;    
	\p31/swclk\: INOUT  STD_LOGIC;    
	\p32/ain2/vcin2\: INOUT  STD_LOGIC;    
	\p33/ain3/vcin3\: INOUT  STD_LOGIC;    
	\p34/ain4/vcin4\: INOUT  STD_LOGIC;    
	\p35/ain5/vcin5\: INOUT  STD_LOGIC;    
	\p36/ain6/vcin6/avref\: INOUT  STD_LOGIC;    
	\resetb/p00\: IN     STD_LOGIC;    
	VCAP:      IN     STD_LOGIC;    
	\xthi/ain7/vcin7/p01\: INOUT  STD_LOGIC;    
	\xtho/ain8/p02\: INOUT  STD_LOGIC);
end hc32f005c6ua;
