// generated by newgenasym  Mon Aug 31 13:55:54 2020


module ft232rl (\3v3out , agnd, cbus0, cbus1, cbus2, cbus3, cbus4, cts, dcd,
        dsr, dtr, gnd_1, gnd_2, gnd_3, nc_1, nc_2, osci, osco, reset,
        ri, rts, rxd, test, txd, usbdm, usbdp, vcc, vccio);
    output \3v3out ;
    inout agnd;
    input cbus0;
    input cbus1;
    input cbus2;
    input cbus3;
    input cbus4;
    input cts;
    input dcd;
    input dsr;
    output dtr;
    input gnd_1;
    input gnd_2;
    input gnd_3;
    inout nc_1;
    inout nc_2;
    input osci;
    output osco;
    input reset;
    input ri;
    output rts;
    input rxd;
    input test;
    output txd;
    inout usbdm;
    inout usbdp;
    input vcc;
    input vccio;


    initial
        begin
        end

endmodule
