// generated by newgenasym  Mon Aug 31 13:54:31 2020


module fem_5g (ant, c_rx, epad, gnd1, gnd2, gnd3, gnd4, lna_en, nc1, nc2,
        pa_en, pdet, rx, tx, vcc1, vcc2, vdd);
    inout ant;
    inout c_rx;
    inout epad;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout lna_en;
    inout nc1;
    inout nc2;
    inout pa_en;
    inout pdet;
    inout rx;
    inout tx;
    inout vcc1;
    inout vcc2;
    inout vdd;


    initial
        begin
        end

endmodule
