// generated by newgenasym  Mon Aug 31 14:07:55 2020


module lm75 (a0, a1, a2, gnd, os, scl, sda, vcc);
    input a0;
    input a1;
    input a2;
    input gnd;
    input os;
    input scl;
    output sda;
    input vcc;


    initial
        begin
        end

endmodule
