// generated by newgenasym  Fri May 27 10:12:39 2022


module gn25l99 (a0, a1, adc_in, bias, gnd, \laser+ , \laser- , mpd, nc1, nc2,
        reset, \rxin+ , \rxin- , \rxout+ , \rxout- , rxref, scl, sd, sda,
        tx_disable, tx_fault, \txin+ , \txin- , vcap, vdd_dig, vdd_rx1,
        vdd_rx2, vdd_rx3, vdd_tx);
    inout a0;
    inout a1;
    input adc_in;
    inout bias;
    input gnd;
    inout \laser+ ;
    inout \laser- ;
    inout mpd;
    inout nc1;
    inout nc2;
    inout reset;
    inout \rxin+ ;
    inout \rxin- ;
    inout \rxout+ ;
    inout \rxout- ;
    inout rxref;
    inout scl;
    output sd;
    inout sda;
    inout tx_disable;
    inout tx_fault;
    inout \txin+ ;
    inout \txin- ;
    input vcap;
    input vdd_dig;
    input vdd_rx1;
    input vdd_rx2;
    input vdd_rx3;
    input vdd_tx;


    initial
        begin
        end

endmodule
