-- generated by newgenasym Tue Dec 05 11:24:23 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity jwh5125ch is
    port (    
	BST:       INOUT  STD_LOGIC;    
	COMP:      INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	EPAD:      IN     STD_LOGIC;    
	FB:        OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	RT:        INOUT  STD_LOGIC;    
	SW:        INOUT  STD_LOGIC;    
	VIN:       IN     STD_LOGIC);
end jwh5125ch;
