// generated by newgenasym  Mon Aug 31 14:26:22 2020


module si32178 (\c1a/nc , \c2a/nc , caplb, capm, capp, cs, dcdrv, dcff, drx, dtx,
        epad1, epad2, fsync, \gpio1/stipc , \gpio2/sringc , int, iref,
        nc1, nc2, nc3, nc4, nc_epad2, pclk, qgnd, ring, rst, sclk, sdch,
        sdcl, sdi, sdithru, sdo, sringac, sringdc, stipac, stipdc,
        svbat, svdc, tip, vbat, vdda, vddd, vddhv, vddreg);
    inout \c1a/nc ;
    inout \c2a/nc ;
    input caplb;
    input capm;
    input capp;
    input cs;
    inout dcdrv;
    inout dcff;
    input drx;
    inout dtx;
    inout epad1;
    inout epad2;
    input fsync;
    inout \gpio1/stipc ;
    inout \gpio2/sringc ;
    inout int;
    input iref;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc_epad2;
    input pclk;
    input qgnd;
    inout ring;
    input rst;
    input sclk;
    input sdch;
    input sdcl;
    input sdi;
    inout sdithru;
    inout sdo;
    input sringac;
    input sringdc;
    input stipac;
    input stipdc;
    input svbat;
    input svdc;
    inout tip;
    inout vbat;
    input vdda;
    input vddd;
    input vddhv;
    input vddreg;


    initial
        begin
        end

endmodule
