// generated by newgenasym  Wed Aug 03 08:45:13 2022


module inductor_gm (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
