-- generated by newgenasym Wed Aug 03 08:45:13 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity inductor_gm is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end inductor_gm;
