// generated by newgenasym  Mon Nov 09 18:07:17 2020


module rtl8812fr (eecs, eesk, epad, gnd_sps, gpio13, gpio5, \gpio6/lte_rxd ,
        \gpio7/lte_coex3 , hsin, hsip, hson, hsop, \icfg0/gpio0 ,
        \icfg1/gpio1 , \icfg2/gpio2 , \icfg3/gpio3 , ldo_v10_o_1,
        ldo_v10_o_2, ldo_v13_i_1, ldo_v13_i_2, ldo_v13_phy_i,
        lx_sps_v13_o_1, lx_sps_v13_o_2, nc1, nc2, perstn, refclk_n,
        refclk_p, s0_rfio_5g, s0_rx_aux_5g, s0_tssi, s0_v13_rx5g,
        s0_v33_5gpa, s0_v33_5gpad, s1_rfio_5g, s1_rx_aux_5g,
        s1_tssi, s1_v13_trx, s1_v33_5gpa, s1_v33_5gpad,
        \test_md_sel/gpio4 , v13_afe, v13_syn, v33_syn, vd10_vddtx,
        vd10d_wl, vd10d_wlbb_right, vd10d_wlbb_top, vd33_hci,
        vd33_io, vd33sps, vd33x, vdd_io, \wl_led/gpio8 , wl_v33_ldo,
        xi, xo);
    inout eecs;
    inout eesk;
    inout epad;
    inout gnd_sps;
    inout gpio13;
    inout gpio5;
    inout \gpio6/lte_rxd ;
    inout \gpio7/lte_coex3 ;
    inout hsin;
    inout hsip;
    inout hson;
    inout hsop;
    inout \icfg0/gpio0 ;
    inout \icfg1/gpio1 ;
    inout \icfg2/gpio2 ;
    inout \icfg3/gpio3 ;
    inout ldo_v10_o_1;
    inout ldo_v10_o_2;
    inout ldo_v13_i_1;
    inout ldo_v13_i_2;
    inout ldo_v13_phy_i;
    inout lx_sps_v13_o_1;
    inout lx_sps_v13_o_2;
    inout nc1;
    inout nc2;
    inout perstn;
    inout refclk_n;
    inout refclk_p;
    inout s0_rfio_5g;
    inout s0_rx_aux_5g;
    inout s0_tssi;
    inout s0_v13_rx5g;
    inout s0_v33_5gpa;
    inout s0_v33_5gpad;
    inout s1_rfio_5g;
    inout s1_rx_aux_5g;
    inout s1_tssi;
    inout s1_v13_trx;
    inout s1_v33_5gpa;
    inout s1_v33_5gpad;
    inout \test_md_sel/gpio4 ;
    inout v13_afe;
    inout v13_syn;
    inout v33_syn;
    inout vd10_vddtx;
    inout vd10d_wl;
    inout vd10d_wlbb_right;
    inout vd10d_wlbb_top;
    inout vd33_hci;
    inout vd33_io;
    inout vd33sps;
    inout vd33x;
    inout vdd_io;
    inout \wl_led/gpio8 ;
    inout wl_v33_ldo;
    inout xi;
    inout xo;


    initial
        begin
        end

endmodule
