-- generated by newgenasym Mon Aug 31 14:16:29 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pusb3f96 is
    port (    
	CH1:       INOUT  STD_LOGIC;    
	CH2:       INOUT  STD_LOGIC;    
	CH3:       INOUT  STD_LOGIC;    
	CH4:       INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC);
end pusb3f96;
