// generated by newgenasym  Mon Nov 06 14:54:51 2023


module mt7976dn (antsel_0, antsel_1, antsel_10, antsel_11, antsel_12,
        antsel_13, antsel_14, antsel_15, antsel_2, antsel_3,
        antsel_4, antsel_5, antsel_6, antsel_7, antsel_8, antsel_9,
        avdd18_wf0_dig, avdd18_wf0_io, avdd18_wf0_sx,
        avdd18_wf0_top, avdd18_wf0_tx, avdd18_wf0_tx_ga,
        avdd18_wf1_tx, avdd18_wf3_dig, avdd18_wf3_sx,
        avdd18_wf3_top, avdd18_wf3_tx_ga, avdd33_esd,
        avdd33_wf0_pa_g, avdd33_wf0_top, avdd33_wf0_tx_ga,
        avdd33_wf1_pa_g, avdd33_wf2_pa_a, avdd33_wf2_pad_a,
        avdd33_wf3_pa_a, avdd33_wf3_pad_a, avdd33_wf3_top,
        avdd33_wf3_tx_ga, avdd33_wf4_pa_a, avdd33_wf4_pad_a,
        avdd33_wf_sx, avdd33_xo, avdd33_xobuf, epad, gnd_101,
        gnd_107, gnd_108, gnd_113, gnd_119, gnd_125, gnd_127,
        gnd_14, gnd_140, gnd_29, gnd_41, gnd_42, gnd_45, gnd_48,
        gnd_51, gnd_54, gnd_57, gnd_60, gnd_63, gnd_66, gnd_69,
        gnd_74, gnd_75, gnd_81, gnd_82, gnd_95, gnd_98, nc_1, nc_103,
        nc_104, nc_110, nc_116, nc_12, nc_122, nc_144, nc_3, nc_31,
        nc_32, nc_6, nc_72, nc_73, nc_9, pad_cba_resetb,
        pad_dig_resetb, pad_pmu_por_b_v18, pad_slp_clk,
        pad_top_clk, pad_top_data, pad_wf_hb0, pad_wf_hb0_b,
        pad_wf_hb1, pad_wf_hb10, pad_wf_hb2, pad_wf_hb3,
        pad_wf_hb4, pad_wf_hb5, pad_wf_hb6, pad_wf_hb7,
        pad_wf_hb8, pad_wf_hb9, pad_xo_req, pdet0, pdet1, pdet2,
        pdet3, pdet4, wf0_aux_g, wf0_g_rfio, wf0_in, wf0_ip, wf0_qn,
        wf0_qp, wf1_aux_g, wf1_g_rfio, wf1_in, wf1_ip, wf1_qn,
        wf1_qp, wf2_a_rfio, wf2_aux_a, wf2_in, wf2_ip, wf2_qn,
        wf2_qp, wf3_a_rfio, wf3_aux_a, wf3_in, wf3_ip, wf3_qn,
        wf3_qp, wf4_a_rfio, wf4_aux_ga, wf4_in, wf4_ip, wf4_qn,
        wf4_qp, xo_buf_in, xo_coclk, xo_in, xo_inb, xo_out);
    inout antsel_0;
    inout antsel_1;
    inout antsel_10;
    inout antsel_11;
    inout antsel_12;
    inout antsel_13;
    inout antsel_14;
    inout antsel_15;
    inout antsel_2;
    inout antsel_3;
    inout antsel_4;
    inout antsel_5;
    inout antsel_6;
    inout antsel_7;
    inout antsel_8;
    inout antsel_9;
    input avdd18_wf0_dig;
    input avdd18_wf0_io;
    input avdd18_wf0_sx;
    input avdd18_wf0_top;
    input avdd18_wf0_tx;
    input avdd18_wf0_tx_ga;
    input avdd18_wf1_tx;
    input avdd18_wf3_dig;
    input avdd18_wf3_sx;
    input avdd18_wf3_top;
    input avdd18_wf3_tx_ga;
    input avdd33_esd;
    input avdd33_wf0_pa_g;
    input avdd33_wf0_top;
    input avdd33_wf0_tx_ga;
    input avdd33_wf1_pa_g;
    input avdd33_wf2_pa_a;
    input avdd33_wf2_pad_a;
    input avdd33_wf3_pa_a;
    input avdd33_wf3_pad_a;
    input avdd33_wf3_top;
    input avdd33_wf3_tx_ga;
    input avdd33_wf4_pa_a;
    input avdd33_wf4_pad_a;
    input avdd33_wf_sx;
    input avdd33_xo;
    input avdd33_xobuf;
    input epad;
    input gnd_101;
    input gnd_107;
    input gnd_108;
    input gnd_113;
    input gnd_119;
    input gnd_125;
    input gnd_127;
    input gnd_14;
    input gnd_140;
    input gnd_29;
    input gnd_41;
    input gnd_42;
    input gnd_45;
    input gnd_48;
    input gnd_51;
    input gnd_54;
    input gnd_57;
    input gnd_60;
    input gnd_63;
    input gnd_66;
    input gnd_69;
    input gnd_74;
    input gnd_75;
    input gnd_81;
    input gnd_82;
    input gnd_95;
    input gnd_98;
    inout nc_1;
    inout nc_103;
    inout nc_104;
    inout nc_110;
    inout nc_116;
    inout nc_12;
    inout nc_122;
    inout nc_144;
    inout nc_3;
    inout nc_31;
    inout nc_32;
    inout nc_6;
    inout nc_72;
    inout nc_73;
    inout nc_9;
    input pad_cba_resetb;
    input pad_dig_resetb;
    input pad_pmu_por_b_v18;
    inout pad_slp_clk;
    inout pad_top_clk;
    inout pad_top_data;
    inout pad_wf_hb0;
    inout pad_wf_hb0_b;
    inout pad_wf_hb1;
    inout pad_wf_hb10;
    inout pad_wf_hb2;
    inout pad_wf_hb3;
    inout pad_wf_hb4;
    inout pad_wf_hb5;
    inout pad_wf_hb6;
    inout pad_wf_hb7;
    inout pad_wf_hb8;
    inout pad_wf_hb9;
    input pad_xo_req;
    input pdet0;
    input pdet1;
    input pdet2;
    input pdet3;
    input pdet4;
    input wf0_aux_g;
    inout wf0_g_rfio;
    inout wf0_in;
    inout wf0_ip;
    inout wf0_qn;
    inout wf0_qp;
    input wf1_aux_g;
    inout wf1_g_rfio;
    inout wf1_in;
    inout wf1_ip;
    inout wf1_qn;
    inout wf1_qp;
    inout wf2_a_rfio;
    input wf2_aux_a;
    inout wf2_in;
    inout wf2_ip;
    inout wf2_qn;
    inout wf2_qp;
    inout wf3_a_rfio;
    input wf3_aux_a;
    inout wf3_in;
    inout wf3_ip;
    inout wf3_qn;
    inout wf3_qp;
    inout wf4_a_rfio;
    input wf4_aux_ga;
    inout wf4_in;
    inout wf4_ip;
    inout wf4_qn;
    inout wf4_qp;
    input xo_buf_in;
    output xo_coclk;
    input xo_in;
    input xo_inb;
    output xo_out;


    initial
        begin
        end

endmodule
