-- generated by newgenasym Mon Aug 31 14:22:37 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rtl8201f is
    port (    
	AVDD10OUT: IN     STD_LOGIC;    
	AVDD33:    IN     STD_LOGIC;    
	AVDD33_1:  IN     STD_LOGIC;    
	CKXTAL1:   INOUT  STD_LOGIC;    
	CKXTAL2:   INOUT  STD_LOGIC;    
	COL:       INOUT  STD_LOGIC;    
	CRS:       INOUT  STD_LOGIC;    
	DVDD10OUT: IN     STD_LOGIC;    
	DVDD33:    IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\led0/phyad_0\: INOUT  STD_LOGIC;    
	\led1/phyad_1\: INOUT  STD_LOGIC;    
	MDC:       INOUT  STD_LOGIC;    
	MDI_0N:    INOUT  STD_LOGIC;    
	MDI_0P:    INOUT  STD_LOGIC;    
	MDI_1N:    INOUT  STD_LOGIC;    
	MDI_1P:    INOUT  STD_LOGIC;    
	MDIO:      INOUT  STD_LOGIC;    
	PHYRSTB:   INOUT  STD_LOGIC;    
	RSET:      INOUT  STD_LOGIC;    
	RXC:       INOUT  STD_LOGIC;    
	RXD_0:     INOUT  STD_LOGIC;    
	RXD_1:     INOUT  STD_LOGIC;    
	\rxd_2/intb\: INOUT  STD_LOGIC;    
	RXD_3:     INOUT  STD_LOGIC;    
	RXDV:      INOUT  STD_LOGIC;    
	\rxer/fxen\: INOUT  STD_LOGIC;    
	TXC:       INOUT  STD_LOGIC;    
	TXD_0:     INOUT  STD_LOGIC;    
	TXD_1:     INOUT  STD_LOGIC;    
	TXD_2:     INOUT  STD_LOGIC;    
	TXD_3:     INOUT  STD_LOGIC;    
	TXEN:      INOUT  STD_LOGIC);
end rtl8201f;
