// generated by newgenasym  Thu Jul 08 10:07:13 2021


module bcm88470 (bs_pll0_testout_n, bs_pll0_testout_p,
        bs_pll1_testout_n, bs_pll1_testout_p, bs_pll_avdd1p8,
        c_pll_agnd, c_pll_avdd1p8, c_pll_byp_clk0,
        c_pll_byp_clk1, c_pll_bypass, c_pll_lock, c_pll_refclk_n,
        c_pll_refclk_p, c_pll_testout_n, c_pll_testout_p,
        clock25, ddr_vddo_1, ddr_vddo_10, ddr_vddo_11,
        ddr_vddo_12, ddr_vddo_13, ddr_vddo_14, ddr_vddo_15,
        ddr_vddo_16, ddr_vddo_17, ddr_vddo_18, ddr_vddo_19,
        ddr_vddo_2, ddr_vddo_20, ddr_vddo_21, ddr_vddo_22,
        ddr_vddo_23, ddr_vddo_24, ddr_vddo_25, ddr_vddo_26,
        ddr_vddo_27, ddr_vddo_28, ddr_vddo_29, ddr_vddo_3,
        ddr_vddo_30, ddr_vddo_31, ddr_vddo_32, ddr_vddo_33,
        ddr_vddo_34, ddr_vddo_35, ddr_vddo_36, ddr_vddo_37,
        ddr_vddo_38, ddr_vddo_39, ddr_vddo_4, ddr_vddo_40,
        ddr_vddo_41, ddr_vddo_42, ddr_vddo_43, ddr_vddo_44,
        ddr_vddo_45, ddr_vddo_46, ddr_vddo_47, ddr_vddo_48,
        ddr_vddo_49, ddr_vddo_5, ddr_vddo_50, ddr_vddo_51,
        ddr_vddo_52, ddr_vddo_53, ddr_vddo_54, ddr_vddo_55,
        ddr_vddo_56, ddr_vddo_57, ddr_vddo_58, ddr_vddo_59,
        ddr_vddo_6, ddr_vddo_60, ddr_vddo_61, ddr_vddo_7,
        ddr_vddo_8, ddr_vddo_9, ddra_a0_a7a8, ddra_a10, ddra_a11,
        ddra_a12, ddra_a13, ddra_a1_a1a9, ddra_a2_a0a10,
        ddra_a3_a6a11, ddra_a3ba3, ddra_a4_a13a12,
        ddra_a5_a14a15, ddra_a6, ddra_a7, ddra_a8, ddra_a9,
        ddra_act_abi_n, ddra_alert_n_0, ddra_alert_n_1,
        ddra_aux_0, ddra_aux_1, ddra_avdd1p8, ddra_avss,
        ddra_ba0_a2ba0, ddra_ba1_a5ba1, ddra_bg0_a4ba2,
        ddra_cas_n, ddra_ck_n, ddra_ck_p, ddra_cke, ddra_cs_n_0,
        ddra_cs_n_1, ddra_dbi_n_0, ddra_dbi_n_1, ddra_dbi_n_2,
        ddra_dbi_n_3, ddra_dq_0, ddra_dq_1, ddra_dq_10,
        ddra_dq_11, ddra_dq_12, ddra_dq_13, ddra_dq_14,
        ddra_dq_15, ddra_dq_16, ddra_dq_17, ddra_dq_18,
        ddra_dq_19, ddra_dq_2, ddra_dq_20, ddra_dq_21, ddra_dq_22,
        ddra_dq_23, ddra_dq_24, ddra_dq_25, ddra_dq_26,
        ddra_dq_27, ddra_dq_28, ddra_dq_29, ddra_dq_3, ddra_dq_30,
        ddra_dq_31, ddra_dq_4, ddra_dq_5, ddra_dq_6, ddra_dq_7,
        ddra_dq_8, ddra_dq_9, ddra_dqs0_wck01_n,
        ddra_dqs0_wck01_p, ddra_dqs1_n, ddra_dqs1_p,
        ddra_dqs2_wck23_n, ddra_dqs2_wck23_p, ddra_dqs3_n,
        ddra_dqs3_p, ddra_edc_0, ddra_edc_1, ddra_edc_2,
        ddra_edc_3, ddra_odt, ddra_par, ddra_pll_clk_mon,
        ddra_ras_n, ddra_refclk_n, ddra_refclk_p, ddra_res_neg,
        ddra_res_pos, ddra_res_vdd, ddra_res_vss, ddra_reset_n,
        ddra_v_analog1p8_1, ddra_v_analog1p8_2, ddra_vddc_1,
        ddra_vddc_2, ddra_vddc_3, ddra_vref_mon, ddra_we_n,
        ddrb_a0_a7a8, ddrb_a10, ddrb_a11, ddrb_a12, ddrb_a13,
        ddrb_a1_a1a9, ddrb_a2_a0a10, ddrb_a3_a6a11, ddrb_a3ba3,
        ddrb_a4_a13a12, ddrb_a5_a14a15, ddrb_a6, ddrb_a7, ddrb_a8,
        ddrb_a9, ddrb_act_abi_n, ddrb_alert_n_0, ddrb_alert_n_1,
        ddrb_aux_0, ddrb_aux_1, ddrb_avdd1p8, ddrb_avss,
        ddrb_ba0_a2ba0, ddrb_ba1_a5ba1, ddrb_bg0_a4ba2,
        ddrb_cas_n, ddrb_ck_n, ddrb_ck_p, ddrb_cke, ddrb_cs_n_0,
        ddrb_cs_n_1, ddrb_dbi_n_0, ddrb_dbi_n_1, ddrb_dbi_n_2,
        ddrb_dbi_n_3, ddrb_dq_0, ddrb_dq_1, ddrb_dq_10,
        ddrb_dq_11, ddrb_dq_12, ddrb_dq_13, ddrb_dq_14,
        ddrb_dq_15, ddrb_dq_16, ddrb_dq_17, ddrb_dq_18,
        ddrb_dq_19, ddrb_dq_2, ddrb_dq_20, ddrb_dq_21, ddrb_dq_22,
        ddrb_dq_23, ddrb_dq_24, ddrb_dq_25, ddrb_dq_26,
        ddrb_dq_27, ddrb_dq_28, ddrb_dq_29, ddrb_dq_3, ddrb_dq_30,
        ddrb_dq_31, ddrb_dq_4, ddrb_dq_5, ddrb_dq_6, ddrb_dq_7,
        ddrb_dq_8, ddrb_dq_9, ddrb_dqs0_wck01_n,
        ddrb_dqs0_wck01_p, ddrb_dqs1_n, ddrb_dqs1_p,
        ddrb_dqs2_wck23_n, ddrb_dqs2_wck23_p, ddrb_dqs3_n,
        ddrb_dqs3_p, ddrb_edc_0, ddrb_edc_1, ddrb_edc_2,
        ddrb_edc_3, ddrb_odt, ddrb_par, ddrb_ras_n, ddrb_refclk_n,
        ddrb_refclk_p, ddrb_reset_n, ddrb_v_analog1p8_1,
        ddrb_v_analog1p8_2, ddrb_vddc_1, ddrb_vddc_2,
        ddrb_vddc_3, ddrb_we_n, ddrc_a0_a7a8, ddrc_a10, ddrc_a11,
        ddrc_a12, ddrc_a13, ddrc_a1_a1a9, ddrc_a2_a0a10,
        ddrc_a3_a6a11, ddrc_a3ba3, ddrc_a4_a13a12,
        ddrc_a5_a14a15, ddrc_a6, ddrc_a7, ddrc_a8, ddrc_a9,
        ddrc_act_abi_n, ddrc_alert_n_0, ddrc_alert_n_1,
        ddrc_aux_0, ddrc_aux_1, ddrc_avdd1p8, ddrc_avss,
        ddrc_ba0_a2ba0, ddrc_ba1_a5ba1, ddrc_bg0_a4ba2,
        ddrc_cas_n, ddrc_ck_n, ddrc_ck_p, ddrc_cke, ddrc_cs_n_0,
        ddrc_cs_n_1, ddrc_dbi_n_0, ddrc_dbi_n_1, ddrc_dbi_n_2,
        ddrc_dbi_n_3, ddrc_dq_0, ddrc_dq_1, ddrc_dq_10,
        ddrc_dq_11, ddrc_dq_12, ddrc_dq_13, ddrc_dq_14,
        ddrc_dq_15, ddrc_dq_16, ddrc_dq_17, ddrc_dq_18,
        ddrc_dq_19, ddrc_dq_2, ddrc_dq_20, ddrc_dq_21, ddrc_dq_22,
        ddrc_dq_23, ddrc_dq_24, ddrc_dq_25, ddrc_dq_26,
        ddrc_dq_27, ddrc_dq_28, ddrc_dq_29, ddrc_dq_3, ddrc_dq_30,
        ddrc_dq_31, ddrc_dq_4, ddrc_dq_5, ddrc_dq_6, ddrc_dq_7,
        ddrc_dq_8, ddrc_dq_9, ddrc_dqs0_wck01_n,
        ddrc_dqs0_wck01_p, ddrc_dqs1_n, ddrc_dqs1_p,
        ddrc_dqs2_wck23_n, ddrc_dqs2_wck23_p, ddrc_dqs3_n,
        ddrc_dqs3_p, ddrc_edc_0, ddrc_edc_1, ddrc_edc_2,
        ddrc_edc_3, ddrc_odt, ddrc_par, ddrc_ras_n, ddrc_refclk_n,
        ddrc_refclk_p, ddrc_res_neg, ddrc_res_pos, ddrc_res_vdd,
        ddrc_res_vss, ddrc_reset_n, ddrc_v_analog1p8_1,
        ddrc_v_analog1p8_2, ddrc_vddc_1, ddrc_vddc_2,
        ddrc_vddc_3, ddrc_we_n, disconnect, fc_rx_clk,
        fc_rx_stat_0, fc_rx_stat_1, fc_synce_vddo_1,
        fc_synce_vddo_2, fc_synce_vddp, fc_tx_clk, fc_tx_stat_0,
        fc_tx_stat_1, ftest_0, ftest_1, ftest_2, gpio0, gpio1,
        i2c_scl, i2c_sda, int_n, io_vddo_3p3_1, io_vddo_3p3_2,
        io_vddo_3p3_3, io_vddo_3p3_4, io_vddo_3p3_5,
        io_vddo_3p3_6, io_vddp_1p8_1, io_vddp_1p8_2, jtag_tce,
        jtag_tck, jtag_tdi, jtag_tdo, jtag_tms, jtag_trst_n,
        led_clk, led_data, mdc_0, mdc_1, mdc_2, mdc_3, mdio_0,
        mdio_1, mdio_2, mdio_3, nc_ochk, nif_lcpll_agnd,
        nif_lcpll_avdd1p8, nif_lcpll_byp_clk,
        nif_lcpll_refclk_n, nif_lcpll_refclk_p,
        nif_lcpll_testout_n, nif_lcpll_testout_p,
        nif_pvdd1p0_q00, nif_pvdd1p0_q01, nif_pvdd1p0_q02,
        nif_pvdd1p0_q03, nif_rvdd1p0_q00_01_1,
        nif_rvdd1p0_q00_01_2, nif_rvdd1p0_q00_01_3,
        nif_rvdd1p0_q00_01_4, nif_rvdd1p0_q00_01_5,
        nif_rvdd1p0_q00_01_6, nif_rvdd1p0_q00_01_7,
        nif_rvdd1p0_q00_01_8, nif_rvdd1p0_q02_03_1,
        nif_rvdd1p0_q02_03_2, nif_rvdd1p0_q02_03_3,
        nif_rvdd1p0_q02_03_4, nif_rvdd1p0_q02_03_5,
        nif_rvdd1p0_q02_03_6, nif_rvdd1p0_q02_03_7,
        nif_rvdd1p0_q02_03_8, nif_rx_00_n, nif_rx_00_p,
        nif_rx_01_n, nif_rx_01_p, nif_rx_02_n, nif_rx_02_p,
        nif_rx_03_n, nif_rx_03_p, nif_rx_04_n, nif_rx_04_p,
        nif_rx_05_n, nif_rx_05_p, nif_rx_06_n, nif_rx_06_p,
        nif_rx_07_n, nif_rx_07_p, nif_rx_08_n, nif_rx_08_p,
        nif_rx_09_n, nif_rx_09_p, nif_rx_10_n, nif_rx_10_p,
        nif_rx_11_n, nif_rx_11_p, nif_rx_12_n, nif_rx_12_p,
        nif_rx_13_n, nif_rx_13_p, nif_rx_14_n, nif_rx_14_p,
        nif_rx_15_n, nif_rx_15_p, nif_srd_refclk_q00_n,
        nif_srd_refclk_q00_p, nif_srd_test_q00_n,
        nif_srd_test_q00_p, nif_tvdd1p0_q00_01_1,
        nif_tvdd1p0_q00_01_2, nif_tvdd1p0_q00_01_3,
        nif_tvdd1p0_q00_01_4, nif_tvdd1p0_q02_03_1,
        nif_tvdd1p0_q02_03_2, nif_tvdd1p0_q02_03_3,
        nif_tvdd1p0_q02_03_4, nif_tvdd1p25_q00_1,
        nif_tvdd1p25_q00_2, nif_tvdd1p25_q01_1,
        nif_tvdd1p25_q01_2, nif_tvdd1p25_q02_1,
        nif_tvdd1p25_q02_2, nif_tvdd1p25_q03_1,
        nif_tvdd1p25_q03_2, nif_tx_00_n, nif_tx_00_p,
        nif_tx_01_n, nif_tx_01_p, nif_tx_02_n, nif_tx_02_p,
        nif_tx_03_n, nif_tx_03_p, nif_tx_04_n, nif_tx_04_p,
        nif_tx_05_n, nif_tx_05_p, nif_tx_06_n, nif_tx_06_p,
        nif_tx_07_n, nif_tx_07_p, nif_tx_08_n, nif_tx_08_p,
        nif_tx_09_n, nif_tx_09_p, nif_tx_10_n, nif_tx_10_p,
        nif_tx_11_n, nif_tx_11_p, nif_tx_12_n, nif_tx_12_p,
        nif_tx_13_n, nif_tx_13_p, nif_tx_14_n, nif_tx_14_p,
        nif_tx_15_n, nif_tx_15_p, nife_lcpll0_agnd,
        nife_lcpll0_avdd1p8, nife_lcpll0_byp_clk,
        nife_lcpll0_refclk_n, nife_lcpll0_refclk_p,
        nife_lcpll0_testout_n, nife_lcpll0_testout_p,
        nife_lcpll1_agnd, nife_lcpll1_avdd1p8,
        nife_lcpll1_byp_clk, nife_lcpll1_refclk_n,
        nife_lcpll1_refclk_p, nife_lcpll1_testout_n,
        nife_lcpll1_testout_p, nife_pvdd1p0_q04,
        nife_pvdd1p0_q05, nife_pvdd1p0_q06, nife_pvdd1p0_q07,
        nife_pvdd1p0_q08, nife_pvdd1p0_q09, nife_pvdd1p0_q10,
        nife_pvdd1p0_q11, nife_rvdd1p0_q04_05_06_1,
        nife_rvdd1p0_q04_05_06_10, nife_rvdd1p0_q04_05_06_11,
        nife_rvdd1p0_q04_05_06_12, nife_rvdd1p0_q04_05_06_2,
        nife_rvdd1p0_q04_05_06_3, nife_rvdd1p0_q04_05_06_4,
        nife_rvdd1p0_q04_05_06_5, nife_rvdd1p0_q04_05_06_6,
        nife_rvdd1p0_q04_05_06_7, nife_rvdd1p0_q04_05_06_8,
        nife_rvdd1p0_q04_05_06_9, nife_rvdd1p0_q07_1,
        nife_rvdd1p0_q07_2, nife_rvdd1p0_q07_3,
        nife_rvdd1p0_q07_4, nife_rvdd1p0_q08_09_10_1,
        nife_rvdd1p0_q08_09_10_10, nife_rvdd1p0_q08_09_10_11,
        nife_rvdd1p0_q08_09_10_12, nife_rvdd1p0_q08_09_10_2,
        nife_rvdd1p0_q08_09_10_3, nife_rvdd1p0_q08_09_10_4,
        nife_rvdd1p0_q08_09_10_5, nife_rvdd1p0_q08_09_10_6,
        nife_rvdd1p0_q08_09_10_7, nife_rvdd1p0_q08_09_10_8,
        nife_rvdd1p0_q08_09_10_9, nife_rvdd1p0_q11_1,
        nife_rvdd1p0_q11_2, nife_rvdd1p0_q11_3,
        nife_rvdd1p0_q11_4, nife_rx_16_n, nife_rx_16_p,
        nife_rx_17_n, nife_rx_17_p, nife_rx_18_n, nife_rx_18_p,
        nife_rx_19_n, nife_rx_19_p, nife_rx_20_n, nife_rx_20_p,
        nife_rx_21_n, nife_rx_21_p, nife_rx_22_n, nife_rx_22_p,
        nife_rx_23_n, nife_rx_23_p, nife_rx_24_n, nife_rx_24_p,
        nife_rx_25_n, nife_rx_25_p, nife_rx_26_n, nife_rx_26_p,
        nife_rx_27_n, nife_rx_27_p, nife_rx_28_n, nife_rx_28_p,
        nife_rx_29_n, nife_rx_29_p, nife_rx_30_n, nife_rx_30_p,
        nife_rx_31_n, nife_rx_31_p, nife_rx_32_n, nife_rx_32_p,
        nife_rx_33_n, nife_rx_33_p, nife_rx_34_n, nife_rx_34_p,
        nife_rx_35_n, nife_rx_35_p, nife_rx_36_n, nife_rx_36_p,
        nife_rx_37_n, nife_rx_37_p, nife_rx_38_n, nife_rx_38_p,
        nife_rx_39_n, nife_rx_39_p, nife_rx_40_n, nife_rx_40_p,
        nife_rx_41_n, nife_rx_41_p, nife_rx_42_n, nife_rx_42_p,
        nife_rx_43_n, nife_rx_43_p, nife_rx_44_n, nife_rx_44_p,
        nife_rx_45_n, nife_rx_45_p, nife_rx_46_n, nife_rx_46_p,
        nife_rx_47_n, nife_rx_47_p, nife_srd_refclk_q05_n,
        nife_srd_refclk_q05_p, nife_srd_test_q05_n,
        nife_srd_test_q05_p, nife_srd_test_q10_n,
        nife_srd_test_q10_p, nife_tvdd1p0_q04_05_06_1,
        nife_tvdd1p0_q04_05_06_10, nife_tvdd1p0_q04_05_06_11,
        nife_tvdd1p0_q04_05_06_12, nife_tvdd1p0_q04_05_06_2,
        nife_tvdd1p0_q04_05_06_3, nife_tvdd1p0_q04_05_06_4,
        nife_tvdd1p0_q04_05_06_5, nife_tvdd1p0_q04_05_06_6,
        nife_tvdd1p0_q04_05_06_7, nife_tvdd1p0_q04_05_06_8,
        nife_tvdd1p0_q04_05_06_9, nife_tvdd1p0_q07_1,
        nife_tvdd1p0_q07_2, nife_tvdd1p0_q07_3,
        nife_tvdd1p0_q07_4, nife_tvdd1p0_q08_09_10_1,
        nife_tvdd1p0_q08_09_10_10, nife_tvdd1p0_q08_09_10_11,
        nife_tvdd1p0_q08_09_10_12, nife_tvdd1p0_q08_09_10_2,
        nife_tvdd1p0_q08_09_10_3, nife_tvdd1p0_q08_09_10_4,
        nife_tvdd1p0_q08_09_10_5, nife_tvdd1p0_q08_09_10_6,
        nife_tvdd1p0_q08_09_10_7, nife_tvdd1p0_q08_09_10_8,
        nife_tvdd1p0_q08_09_10_9, nife_tvdd1p0_q11_1,
        nife_tvdd1p0_q11_2, nife_tvdd1p0_q11_3,
        nife_tvdd1p0_q11_4, nife_tx_16_n, nife_tx_16_p,
        nife_tx_17_n, nife_tx_17_p, nife_tx_18_n, nife_tx_18_p,
        nife_tx_19_n, nife_tx_19_p, nife_tx_20_n, nife_tx_20_p,
        nife_tx_21_n, nife_tx_21_p, nife_tx_22_n, nife_tx_22_p,
        nife_tx_23_n, nife_tx_23_p, nife_tx_24_n, nife_tx_24_p,
        nife_tx_25_n, nife_tx_25_p, nife_tx_26_n, nife_tx_26_p,
        nife_tx_27_n, nife_tx_27_p, nife_tx_28_n, nife_tx_28_p,
        nife_tx_29_n, nife_tx_29_p, nife_tx_30_n, nife_tx_30_p,
        nife_tx_31_n, nife_tx_31_p, nife_tx_32_n, nife_tx_32_p,
        nife_tx_33_n, nife_tx_33_p, nife_tx_34_n, nife_tx_34_p,
        nife_tx_35_n, nife_tx_35_p, nife_tx_36_n, nife_tx_36_p,
        nife_tx_37_n, nife_tx_37_p, nife_tx_38_n, nife_tx_38_p,
        nife_tx_39_n, nife_tx_39_p, nife_tx_40_n, nife_tx_40_p,
        nife_tx_41_n, nife_tx_41_p, nife_tx_42_n, nife_tx_42_p,
        nife_tx_43_n, nife_tx_43_p, nife_tx_44_n, nife_tx_44_p,
        nife_tx_45_n, nife_tx_45_p, nife_tx_46_n, nife_tx_46_p,
        nife_tx_47_n, nife_tx_47_p, nse_sync_in0, nse_sync_in1,
        nse_sync_out, pcie_ptest_n, pcie_ptest_p, pcie_pvdd1p0,
        pcie_refclk_n, pcie_refclk_p, pcie_rvdd1p0_1,
        pcie_rvdd1p0_2, pcie_rx0_n, pcie_rx0_p, pcie_tvdd1p0_1,
        pcie_tvdd1p0_2, pcie_tx0_n, pcie_tx0_p,
        puc_00_core_pll_freq_0, puc_01_core_pll_freq_1,
        puc_02_core_pll_freq_2, puc_03_core_pll_freq_3, puc_04,
        puc_05_i2c_add_0, puc_06_i2c_add_1, puc_07_pcie_dis,
        puc_08, puc_09, puc_10, puc_11, pvtmon_a_aio, pvtmon_b_aio,
        res_cal0, res_cal1, rov_0, rov_1, rov_2, scan_mode, spi_clk,
        spi_miso, spi_mosi, spi_ssn, srd_agnd_1, srd_agnd_10,
        srd_agnd_100, srd_agnd_101, srd_agnd_102, srd_agnd_103,
        srd_agnd_104, srd_agnd_105, srd_agnd_106, srd_agnd_107,
        srd_agnd_108, srd_agnd_109, srd_agnd_11, srd_agnd_110,
        srd_agnd_111, srd_agnd_112, srd_agnd_113, srd_agnd_114,
        srd_agnd_115, srd_agnd_116, srd_agnd_117, srd_agnd_118,
        srd_agnd_119, srd_agnd_12, srd_agnd_120, srd_agnd_121,
        srd_agnd_122, srd_agnd_123, srd_agnd_124, srd_agnd_125,
        srd_agnd_126, srd_agnd_127, srd_agnd_128, srd_agnd_129,
        srd_agnd_13, srd_agnd_130, srd_agnd_131, srd_agnd_132,
        srd_agnd_133, srd_agnd_134, srd_agnd_135, srd_agnd_136,
        srd_agnd_137, srd_agnd_138, srd_agnd_139, srd_agnd_14,
        srd_agnd_140, srd_agnd_141, srd_agnd_142, srd_agnd_143,
        srd_agnd_144, srd_agnd_145, srd_agnd_146, srd_agnd_147,
        srd_agnd_148, srd_agnd_149, srd_agnd_15, srd_agnd_150,
        srd_agnd_151, srd_agnd_152, srd_agnd_153, srd_agnd_154,
        srd_agnd_155, srd_agnd_156, srd_agnd_157, srd_agnd_158,
        srd_agnd_159, srd_agnd_16, srd_agnd_160, srd_agnd_161,
        srd_agnd_162, srd_agnd_163, srd_agnd_164, srd_agnd_165,
        srd_agnd_166, srd_agnd_167, srd_agnd_168, srd_agnd_169,
        srd_agnd_17, srd_agnd_170, srd_agnd_171, srd_agnd_172,
        srd_agnd_173, srd_agnd_174, srd_agnd_175, srd_agnd_176,
        srd_agnd_177, srd_agnd_178, srd_agnd_179, srd_agnd_18,
        srd_agnd_180, srd_agnd_181, srd_agnd_182, srd_agnd_183,
        srd_agnd_184, srd_agnd_185, srd_agnd_186, srd_agnd_187,
        srd_agnd_188, srd_agnd_189, srd_agnd_19, srd_agnd_190,
        srd_agnd_191, srd_agnd_192, srd_agnd_193, srd_agnd_194,
        srd_agnd_195, srd_agnd_196, srd_agnd_197, srd_agnd_198,
        srd_agnd_199, srd_agnd_2, srd_agnd_20, srd_agnd_200,
        srd_agnd_201, srd_agnd_202, srd_agnd_203, srd_agnd_204,
        srd_agnd_205, srd_agnd_206, srd_agnd_207, srd_agnd_208,
        srd_agnd_209, srd_agnd_21, srd_agnd_210, srd_agnd_211,
        srd_agnd_212, srd_agnd_213, srd_agnd_214, srd_agnd_215,
        srd_agnd_216, srd_agnd_217, srd_agnd_218, srd_agnd_219,
        srd_agnd_22, srd_agnd_220, srd_agnd_221, srd_agnd_222,
        srd_agnd_223, srd_agnd_224, srd_agnd_225, srd_agnd_226,
        srd_agnd_227, srd_agnd_228, srd_agnd_229, srd_agnd_23,
        srd_agnd_230, srd_agnd_231, srd_agnd_232, srd_agnd_233,
        srd_agnd_234, srd_agnd_235, srd_agnd_236, srd_agnd_237,
        srd_agnd_238, srd_agnd_239, srd_agnd_24, srd_agnd_240,
        srd_agnd_241, srd_agnd_242, srd_agnd_243, srd_agnd_244,
        srd_agnd_245, srd_agnd_246, srd_agnd_247, srd_agnd_248,
        srd_agnd_249, srd_agnd_25, srd_agnd_250, srd_agnd_251,
        srd_agnd_252, srd_agnd_253, srd_agnd_254, srd_agnd_255,
        srd_agnd_256, srd_agnd_257, srd_agnd_258, srd_agnd_259,
        srd_agnd_26, srd_agnd_260, srd_agnd_261, srd_agnd_262,
        srd_agnd_263, srd_agnd_264, srd_agnd_265, srd_agnd_266,
        srd_agnd_267, srd_agnd_268, srd_agnd_269, srd_agnd_27,
        srd_agnd_270, srd_agnd_271, srd_agnd_28, srd_agnd_29,
        srd_agnd_3, srd_agnd_30, srd_agnd_31, srd_agnd_32,
        srd_agnd_33, srd_agnd_34, srd_agnd_35, srd_agnd_36,
        srd_agnd_37, srd_agnd_38, srd_agnd_39, srd_agnd_4,
        srd_agnd_40, srd_agnd_41, srd_agnd_42, srd_agnd_43,
        srd_agnd_44, srd_agnd_45, srd_agnd_46, srd_agnd_47,
        srd_agnd_48, srd_agnd_49, srd_agnd_5, srd_agnd_50,
        srd_agnd_51, srd_agnd_52, srd_agnd_53, srd_agnd_54,
        srd_agnd_55, srd_agnd_56, srd_agnd_57, srd_agnd_58,
        srd_agnd_59, srd_agnd_6, srd_agnd_60, srd_agnd_61,
        srd_agnd_62, srd_agnd_63, srd_agnd_64, srd_agnd_65,
        srd_agnd_66, srd_agnd_67, srd_agnd_68, srd_agnd_69,
        srd_agnd_7, srd_agnd_70, srd_agnd_71, srd_agnd_72,
        srd_agnd_73, srd_agnd_74, srd_agnd_75, srd_agnd_76,
        srd_agnd_77, srd_agnd_78, srd_agnd_79, srd_agnd_8,
        srd_agnd_80, srd_agnd_81, srd_agnd_82, srd_agnd_83,
        srd_agnd_84, srd_agnd_85, srd_agnd_86, srd_agnd_87,
        srd_agnd_88, srd_agnd_89, srd_agnd_9, srd_agnd_90,
        srd_agnd_91, srd_agnd_92, srd_agnd_93, srd_agnd_94,
        srd_agnd_95, srd_agnd_96, srd_agnd_97, srd_agnd_98,
        srd_agnd_99, srd_refclk_out_0, srd_refclk_out_1,
        srd_refclk_out_2, srd_refclk_out_3, synce_0_pll_agnd,
        synce_0_pll_avdd1p8, synce_0_pll_testout_n,
        synce_0_pll_testout_p, synce_1_pll_agnd,
        synce_1_pll_avdd1p8, sys_rst_n, test_0, test_1, test_2,
        test_3, test_4, therm_diode_n, therm_diode_p,
        therm_diode_vdd3p3, ts_bit_clk0, ts_bit_clk1,
        ts_pll_refclk_n, ts_pll_refclk_p, ts_pll_testout_n,
        ts_pll_testout_p, ts_sync0, ts_sync1, ts_time_val0,
        ts_time_val1, uart0_rx, uart0_tx, uart1_rx, uart1_tx,
        uc_pll_agnd, uc_pll_avdd1p8, uc_pll_byp_clk0,
        uc_pll_byp_clk1, uc_pll_lock, uc_pll_refclk_n,
        uc_pll_refclk_p, uc_pll_testout_n, uc_pll_testout_p,
        vddc_1, vddc_10, vddc_11, vddc_12, vddc_13, vddc_14,
        vddc_15, vddc_16, vddc_17, vddc_18, vddc_19, vddc_2,
        vddc_20, vddc_21, vddc_22, vddc_23, vddc_24, vddc_25,
        vddc_26, vddc_27, vddc_28, vddc_29, vddc_3, vddc_30,
        vddc_31, vddc_32, vddc_33, vddc_34, vddc_35, vddc_36,
        vddc_37, vddc_38, vddc_39, vddc_4, vddc_40, vddc_41,
        vddc_42, vddc_43, vddc_44, vddc_45, vddc_46, vddc_47,
        vddc_48, vddc_49, vddc_5, vddc_50, vddc_51, vddc_52,
        vddc_53, vddc_54, vddc_55, vddc_56, vddc_57, vddc_58,
        vddc_59, vddc_6, vddc_60, vddc_61, vddc_62, vddc_63,
        vddc_64, vddc_65, vddc_66, vddc_67, vddc_68, vddc_69,
        vddc_7, vddc_70, vddc_71, vddc_72, vddc_73, vddc_74,
        vddc_75, vddc_76, vddc_77, vddc_78, vddc_79, vddc_8,
        vddc_80, vddc_81, vddc_82, vddc_83, vddc_84, vddc_85,
        vddc_86, vddc_87, vddc_88, vddc_9, vddc_sense, vss_1,
        vss_10, vss_100, vss_101, vss_102, vss_103, vss_104,
        vss_105, vss_106, vss_107, vss_108, vss_109, vss_11,
        vss_110, vss_111, vss_112, vss_113, vss_114, vss_115,
        vss_116, vss_117, vss_118, vss_119, vss_12, vss_120,
        vss_121, vss_122, vss_123, vss_124, vss_125, vss_126,
        vss_127, vss_128, vss_129, vss_13, vss_130, vss_131,
        vss_132, vss_133, vss_134, vss_135, vss_136, vss_137,
        vss_138, vss_139, vss_14, vss_140, vss_141, vss_142,
        vss_143, vss_144, vss_145, vss_146, vss_147, vss_148,
        vss_149, vss_15, vss_150, vss_151, vss_152, vss_153,
        vss_154, vss_155, vss_156, vss_157, vss_158, vss_159,
        vss_16, vss_160, vss_161, vss_162, vss_163, vss_164,
        vss_165, vss_166, vss_167, vss_168, vss_169, vss_17,
        vss_170, vss_171, vss_172, vss_173, vss_174, vss_175,
        vss_176, vss_177, vss_178, vss_179, vss_18, vss_180,
        vss_181, vss_182, vss_183, vss_184, vss_185, vss_186,
        vss_187, vss_188, vss_19, vss_2, vss_20, vss_21, vss_22,
        vss_23, vss_24, vss_25, vss_26, vss_27, vss_28, vss_29,
        vss_3, vss_30, vss_31, vss_32, vss_33, vss_34, vss_35,
        vss_36, vss_37, vss_38, vss_39, vss_4, vss_40, vss_41,
        vss_42, vss_43, vss_44, vss_45, vss_46, vss_47, vss_48,
        vss_49, vss_5, vss_50, vss_51, vss_52, vss_53, vss_54,
        vss_55, vss_56, vss_57, vss_58, vss_59, vss_6, vss_60,
        vss_61, vss_62, vss_63, vss_64, vss_65, vss_66, vss_67,
        vss_68, vss_69, vss_7, vss_70, vss_71, vss_72, vss_73,
        vss_74, vss_75, vss_76, vss_77, vss_78, vss_79, vss_8,
        vss_80, vss_81, vss_82, vss_83, vss_84, vss_85, vss_86,
        vss_87, vss_88, vss_89, vss_9, vss_90, vss_91, vss_92,
        vss_93, vss_94, vss_95, vss_96, vss_97, vss_98, vss_99,
        vss_sense);
    output bs_pll0_testout_n;
    output bs_pll0_testout_p;
    output bs_pll1_testout_n;
    output bs_pll1_testout_p;
    input bs_pll_avdd1p8;
    input c_pll_agnd;
    input c_pll_avdd1p8;
    input c_pll_byp_clk0;
    input c_pll_byp_clk1;
    input c_pll_bypass;
    output c_pll_lock;
    input c_pll_refclk_n;
    input c_pll_refclk_p;
    output c_pll_testout_n;
    output c_pll_testout_p;
    input clock25;
    input ddr_vddo_1;
    input ddr_vddo_10;
    input ddr_vddo_11;
    input ddr_vddo_12;
    input ddr_vddo_13;
    input ddr_vddo_14;
    input ddr_vddo_15;
    input ddr_vddo_16;
    input ddr_vddo_17;
    input ddr_vddo_18;
    input ddr_vddo_19;
    input ddr_vddo_2;
    input ddr_vddo_20;
    input ddr_vddo_21;
    input ddr_vddo_22;
    input ddr_vddo_23;
    input ddr_vddo_24;
    input ddr_vddo_25;
    input ddr_vddo_26;
    input ddr_vddo_27;
    input ddr_vddo_28;
    input ddr_vddo_29;
    input ddr_vddo_3;
    input ddr_vddo_30;
    input ddr_vddo_31;
    input ddr_vddo_32;
    input ddr_vddo_33;
    input ddr_vddo_34;
    input ddr_vddo_35;
    input ddr_vddo_36;
    input ddr_vddo_37;
    input ddr_vddo_38;
    input ddr_vddo_39;
    input ddr_vddo_4;
    input ddr_vddo_40;
    input ddr_vddo_41;
    input ddr_vddo_42;
    input ddr_vddo_43;
    input ddr_vddo_44;
    input ddr_vddo_45;
    input ddr_vddo_46;
    input ddr_vddo_47;
    input ddr_vddo_48;
    input ddr_vddo_49;
    input ddr_vddo_5;
    input ddr_vddo_50;
    input ddr_vddo_51;
    input ddr_vddo_52;
    input ddr_vddo_53;
    input ddr_vddo_54;
    input ddr_vddo_55;
    input ddr_vddo_56;
    input ddr_vddo_57;
    input ddr_vddo_58;
    input ddr_vddo_59;
    input ddr_vddo_6;
    input ddr_vddo_60;
    input ddr_vddo_61;
    input ddr_vddo_7;
    input ddr_vddo_8;
    input ddr_vddo_9;
    output ddra_a0_a7a8;
    output ddra_a10;
    output ddra_a11;
    output ddra_a12;
    output ddra_a13;
    output ddra_a1_a1a9;
    output ddra_a2_a0a10;
    output ddra_a3_a6a11;
    output ddra_a3ba3;
    output ddra_a4_a13a12;
    output ddra_a5_a14a15;
    output ddra_a6;
    output ddra_a7;
    output ddra_a8;
    output ddra_a9;
    output ddra_act_abi_n;
    input ddra_alert_n_0;
    input ddra_alert_n_1;
    output ddra_aux_0;
    output ddra_aux_1;
    input ddra_avdd1p8;
    input ddra_avss;
    output ddra_ba0_a2ba0;
    output ddra_ba1_a5ba1;
    output ddra_bg0_a4ba2;
    output ddra_cas_n;
    output ddra_ck_n;
    output ddra_ck_p;
    output ddra_cke;
    output ddra_cs_n_0;
    output ddra_cs_n_1;
    inout ddra_dbi_n_0;
    inout ddra_dbi_n_1;
    inout ddra_dbi_n_2;
    inout ddra_dbi_n_3;
    inout ddra_dq_0;
    inout ddra_dq_1;
    inout ddra_dq_10;
    inout ddra_dq_11;
    inout ddra_dq_12;
    inout ddra_dq_13;
    inout ddra_dq_14;
    inout ddra_dq_15;
    inout ddra_dq_16;
    inout ddra_dq_17;
    inout ddra_dq_18;
    inout ddra_dq_19;
    inout ddra_dq_2;
    inout ddra_dq_20;
    inout ddra_dq_21;
    inout ddra_dq_22;
    inout ddra_dq_23;
    inout ddra_dq_24;
    inout ddra_dq_25;
    inout ddra_dq_26;
    inout ddra_dq_27;
    inout ddra_dq_28;
    inout ddra_dq_29;
    inout ddra_dq_3;
    inout ddra_dq_30;
    inout ddra_dq_31;
    inout ddra_dq_4;
    inout ddra_dq_5;
    inout ddra_dq_6;
    inout ddra_dq_7;
    inout ddra_dq_8;
    inout ddra_dq_9;
    inout ddra_dqs0_wck01_n;
    inout ddra_dqs0_wck01_p;
    inout ddra_dqs1_n;
    inout ddra_dqs1_p;
    inout ddra_dqs2_wck23_n;
    inout ddra_dqs2_wck23_p;
    inout ddra_dqs3_n;
    inout ddra_dqs3_p;
    input ddra_edc_0;
    input ddra_edc_1;
    input ddra_edc_2;
    input ddra_edc_3;
    output ddra_odt;
    output ddra_par;
    output ddra_pll_clk_mon;
    output ddra_ras_n;
    input ddra_refclk_n;
    input ddra_refclk_p;
    inout ddra_res_neg;
    inout ddra_res_pos;
    inout ddra_res_vdd;
    inout ddra_res_vss;
    output ddra_reset_n;
    input ddra_v_analog1p8_1;
    input ddra_v_analog1p8_2;
    input ddra_vddc_1;
    input ddra_vddc_2;
    input ddra_vddc_3;
    output ddra_vref_mon;
    output ddra_we_n;
    output ddrb_a0_a7a8;
    output ddrb_a10;
    output ddrb_a11;
    output ddrb_a12;
    output ddrb_a13;
    output ddrb_a1_a1a9;
    output ddrb_a2_a0a10;
    output ddrb_a3_a6a11;
    output ddrb_a3ba3;
    output ddrb_a4_a13a12;
    output ddrb_a5_a14a15;
    output ddrb_a6;
    output ddrb_a7;
    output ddrb_a8;
    output ddrb_a9;
    output ddrb_act_abi_n;
    input ddrb_alert_n_0;
    input ddrb_alert_n_1;
    output ddrb_aux_0;
    output ddrb_aux_1;
    input ddrb_avdd1p8;
    input ddrb_avss;
    output ddrb_ba0_a2ba0;
    output ddrb_ba1_a5ba1;
    output ddrb_bg0_a4ba2;
    output ddrb_cas_n;
    output ddrb_ck_n;
    output ddrb_ck_p;
    output ddrb_cke;
    output ddrb_cs_n_0;
    output ddrb_cs_n_1;
    inout ddrb_dbi_n_0;
    inout ddrb_dbi_n_1;
    inout ddrb_dbi_n_2;
    inout ddrb_dbi_n_3;
    inout ddrb_dq_0;
    inout ddrb_dq_1;
    inout ddrb_dq_10;
    inout ddrb_dq_11;
    inout ddrb_dq_12;
    inout ddrb_dq_13;
    inout ddrb_dq_14;
    inout ddrb_dq_15;
    inout ddrb_dq_16;
    inout ddrb_dq_17;
    inout ddrb_dq_18;
    inout ddrb_dq_19;
    inout ddrb_dq_2;
    inout ddrb_dq_20;
    inout ddrb_dq_21;
    inout ddrb_dq_22;
    inout ddrb_dq_23;
    inout ddrb_dq_24;
    inout ddrb_dq_25;
    inout ddrb_dq_26;
    inout ddrb_dq_27;
    inout ddrb_dq_28;
    inout ddrb_dq_29;
    inout ddrb_dq_3;
    inout ddrb_dq_30;
    inout ddrb_dq_31;
    inout ddrb_dq_4;
    inout ddrb_dq_5;
    inout ddrb_dq_6;
    inout ddrb_dq_7;
    inout ddrb_dq_8;
    inout ddrb_dq_9;
    inout ddrb_dqs0_wck01_n;
    inout ddrb_dqs0_wck01_p;
    inout ddrb_dqs1_n;
    inout ddrb_dqs1_p;
    inout ddrb_dqs2_wck23_n;
    inout ddrb_dqs2_wck23_p;
    inout ddrb_dqs3_n;
    inout ddrb_dqs3_p;
    input ddrb_edc_0;
    input ddrb_edc_1;
    input ddrb_edc_2;
    input ddrb_edc_3;
    output ddrb_odt;
    output ddrb_par;
    output ddrb_ras_n;
    input ddrb_refclk_n;
    input ddrb_refclk_p;
    output ddrb_reset_n;
    input ddrb_v_analog1p8_1;
    input ddrb_v_analog1p8_2;
    input ddrb_vddc_1;
    input ddrb_vddc_2;
    input ddrb_vddc_3;
    output ddrb_we_n;
    output ddrc_a0_a7a8;
    output ddrc_a10;
    output ddrc_a11;
    output ddrc_a12;
    output ddrc_a13;
    output ddrc_a1_a1a9;
    output ddrc_a2_a0a10;
    output ddrc_a3_a6a11;
    output ddrc_a3ba3;
    output ddrc_a4_a13a12;
    output ddrc_a5_a14a15;
    output ddrc_a6;
    output ddrc_a7;
    output ddrc_a8;
    output ddrc_a9;
    output ddrc_act_abi_n;
    input ddrc_alert_n_0;
    input ddrc_alert_n_1;
    output ddrc_aux_0;
    output ddrc_aux_1;
    input ddrc_avdd1p8;
    input ddrc_avss;
    output ddrc_ba0_a2ba0;
    output ddrc_ba1_a5ba1;
    output ddrc_bg0_a4ba2;
    output ddrc_cas_n;
    output ddrc_ck_n;
    output ddrc_ck_p;
    output ddrc_cke;
    output ddrc_cs_n_0;
    output ddrc_cs_n_1;
    inout ddrc_dbi_n_0;
    inout ddrc_dbi_n_1;
    inout ddrc_dbi_n_2;
    inout ddrc_dbi_n_3;
    inout ddrc_dq_0;
    inout ddrc_dq_1;
    inout ddrc_dq_10;
    inout ddrc_dq_11;
    inout ddrc_dq_12;
    inout ddrc_dq_13;
    inout ddrc_dq_14;
    inout ddrc_dq_15;
    inout ddrc_dq_16;
    inout ddrc_dq_17;
    inout ddrc_dq_18;
    inout ddrc_dq_19;
    inout ddrc_dq_2;
    inout ddrc_dq_20;
    inout ddrc_dq_21;
    inout ddrc_dq_22;
    inout ddrc_dq_23;
    inout ddrc_dq_24;
    inout ddrc_dq_25;
    inout ddrc_dq_26;
    inout ddrc_dq_27;
    inout ddrc_dq_28;
    inout ddrc_dq_29;
    inout ddrc_dq_3;
    inout ddrc_dq_30;
    inout ddrc_dq_31;
    inout ddrc_dq_4;
    inout ddrc_dq_5;
    inout ddrc_dq_6;
    inout ddrc_dq_7;
    inout ddrc_dq_8;
    inout ddrc_dq_9;
    inout ddrc_dqs0_wck01_n;
    inout ddrc_dqs0_wck01_p;
    inout ddrc_dqs1_n;
    inout ddrc_dqs1_p;
    inout ddrc_dqs2_wck23_n;
    inout ddrc_dqs2_wck23_p;
    inout ddrc_dqs3_n;
    inout ddrc_dqs3_p;
    input ddrc_edc_0;
    input ddrc_edc_1;
    input ddrc_edc_2;
    input ddrc_edc_3;
    output ddrc_odt;
    output ddrc_par;
    output ddrc_ras_n;
    input ddrc_refclk_n;
    input ddrc_refclk_p;
    inout ddrc_res_neg;
    inout ddrc_res_pos;
    inout ddrc_res_vdd;
    inout ddrc_res_vss;
    output ddrc_reset_n;
    input ddrc_v_analog1p8_1;
    input ddrc_v_analog1p8_2;
    input ddrc_vddc_1;
    input ddrc_vddc_2;
    input ddrc_vddc_3;
    output ddrc_we_n;
    input disconnect;
    input fc_rx_clk;
    input fc_rx_stat_0;
    input fc_rx_stat_1;
    input fc_synce_vddo_1;
    input fc_synce_vddo_2;
    input fc_synce_vddp;
    output fc_tx_clk;
    output fc_tx_stat_0;
    output fc_tx_stat_1;
    input ftest_0;
    input ftest_1;
    input ftest_2;
    inout gpio0;
    inout gpio1;
    inout i2c_scl;
    inout i2c_sda;
    output int_n;
    input io_vddo_3p3_1;
    input io_vddo_3p3_2;
    input io_vddo_3p3_3;
    input io_vddo_3p3_4;
    input io_vddo_3p3_5;
    input io_vddo_3p3_6;
    input io_vddp_1p8_1;
    input io_vddp_1p8_2;
    input jtag_tce;
    input jtag_tck;
    input jtag_tdi;
    output jtag_tdo;
    input jtag_tms;
    input jtag_trst_n;
    output led_clk;
    output led_data;
    output mdc_0;
    output mdc_1;
    output mdc_2;
    output mdc_3;
    inout mdio_0;
    inout mdio_1;
    inout mdio_2;
    inout mdio_3;
    inout nc_ochk;
    input nif_lcpll_agnd;
    input nif_lcpll_avdd1p8;
    input nif_lcpll_byp_clk;
    input nif_lcpll_refclk_n;
    input nif_lcpll_refclk_p;
    output nif_lcpll_testout_n;
    output nif_lcpll_testout_p;
    input nif_pvdd1p0_q00;
    input nif_pvdd1p0_q01;
    input nif_pvdd1p0_q02;
    input nif_pvdd1p0_q03;
    input nif_rvdd1p0_q00_01_1;
    input nif_rvdd1p0_q00_01_2;
    input nif_rvdd1p0_q00_01_3;
    input nif_rvdd1p0_q00_01_4;
    input nif_rvdd1p0_q00_01_5;
    input nif_rvdd1p0_q00_01_6;
    input nif_rvdd1p0_q00_01_7;
    input nif_rvdd1p0_q00_01_8;
    input nif_rvdd1p0_q02_03_1;
    input nif_rvdd1p0_q02_03_2;
    input nif_rvdd1p0_q02_03_3;
    input nif_rvdd1p0_q02_03_4;
    input nif_rvdd1p0_q02_03_5;
    input nif_rvdd1p0_q02_03_6;
    input nif_rvdd1p0_q02_03_7;
    input nif_rvdd1p0_q02_03_8;
    input nif_rx_00_n;
    input nif_rx_00_p;
    input nif_rx_01_n;
    input nif_rx_01_p;
    input nif_rx_02_n;
    input nif_rx_02_p;
    input nif_rx_03_n;
    input nif_rx_03_p;
    input nif_rx_04_n;
    input nif_rx_04_p;
    input nif_rx_05_n;
    input nif_rx_05_p;
    input nif_rx_06_n;
    input nif_rx_06_p;
    input nif_rx_07_n;
    input nif_rx_07_p;
    input nif_rx_08_n;
    input nif_rx_08_p;
    input nif_rx_09_n;
    input nif_rx_09_p;
    input nif_rx_10_n;
    input nif_rx_10_p;
    input nif_rx_11_n;
    input nif_rx_11_p;
    input nif_rx_12_n;
    input nif_rx_12_p;
    input nif_rx_13_n;
    input nif_rx_13_p;
    input nif_rx_14_n;
    input nif_rx_14_p;
    input nif_rx_15_n;
    input nif_rx_15_p;
    input nif_srd_refclk_q00_n;
    input nif_srd_refclk_q00_p;
    output nif_srd_test_q00_n;
    output nif_srd_test_q00_p;
    input nif_tvdd1p0_q00_01_1;
    input nif_tvdd1p0_q00_01_2;
    input nif_tvdd1p0_q00_01_3;
    input nif_tvdd1p0_q00_01_4;
    input nif_tvdd1p0_q02_03_1;
    input nif_tvdd1p0_q02_03_2;
    input nif_tvdd1p0_q02_03_3;
    input nif_tvdd1p0_q02_03_4;
    input nif_tvdd1p25_q00_1;
    input nif_tvdd1p25_q00_2;
    input nif_tvdd1p25_q01_1;
    input nif_tvdd1p25_q01_2;
    input nif_tvdd1p25_q02_1;
    input nif_tvdd1p25_q02_2;
    input nif_tvdd1p25_q03_1;
    input nif_tvdd1p25_q03_2;
    output nif_tx_00_n;
    output nif_tx_00_p;
    output nif_tx_01_n;
    output nif_tx_01_p;
    output nif_tx_02_n;
    output nif_tx_02_p;
    output nif_tx_03_n;
    output nif_tx_03_p;
    output nif_tx_04_n;
    output nif_tx_04_p;
    output nif_tx_05_n;
    output nif_tx_05_p;
    output nif_tx_06_n;
    output nif_tx_06_p;
    output nif_tx_07_n;
    output nif_tx_07_p;
    output nif_tx_08_n;
    output nif_tx_08_p;
    output nif_tx_09_n;
    output nif_tx_09_p;
    output nif_tx_10_n;
    output nif_tx_10_p;
    output nif_tx_11_n;
    output nif_tx_11_p;
    output nif_tx_12_n;
    output nif_tx_12_p;
    output nif_tx_13_n;
    output nif_tx_13_p;
    output nif_tx_14_n;
    output nif_tx_14_p;
    output nif_tx_15_n;
    output nif_tx_15_p;
    input nife_lcpll0_agnd;
    input nife_lcpll0_avdd1p8;
    input nife_lcpll0_byp_clk;
    input nife_lcpll0_refclk_n;
    input nife_lcpll0_refclk_p;
    output nife_lcpll0_testout_n;
    output nife_lcpll0_testout_p;
    input nife_lcpll1_agnd;
    input nife_lcpll1_avdd1p8;
    input nife_lcpll1_byp_clk;
    input nife_lcpll1_refclk_n;
    input nife_lcpll1_refclk_p;
    output nife_lcpll1_testout_n;
    output nife_lcpll1_testout_p;
    input nife_pvdd1p0_q04;
    input nife_pvdd1p0_q05;
    input nife_pvdd1p0_q06;
    input nife_pvdd1p0_q07;
    input nife_pvdd1p0_q08;
    input nife_pvdd1p0_q09;
    input nife_pvdd1p0_q10;
    input nife_pvdd1p0_q11;
    input nife_rvdd1p0_q04_05_06_1;
    input nife_rvdd1p0_q04_05_06_10;
    input nife_rvdd1p0_q04_05_06_11;
    input nife_rvdd1p0_q04_05_06_12;
    input nife_rvdd1p0_q04_05_06_2;
    input nife_rvdd1p0_q04_05_06_3;
    input nife_rvdd1p0_q04_05_06_4;
    input nife_rvdd1p0_q04_05_06_5;
    input nife_rvdd1p0_q04_05_06_6;
    input nife_rvdd1p0_q04_05_06_7;
    input nife_rvdd1p0_q04_05_06_8;
    input nife_rvdd1p0_q04_05_06_9;
    input nife_rvdd1p0_q07_1;
    input nife_rvdd1p0_q07_2;
    input nife_rvdd1p0_q07_3;
    input nife_rvdd1p0_q07_4;
    input nife_rvdd1p0_q08_09_10_1;
    input nife_rvdd1p0_q08_09_10_10;
    input nife_rvdd1p0_q08_09_10_11;
    input nife_rvdd1p0_q08_09_10_12;
    input nife_rvdd1p0_q08_09_10_2;
    input nife_rvdd1p0_q08_09_10_3;
    input nife_rvdd1p0_q08_09_10_4;
    input nife_rvdd1p0_q08_09_10_5;
    input nife_rvdd1p0_q08_09_10_6;
    input nife_rvdd1p0_q08_09_10_7;
    input nife_rvdd1p0_q08_09_10_8;
    input nife_rvdd1p0_q08_09_10_9;
    input nife_rvdd1p0_q11_1;
    input nife_rvdd1p0_q11_2;
    input nife_rvdd1p0_q11_3;
    input nife_rvdd1p0_q11_4;
    input nife_rx_16_n;
    input nife_rx_16_p;
    input nife_rx_17_n;
    input nife_rx_17_p;
    input nife_rx_18_n;
    input nife_rx_18_p;
    input nife_rx_19_n;
    input nife_rx_19_p;
    input nife_rx_20_n;
    input nife_rx_20_p;
    input nife_rx_21_n;
    input nife_rx_21_p;
    input nife_rx_22_n;
    input nife_rx_22_p;
    input nife_rx_23_n;
    input nife_rx_23_p;
    input nife_rx_24_n;
    input nife_rx_24_p;
    input nife_rx_25_n;
    input nife_rx_25_p;
    input nife_rx_26_n;
    input nife_rx_26_p;
    input nife_rx_27_n;
    input nife_rx_27_p;
    input nife_rx_28_n;
    input nife_rx_28_p;
    input nife_rx_29_n;
    input nife_rx_29_p;
    input nife_rx_30_n;
    input nife_rx_30_p;
    input nife_rx_31_n;
    input nife_rx_31_p;
    input nife_rx_32_n;
    input nife_rx_32_p;
    input nife_rx_33_n;
    input nife_rx_33_p;
    input nife_rx_34_n;
    input nife_rx_34_p;
    input nife_rx_35_n;
    input nife_rx_35_p;
    input nife_rx_36_n;
    input nife_rx_36_p;
    input nife_rx_37_n;
    input nife_rx_37_p;
    input nife_rx_38_n;
    input nife_rx_38_p;
    input nife_rx_39_n;
    input nife_rx_39_p;
    input nife_rx_40_n;
    input nife_rx_40_p;
    input nife_rx_41_n;
    input nife_rx_41_p;
    input nife_rx_42_n;
    input nife_rx_42_p;
    input nife_rx_43_n;
    input nife_rx_43_p;
    input nife_rx_44_n;
    input nife_rx_44_p;
    input nife_rx_45_n;
    input nife_rx_45_p;
    input nife_rx_46_n;
    input nife_rx_46_p;
    input nife_rx_47_n;
    input nife_rx_47_p;
    input nife_srd_refclk_q05_n;
    input nife_srd_refclk_q05_p;
    output nife_srd_test_q05_n;
    output nife_srd_test_q05_p;
    output nife_srd_test_q10_n;
    output nife_srd_test_q10_p;
    input nife_tvdd1p0_q04_05_06_1;
    input nife_tvdd1p0_q04_05_06_10;
    input nife_tvdd1p0_q04_05_06_11;
    input nife_tvdd1p0_q04_05_06_12;
    input nife_tvdd1p0_q04_05_06_2;
    input nife_tvdd1p0_q04_05_06_3;
    input nife_tvdd1p0_q04_05_06_4;
    input nife_tvdd1p0_q04_05_06_5;
    input nife_tvdd1p0_q04_05_06_6;
    input nife_tvdd1p0_q04_05_06_7;
    input nife_tvdd1p0_q04_05_06_8;
    input nife_tvdd1p0_q04_05_06_9;
    input nife_tvdd1p0_q07_1;
    input nife_tvdd1p0_q07_2;
    input nife_tvdd1p0_q07_3;
    input nife_tvdd1p0_q07_4;
    input nife_tvdd1p0_q08_09_10_1;
    input nife_tvdd1p0_q08_09_10_10;
    input nife_tvdd1p0_q08_09_10_11;
    input nife_tvdd1p0_q08_09_10_12;
    input nife_tvdd1p0_q08_09_10_2;
    input nife_tvdd1p0_q08_09_10_3;
    input nife_tvdd1p0_q08_09_10_4;
    input nife_tvdd1p0_q08_09_10_5;
    input nife_tvdd1p0_q08_09_10_6;
    input nife_tvdd1p0_q08_09_10_7;
    input nife_tvdd1p0_q08_09_10_8;
    input nife_tvdd1p0_q08_09_10_9;
    input nife_tvdd1p0_q11_1;
    input nife_tvdd1p0_q11_2;
    input nife_tvdd1p0_q11_3;
    input nife_tvdd1p0_q11_4;
    output nife_tx_16_n;
    output nife_tx_16_p;
    output nife_tx_17_n;
    output nife_tx_17_p;
    output nife_tx_18_n;
    output nife_tx_18_p;
    output nife_tx_19_n;
    output nife_tx_19_p;
    output nife_tx_20_n;
    output nife_tx_20_p;
    output nife_tx_21_n;
    output nife_tx_21_p;
    output nife_tx_22_n;
    output nife_tx_22_p;
    output nife_tx_23_n;
    output nife_tx_23_p;
    output nife_tx_24_n;
    output nife_tx_24_p;
    output nife_tx_25_n;
    output nife_tx_25_p;
    output nife_tx_26_n;
    output nife_tx_26_p;
    output nife_tx_27_n;
    output nife_tx_27_p;
    output nife_tx_28_n;
    output nife_tx_28_p;
    output nife_tx_29_n;
    output nife_tx_29_p;
    output nife_tx_30_n;
    output nife_tx_30_p;
    output nife_tx_31_n;
    output nife_tx_31_p;
    output nife_tx_32_n;
    output nife_tx_32_p;
    output nife_tx_33_n;
    output nife_tx_33_p;
    output nife_tx_34_n;
    output nife_tx_34_p;
    output nife_tx_35_n;
    output nife_tx_35_p;
    output nife_tx_36_n;
    output nife_tx_36_p;
    output nife_tx_37_n;
    output nife_tx_37_p;
    output nife_tx_38_n;
    output nife_tx_38_p;
    output nife_tx_39_n;
    output nife_tx_39_p;
    output nife_tx_40_n;
    output nife_tx_40_p;
    output nife_tx_41_n;
    output nife_tx_41_p;
    output nife_tx_42_n;
    output nife_tx_42_p;
    output nife_tx_43_n;
    output nife_tx_43_p;
    output nife_tx_44_n;
    output nife_tx_44_p;
    output nife_tx_45_n;
    output nife_tx_45_p;
    output nife_tx_46_n;
    output nife_tx_46_p;
    output nife_tx_47_n;
    output nife_tx_47_p;
    input nse_sync_in0;
    input nse_sync_in1;
    output nse_sync_out;
    output pcie_ptest_n;
    output pcie_ptest_p;
    input pcie_pvdd1p0;
    input pcie_refclk_n;
    input pcie_refclk_p;
    input pcie_rvdd1p0_1;
    input pcie_rvdd1p0_2;
    input pcie_rx0_n;
    input pcie_rx0_p;
    input pcie_tvdd1p0_1;
    input pcie_tvdd1p0_2;
    output pcie_tx0_n;
    output pcie_tx0_p;
    input puc_00_core_pll_freq_0;
    input puc_01_core_pll_freq_1;
    input puc_02_core_pll_freq_2;
    input puc_03_core_pll_freq_3;
    input puc_04;
    input puc_05_i2c_add_0;
    input puc_06_i2c_add_1;
    input puc_07_pcie_dis;
    input puc_08;
    input puc_09;
    input puc_10;
    input puc_11;
    inout pvtmon_a_aio;
    inout pvtmon_b_aio;
    inout res_cal0;
    inout res_cal1;
    output rov_0;
    output rov_1;
    output rov_2;
    input scan_mode;
    output spi_clk;
    input spi_miso;
    output spi_mosi;
    output spi_ssn;
    input srd_agnd_1;
    input srd_agnd_10;
    input srd_agnd_100;
    input srd_agnd_101;
    input srd_agnd_102;
    input srd_agnd_103;
    input srd_agnd_104;
    input srd_agnd_105;
    input srd_agnd_106;
    input srd_agnd_107;
    input srd_agnd_108;
    input srd_agnd_109;
    input srd_agnd_11;
    input srd_agnd_110;
    input srd_agnd_111;
    input srd_agnd_112;
    input srd_agnd_113;
    input srd_agnd_114;
    input srd_agnd_115;
    input srd_agnd_116;
    input srd_agnd_117;
    input srd_agnd_118;
    input srd_agnd_119;
    input srd_agnd_12;
    input srd_agnd_120;
    input srd_agnd_121;
    input srd_agnd_122;
    input srd_agnd_123;
    input srd_agnd_124;
    input srd_agnd_125;
    input srd_agnd_126;
    input srd_agnd_127;
    input srd_agnd_128;
    input srd_agnd_129;
    input srd_agnd_13;
    input srd_agnd_130;
    input srd_agnd_131;
    input srd_agnd_132;
    input srd_agnd_133;
    input srd_agnd_134;
    input srd_agnd_135;
    input srd_agnd_136;
    input srd_agnd_137;
    input srd_agnd_138;
    input srd_agnd_139;
    input srd_agnd_14;
    input srd_agnd_140;
    input srd_agnd_141;
    input srd_agnd_142;
    input srd_agnd_143;
    input srd_agnd_144;
    input srd_agnd_145;
    input srd_agnd_146;
    input srd_agnd_147;
    input srd_agnd_148;
    input srd_agnd_149;
    input srd_agnd_15;
    input srd_agnd_150;
    input srd_agnd_151;
    input srd_agnd_152;
    input srd_agnd_153;
    input srd_agnd_154;
    input srd_agnd_155;
    input srd_agnd_156;
    input srd_agnd_157;
    input srd_agnd_158;
    input srd_agnd_159;
    input srd_agnd_16;
    input srd_agnd_160;
    input srd_agnd_161;
    input srd_agnd_162;
    input srd_agnd_163;
    input srd_agnd_164;
    input srd_agnd_165;
    input srd_agnd_166;
    input srd_agnd_167;
    input srd_agnd_168;
    input srd_agnd_169;
    input srd_agnd_17;
    input srd_agnd_170;
    input srd_agnd_171;
    input srd_agnd_172;
    input srd_agnd_173;
    input srd_agnd_174;
    input srd_agnd_175;
    input srd_agnd_176;
    input srd_agnd_177;
    input srd_agnd_178;
    input srd_agnd_179;
    input srd_agnd_18;
    input srd_agnd_180;
    input srd_agnd_181;
    input srd_agnd_182;
    input srd_agnd_183;
    input srd_agnd_184;
    input srd_agnd_185;
    input srd_agnd_186;
    input srd_agnd_187;
    input srd_agnd_188;
    input srd_agnd_189;
    input srd_agnd_19;
    input srd_agnd_190;
    input srd_agnd_191;
    input srd_agnd_192;
    input srd_agnd_193;
    input srd_agnd_194;
    input srd_agnd_195;
    input srd_agnd_196;
    input srd_agnd_197;
    input srd_agnd_198;
    input srd_agnd_199;
    input srd_agnd_2;
    input srd_agnd_20;
    input srd_agnd_200;
    input srd_agnd_201;
    input srd_agnd_202;
    input srd_agnd_203;
    input srd_agnd_204;
    input srd_agnd_205;
    input srd_agnd_206;
    input srd_agnd_207;
    input srd_agnd_208;
    input srd_agnd_209;
    input srd_agnd_21;
    input srd_agnd_210;
    input srd_agnd_211;
    input srd_agnd_212;
    input srd_agnd_213;
    input srd_agnd_214;
    input srd_agnd_215;
    input srd_agnd_216;
    input srd_agnd_217;
    input srd_agnd_218;
    input srd_agnd_219;
    input srd_agnd_22;
    input srd_agnd_220;
    input srd_agnd_221;
    input srd_agnd_222;
    input srd_agnd_223;
    input srd_agnd_224;
    input srd_agnd_225;
    input srd_agnd_226;
    input srd_agnd_227;
    input srd_agnd_228;
    input srd_agnd_229;
    input srd_agnd_23;
    input srd_agnd_230;
    input srd_agnd_231;
    input srd_agnd_232;
    input srd_agnd_233;
    input srd_agnd_234;
    input srd_agnd_235;
    input srd_agnd_236;
    input srd_agnd_237;
    input srd_agnd_238;
    input srd_agnd_239;
    input srd_agnd_24;
    input srd_agnd_240;
    input srd_agnd_241;
    input srd_agnd_242;
    input srd_agnd_243;
    input srd_agnd_244;
    input srd_agnd_245;
    input srd_agnd_246;
    input srd_agnd_247;
    input srd_agnd_248;
    input srd_agnd_249;
    input srd_agnd_25;
    input srd_agnd_250;
    input srd_agnd_251;
    input srd_agnd_252;
    input srd_agnd_253;
    input srd_agnd_254;
    input srd_agnd_255;
    input srd_agnd_256;
    input srd_agnd_257;
    input srd_agnd_258;
    input srd_agnd_259;
    input srd_agnd_26;
    input srd_agnd_260;
    input srd_agnd_261;
    input srd_agnd_262;
    input srd_agnd_263;
    input srd_agnd_264;
    input srd_agnd_265;
    input srd_agnd_266;
    input srd_agnd_267;
    input srd_agnd_268;
    input srd_agnd_269;
    input srd_agnd_27;
    input srd_agnd_270;
    input srd_agnd_271;
    input srd_agnd_28;
    input srd_agnd_29;
    input srd_agnd_3;
    input srd_agnd_30;
    input srd_agnd_31;
    input srd_agnd_32;
    input srd_agnd_33;
    input srd_agnd_34;
    input srd_agnd_35;
    input srd_agnd_36;
    input srd_agnd_37;
    input srd_agnd_38;
    input srd_agnd_39;
    input srd_agnd_4;
    input srd_agnd_40;
    input srd_agnd_41;
    input srd_agnd_42;
    input srd_agnd_43;
    input srd_agnd_44;
    input srd_agnd_45;
    input srd_agnd_46;
    input srd_agnd_47;
    input srd_agnd_48;
    input srd_agnd_49;
    input srd_agnd_5;
    input srd_agnd_50;
    input srd_agnd_51;
    input srd_agnd_52;
    input srd_agnd_53;
    input srd_agnd_54;
    input srd_agnd_55;
    input srd_agnd_56;
    input srd_agnd_57;
    input srd_agnd_58;
    input srd_agnd_59;
    input srd_agnd_6;
    input srd_agnd_60;
    input srd_agnd_61;
    input srd_agnd_62;
    input srd_agnd_63;
    input srd_agnd_64;
    input srd_agnd_65;
    input srd_agnd_66;
    input srd_agnd_67;
    input srd_agnd_68;
    input srd_agnd_69;
    input srd_agnd_7;
    input srd_agnd_70;
    input srd_agnd_71;
    input srd_agnd_72;
    input srd_agnd_73;
    input srd_agnd_74;
    input srd_agnd_75;
    input srd_agnd_76;
    input srd_agnd_77;
    input srd_agnd_78;
    input srd_agnd_79;
    input srd_agnd_8;
    input srd_agnd_80;
    input srd_agnd_81;
    input srd_agnd_82;
    input srd_agnd_83;
    input srd_agnd_84;
    input srd_agnd_85;
    input srd_agnd_86;
    input srd_agnd_87;
    input srd_agnd_88;
    input srd_agnd_89;
    input srd_agnd_9;
    input srd_agnd_90;
    input srd_agnd_91;
    input srd_agnd_92;
    input srd_agnd_93;
    input srd_agnd_94;
    input srd_agnd_95;
    input srd_agnd_96;
    input srd_agnd_97;
    input srd_agnd_98;
    input srd_agnd_99;
    output srd_refclk_out_0;
    output srd_refclk_out_1;
    output srd_refclk_out_2;
    output srd_refclk_out_3;
    input synce_0_pll_agnd;
    input synce_0_pll_avdd1p8;
    output synce_0_pll_testout_n;
    output synce_0_pll_testout_p;
    input synce_1_pll_agnd;
    input synce_1_pll_avdd1p8;
    input sys_rst_n;
    input test_0;
    input test_1;
    input test_2;
    input test_3;
    input test_4;
    input therm_diode_n;
    input therm_diode_p;
    input therm_diode_vdd3p3;
    inout ts_bit_clk0;
    inout ts_bit_clk1;
    input ts_pll_refclk_n;
    input ts_pll_refclk_p;
    output ts_pll_testout_n;
    output ts_pll_testout_p;
    inout ts_sync0;
    inout ts_sync1;
    inout ts_time_val0;
    inout ts_time_val1;
    input uart0_rx;
    output uart0_tx;
    input uart1_rx;
    output uart1_tx;
    input uc_pll_agnd;
    input uc_pll_avdd1p8;
    input uc_pll_byp_clk0;
    input uc_pll_byp_clk1;
    output uc_pll_lock;
    input uc_pll_refclk_n;
    input uc_pll_refclk_p;
    output uc_pll_testout_n;
    output uc_pll_testout_p;
    input vddc_1;
    input vddc_10;
    input vddc_11;
    input vddc_12;
    input vddc_13;
    input vddc_14;
    input vddc_15;
    input vddc_16;
    input vddc_17;
    input vddc_18;
    input vddc_19;
    input vddc_2;
    input vddc_20;
    input vddc_21;
    input vddc_22;
    input vddc_23;
    input vddc_24;
    input vddc_25;
    input vddc_26;
    input vddc_27;
    input vddc_28;
    input vddc_29;
    input vddc_3;
    input vddc_30;
    input vddc_31;
    input vddc_32;
    input vddc_33;
    input vddc_34;
    input vddc_35;
    input vddc_36;
    input vddc_37;
    input vddc_38;
    input vddc_39;
    input vddc_4;
    input vddc_40;
    input vddc_41;
    input vddc_42;
    input vddc_43;
    input vddc_44;
    input vddc_45;
    input vddc_46;
    input vddc_47;
    input vddc_48;
    input vddc_49;
    input vddc_5;
    input vddc_50;
    input vddc_51;
    input vddc_52;
    input vddc_53;
    input vddc_54;
    input vddc_55;
    input vddc_56;
    input vddc_57;
    input vddc_58;
    input vddc_59;
    input vddc_6;
    input vddc_60;
    input vddc_61;
    input vddc_62;
    input vddc_63;
    input vddc_64;
    input vddc_65;
    input vddc_66;
    input vddc_67;
    input vddc_68;
    input vddc_69;
    input vddc_7;
    input vddc_70;
    input vddc_71;
    input vddc_72;
    input vddc_73;
    input vddc_74;
    input vddc_75;
    input vddc_76;
    input vddc_77;
    input vddc_78;
    input vddc_79;
    input vddc_8;
    input vddc_80;
    input vddc_81;
    input vddc_82;
    input vddc_83;
    input vddc_84;
    input vddc_85;
    input vddc_86;
    input vddc_87;
    input vddc_88;
    input vddc_9;
    output vddc_sense;
    input vss_1;
    input vss_10;
    input vss_100;
    input vss_101;
    input vss_102;
    input vss_103;
    input vss_104;
    input vss_105;
    input vss_106;
    input vss_107;
    input vss_108;
    input vss_109;
    input vss_11;
    input vss_110;
    input vss_111;
    input vss_112;
    input vss_113;
    input vss_114;
    input vss_115;
    input vss_116;
    input vss_117;
    input vss_118;
    input vss_119;
    input vss_12;
    input vss_120;
    input vss_121;
    input vss_122;
    input vss_123;
    input vss_124;
    input vss_125;
    input vss_126;
    input vss_127;
    input vss_128;
    input vss_129;
    input vss_13;
    input vss_130;
    input vss_131;
    input vss_132;
    input vss_133;
    input vss_134;
    input vss_135;
    input vss_136;
    input vss_137;
    input vss_138;
    input vss_139;
    input vss_14;
    input vss_140;
    input vss_141;
    input vss_142;
    input vss_143;
    input vss_144;
    input vss_145;
    input vss_146;
    input vss_147;
    input vss_148;
    input vss_149;
    input vss_15;
    input vss_150;
    input vss_151;
    input vss_152;
    input vss_153;
    input vss_154;
    input vss_155;
    input vss_156;
    input vss_157;
    input vss_158;
    input vss_159;
    input vss_16;
    input vss_160;
    input vss_161;
    input vss_162;
    input vss_163;
    input vss_164;
    input vss_165;
    input vss_166;
    input vss_167;
    input vss_168;
    input vss_169;
    input vss_17;
    input vss_170;
    input vss_171;
    input vss_172;
    input vss_173;
    input vss_174;
    input vss_175;
    input vss_176;
    input vss_177;
    input vss_178;
    input vss_179;
    input vss_18;
    input vss_180;
    input vss_181;
    input vss_182;
    input vss_183;
    input vss_184;
    input vss_185;
    input vss_186;
    input vss_187;
    input vss_188;
    input vss_19;
    input vss_2;
    input vss_20;
    input vss_21;
    input vss_22;
    input vss_23;
    input vss_24;
    input vss_25;
    input vss_26;
    input vss_27;
    input vss_28;
    input vss_29;
    input vss_3;
    input vss_30;
    input vss_31;
    input vss_32;
    input vss_33;
    input vss_34;
    input vss_35;
    input vss_36;
    input vss_37;
    input vss_38;
    input vss_39;
    input vss_4;
    input vss_40;
    input vss_41;
    input vss_42;
    input vss_43;
    input vss_44;
    input vss_45;
    input vss_46;
    input vss_47;
    input vss_48;
    input vss_49;
    input vss_5;
    input vss_50;
    input vss_51;
    input vss_52;
    input vss_53;
    input vss_54;
    input vss_55;
    input vss_56;
    input vss_57;
    input vss_58;
    input vss_59;
    input vss_6;
    input vss_60;
    input vss_61;
    input vss_62;
    input vss_63;
    input vss_64;
    input vss_65;
    input vss_66;
    input vss_67;
    input vss_68;
    input vss_69;
    input vss_7;
    input vss_70;
    input vss_71;
    input vss_72;
    input vss_73;
    input vss_74;
    input vss_75;
    input vss_76;
    input vss_77;
    input vss_78;
    input vss_79;
    input vss_8;
    input vss_80;
    input vss_81;
    input vss_82;
    input vss_83;
    input vss_84;
    input vss_85;
    input vss_86;
    input vss_87;
    input vss_88;
    input vss_89;
    input vss_9;
    input vss_90;
    input vss_91;
    input vss_92;
    input vss_93;
    input vss_94;
    input vss_95;
    input vss_96;
    input vss_97;
    input vss_98;
    input vss_99;
    output vss_sense;


    initial
        begin
        end

endmodule
