// generated by newgenasym  Mon Aug 31 14:30:02 2020


module zl88601 (avdd1, avdd2, cs, dclk, din, dout, \dra/zmosi , dvdd,
        \dxa/zmiso , epad, \fs/zsync , \i/o11 , \i/o12 , \i/o21/vs1 ,
        \i/o22/vs2 , ihl1, ihl2, int, iref, lfc1, lfc2, \pclk/zclk , rac1,
        rac2, rdc1, rdc2, ringd1, ringd2, rsn1, rsn2, rst, rtv1, rtv2,
        swcmpy, swcmpz, swisy, swisz, swouty, swoutz, swvsy, swvsz,
        tac1, tac2, tdc1, tdc2, tipd1, tipd2, tsca, vbh, vbl1, vbl2,
        vdd1v2, vddhpi, vddsw, vref, zsi);
    input avdd1;
    input avdd2;
    input cs;
    input dclk;
    input din;
    output dout;
    input \dra/zmosi ;
    input dvdd;
    output \dxa/zmiso ;
    input epad;
    input \fs/zsync ;
    inout \i/o11 ;
    inout \i/o12 ;
    inout \i/o21/vs1 ;
    inout \i/o22/vs2 ;
    output ihl1;
    output ihl2;
    output int;
    input iref;
    output lfc1;
    output lfc2;
    input \pclk/zclk ;
    input rac1;
    input rac2;
    input rdc1;
    input rdc2;
    output ringd1;
    output ringd2;
    input rsn1;
    input rsn2;
    input rst;
    output rtv1;
    output rtv2;
    output swcmpy;
    output swcmpz;
    input swisy;
    input swisz;
    output swouty;
    output swoutz;
    input swvsy;
    input swvsz;
    input tac1;
    input tac2;
    input tdc1;
    input tdc2;
    output tipd1;
    output tipd2;
    output tsca;
    input vbh;
    input vbl1;
    input vbl2;
    output vdd1v2;
    input vddhpi;
    input vddsw;
    output vref;
    input zsi;


    initial
        begin
        end

endmodule
