// generated by newgenasym  Tue Oct 20 17:35:49 2020


module connector (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \19 , \2 , \20 , \21 , \22 , \23 , \24 , \25 ,
        \26 , \27 , \28 , \29 , \3 , \30 , \31 , \32 , \33 , \34 , \35 , \36 , \37 , \4 , \5 , \6 , \7 , \8 , \9 , a,
        a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21,
        a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33,
        a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45,
        a46, a47, a48, a5, a6, a7, a8, a9, b, b1, b10, b11, b12, b13, b14,
        b15, b16, b17, b18, b19, b2, b20, b21, b22, b23, b24, b25, b26,
        b27, b28, b29, b3, b30, b31, b32, b33, b34, b35, b36, b37, b38,
        b39, b4, b40, b41, b42, b43, b44, b45, b46, b47, b48, b5, b6, b7,
        b8, b9, c1, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c2,
        c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c3, c30, c31,
        c32, c4, c5, c6, c7, c8, c9, g1, g2, gnd2, gnd_1, gnd_10, gnd_11,
        gnd_12, gnd_13, gnd_14, gnd_15, gnd_16, gnd_17, gnd_18,
        gnd_19, gnd_2, gnd_20, gnd_21, gnd_22, gnd_23, gnd_24,
        gnd_25, gnd_26, gnd_27, gnd_28, gnd_29, gnd_3, gnd_30,
        gnd_31, gnd_32, gnd_33, gnd_34, gnd_35, gnd_36, gnd_37,
        gnd_38, gnd_39, gnd_4, gnd_40, gnd_41, gnd_42, gnd_43,
        gnd_44, gnd_45, gnd_46, gnd_47, gnd_48, gnd_49, gnd_5,
        gnd_50, gnd_6, gnd_7, gnd_8, gnd_9, gng1, los, mod_abs, n1, n2,
        n3, n4, n5, n6, n7, n8, nc1, nc2, nc3, nc4, nc5, rdn, rdp, reset,
        rssi, \rx_10g* , rx_10g_p, \rx_1g* , rx_1g_p, rx_los,
        rx_rssi_tri, \rx_sd/reset_sd , scl, sda, sh1, sh10, sh11, sh12,
        sh13, sh14, sh2, sh3, sh4, sh5, sh6, sh7, sh8, sh9, tdn, tdp,
        \tx_10g* , tx_10g_p, \tx_1g* , tx_1g_p, tx_dis, txdisable,
        txfault, vcc3_1, vcc3_2, vcc5, vccr, vcct, veer_1,
        \veer_1/nc2 , veer_2, veer_3, veer_4, veet_1, veet_2, veet_3);
    inout \1 ;
    inout \10 ;
    inout \11 ;
    input \12 ;
    input \13 ;
    input \14 ;
    input \15 ;
    input \16 ;
    input \17 ;
    input \18 ;
    input \19 ;
    inout \2 ;
    input \20 ;
    input \21 ;
    input \22 ;
    input \23 ;
    input \24 ;
    input \25 ;
    input \26 ;
    input \27 ;
    input \28 ;
    input \29 ;
    inout \3 ;
    input \30 ;
    input \31 ;
    input \32 ;
    input \33 ;
    input \34 ;
    input \35 ;
    input \36 ;
    input \37 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    input \7 ;
    input \8 ;
    input \9 ;
    input [34:1] a;
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a13;
    inout a14;
    inout a15;
    inout a16;
    inout a17;
    inout a18;
    inout a19;
    inout a2;
    inout a20;
    inout a21;
    inout a22;
    inout a23;
    inout a24;
    inout a25;
    inout a26;
    inout a27;
    inout a28;
    inout a29;
    inout a3;
    inout a30;
    inout a31;
    inout a32;
    input a33;
    input a34;
    input a35;
    input a36;
    input a37;
    input a38;
    input a39;
    inout a4;
    input a40;
    input a41;
    input a42;
    input a43;
    input a44;
    input a45;
    input a46;
    input a47;
    input a48;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout [34:1] b;
    inout b1;
    output b10;
    output b11;
    output b12;
    output b13;
    output b14;
    output b15;
    output b16;
    output b17;
    output b18;
    output b19;
    inout b2;
    output b20;
    output b21;
    output b22;
    output b23;
    output b24;
    output b25;
    output b26;
    output b27;
    output b28;
    output b29;
    inout b3;
    output b30;
    output b31;
    output b32;
    output b33;
    output b34;
    output b35;
    output b36;
    output b37;
    output b38;
    output b39;
    inout b4;
    output b40;
    output b41;
    output b42;
    output b43;
    output b44;
    output b45;
    output b46;
    output b47;
    output b48;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    output b9;
    inout c1;
    output c10;
    output c11;
    output c12;
    output c13;
    output c14;
    output c15;
    output c16;
    output c17;
    output c18;
    output c19;
    inout c2;
    output c20;
    output c21;
    output c22;
    output c23;
    output c24;
    output c25;
    output c26;
    output c27;
    output c28;
    output c29;
    inout c3;
    output c30;
    output c31;
    output c32;
    inout c4;
    inout c5;
    inout c6;
    inout c7;
    inout c8;
    output c9;
    output g1;
    output g2;
    output gnd2;
    inout gnd_1;
    inout gnd_10;
    inout gnd_11;
    inout gnd_12;
    inout gnd_13;
    inout gnd_14;
    inout gnd_15;
    inout gnd_16;
    inout gnd_17;
    inout gnd_18;
    inout gnd_19;
    inout gnd_2;
    inout gnd_20;
    input gnd_21;
    input gnd_22;
    input gnd_23;
    input gnd_24;
    input gnd_25;
    input gnd_26;
    input gnd_27;
    input gnd_28;
    input gnd_29;
    inout gnd_3;
    input gnd_30;
    input gnd_31;
    output gnd_32;
    output gnd_33;
    output gnd_34;
    output gnd_35;
    output gnd_36;
    output gnd_37;
    output gnd_38;
    output gnd_39;
    inout gnd_4;
    output gnd_40;
    output gnd_41;
    output gnd_42;
    output gnd_43;
    output gnd_44;
    output gnd_45;
    output gnd_46;
    output gnd_47;
    output gnd_48;
    output gnd_49;
    inout gnd_5;
    output gnd_50;
    inout gnd_6;
    inout gnd_7;
    inout gnd_8;
    inout gnd_9;
    output gng1;
    input los;
    input mod_abs;
    inout n1;
    inout n2;
    output n3;
    output n4;
    output n5;
    output n6;
    output n7;
    output n8;
    input nc1;
    input nc2;
    input nc3;
    input nc4;
    input nc5;
    input rdn;
    input rdp;
    input reset;
    input rssi;
    input \rx_10g* ;
    input rx_10g_p;
    input \rx_1g* ;
    input rx_1g_p;
    input rx_los;
    input rx_rssi_tri;
    input \rx_sd/reset_sd ;
    input scl;
    input sda;
    output sh1;
    output sh10;
    output sh11;
    output sh12;
    output sh13;
    output sh14;
    output sh2;
    output sh3;
    output sh4;
    output sh5;
    output sh6;
    output sh7;
    output sh8;
    output sh9;
    input tdn;
    input tdp;
    input \tx_10g* ;
    input tx_10g_p;
    input \tx_1g* ;
    input tx_1g_p;
    input tx_dis;
    input txdisable;
    input txfault;
    output vcc3_1;
    output vcc3_2;
    output vcc5;
    input vccr;
    input vcct;
    output veer_1;
    output \veer_1/nc2 ;
    output veer_2;
    output veer_3;
    output veer_4;
    output veet_1;
    output veet_2;
    output veet_3;


    initial
        begin
        end

endmodule
