-- generated by newgenasym Mon Aug 31 16:16:28 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       OUT    STD_LOGIC;    
	ANODE:     INOUT  STD_LOGIC;    
	CATHODE:   INOUT  STD_LOGIC;    
	N1:        IN     STD_LOGIC;    
	N2:        IN     STD_LOGIC;    
	N3:        IN     STD_LOGIC;    
	N4:        IN     STD_LOGIC;    
	P1:        OUT    STD_LOGIC;    
	P2:        OUT    STD_LOGIC;    
	P3:        OUT    STD_LOGIC;    
	P4:        OUT    STD_LOGIC);
end led;
