// generated by newgenasym  Fri Oct 30 11:26:27 2020


module gn25l95 (adc_in, apd_dac, \ben+ , \ben- , \bias+ , \bias- , ee_scl, ee_sda,
        epad, \laser+ , \laser- , mpd, rssi, rx_slp, \rxin+ , \rxin- , \rxout+ ,
        \rxout- , scl, \sd/los , sda, \tx_disable/tx_sleep , tx_fault,
        tx_sd, \txin+ , \txin- , vcc_dig, vcc_tx, vddrx);
    inout adc_in;
    inout apd_dac;
    inout \ben+ ;
    inout \ben- ;
    inout \bias+ ;
    inout \bias- ;
    inout ee_scl;
    inout ee_sda;
    inout epad;
    inout \laser+ ;
    inout \laser- ;
    inout mpd;
    inout rssi;
    inout rx_slp;
    inout \rxin+ ;
    inout \rxin- ;
    inout \rxout+ ;
    inout \rxout- ;
    inout scl;
    inout \sd/los ;
    inout sda;
    inout \tx_disable/tx_sleep ;
    inout tx_fault;
    inout tx_sd;
    inout \txin+ ;
    inout \txin- ;
    inout vcc_dig;
    inout vcc_tx;
    inout vddrx;


    initial
        begin
        end

endmodule
