-- generated by newgenasym Mon Aug 31 13:56:36 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity gn25l95 is
    port (    
	ADC_IN:    INOUT  STD_LOGIC;    
	APD_DAC:   INOUT  STD_LOGIC;    
	\ben+\:    INOUT  STD_LOGIC;    
	\ben-\:    INOUT  STD_LOGIC;    
	\bias+\:   INOUT  STD_LOGIC;    
	\bias-\:   INOUT  STD_LOGIC;    
	EE_SCL:    INOUT  STD_LOGIC;    
	EE_SDA:    INOUT  STD_LOGIC;    
	EPAD:      INOUT  STD_LOGIC;    
	\laser+\:  INOUT  STD_LOGIC;    
	\laser-\:  INOUT  STD_LOGIC;    
	MPD:       INOUT  STD_LOGIC;    
	RSSI:      INOUT  STD_LOGIC;    
	RX_SLP:    INOUT  STD_LOGIC;    
	\rxin+\:   INOUT  STD_LOGIC;    
	\rxin-\:   INOUT  STD_LOGIC;    
	\rxout+\:  INOUT  STD_LOGIC;    
	\rxout-\:  INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	\sd/los\:  INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	\tx_disable/tx_sleep\: INOUT  STD_LOGIC;    
	TX_FAULT:  INOUT  STD_LOGIC;    
	TX_SD:     INOUT  STD_LOGIC;    
	\txin+\:   INOUT  STD_LOGIC;    
	\txin-\:   INOUT  STD_LOGIC;    
	VCC_DIG:   INOUT  STD_LOGIC;    
	VCC_TX:    INOUT  STD_LOGIC;    
	VDDRX:     INOUT  STD_LOGIC);
end gn25l95;
