// generated by newgenasym  Mon Jan 11 10:34:19 2021


module \88e6071  (\avdd/pll , \ee_clk/c1_led/flow , \ee_cs/c2_led/ee_we ,
        \ee_din/c0_led/eee , \ee_dout/c3_led , ee_vddo, epad, intn,
        iref, mdc_cpu, mdio_cpu, p0_avdd, p0_rxn, p0_rxp, p0_txn,
        p0_txp, p1_avdd, p1_rxn, p1_rxp, p1_txn, p1_txp, p2_avdd,
        p2_rxn, p2_rxp, p2_txn, p2_txp, p3_avdd, p3_rxn, p3_rxp,
        p3_txn, p3_txp, p4_avdd, p4_rxn, p4_rxp, p4_txn, p4_txp,
        \p5_col/p6_refclk/gpio1/sdet/tai_1 ,
        \p5_crs/p6_octl/gpio0/tai_0 , \p5_inclk/p6_ictl ,
        \p5_ind0/p5_id0 , \p5_ind1/p5_id1 , \p5_ind2/gpio2/p6_id0 ,
        \p5_ind3/gpio3/tai_2/p6_id1 , \p5_indv/p5_ictl ,
        \p5_outclk/refclk , \p5_outd0/p5_od0/p5_mode0 ,
        \p5_outd1/p5_od1/p5_mode1 , \p5_outd2/p6_od0/p5_mode2 ,
        \p5_outd3/p6_od1/p5_mode3 , \p5_outen/p5_octl/p5_sel ,
        p5_vddo, \r0_led/addr4 , \r1_led/no_cpu , \r2_led/4col , resetn,
        vdd18_in, vdd18_out, vdd33, vdd_core_1, vdd_core_2,
        vdd_core_3, vdd_core_4, vss, xtal_in, xtal_out);
    input \avdd/pll ;
    inout \ee_clk/c1_led/flow ;
    inout \ee_cs/c2_led/ee_we ;
    inout \ee_din/c0_led/eee ;
    inout \ee_dout/c3_led ;
    input ee_vddo;
    input epad;
    inout intn;
    inout iref;
    inout mdc_cpu;
    inout mdio_cpu;
    input p0_avdd;
    inout p0_rxn;
    inout p0_rxp;
    inout p0_txn;
    inout p0_txp;
    input p1_avdd;
    inout p1_rxn;
    inout p1_rxp;
    inout p1_txn;
    inout p1_txp;
    input p2_avdd;
    inout p2_rxn;
    inout p2_rxp;
    inout p2_txn;
    inout p2_txp;
    input p3_avdd;
    inout p3_rxn;
    inout p3_rxp;
    inout p3_txn;
    inout p3_txp;
    input p4_avdd;
    inout p4_rxn;
    inout p4_rxp;
    inout p4_txn;
    inout p4_txp;
    inout \p5_col/p6_refclk/gpio1/sdet/tai_1 ;
    inout \p5_crs/p6_octl/gpio0/tai_0 ;
    inout \p5_inclk/p6_ictl ;
    inout \p5_ind0/p5_id0 ;
    inout \p5_ind1/p5_id1 ;
    inout \p5_ind2/gpio2/p6_id0 ;
    inout \p5_ind3/gpio3/tai_2/p6_id1 ;
    inout \p5_indv/p5_ictl ;
    inout \p5_outclk/refclk ;
    inout \p5_outd0/p5_od0/p5_mode0 ;
    inout \p5_outd1/p5_od1/p5_mode1 ;
    inout \p5_outd2/p6_od0/p5_mode2 ;
    inout \p5_outd3/p6_od1/p5_mode3 ;
    inout \p5_outen/p5_octl/p5_sel ;
    input p5_vddo;
    inout \r0_led/addr4 ;
    inout \r1_led/no_cpu ;
    inout \r2_led/4col ;
    inout resetn;
    input vdd18_in;
    input vdd18_out;
    input vdd33;
    input vdd_core_1;
    input vdd_core_2;
    input vdd_core_3;
    input vdd_core_4;
    input vss;
    inout xtal_in;
    inout xtal_out;


    initial
        begin
        end

endmodule
