// generated by newgenasym  Fri Sep 11 10:32:03 2020


module ddr (a0, a1, a10, \a10/ap , a11, a12, \a12/bc# , a13, \a13/nc , \a14/nc ,
        \a15/nc , a2, a3, a4, a5, a6, a7, a8, a9, ba0, ba1, ba2, \cas# , cas_n,
        ck, \ck# , cke, clk_n, clk_p, clkn, clkp, \cs# , cs_n, dq0,
        \dq0/dql0 , dq1, \dq1/dql1 , dq10, \dq10/dqu2 , dq11, \dq11/dqu3 ,
        dq12, \dq12/dqu4 , dq13, \dq13/dqu5 , dq14, \dq14/dqu6 , dq15,
        \dq15/dqu7 , dq2, \dq2/dql2 , dq3, \dq3/dql3 , dq4, \dq4/dql4 , dq5,
        \dq5/dql5 , dq6, \dq6/dql6 , dq7, \dq7/dql7 , dq8, \dq8/dqu0 , dq9,
        \dq9/dqu1 , dqs_n, dqs_p, dqsl, \dqsl# , dqsu, \dqsu# , ldm, ldqs,
        \ldqs# , nc0, nc1, nc2, nc3, nc4, nc5, nc6, \nc7/a14 , odt, \ras# ,
        ras_n, \reset# , reset_n, rfu1, rfu2, rfu3, tdqs, tdqs_n, udm,
        udqs, \udqs# , vdd0, vdd1, vdd2, vdd3, vdd4, vdd5, vdd6, vdd7,
        vdd8, vdd9, vddl, vddq0, vddq1, vddq10, vddq2, vddq3, vddq4,
        vddq5, vddq6, vddq7, vddq8, vddq9, vref, vrefca, vrefdq, vss0,
        vss1, vss10, vss11, vss12, vss2, vss3, vss4, vss5, vss6, vss7,
        vss8, vss9, vssdl, vssq0, vssq1, vssq10, vssq2, vssq3, vssq4,
        vssq5, vssq6, vssq7, vssq8, vssq9, \we# , we_n, zq);
    input a0;
    input a1;
    input a10;
    input \a10/ap ;
    input a11;
    input a12;
    input \a12/bc# ;
    input a13;
    input \a13/nc ;
    input \a14/nc ;
    inout \a15/nc ;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    input a9;
    input ba0;
    input ba1;
    input ba2;
    input \cas# ;
    input cas_n;
    input ck;
    input \ck# ;
    input cke;
    input clk_n;
    input clk_p;
    input clkn;
    input clkp;
    input \cs# ;
    input cs_n;
    input dq0;
    inout \dq0/dql0 ;
    input dq1;
    inout \dq1/dql1 ;
    input dq10;
    inout \dq10/dqu2 ;
    input dq11;
    inout \dq11/dqu3 ;
    input dq12;
    inout \dq12/dqu4 ;
    input dq13;
    inout \dq13/dqu5 ;
    input dq14;
    inout \dq14/dqu6 ;
    input dq15;
    inout \dq15/dqu7 ;
    input dq2;
    inout \dq2/dql2 ;
    input dq3;
    inout \dq3/dql3 ;
    input dq4;
    inout \dq4/dql4 ;
    input dq5;
    inout \dq5/dql5 ;
    input dq6;
    inout \dq6/dql6 ;
    input dq7;
    inout \dq7/dql7 ;
    input dq8;
    inout \dq8/dqu0 ;
    input dq9;
    inout \dq9/dqu1 ;
    input dqs_n;
    input dqs_p;
    inout dqsl;
    inout \dqsl# ;
    inout dqsu;
    inout \dqsu# ;
    input ldm;
    input ldqs;
    input \ldqs# ;
    inout nc0;
    inout nc1;
    output nc2;
    inout nc3;
    inout nc4;
    output nc5;
    output nc6;
    input \nc7/a14 ;
    input odt;
    input \ras# ;
    input ras_n;
    input \reset# ;
    input reset_n;
    input rfu1;
    input rfu2;
    input rfu3;
    input tdqs;
    input tdqs_n;
    input udm;
    input udqs;
    input \udqs# ;
    input vdd0;
    input vdd1;
    input vdd2;
    input vdd3;
    input vdd4;
    input vdd5;
    input vdd6;
    input vdd7;
    input vdd8;
    output vdd9;
    output vddl;
    input vddq0;
    input vddq1;
    output vddq10;
    input vddq2;
    input vddq3;
    input vddq4;
    input vddq5;
    input vddq6;
    input vddq7;
    input vddq8;
    output vddq9;
    output vref;
    input vrefca;
    input vrefdq;
    input vss0;
    input vss1;
    input vss10;
    input vss11;
    output vss12;
    input vss2;
    input vss3;
    input vss4;
    input vss5;
    input vss6;
    input vss7;
    input vss8;
    input vss9;
    output vssdl;
    input vssq0;
    input vssq1;
    output vssq10;
    input vssq2;
    input vssq3;
    input vssq4;
    input vssq5;
    input vssq6;
    input vssq7;
    input vssq8;
    output vssq9;
    input \we# ;
    input we_n;
    input zq;


    initial
        begin
        end

endmodule
