// generated by newgenasym  Fri Nov 03 18:00:26 2023


module an7552ct (act_n, arca8, avdd12_ddr_0, avdd12_ddr_1, avdd12_ddr_2,
        avdd25_rddr, avdd33_gbe_0, avdd33_gbe_1, avdd33_gbe_2,
        avdd33_pcie0, avdd33_pcie1, avdd33_pon, avdd33_rddr,
        avdd33_ssusb, avdd33_usb0, avdd33_usb1, avdd33_xtal,
        avddk_gbe_0, avddk_gbe_1, avddk_gbe_2, avddk_pcie0,
        avddk_pcie1, avddk_pon, avddk_ssusb, avsmon, avssk_pon_0,
        avssk_pon_1, avssk_pon_2, avssk_pon_3, avssk_pon_4,
        avssk_pon_5, avssk_pon_6, avssk_pon_7, avssk_pon_8, bg0,
        bgpor_dginp, bgpor_tn, bgpor_tp, clk, clkb, ddr_reset_n,
        dq0, dq1, dq10, dq11, dq12, dq13, dq14, dq15, dq2, dq3, dq4, dq5,
        dq6, dq7, dq8, dq9, dqm0, dqm1, dqs0, dqs1, dqsb0, dqsb1,
        dvdd33_0, dvdd33_1, dvdd33_2, dvdd33_3, dvdd33_4,
        dvddk_ddr_0, dvddk_ddr_1, dvddk_ddr_rc_0, dvddk_ddr_rc_1,
        dvddk_ddr_rx, efuse, gbe_rext, gnd_0, gnd_1, gnd_10,
        gnd_100, gnd_101, gnd_102, gnd_103, gnd_104, gnd_105,
        gnd_106, gnd_107, gnd_108, gnd_109, gnd_11, gnd_110,
        gnd_111, gnd_112, gnd_113, gnd_114, gnd_115, gnd_116,
        gnd_117, gnd_118, gnd_119, gnd_12, gnd_120, gnd_121,
        gnd_122, gnd_123, gnd_124, gnd_125, gnd_126, gnd_127,
        gnd_128, gnd_129, gnd_13, gnd_130, gnd_131, gnd_132, gnd_14,
        gnd_15, gnd_16, gnd_17, gnd_18, gnd_19, gnd_2, gnd_20,
        gnd_21, gnd_22, gnd_23, gnd_24, gnd_25, gnd_26, gnd_27,
        gnd_28, gnd_29, gnd_3, gnd_30, gnd_31, gnd_32, gnd_33,
        gnd_34, gnd_35, gnd_36, gnd_37, gnd_38, gnd_39, gnd_4,
        gnd_40, gnd_41, gnd_42, gnd_43, gnd_44, gnd_45, gnd_46,
        gnd_47, gnd_48, gnd_49, gnd_5, gnd_50, gnd_51, gnd_52,
        gnd_53, gnd_54, gnd_55, gnd_56, gnd_57, gnd_58, gnd_59,
        gnd_6, gnd_60, gnd_61, gnd_62, gnd_63, gnd_64, gnd_65,
        gnd_66, gnd_67, gnd_68, gnd_69, gnd_7, gnd_70, gnd_71,
        gnd_72, gnd_73, gnd_74, gnd_75, gnd_76, gnd_77, gnd_78,
        gnd_79, gnd_8, gnd_80, gnd_81, gnd_82, gnd_83, gnd_84,
        gnd_85, gnd_86, gnd_87, gnd_88, gnd_89, gnd_9, gnd_90,
        gnd_91, gnd_92, gnd_93, gnd_94, gnd_95, gnd_96, gnd_97,
        gnd_98, gnd_99, gpio0, gpio10_0, gpio11_0, gpio12_0, gpio13,
        gpio14_0, gpio15_0, gpio16_0, gpio17_0, gpio18_0, gpio19_0,
        gpio1_0, gpio20_0, gpio21_0, gpio22_1, gpio23_1, gpio24_1,
        gpio25_1, gpio26_0, gpio27_0, gpio2_0, gpio3_0, gpio4_0,
        gpio5_0, gpio6_0, gpio7_0, gpio8_0, gpio9_0, hw_rstn,
        i2c_scl, i2c_sda, nc, pcie_ckn0, pcie_ckn1, pcie_ckp0,
        pcie_ckp1, pcie_reset0, pcie_reset1, pcie_rxn0, pcie_rxn1,
        pcie_rxp0, pcie_rxp1, pcie_txn0, pcie_txn1, pcie_txp0,
        pcie_txp1, pon_rxn, pon_rxp, pon_txn, pon_txp, ra0, ra1,
        ra10, ra11, ra12, ra13, ra2, ra3, ra4, ra5, ra6, ra7, ra8, ra9,
        rba0, rba1, rcas_n, rcke0, rcs0, ref_cko, rodt, rras_n, rwe_n,
        spi_clk, spi_cs, spi_miso, spi_mosi, ssusb_rxn, ssusb_rxp,
        ssusb_txn, ssusb_txp, txvn_a_p0, txvn_a_p1, txvn_a_p2,
        txvn_a_p3, txvn_b_p0, txvn_b_p1, txvn_b_p2, txvn_b_p3,
        txvn_c_p0, txvn_c_p1, txvn_c_p2, txvn_c_p3, txvn_d_p0,
        txvn_d_p1, txvn_d_p2, txvn_d_p3, txvp_a_p0, txvp_a_p1,
        txvp_a_p2, txvp_a_p3, txvp_b_p0, txvp_b_p1, txvp_b_p2,
        txvp_b_p3, txvp_c_p0, txvp_c_p1, txvp_c_p2, txvp_c_p3,
        txvp_d_p0, txvp_d_p1, txvp_d_p2, txvp_d_p3, uart_rxd,
        uart_txd, usb_dm0, usb_dm1, usb_dp0, usb_dp1, vcck_0,
        vcck_1, vcck_10, vcck_11, vcck_12, vcck_13, vcck_14,
        vcck_15, vcck_16, vcck_17, vcck_18, vcck_19, vcck_2,
        vcck_20, vcck_21, vcck_22, vcck_23, vcck_3, vcck_4, vcck_5,
        vcck_6, vcck_7, vcck_8, vcck_9, xtal_in, xtal_out);
    inout act_n;
    inout arca8;
    inout avdd12_ddr_0;
    inout avdd12_ddr_1;
    inout avdd12_ddr_2;
    inout avdd25_rddr;
    inout avdd33_gbe_0;
    inout avdd33_gbe_1;
    inout avdd33_gbe_2;
    inout avdd33_pcie0;
    inout avdd33_pcie1;
    inout avdd33_pon;
    inout avdd33_rddr;
    inout avdd33_ssusb;
    inout avdd33_usb0;
    inout avdd33_usb1;
    inout avdd33_xtal;
    inout avddk_gbe_0;
    inout avddk_gbe_1;
    inout avddk_gbe_2;
    inout avddk_pcie0;
    inout avddk_pcie1;
    inout avddk_pon;
    inout avddk_ssusb;
    inout avsmon;
    inout avssk_pon_0;
    inout avssk_pon_1;
    inout avssk_pon_2;
    inout avssk_pon_3;
    inout avssk_pon_4;
    inout avssk_pon_5;
    inout avssk_pon_6;
    inout avssk_pon_7;
    inout avssk_pon_8;
    inout bg0;
    inout bgpor_dginp;
    inout bgpor_tn;
    inout bgpor_tp;
    inout clk;
    inout clkb;
    inout ddr_reset_n;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout dq15;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dq8;
    inout dq9;
    inout dqm0;
    inout dqm1;
    inout dqs0;
    inout dqs1;
    inout dqsb0;
    inout dqsb1;
    inout dvdd33_0;
    inout dvdd33_1;
    inout dvdd33_2;
    inout dvdd33_3;
    inout dvdd33_4;
    inout dvddk_ddr_0;
    inout dvddk_ddr_1;
    inout dvddk_ddr_rc_0;
    inout dvddk_ddr_rc_1;
    inout dvddk_ddr_rx;
    inout efuse;
    inout gbe_rext;
    inout gnd_0;
    inout gnd_1;
    inout gnd_10;
    inout gnd_100;
    inout gnd_101;
    inout gnd_102;
    inout gnd_103;
    inout gnd_104;
    inout gnd_105;
    inout gnd_106;
    inout gnd_107;
    inout gnd_108;
    inout gnd_109;
    inout gnd_11;
    inout gnd_110;
    inout gnd_111;
    inout gnd_112;
    inout gnd_113;
    inout gnd_114;
    inout gnd_115;
    inout gnd_116;
    inout gnd_117;
    inout gnd_118;
    inout gnd_119;
    inout gnd_12;
    inout gnd_120;
    inout gnd_121;
    inout gnd_122;
    inout gnd_123;
    inout gnd_124;
    inout gnd_125;
    inout gnd_126;
    inout gnd_127;
    inout gnd_128;
    inout gnd_129;
    inout gnd_13;
    inout gnd_130;
    inout gnd_131;
    inout gnd_132;
    inout gnd_14;
    inout gnd_15;
    inout gnd_16;
    inout gnd_17;
    inout gnd_18;
    inout gnd_19;
    inout gnd_2;
    inout gnd_20;
    inout gnd_21;
    inout gnd_22;
    inout gnd_23;
    inout gnd_24;
    inout gnd_25;
    inout gnd_26;
    inout gnd_27;
    inout gnd_28;
    inout gnd_29;
    inout gnd_3;
    inout gnd_30;
    inout gnd_31;
    inout gnd_32;
    inout gnd_33;
    inout gnd_34;
    inout gnd_35;
    inout gnd_36;
    inout gnd_37;
    inout gnd_38;
    inout gnd_39;
    inout gnd_4;
    inout gnd_40;
    inout gnd_41;
    inout gnd_42;
    inout gnd_43;
    inout gnd_44;
    inout gnd_45;
    inout gnd_46;
    inout gnd_47;
    inout gnd_48;
    inout gnd_49;
    inout gnd_5;
    inout gnd_50;
    inout gnd_51;
    inout gnd_52;
    inout gnd_53;
    inout gnd_54;
    inout gnd_55;
    inout gnd_56;
    inout gnd_57;
    inout gnd_58;
    inout gnd_59;
    inout gnd_6;
    inout gnd_60;
    inout gnd_61;
    inout gnd_62;
    inout gnd_63;
    inout gnd_64;
    inout gnd_65;
    inout gnd_66;
    inout gnd_67;
    inout gnd_68;
    inout gnd_69;
    inout gnd_7;
    inout gnd_70;
    inout gnd_71;
    inout gnd_72;
    inout gnd_73;
    inout gnd_74;
    inout gnd_75;
    inout gnd_76;
    inout gnd_77;
    inout gnd_78;
    inout gnd_79;
    inout gnd_8;
    inout gnd_80;
    inout gnd_81;
    inout gnd_82;
    inout gnd_83;
    inout gnd_84;
    inout gnd_85;
    inout gnd_86;
    inout gnd_87;
    inout gnd_88;
    inout gnd_89;
    inout gnd_9;
    inout gnd_90;
    inout gnd_91;
    inout gnd_92;
    inout gnd_93;
    inout gnd_94;
    inout gnd_95;
    inout gnd_96;
    inout gnd_97;
    inout gnd_98;
    inout gnd_99;
    inout gpio0;
    inout gpio10_0;
    inout gpio11_0;
    inout gpio12_0;
    inout gpio13;
    inout gpio14_0;
    inout gpio15_0;
    inout gpio16_0;
    inout gpio17_0;
    inout gpio18_0;
    inout gpio19_0;
    inout gpio1_0;
    inout gpio20_0;
    inout gpio21_0;
    inout gpio22_1;
    inout gpio23_1;
    inout gpio24_1;
    inout gpio25_1;
    inout gpio26_0;
    inout gpio27_0;
    inout gpio2_0;
    inout gpio3_0;
    inout gpio4_0;
    inout gpio5_0;
    inout gpio6_0;
    inout gpio7_0;
    inout gpio8_0;
    inout gpio9_0;
    inout hw_rstn;
    inout i2c_scl;
    inout i2c_sda;
    inout nc;
    inout pcie_ckn0;
    inout pcie_ckn1;
    inout pcie_ckp0;
    inout pcie_ckp1;
    inout pcie_reset0;
    inout pcie_reset1;
    inout pcie_rxn0;
    inout pcie_rxn1;
    inout pcie_rxp0;
    inout pcie_rxp1;
    inout pcie_txn0;
    inout pcie_txn1;
    inout pcie_txp0;
    inout pcie_txp1;
    inout pon_rxn;
    inout pon_rxp;
    inout pon_txn;
    inout pon_txp;
    inout ra0;
    inout ra1;
    inout ra10;
    inout ra11;
    inout ra12;
    inout ra13;
    inout ra2;
    inout ra3;
    inout ra4;
    inout ra5;
    inout ra6;
    inout ra7;
    inout ra8;
    inout ra9;
    inout rba0;
    inout rba1;
    inout rcas_n;
    inout rcke0;
    inout rcs0;
    inout ref_cko;
    inout rodt;
    inout rras_n;
    inout rwe_n;
    inout spi_clk;
    inout spi_cs;
    inout spi_miso;
    inout spi_mosi;
    inout ssusb_rxn;
    inout ssusb_rxp;
    inout ssusb_txn;
    inout ssusb_txp;
    inout txvn_a_p0;
    inout txvn_a_p1;
    inout txvn_a_p2;
    inout txvn_a_p3;
    inout txvn_b_p0;
    inout txvn_b_p1;
    inout txvn_b_p2;
    inout txvn_b_p3;
    inout txvn_c_p0;
    inout txvn_c_p1;
    inout txvn_c_p2;
    inout txvn_c_p3;
    inout txvn_d_p0;
    inout txvn_d_p1;
    inout txvn_d_p2;
    inout txvn_d_p3;
    inout txvp_a_p0;
    inout txvp_a_p1;
    inout txvp_a_p2;
    inout txvp_a_p3;
    inout txvp_b_p0;
    inout txvp_b_p1;
    inout txvp_b_p2;
    inout txvp_b_p3;
    inout txvp_c_p0;
    inout txvp_c_p1;
    inout txvp_c_p2;
    inout txvp_c_p3;
    inout txvp_d_p0;
    inout txvp_d_p1;
    inout txvp_d_p2;
    inout txvp_d_p3;
    inout uart_rxd;
    inout uart_txd;
    inout usb_dm0;
    inout usb_dm1;
    inout usb_dp0;
    inout usb_dp1;
    inout vcck_0;
    inout vcck_1;
    inout vcck_10;
    inout vcck_11;
    inout vcck_12;
    inout vcck_13;
    inout vcck_14;
    inout vcck_15;
    inout vcck_16;
    inout vcck_17;
    inout vcck_18;
    inout vcck_19;
    inout vcck_2;
    inout vcck_20;
    inout vcck_21;
    inout vcck_22;
    inout vcck_23;
    inout vcck_3;
    inout vcck_4;
    inout vcck_5;
    inout vcck_6;
    inout vcck_7;
    inout vcck_8;
    inout vcck_9;
    inout xtal_in;
    inout xtal_out;


    initial
        begin
        end

endmodule
