-- generated by newgenasym Mon Aug 31 11:33:26 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity amplifier is
    port (    
	\in+\:     IN     STD_LOGIC;    
	\in+1\:    IN     STD_LOGIC;    
	\in+2\:    IN     STD_LOGIC;    
	\in-\:     IN     STD_LOGIC;    
	\in-1\:    IN     STD_LOGIC;    
	\in-2\:    IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	OUT1:      OUT    STD_LOGIC;    
	OUT2:      OUT    STD_LOGIC;    
	\vs+\:     IN     STD_LOGIC;    
	\vs-\:     IN     STD_LOGIC);
end amplifier;
