-- generated by newgenasym Fri Dec 17 10:00:32 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ldo is
    port (    
	\4\:       IN     STD_LOGIC;    
	ADJ:       OUT    STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      IN     STD_LOGIC);
end ldo;
