// generated by newgenasym  Mon Dec 06 14:02:23 2021


module att7022e (agnd1, agnd2, agnd3, avcc1, avcc2, cf1, cf2, cf3, cf4, cs, din,
        dout, gnd1, gnd2, gnd3, irq, nc1, nc2, osci, osco, refcap,
        reset, revp, sclk, sel, sleep, test, v0n, v0p, v1n, v1p, v2n,
        v2p, v3n, v3p, v4n, v4p, v5n, v5p, v6n, v6p, vcc1, vcc2, vdd);
    input agnd1;
    input agnd2;
    input agnd3;
    input avcc1;
    input avcc2;
    output cf1;
    output cf2;
    output cf3;
    output cf4;
    input cs;
    input din;
    output dout;
    input gnd1;
    input gnd2;
    input gnd3;
    output irq;
    inout nc1;
    inout nc2;
    input osci;
    output osco;
    output refcap;
    input reset;
    output revp;
    input sclk;
    input sel;
    input sleep;
    input test;
    input v0n;
    input v0p;
    input v1n;
    input v1p;
    input v2n;
    input v2p;
    input v3n;
    input v3p;
    input v4n;
    input v4p;
    input v5n;
    input v5p;
    input v6n;
    input v6p;
    input vcc1;
    input vcc2;
    input vdd;


    initial
        begin
        end

endmodule
