// generated by newgenasym  Mon Aug 31 14:27:16 2020


module uc2843 (comp, gnd, isense, \output , \rt/ct , vcc, vfb, vref);
    inout comp;
    inout gnd;
    inout isense;
    inout \output ;
    inout \rt/ct ;
    inout vcc;
    inout vfb;
    inout vref;


    initial
        begin
        end

endmodule
