-- generated by newgenasym Thu Oct 21 09:53:19 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bosa is
    port (    
	GND1:      OUT    STD_LOGIC;    
	GND2:      OUT    STD_LOGIC;    
	GND3:      OUT    STD_LOGIC;    
	GND_R:     INOUT  STD_LOGIC;    
	GND_T:     INOUT  STD_LOGIC;    
	GND_T1:    OUT    STD_LOGIC;    
	GND_T2:    OUT    STD_LOGIC;    
	GND_T3:    OUT    STD_LOGIC;    
	\ld+/pd-\: INOUT  STD_LOGIC;    
	\ld-\:     INOUT  STD_LOGIC;    
	\pd+\:     INOUT  STD_LOGIC;    
	RXN:       INOUT  STD_LOGIC;    
	RXP:       INOUT  STD_LOGIC;    
	VAPD:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end bosa;
