// generated by newgenasym  Thu Nov 05 17:08:31 2020


module rtl8221b (avdd09_1, avdd09_2, avdd09_3, avdd33_1, avdd33_2,
        avdd33_3, avdd33_xtal, \cfg_opt0/gpio15880 ,
        \cfg_opt1/gpio15883 , ckxtal1, ckxtal2, \clkout/synce_clk ,
        dvdd09_1, dvdd09_2, dvdd09_3, dvdd3318, dvdd33_1, dvdd33_2,
        epad, evdd09, gnd, hsin, hsip, hson, hsop, \intb/pmeb ,
        \led0/phyad0 , \led1/phyad1 , \led2/phyad2 , mdc, mdin0, mdin1,
        mdin2, mdin3, mdio, mdip0, mdip1, mdip2, mdip3, \nc/vddreg_1 ,
        \nc/vddreg_2 , nc1, phyrstb, pow_ext_swr, rset,
        \spick/gpio15882/synce_lock , spicsb, \spisi/gpio15881 ,
        spiso);
    input avdd09_1;
    input avdd09_2;
    input avdd09_3;
    input avdd33_1;
    input avdd33_2;
    input avdd33_3;
    input avdd33_xtal;
    inout \cfg_opt0/gpio15880 ;
    inout \cfg_opt1/gpio15883 ;
    input ckxtal1;
    output ckxtal2;
    output \clkout/synce_clk ;
    input dvdd09_1;
    input dvdd09_2;
    input dvdd09_3;
    input dvdd3318;
    input dvdd33_1;
    input dvdd33_2;
    input epad;
    input evdd09;
    input gnd;
    input hsin;
    input hsip;
    output hson;
    inout hsop;
    output \intb/pmeb ;
    output \led0/phyad0 ;
    output \led1/phyad1 ;
    output \led2/phyad2 ;
    input mdc;
    inout mdin0;
    inout mdin1;
    inout mdin2;
    inout mdin3;
    inout mdio;
    inout mdip0;
    inout mdip1;
    inout mdip2;
    inout mdip3;
    input \nc/vddreg_1 ;
    input \nc/vddreg_2 ;
    input nc1;
    input phyrstb;
    inout pow_ext_swr;
    inout rset;
    inout \spick/gpio15882/synce_lock ;
    output spicsb;
    inout \spisi/gpio15881 ;
    input spiso;


    initial
        begin
        end

endmodule
