// generated by newgenasym  Sun Sep 27 14:35:47 2020


module mt7603 (agnd_pmu, antsel0, antsel1,
        \antsel2/trsw/gpio9/wf_trx_qp ,
        \antsel3/trsw_n/gpio10/wf_trx_qn , antsel4, antsel5,
        antsel6, avdd12, avdd12_pcie, avdd16, avdd16_wf0_trx,
        avdd16_wf1_trx, avdd16_wf_rfdig, avdd16_wf_sx,
        avdd33_pcie, avdd33_wf0_tx, avdd33_wf1_tx, avdd33_xtal,
        avss33_1, avss33_2, clk_req_n, clkoutn, clkoutp, epad,
        gpio0, gpio1, gpio13, gpio16, gpio2, gpio3, gpio4, gpio5,
        ldo_rst_n, lx, pcie_ckn, pcie_ckp, pcie_rxn, pcie_rxp,
        pcie_txn, pcie_txp, pcie_vrt, perst_n, pgnd, pvdo, vdd12_1,
        vdd12_2, vdd33_1, vdd33_2, wake_n, wf0_lna_ext, wf0_rfion,
        wf0_rfiop, wf1_lna_ext, wf1_rfion, wf1_rfiop, xtalin);
    input agnd_pmu;
    inout antsel0;
    inout antsel1;
    inout \antsel2/trsw/gpio9/wf_trx_qp ;
    inout \antsel3/trsw_n/gpio10/wf_trx_qn ;
    inout antsel4;
    inout antsel5;
    inout antsel6;
    input avdd12;
    input avdd12_pcie;
    input avdd16;
    input avdd16_wf0_trx;
    input avdd16_wf1_trx;
    input avdd16_wf_rfdig;
    input avdd16_wf_sx;
    input avdd33_pcie;
    input avdd33_wf0_tx;
    input avdd33_wf1_tx;
    input avdd33_xtal;
    input avss33_1;
    input avss33_2;
    inout clk_req_n;
    inout clkoutn;
    inout clkoutp;
    input epad;
    inout gpio0;
    inout gpio1;
    inout gpio13;
    inout gpio16;
    inout gpio2;
    inout gpio3;
    inout gpio4;
    inout gpio5;
    input ldo_rst_n;
    inout lx;
    input pcie_ckn;
    input pcie_ckp;
    inout pcie_rxn;
    inout pcie_rxp;
    inout pcie_txn;
    inout pcie_txp;
    inout pcie_vrt;
    input perst_n;
    input pgnd;
    input pvdo;
    input vdd12_1;
    input vdd12_2;
    input vdd33_1;
    input vdd33_2;
    inout wake_n;
    inout wf0_lna_ext;
    inout wf0_rfion;
    inout wf0_rfiop;
    inout wf1_lna_ext;
    inout wf1_rfion;
    inout wf1_rfiop;
    inout xtalin;


    initial
        begin
        end

endmodule
