// generated by newgenasym  Thu Sep 17 13:32:55 2020


module db9 (gnd1, gnd2, gnd3, gnd4, p1a, p1b, p2a, p2b, p3a, p3b, p4a, p4b,
        p5a, p5b, p6a, p6b, p7a, p7b, p8a, p8b, p9a, p9b);
    input gnd1;
    input gnd2;
    inout gnd3;
    inout gnd4;
    input p1a;
    input p1b;
    input p2a;
    input p2b;
    input p3a;
    input p3b;
    input p4a;
    input p4b;
    input p5a;
    input p5b;
    input p6a;
    input p6b;
    input p7a;
    input p7b;
    input p8a;
    input p8b;
    input p9a;
    input p9b;


    initial
        begin
        end

endmodule
