// generated by newgenasym  Mon Aug 31 14:23:46 2020


module rtl8814 (antsw, antswb, chip_en, clkreqn, epad, gndrx, gnds, gndsps,
        gndsps_1, gpio_0, gpio_1, gpio_10, gpio_11, gpio_12,
        gpio_13, gpio_14, gpio_15, gpio_2, gpio_3, gpio_4, gpio_5,
        gpio_6, \gpio_7/led2 , \gpio_8/led0 , \gpio_9/led1 , hsin, hsip,
        hson, hsop, lx_sps0, lx_sps1, lx_sps2, nc_1, nc_2, nc_3, nc_4,
        nc_5, nc_6, nc_7, nc_8, nc_9, pape_2g_s0, pape_2g_s1,
        pape_2g_s2, pape_2g_s3, pape_5g_s0, pape_5g_s1,
        pape_5g_s2, pape_5g_s3, perstn, refclk_m, refclk_p,
        rf2incs_s0, rf2incs_s1, rf2incs_s2, rf2incs_s3, rf2on_s0,
        rf2on_s1, rf2on_s2, rf2on_s3, rf2op_s0, rf2op_s1, rf2op_s2,
        rf2op_s3, rf5in_s0, rf5in_s1, rf5in_s2, rf5in_s3,
        rf5out_s0, rf5out_s1, rf5out_s2, rf5out_s3, test_s0,
        test_s1, test_s2, test_s3, testpin1, testpin2, trsw_s0,
        trsw_s1, trsw_s2, trsw_s3, trswb_s0, trswb_s1, trswb_s2,
        trswb_s3, vd125g_s0, vd125g_s2, vd12_lobf, vd12_s0,
        vd12_s1, vd12_s2, vd12_s3, vd12_syn, vd12a, vd12d, vd12db,
        vd12dm, vd335g0_s0, vd335g0_s1, vd335g0_s2, vd335g0_s3,
        vd335g1_s0, vd335g1_s1, vd335g1_s2, vd335g1_s3, vd33_lobf,
        vd33_s0, vd33_s1, vd33_s2, vd33_s3, vd33_syn, vd33a,
        vd33io_0, vd33io_1, vd33io_2, vd33s, vdd33d_0, vdd33d_1,
        vdd33sps, vddrx, vddtx, vtssi_s0, vtssi_s1, vtssi_s2,
        vtssi_s3, waken, xi, xo);
    inout antsw;
    inout antswb;
    inout chip_en;
    inout clkreqn;
    inout epad;
    inout gndrx;
    inout gnds;
    inout gndsps;
    inout gndsps_1;
    inout gpio_0;
    inout gpio_1;
    inout gpio_10;
    inout gpio_11;
    inout gpio_12;
    inout gpio_13;
    inout gpio_14;
    inout gpio_15;
    inout gpio_2;
    inout gpio_3;
    inout gpio_4;
    inout gpio_5;
    inout gpio_6;
    inout \gpio_7/led2 ;
    inout \gpio_8/led0 ;
    inout \gpio_9/led1 ;
    inout hsin;
    inout hsip;
    inout hson;
    inout hsop;
    inout lx_sps0;
    inout lx_sps1;
    inout lx_sps2;
    inout nc_1;
    inout nc_2;
    inout nc_3;
    inout nc_4;
    inout nc_5;
    inout nc_6;
    inout nc_7;
    inout nc_8;
    inout nc_9;
    inout pape_2g_s0;
    inout pape_2g_s1;
    inout pape_2g_s2;
    inout pape_2g_s3;
    inout pape_5g_s0;
    inout pape_5g_s1;
    inout pape_5g_s2;
    inout pape_5g_s3;
    inout perstn;
    inout refclk_m;
    inout refclk_p;
    inout rf2incs_s0;
    inout rf2incs_s1;
    inout rf2incs_s2;
    inout rf2incs_s3;
    inout rf2on_s0;
    inout rf2on_s1;
    inout rf2on_s2;
    inout rf2on_s3;
    inout rf2op_s0;
    inout rf2op_s1;
    inout rf2op_s2;
    inout rf2op_s3;
    inout rf5in_s0;
    inout rf5in_s1;
    inout rf5in_s2;
    inout rf5in_s3;
    inout rf5out_s0;
    inout rf5out_s1;
    inout rf5out_s2;
    inout rf5out_s3;
    inout test_s0;
    inout test_s1;
    inout test_s2;
    inout test_s3;
    inout testpin1;
    inout testpin2;
    inout trsw_s0;
    inout trsw_s1;
    inout trsw_s2;
    inout trsw_s3;
    inout trswb_s0;
    inout trswb_s1;
    inout trswb_s2;
    inout trswb_s3;
    inout vd125g_s0;
    inout vd125g_s2;
    inout vd12_lobf;
    inout vd12_s0;
    inout vd12_s1;
    inout vd12_s2;
    inout vd12_s3;
    inout vd12_syn;
    inout vd12a;
    inout vd12d;
    inout vd12db;
    inout vd12dm;
    inout vd335g0_s0;
    inout vd335g0_s1;
    inout vd335g0_s2;
    inout vd335g0_s3;
    inout vd335g1_s0;
    inout vd335g1_s1;
    inout vd335g1_s2;
    inout vd335g1_s3;
    inout vd33_lobf;
    inout vd33_s0;
    inout vd33_s1;
    inout vd33_s2;
    inout vd33_s3;
    inout vd33_syn;
    inout vd33a;
    inout vd33io_0;
    inout vd33io_1;
    inout vd33io_2;
    inout vd33s;
    inout vdd33d_0;
    inout vdd33d_1;
    inout vdd33sps;
    inout vddrx;
    inout vddtx;
    inout vtssi_s0;
    inout vtssi_s1;
    inout vtssi_s2;
    inout vtssi_s3;
    inout waken;
    inout xi;
    inout xo;


    initial
        begin
        end

endmodule
