// generated by newgenasym  Mon Aug 31 15:11:07 2020


module bcm56150k (avdd33_m12, avs0, bs0_clk, bs0_heartbeat,
        bs0_pll_avdd33_t4, bs0_pll_refclkn, bs0_pll_refclkp,
        bs0_pll_testn, bs0_pll_testp, bs0_time_code, bs1_clk,
        bs1_heartbeat, bs1_pll_avdd33_r4, bs1_pll_refclkn,
        bs1_pll_refclkp, bs1_pll_testn, bs1_pll_testp,
        bs1_time_code, bsc_sa0, bsc_sa1, bsc_scl, bsc_sda,
        core_pll_vdd33_v4, direct_scan, dnc_aa29, dnc_aa30,
        dnc_aa33, dnc_ac6, dnc_ac7, dnc_af29, dnc_ag29, dnc_al27,
        dnc_al30, dnc_al6, dnc_al9, dnc_b22, dnc_c22, dnc_c32,
        dnc_d32, dnc_n1, dnc_n12, dnc_n13, dnc_n2, dnc_v1, dnc_v2,
        ext_qs2_clkn, ext_qs2_clkp, ext_rcvrd_clk0,
        ext_rcvrd_clk0_vld, ext_rcvrd_clk1, ext_rcvrd_clk1_vld,
        ext_uc_present, ge0_led_0, ge0_led_1, ge0_led_2, ge0_td0n,
        ge0_td0p, ge0_td1n, ge0_td1p, ge0_td2n, ge0_td2p, ge0_td3n,
        ge0_td3p, ge10_led_0, ge10_led_1, ge10_led_2, ge10_td0n,
        ge10_td0p, ge10_td1n, ge10_td1p, ge10_td2n, ge10_td2p,
        ge10_td3n, ge10_td3p, ge11_led_0, ge11_led_1, ge11_led_2,
        ge11_td0n, ge11_td0p, ge11_td1n, ge11_td1p, ge11_td2n,
        ge11_td2p, ge11_td3n, ge11_td3p, ge12_led_0, ge12_led_1,
        ge12_led_2, ge12_td0n, ge12_td0p, ge12_td1n, ge12_td1p,
        ge12_td2n, ge12_td2p, ge12_td3n, ge12_td3p, ge13_led_0,
        ge13_led_1, ge13_led_2, ge13_td0n, ge13_td0p, ge13_td1n,
        ge13_td1p, ge13_td2n, ge13_td2p, ge13_td3n, ge13_td3p,
        ge14_led_0, ge14_led_1, ge14_led_2, ge14_td0n, ge14_td0p,
        ge14_td1n, ge14_td1p, ge14_td2n, ge14_td2p, ge14_td3n,
        ge14_td3p, ge15_led_0, ge15_led_1, ge15_led_2, ge15_td0n,
        ge15_td0p, ge15_td1n, ge15_td1p, ge15_td2n, ge15_td2p,
        ge15_td3n, ge15_td3p, ge1_led_0, ge1_led_1, ge1_led_2,
        ge1_td0n, ge1_td0p, ge1_td1n, ge1_td1p, ge1_td2n, ge1_td2p,
        ge1_td3n, ge1_td3p, ge2_led_0, ge2_led_1, ge2_led_2,
        ge2_td0n, ge2_td0p, ge2_td1n, ge2_td1p, ge2_td2n, ge2_td2p,
        ge2_td3n, ge2_td3p, ge3_led_0, ge3_led_1, ge3_led_2,
        ge3_td0n, ge3_td0p, ge3_td1n, ge3_td1p, ge3_td2n, ge3_td2p,
        ge3_td3n, ge3_td3p, ge4_led_0, ge4_led_1, ge4_led_2,
        ge4_td0n, ge4_td0p, ge4_td1n, ge4_td1p, ge4_td2n, ge4_td2p,
        ge4_td3n, ge4_td3p, ge5_led_0, ge5_led_1, ge5_led_2,
        ge5_td0n, ge5_td0p, ge5_td1n, ge5_td1p, ge5_td2n, ge5_td2p,
        ge5_td3n, ge5_td3p, ge6_led_0, ge6_led_1, ge6_led_2,
        ge6_td0n, ge6_td0p, ge6_td1n, ge6_td1p, ge6_td2n, ge6_td2p,
        ge6_td3n, ge6_td3p, ge7_led_0, ge7_led_1, ge7_led_2,
        ge7_td0n, ge7_td0p, ge7_td1n, ge7_td1p, ge7_td2n, ge7_td2p,
        ge7_td3n, ge7_td3p, ge8_led_0, ge8_led_1, ge8_led_2,
        ge8_td0n, ge8_td0p, ge8_td1n, ge8_td1p, ge8_td2n, ge8_td2p,
        ge8_td3n, ge8_td3p, ge9_led_0, ge9_led_1, ge9_led_2,
        ge9_td0n, ge9_td0p, ge9_td1n, ge9_td1p, ge9_td2n, ge9_td2p,
        ge9_td3n, ge9_td3p, gen_pll_vdd10_u12, gig_mdc, gig_mdio,
        \global_disable* , gnd_a10, gnd_a13, gnd_a2, gnd_a22,
        gnd_a23, gnd_a25, gnd_a27, gnd_a29, gnd_a31, gnd_a34,
        gnd_aa13, gnd_aa14, gnd_aa15, gnd_aa28, gnd_aa31, gnd_aa32,
        gnd_aa34, gnd_aa35, gnd_aa4, gnd_aa5, gnd_aa8, gnd_ab13,
        gnd_ab14, gnd_ab15, gnd_ab16, gnd_ab17, gnd_ab18, gnd_ab19,
        gnd_ab20, gnd_ab21, gnd_ab22, gnd_ab23, gnd_ab24, gnd_ab29,
        gnd_ab32, gnd_ab4, gnd_ab5, gnd_ab8, gnd_ac12, gnd_ac13,
        gnd_ac14, gnd_ac15, gnd_ac16, gnd_ac17, gnd_ac18, gnd_ac19,
        gnd_ac20, gnd_ac21, gnd_ac22, gnd_ac23, gnd_ac24, gnd_ac28,
        gnd_ac29, gnd_ac30, gnd_ac31, gnd_ac32, gnd_ac33, gnd_ac34,
        gnd_ac35, gnd_ac4, gnd_ac5, gnd_ac8, gnd_ad29, gnd_ad32,
        gnd_ad33, gnd_ad6, gnd_ad7, gnd_ae28, gnd_ae29, gnd_ae30,
        gnd_ae31, gnd_ae32, gnd_ae33, gnd_ae34, gnd_ae35, gnd_ae8,
        gnd_af33, gnd_af4, gnd_ag31, gnd_ag32, gnd_ag33, gnd_ag34,
        gnd_ag35, gnd_ag8, gnd_ah13, gnd_ah14, gnd_ah16, gnd_ah18,
        gnd_ah20, gnd_ah22, gnd_ah23, gnd_ah27, gnd_ah28, gnd_ah33,
        gnd_ah9, gnd_aj12, gnd_aj14, gnd_aj16, gnd_aj18, gnd_aj20,
        gnd_aj22, gnd_aj24, gnd_aj28, gnd_aj29, gnd_aj30, gnd_aj31,
        gnd_aj32, gnd_aj33, gnd_aj34, gnd_aj35, gnd_aj4, gnd_aj5,
        gnd_aj8, gnd_ak10, gnd_ak11, gnd_ak12, gnd_ak14, gnd_ak15,
        gnd_ak16, gnd_ak17, gnd_ak18, gnd_ak19, gnd_ak20, gnd_ak21,
        gnd_ak22, gnd_ak24, gnd_ak25, gnd_ak26, gnd_ak27, gnd_ak28,
        gnd_ak29, gnd_ak30, gnd_ak31, gnd_ak32, gnd_ak5, gnd_ak8,
        gnd_ak9, gnd_al10, gnd_al11, gnd_al13, gnd_al14, gnd_al16,
        gnd_al20, gnd_al22, gnd_al23, gnd_al25, gnd_al26, gnd_al28,
        gnd_al29, gnd_al31, gnd_al5, gnd_al7, gnd_al8, gnd_am12,
        gnd_am15, gnd_am18, gnd_am21, gnd_am24, gnd_am27, gnd_am30,
        gnd_am33, gnd_am4, gnd_am6, gnd_am9, gnd_ap1, gnd_ap2,
        gnd_ap34, gnd_ap35, gnd_ar2, gnd_ar34, gnd_b15, gnd_b17,
        gnd_b2, gnd_b23, gnd_b25, gnd_b27, gnd_b29, gnd_b31,
        gnd_b32, gnd_b33, gnd_b34, gnd_b35, gnd_b7, gnd_c12,
        gnd_c20, gnd_c23, gnd_c24, gnd_c25, gnd_c26, gnd_c27,
        gnd_c28, gnd_c29, gnd_c30, gnd_c31, gnd_c33, gnd_c4, gnd_d1,
        gnd_d11, gnd_d14, gnd_d16, gnd_d18, gnd_d22, gnd_d23,
        gnd_d24, gnd_d25, gnd_d26, gnd_d27, gnd_d28, gnd_d29,
        gnd_d30, gnd_d31, gnd_d33, gnd_d34, gnd_d35, gnd_d4, gnd_d6,
        gnd_d8, gnd_d9, gnd_e12, gnd_e15, gnd_e22, gnd_e24, gnd_e26,
        gnd_e28, gnd_e30, gnd_e32, gnd_e33, gnd_f22, gnd_f24,
        gnd_f26, gnd_f28, gnd_f3, gnd_f30, gnd_f32, gnd_f33,
        gnd_f34, gnd_f35, gnd_f4, gnd_g18, gnd_g23, gnd_g24,
        gnd_g25, gnd_g26, gnd_g27, gnd_g28, gnd_g29, gnd_g30,
        gnd_g31, gnd_g32, gnd_g33, gnd_h10, gnd_h12, gnd_h14,
        gnd_h16, gnd_h18, gnd_h19, gnd_h23, gnd_h24, gnd_h27,
        gnd_h28, gnd_h29, gnd_h32, gnd_h33, gnd_h34, gnd_h35,
        gnd_h8, gnd_h9, gnd_j2, gnd_j28, gnd_j29, gnd_j30, gnd_j31,
        gnd_j32, gnd_j33, gnd_j4, gnd_k29, gnd_k32, gnd_k33,
        gnd_k34, gnd_k35, gnd_k8, gnd_l1, gnd_l2, gnd_l29, gnd_l3,
        gnd_l30, gnd_l31, gnd_l32, gnd_l33, gnd_l34, gnd_l35,
        gnd_l4, gnd_m13, gnd_m14, gnd_m15, gnd_m16, gnd_m17,
        gnd_m18, gnd_m20, gnd_m22, gnd_m28, gnd_m29, gnd_m32,
        gnd_m33, gnd_m4, gnd_m5, gnd_m8, gnd_n14, gnd_n15, gnd_n16,
        gnd_n17, gnd_n18, gnd_n20, gnd_n22, gnd_n23, gnd_n24,
        gnd_n28, gnd_n29, gnd_n3, gnd_n30, gnd_n31, gnd_n32,
        gnd_n33, gnd_n5, gnd_p12, gnd_p13, gnd_p14, gnd_p15,
        gnd_p16, gnd_p17, gnd_p18, gnd_p19, gnd_p20, gnd_p21,
        gnd_p22, gnd_p29, gnd_p3, gnd_p31, gnd_p32, gnd_p4, gnd_p5,
        gnd_p8, gnd_r12, gnd_r13, gnd_r14, gnd_r15, gnd_r16,
        gnd_r17, gnd_r18, gnd_r19, gnd_r20, gnd_r21, gnd_r22,
        gnd_r23, gnd_r24, gnd_r3, gnd_r5, gnd_sense_t17, gnd_t12,
        gnd_t13, gnd_t14, gnd_t15, gnd_t16, gnd_t19, gnd_t20,
        gnd_t21, gnd_t22, gnd_t23, gnd_t24, gnd_t3, gnd_t5, gnd_u13,
        gnd_u14, gnd_u15, gnd_u16, gnd_u17, gnd_u18, gnd_u19,
        gnd_u20, gnd_u21, gnd_u22, gnd_u23, gnd_u24, gnd_u28,
        gnd_u3, gnd_u32, gnd_u4, gnd_u5, gnd_u8, gnd_v12, gnd_v13,
        gnd_v14, gnd_v15, gnd_v3, gnd_v5, gnd_v6, gnd_v7, gnd_v8,
        gnd_w13, gnd_w14, gnd_w15, gnd_w16, gnd_w17, gnd_w18,
        gnd_w19, gnd_w20, gnd_w21, gnd_w22, gnd_w23, gnd_w24,
        gnd_w28, gnd_w3, gnd_w5, gnd_w8, gnd_y12, gnd_y13, gnd_y14,
        gnd_y15, gnd_y32, gnd_y4, gnd_y5, gnd_y8,
        gphy0_bvdd33_aj13, gphy0_pvdd10_ah15, gphy0_pvdd33_aj15,
        gphy0_rdac, gphy1_bvdd33_ak13, gphy1_pvdd10_ah17,
        gphy1_pvdd33_aj17, gphy1_rdac, gphy2_bvdd33_aj23,
        gphy2_pvdd10_ah19, gphy2_pvdd33_aj19, gphy2_rdac,
        gphy3_bvdd33_ak23, gphy3_pvdd10_ah21, gphy3_pvdd33_aj21,
        gphy3_rdac, gphy_avddh_ah10, gphy_avddh_ah11,
        gphy_avddh_ah12, gphy_avddh_ah24, gphy_avddh_ah25,
        gphy_avddh_ah26, gphy_avddh_aj10, gphy_avddh_aj11,
        gphy_avddh_aj25, gphy_avddh_aj26, gphy_avddh_aj27,
        gphy_avddh_aj9, gphy_avddh_al17, gphy_avddh_al18,
        gphy_avddh_al19, gphy_avddl_ad12, gphy_avddl_ad13,
        gphy_avddl_ad14, gphy_avddl_ad15, gphy_avddl_ad16,
        gphy_avddl_ad17, gphy_avddl_ad18, gphy_avddl_ad19,
        gphy_avddl_ad20, gphy_avddl_ad21, gphy_avddl_ad22,
        gphy_avddl_ad23, gphy_avddl_ad24, ip_boot_dev0,
        ip_boot_dev1, ip_boot_dev2, ip_ddr_ad0, ip_ddr_ad1,
        ip_ddr_ad10, ip_ddr_ad11, ip_ddr_ad12, ip_ddr_ad13,
        ip_ddr_ad14, ip_ddr_ad15, ip_ddr_ad2, ip_ddr_ad3,
        ip_ddr_ad4, ip_ddr_ad5, ip_ddr_ad6, ip_ddr_ad7,
        ip_ddr_ad8, ip_ddr_ad9, ip_ddr_avdd15_d15, ip_ddr_ba0,
        ip_ddr_ba1, ip_ddr_ba2, \ip_ddr_cas* , ip_ddr_cke,
        ip_ddr_clk0n, ip_ddr_clk0p, ip_ddr_clk1n, ip_ddr_clk1p,
        ip_ddr_clk_vddo_d12, \ip_ddr_cs0* , \ip_ddr_cs1* ,
        ip_ddr_dm0, ip_ddr_dm1, ip_ddr_dq0, ip_ddr_dq1,
        ip_ddr_dq10, ip_ddr_dq11, ip_ddr_dq12, ip_ddr_dq13,
        ip_ddr_dq14, ip_ddr_dq15, ip_ddr_dq2, ip_ddr_dq3,
        ip_ddr_dq4, ip_ddr_dq5, ip_ddr_dq6, ip_ddr_dq7,
        ip_ddr_dq8, ip_ddr_dq9, ip_ddr_dqs0n, ip_ddr_dqs0p,
        ip_ddr_dqs1n, ip_ddr_dqs1p, ip_ddr_odt, \ip_ddr_ras* ,
        \ip_ddr_rst* , ip_ddr_vddo_a14, ip_ddr_vddo_a18,
        ip_ddr_vddo_a6, ip_ddr_vddo_b1, ip_ddr_vddo_b11,
        ip_ddr_vddo_b21, ip_ddr_vddo_b3, ip_ddr_vddo_c16,
        ip_ddr_vddo_c8, ip_ddr_vddo_d10, ip_ddr_vddo_d13,
        ip_ddr_vddo_d17, ip_ddr_vddo_d19, ip_ddr_vddo_d5,
        ip_ddr_vddo_d7, ip_ddr_vddo_e2, ip_ddr_vddo_g4,
        ip_ddr_vddo_h1, ip_ddr_vddo_h4, ip_ddr_vddo_k2,
        ip_ddr_vref, \ip_ddr_we* , ip_ddr_zq, ip_flash_addr0,
        ip_flash_addr1, ip_flash_addr10, ip_flash_addr11,
        ip_flash_addr12, ip_flash_addr13, ip_flash_addr14,
        ip_flash_addr15, ip_flash_addr16, ip_flash_addr17,
        ip_flash_addr18, ip_flash_addr19, ip_flash_addr2,
        ip_flash_addr20, ip_flash_addr21, ip_flash_addr22,
        ip_flash_addr23, ip_flash_addr24, ip_flash_addr3,
        ip_flash_addr4, ip_flash_addr5, ip_flash_addr6,
        ip_flash_addr7, ip_flash_addr8, ip_flash_addr9,
        \ip_flash_cs0* , \ip_flash_cs1* , ip_flash_data0,
        ip_flash_data1, ip_flash_data10, ip_flash_data11,
        ip_flash_data12, ip_flash_data13, ip_flash_data14,
        ip_flash_data15, ip_flash_data2, ip_flash_data3,
        ip_flash_data4, ip_flash_data5, ip_flash_data6,
        ip_flash_data7, ip_flash_data8, ip_flash_data9,
        \ip_flash_rb* , \ip_flash_re* , ip_flash_vddo_t28,
        ip_flash_vddo_v28, ip_flash_vddo_y28, \ip_flash_we* ,
        ip_gpio0, ip_gpio1, ip_gpio2, ip_gpio3, ip_gpio4, ip_gpio5,
        ip_gpio6, ip_gpio7, ip_mdc, ip_mdio, \ip_pcie_intr* ,
        ip_pcie_perstb, \ip_pcie_pme_wake* , ip_pcie_pvdd_w12,
        ip_pcie_rd0n, ip_pcie_rd0p, ip_pcie_refclkn,
        ip_pcie_refclkp, ip_pcie_td0n, ip_pcie_td0p,
        ip_pcie_tvdd_aa12, ip_pcie_tvdd_ab12, \ip_qspi_cs* ,
        \ip_qspi_hold* , ip_qspi_miso, ip_qspi_mosi, ip_qspi_sck,
        \ip_qspi_wp* , \ip_uart1_cts* , \ip_uart1_dcd* , \ip_uart1_dsr* ,
        \ip_uart1_dtr* , \ip_uart1_ri* , \ip_uart1_rts* , ip_uart1_rx,
        ip_uart1_tx, ip_uart2_rx, ip_uart2_tx, jtag_tce,
        jtag_tce1, jtag_tck, jtag_tdi, jtag_tdo, jtag_tms,
        \jtag_trst* , l1_rcvrd_clk, l1_rcvrd_clk_bkup,
        l1_rcvrd_clk_valid, l1_rcvrd_clk_valid_bkup,
        lc_pll0_avdd33_ad28, lc_pll0_refclkn, lc_pll0_refclkp,
        lc_pll1_avdd33_ab28, lc_pll1_refclkn, lc_pll1_refclkp,
        led_clk, led_data, \led_mii_gpio-spi_sel0 ,
        \led_mii_gpio-spi_sel1 , los_0, los_1, los_2, los_3,
        pcie_clkoutn, pcie_clkoutp, qg_pvdd_af28, qg_pvdd_ag28,
        qg_rd0n, qg_rd0p, qg_rd1n, qg_rd1p, qg_td0n, qg_td0p,
        qg_td1n, qg_td1p, qg_tvdd_af30, qg_tvdd_ag30,
        qg_tvdd_ah29, qg_tvdd_ah30, \sys_reset* , ts_ip_gpio0,
        ts_ip_gpio1, ts_pll_refclkn, ts_pll_refclkp,
        ts_pll_vdd33_w4, vdd33_ad8, vdd33_af8, vdd33_h11,
        vdd33_h13, vdd33_h15, vdd33_h17, vdd33_l8, vdd33_n8,
        vdd33_r8, vdd_sense_t18, vddc_aa16, vddc_aa17, vddc_aa18,
        vddc_aa19, vddc_aa20, vddc_aa21, vddc_aa22, vddc_aa23,
        vddc_aa24, vddc_v16, vddc_v17, vddc_v18, vddc_v19,
        vddc_v20, vddc_v21, vddc_v22, vddc_v23, vddc_v24, vddc_y16,
        vddc_y17, vddc_y18, vddc_y19, vddc_y20, vddc_y21, vddc_y22,
        vddc_y23, vddc_y24, wc0_pvdd_k28, wc0_pvdd_l28, wc0_rd0n,
        wc0_rd0p, wc0_rd1n, wc0_rd1p, wc0_rd2n, wc0_rd2p, wc0_rd3n,
        wc0_rd3p, wc0_refclkn, wc0_refclkp, wc0_rx_avdd_m23,
        wc0_rx_avdd_m24, wc0_td0n, wc0_td0p, wc0_td1n, wc0_td1p,
        wc0_td2n, wc0_td2p, wc0_td3n, wc0_td3p, wc0_tx_avdd_p23,
        wc0_tx_avdd_p24, wc1_pvdd_h25, wc1_pvdd_h26, wc1_rd0n,
        wc1_rd0p, wc1_rd1n, wc1_rd1p, wc1_rd2n, wc1_rd2p, wc1_rd3n,
        wc1_rd3p, wc1_refclkn, wc1_refclkp, wc1_rx_avdd_m21,
        wc1_rx_avdd_n21, wc1_td0n, wc1_td0p, wc1_td1n, wc1_td1p,
        wc1_td2n, wc1_td2p, wc1_td3n, wc1_td3p, wc1_tx_avdd_m19,
        wc1_tx_avdd_n19, xg_mdc, xg_mdio, xg_pll2_avdd33_m3,
        xg_pll2_refclkn, xg_pll2_refclkp, xg_vddo,
        xtal_avdd_ab33, xtaln, xtalp);
    input avdd33_m12;
    inout avs0;
    inout bs0_clk;
    inout bs0_heartbeat;
    input bs0_pll_avdd33_t4;
    inout bs0_pll_refclkn;
    inout bs0_pll_refclkp;
    inout bs0_pll_testn;
    inout bs0_pll_testp;
    inout bs0_time_code;
    inout bs1_clk;
    inout bs1_heartbeat;
    input bs1_pll_avdd33_r4;
    inout bs1_pll_refclkn;
    inout bs1_pll_refclkp;
    inout bs1_pll_testn;
    inout bs1_pll_testp;
    inout bs1_time_code;
    inout bsc_sa0;
    inout bsc_sa1;
    inout bsc_scl;
    inout bsc_sda;
    input core_pll_vdd33_v4;
    inout direct_scan;
    inout dnc_aa29;
    inout dnc_aa30;
    inout dnc_aa33;
    inout dnc_ac6;
    inout dnc_ac7;
    inout dnc_af29;
    inout dnc_ag29;
    inout dnc_al27;
    inout dnc_al30;
    inout dnc_al6;
    inout dnc_al9;
    inout dnc_b22;
    inout dnc_c22;
    inout dnc_c32;
    inout dnc_d32;
    inout dnc_n1;
    inout dnc_n12;
    inout dnc_n13;
    inout dnc_n2;
    inout dnc_v1;
    inout dnc_v2;
    inout ext_qs2_clkn;
    inout ext_qs2_clkp;
    inout ext_rcvrd_clk0;
    inout ext_rcvrd_clk0_vld;
    inout ext_rcvrd_clk1;
    inout ext_rcvrd_clk1_vld;
    inout ext_uc_present;
    inout ge0_led_0;
    inout ge0_led_1;
    inout ge0_led_2;
    inout ge0_td0n;
    inout ge0_td0p;
    inout ge0_td1n;
    inout ge0_td1p;
    inout ge0_td2n;
    inout ge0_td2p;
    inout ge0_td3n;
    inout ge0_td3p;
    inout ge10_led_0;
    inout ge10_led_1;
    inout ge10_led_2;
    inout ge10_td0n;
    inout ge10_td0p;
    inout ge10_td1n;
    inout ge10_td1p;
    inout ge10_td2n;
    inout ge10_td2p;
    inout ge10_td3n;
    inout ge10_td3p;
    inout ge11_led_0;
    inout ge11_led_1;
    inout ge11_led_2;
    inout ge11_td0n;
    inout ge11_td0p;
    inout ge11_td1n;
    inout ge11_td1p;
    inout ge11_td2n;
    inout ge11_td2p;
    inout ge11_td3n;
    inout ge11_td3p;
    inout ge12_led_0;
    inout ge12_led_1;
    inout ge12_led_2;
    inout ge12_td0n;
    inout ge12_td0p;
    inout ge12_td1n;
    inout ge12_td1p;
    inout ge12_td2n;
    inout ge12_td2p;
    inout ge12_td3n;
    inout ge12_td3p;
    inout ge13_led_0;
    inout ge13_led_1;
    inout ge13_led_2;
    inout ge13_td0n;
    inout ge13_td0p;
    inout ge13_td1n;
    inout ge13_td1p;
    inout ge13_td2n;
    inout ge13_td2p;
    inout ge13_td3n;
    inout ge13_td3p;
    inout ge14_led_0;
    inout ge14_led_1;
    inout ge14_led_2;
    inout ge14_td0n;
    inout ge14_td0p;
    inout ge14_td1n;
    inout ge14_td1p;
    inout ge14_td2n;
    inout ge14_td2p;
    inout ge14_td3n;
    inout ge14_td3p;
    inout ge15_led_0;
    inout ge15_led_1;
    inout ge15_led_2;
    inout ge15_td0n;
    inout ge15_td0p;
    inout ge15_td1n;
    inout ge15_td1p;
    inout ge15_td2n;
    inout ge15_td2p;
    inout ge15_td3n;
    inout ge15_td3p;
    inout ge1_led_0;
    inout ge1_led_1;
    inout ge1_led_2;
    inout ge1_td0n;
    inout ge1_td0p;
    inout ge1_td1n;
    inout ge1_td1p;
    inout ge1_td2n;
    inout ge1_td2p;
    inout ge1_td3n;
    inout ge1_td3p;
    inout ge2_led_0;
    inout ge2_led_1;
    inout ge2_led_2;
    inout ge2_td0n;
    inout ge2_td0p;
    inout ge2_td1n;
    inout ge2_td1p;
    inout ge2_td2n;
    inout ge2_td2p;
    inout ge2_td3n;
    inout ge2_td3p;
    inout ge3_led_0;
    inout ge3_led_1;
    inout ge3_led_2;
    inout ge3_td0n;
    inout ge3_td0p;
    inout ge3_td1n;
    inout ge3_td1p;
    inout ge3_td2n;
    inout ge3_td2p;
    inout ge3_td3n;
    inout ge3_td3p;
    inout ge4_led_0;
    inout ge4_led_1;
    inout ge4_led_2;
    inout ge4_td0n;
    inout ge4_td0p;
    inout ge4_td1n;
    inout ge4_td1p;
    inout ge4_td2n;
    inout ge4_td2p;
    inout ge4_td3n;
    inout ge4_td3p;
    inout ge5_led_0;
    inout ge5_led_1;
    inout ge5_led_2;
    inout ge5_td0n;
    inout ge5_td0p;
    inout ge5_td1n;
    inout ge5_td1p;
    inout ge5_td2n;
    inout ge5_td2p;
    inout ge5_td3n;
    inout ge5_td3p;
    inout ge6_led_0;
    inout ge6_led_1;
    inout ge6_led_2;
    inout ge6_td0n;
    inout ge6_td0p;
    inout ge6_td1n;
    inout ge6_td1p;
    inout ge6_td2n;
    inout ge6_td2p;
    inout ge6_td3n;
    inout ge6_td3p;
    inout ge7_led_0;
    inout ge7_led_1;
    inout ge7_led_2;
    inout ge7_td0n;
    inout ge7_td0p;
    inout ge7_td1n;
    inout ge7_td1p;
    inout ge7_td2n;
    inout ge7_td2p;
    inout ge7_td3n;
    inout ge7_td3p;
    inout ge8_led_0;
    inout ge8_led_1;
    inout ge8_led_2;
    inout ge8_td0n;
    inout ge8_td0p;
    inout ge8_td1n;
    inout ge8_td1p;
    inout ge8_td2n;
    inout ge8_td2p;
    inout ge8_td3n;
    inout ge8_td3p;
    inout ge9_led_0;
    inout ge9_led_1;
    inout ge9_led_2;
    inout ge9_td0n;
    inout ge9_td0p;
    inout ge9_td1n;
    inout ge9_td1p;
    inout ge9_td2n;
    inout ge9_td2p;
    inout ge9_td3n;
    inout ge9_td3p;
    input gen_pll_vdd10_u12;
    inout gig_mdc;
    inout gig_mdio;
    inout \global_disable* ;
    input gnd_a10;
    input gnd_a13;
    input gnd_a2;
    input gnd_a22;
    input gnd_a23;
    input gnd_a25;
    input gnd_a27;
    input gnd_a29;
    input gnd_a31;
    input gnd_a34;
    input gnd_aa13;
    input gnd_aa14;
    input gnd_aa15;
    input gnd_aa28;
    inout gnd_aa31;
    inout gnd_aa32;
    input gnd_aa34;
    input gnd_aa35;
    inout gnd_aa4;
    input gnd_aa5;
    input gnd_aa8;
    input gnd_ab13;
    input gnd_ab14;
    input gnd_ab15;
    input gnd_ab16;
    input gnd_ab17;
    input gnd_ab18;
    input gnd_ab19;
    input gnd_ab20;
    input gnd_ab21;
    input gnd_ab22;
    input gnd_ab23;
    input gnd_ab24;
    input gnd_ab29;
    input gnd_ab32;
    inout gnd_ab4;
    input gnd_ab5;
    input gnd_ab8;
    input gnd_ac12;
    input gnd_ac13;
    input gnd_ac14;
    input gnd_ac15;
    input gnd_ac16;
    input gnd_ac17;
    input gnd_ac18;
    input gnd_ac19;
    input gnd_ac20;
    input gnd_ac21;
    input gnd_ac22;
    input gnd_ac23;
    input gnd_ac24;
    input gnd_ac28;
    input gnd_ac29;
    input gnd_ac30;
    inout gnd_ac31;
    inout gnd_ac32;
    input gnd_ac33;
    input gnd_ac34;
    input gnd_ac35;
    input gnd_ac4;
    input gnd_ac5;
    input gnd_ac8;
    input gnd_ad29;
    input gnd_ad32;
    input gnd_ad33;
    inout gnd_ad6;
    inout gnd_ad7;
    input gnd_ae28;
    input gnd_ae29;
    input gnd_ae30;
    input gnd_ae31;
    input gnd_ae32;
    input gnd_ae33;
    input gnd_ae34;
    input gnd_ae35;
    input gnd_ae8;
    input gnd_af33;
    input gnd_af4;
    input gnd_ag31;
    input gnd_ag32;
    input gnd_ag33;
    input gnd_ag34;
    input gnd_ag35;
    input gnd_ag8;
    input gnd_ah13;
    input gnd_ah14;
    input gnd_ah16;
    input gnd_ah18;
    input gnd_ah20;
    input gnd_ah22;
    input gnd_ah23;
    input gnd_ah27;
    input gnd_ah28;
    input gnd_ah33;
    input gnd_ah9;
    input gnd_aj12;
    input gnd_aj14;
    input gnd_aj16;
    input gnd_aj18;
    input gnd_aj20;
    input gnd_aj22;
    input gnd_aj24;
    input gnd_aj28;
    input gnd_aj29;
    input gnd_aj30;
    input gnd_aj31;
    input gnd_aj32;
    input gnd_aj33;
    input gnd_aj34;
    input gnd_aj35;
    input gnd_aj4;
    input gnd_aj5;
    input gnd_aj8;
    input gnd_ak10;
    input gnd_ak11;
    input gnd_ak12;
    input gnd_ak14;
    input gnd_ak15;
    input gnd_ak16;
    input gnd_ak17;
    input gnd_ak18;
    input gnd_ak19;
    input gnd_ak20;
    input gnd_ak21;
    input gnd_ak22;
    input gnd_ak24;
    input gnd_ak25;
    input gnd_ak26;
    input gnd_ak27;
    input gnd_ak28;
    input gnd_ak29;
    input gnd_ak30;
    input gnd_ak31;
    input gnd_ak32;
    input gnd_ak5;
    input gnd_ak8;
    input gnd_ak9;
    input gnd_al10;
    input gnd_al11;
    input gnd_al13;
    input gnd_al14;
    input gnd_al16;
    input gnd_al20;
    input gnd_al22;
    input gnd_al23;
    input gnd_al25;
    input gnd_al26;
    input gnd_al28;
    input gnd_al29;
    input gnd_al31;
    input gnd_al5;
    input gnd_al7;
    input gnd_al8;
    input gnd_am12;
    input gnd_am15;
    input gnd_am18;
    input gnd_am21;
    input gnd_am24;
    input gnd_am27;
    input gnd_am30;
    input gnd_am33;
    input gnd_am4;
    input gnd_am6;
    input gnd_am9;
    input gnd_ap1;
    input gnd_ap2;
    input gnd_ap34;
    input gnd_ap35;
    input gnd_ar2;
    input gnd_ar34;
    input gnd_b15;
    input gnd_b17;
    input gnd_b2;
    input gnd_b23;
    input gnd_b25;
    input gnd_b27;
    input gnd_b29;
    input gnd_b31;
    input gnd_b32;
    input gnd_b33;
    input gnd_b34;
    input gnd_b35;
    input gnd_b7;
    input gnd_c12;
    input gnd_c20;
    input gnd_c23;
    input gnd_c24;
    input gnd_c25;
    input gnd_c26;
    input gnd_c27;
    input gnd_c28;
    input gnd_c29;
    input gnd_c30;
    input gnd_c31;
    input gnd_c33;
    input gnd_c4;
    input gnd_d1;
    input gnd_d11;
    input gnd_d14;
    input gnd_d16;
    input gnd_d18;
    input gnd_d22;
    input gnd_d23;
    input gnd_d24;
    input gnd_d25;
    input gnd_d26;
    input gnd_d27;
    input gnd_d28;
    input gnd_d29;
    input gnd_d30;
    input gnd_d31;
    input gnd_d33;
    input gnd_d34;
    input gnd_d35;
    input gnd_d4;
    input gnd_d6;
    input gnd_d8;
    input gnd_d9;
    input gnd_e12;
    input gnd_e15;
    input gnd_e22;
    input gnd_e24;
    input gnd_e26;
    input gnd_e28;
    input gnd_e30;
    input gnd_e32;
    input gnd_e33;
    input gnd_f22;
    input gnd_f24;
    input gnd_f26;
    input gnd_f28;
    input gnd_f3;
    input gnd_f30;
    input gnd_f32;
    input gnd_f33;
    input gnd_f34;
    input gnd_f35;
    input gnd_f4;
    inout gnd_g18;
    input gnd_g23;
    input gnd_g24;
    input gnd_g25;
    input gnd_g26;
    input gnd_g27;
    input gnd_g28;
    input gnd_g29;
    input gnd_g30;
    input gnd_g31;
    input gnd_g32;
    input gnd_g33;
    input gnd_h10;
    input gnd_h12;
    input gnd_h14;
    input gnd_h16;
    input gnd_h18;
    input gnd_h19;
    input gnd_h23;
    input gnd_h24;
    input gnd_h27;
    input gnd_h28;
    input gnd_h29;
    input gnd_h32;
    input gnd_h33;
    input gnd_h34;
    input gnd_h35;
    input gnd_h8;
    inout gnd_h9;
    input gnd_j2;
    input gnd_j28;
    input gnd_j29;
    input gnd_j30;
    input gnd_j31;
    input gnd_j32;
    input gnd_j33;
    input gnd_j4;
    input gnd_k29;
    input gnd_k32;
    input gnd_k33;
    input gnd_k34;
    input gnd_k35;
    input gnd_k8;
    input gnd_l1;
    input gnd_l2;
    input gnd_l29;
    input gnd_l3;
    input gnd_l30;
    input gnd_l31;
    input gnd_l32;
    input gnd_l33;
    input gnd_l34;
    input gnd_l35;
    input gnd_l4;
    input gnd_m13;
    input gnd_m14;
    input gnd_m15;
    input gnd_m16;
    input gnd_m17;
    input gnd_m18;
    input gnd_m20;
    input gnd_m22;
    input gnd_m28;
    input gnd_m29;
    input gnd_m32;
    input gnd_m33;
    input gnd_m4;
    input gnd_m5;
    input gnd_m8;
    input gnd_n14;
    input gnd_n15;
    input gnd_n16;
    input gnd_n17;
    input gnd_n18;
    input gnd_n20;
    input gnd_n22;
    input gnd_n23;
    input gnd_n24;
    input gnd_n28;
    input gnd_n29;
    input gnd_n3;
    input gnd_n30;
    input gnd_n31;
    input gnd_n32;
    input gnd_n33;
    input gnd_n5;
    input gnd_p12;
    input gnd_p13;
    input gnd_p14;
    input gnd_p15;
    input gnd_p16;
    input gnd_p17;
    input gnd_p18;
    input gnd_p19;
    input gnd_p20;
    input gnd_p21;
    input gnd_p22;
    input gnd_p29;
    input gnd_p3;
    input gnd_p31;
    input gnd_p32;
    inout gnd_p4;
    inout gnd_p5;
    input gnd_p8;
    input gnd_r12;
    input gnd_r13;
    input gnd_r14;
    input gnd_r15;
    input gnd_r16;
    input gnd_r17;
    input gnd_r18;
    input gnd_r19;
    input gnd_r20;
    input gnd_r21;
    input gnd_r22;
    input gnd_r23;
    input gnd_r24;
    input gnd_r3;
    input gnd_r5;
    inout gnd_sense_t17;
    input gnd_t12;
    input gnd_t13;
    input gnd_t14;
    input gnd_t15;
    input gnd_t16;
    input gnd_t19;
    input gnd_t20;
    input gnd_t21;
    input gnd_t22;
    input gnd_t23;
    input gnd_t24;
    input gnd_t3;
    input gnd_t5;
    input gnd_u13;
    input gnd_u14;
    input gnd_u15;
    input gnd_u16;
    input gnd_u17;
    input gnd_u18;
    input gnd_u19;
    input gnd_u20;
    input gnd_u21;
    input gnd_u22;
    input gnd_u23;
    input gnd_u24;
    input gnd_u28;
    input gnd_u3;
    input gnd_u32;
    inout gnd_u4;
    inout gnd_u5;
    input gnd_u8;
    input gnd_v12;
    input gnd_v13;
    input gnd_v14;
    input gnd_v15;
    input gnd_v3;
    input gnd_v5;
    input gnd_v6;
    input gnd_v7;
    input gnd_v8;
    input gnd_w13;
    input gnd_w14;
    input gnd_w15;
    input gnd_w16;
    input gnd_w17;
    input gnd_w18;
    input gnd_w19;
    input gnd_w20;
    input gnd_w21;
    input gnd_w22;
    input gnd_w23;
    input gnd_w24;
    input gnd_w28;
    input gnd_w3;
    input gnd_w5;
    input gnd_w8;
    input gnd_y12;
    input gnd_y13;
    input gnd_y14;
    input gnd_y15;
    input gnd_y32;
    inout gnd_y4;
    input gnd_y5;
    input gnd_y8;
    input gphy0_bvdd33_aj13;
    input gphy0_pvdd10_ah15;
    input gphy0_pvdd33_aj15;
    inout gphy0_rdac;
    input gphy1_bvdd33_ak13;
    input gphy1_pvdd10_ah17;
    input gphy1_pvdd33_aj17;
    inout gphy1_rdac;
    input gphy2_bvdd33_aj23;
    input gphy2_pvdd10_ah19;
    input gphy2_pvdd33_aj19;
    inout gphy2_rdac;
    input gphy3_bvdd33_ak23;
    input gphy3_pvdd10_ah21;
    input gphy3_pvdd33_aj21;
    inout gphy3_rdac;
    input gphy_avddh_ah10;
    input gphy_avddh_ah11;
    input gphy_avddh_ah12;
    input gphy_avddh_ah24;
    input gphy_avddh_ah25;
    input gphy_avddh_ah26;
    input gphy_avddh_aj10;
    input gphy_avddh_aj11;
    input gphy_avddh_aj25;
    input gphy_avddh_aj26;
    input gphy_avddh_aj27;
    input gphy_avddh_aj9;
    input gphy_avddh_al17;
    input gphy_avddh_al18;
    input gphy_avddh_al19;
    input gphy_avddl_ad12;
    input gphy_avddl_ad13;
    input gphy_avddl_ad14;
    input gphy_avddl_ad15;
    input gphy_avddl_ad16;
    input gphy_avddl_ad17;
    input gphy_avddl_ad18;
    input gphy_avddl_ad19;
    input gphy_avddl_ad20;
    input gphy_avddl_ad21;
    input gphy_avddl_ad22;
    input gphy_avddl_ad23;
    input gphy_avddl_ad24;
    inout ip_boot_dev0;
    inout ip_boot_dev1;
    inout ip_boot_dev2;
    inout ip_ddr_ad0;
    inout ip_ddr_ad1;
    inout ip_ddr_ad10;
    inout ip_ddr_ad11;
    inout ip_ddr_ad12;
    inout ip_ddr_ad13;
    inout ip_ddr_ad14;
    inout ip_ddr_ad15;
    inout ip_ddr_ad2;
    inout ip_ddr_ad3;
    inout ip_ddr_ad4;
    inout ip_ddr_ad5;
    inout ip_ddr_ad6;
    inout ip_ddr_ad7;
    inout ip_ddr_ad8;
    inout ip_ddr_ad9;
    input ip_ddr_avdd15_d15;
    inout ip_ddr_ba0;
    inout ip_ddr_ba1;
    inout ip_ddr_ba2;
    inout \ip_ddr_cas* ;
    inout ip_ddr_cke;
    inout ip_ddr_clk0n;
    inout ip_ddr_clk0p;
    inout ip_ddr_clk1n;
    inout ip_ddr_clk1p;
    input ip_ddr_clk_vddo_d12;
    inout \ip_ddr_cs0* ;
    inout \ip_ddr_cs1* ;
    inout ip_ddr_dm0;
    inout ip_ddr_dm1;
    inout ip_ddr_dq0;
    inout ip_ddr_dq1;
    inout ip_ddr_dq10;
    inout ip_ddr_dq11;
    inout ip_ddr_dq12;
    inout ip_ddr_dq13;
    inout ip_ddr_dq14;
    inout ip_ddr_dq15;
    inout ip_ddr_dq2;
    inout ip_ddr_dq3;
    inout ip_ddr_dq4;
    inout ip_ddr_dq5;
    inout ip_ddr_dq6;
    inout ip_ddr_dq7;
    inout ip_ddr_dq8;
    inout ip_ddr_dq9;
    inout ip_ddr_dqs0n;
    inout ip_ddr_dqs0p;
    inout ip_ddr_dqs1n;
    inout ip_ddr_dqs1p;
    inout ip_ddr_odt;
    inout \ip_ddr_ras* ;
    inout \ip_ddr_rst* ;
    input ip_ddr_vddo_a14;
    input ip_ddr_vddo_a18;
    input ip_ddr_vddo_a6;
    input ip_ddr_vddo_b1;
    input ip_ddr_vddo_b11;
    input ip_ddr_vddo_b21;
    input ip_ddr_vddo_b3;
    input ip_ddr_vddo_c16;
    input ip_ddr_vddo_c8;
    input ip_ddr_vddo_d10;
    input ip_ddr_vddo_d13;
    input ip_ddr_vddo_d17;
    input ip_ddr_vddo_d19;
    input ip_ddr_vddo_d5;
    input ip_ddr_vddo_d7;
    input ip_ddr_vddo_e2;
    input ip_ddr_vddo_g4;
    input ip_ddr_vddo_h1;
    input ip_ddr_vddo_h4;
    input ip_ddr_vddo_k2;
    inout ip_ddr_vref;
    inout \ip_ddr_we* ;
    inout ip_ddr_zq;
    inout ip_flash_addr0;
    inout ip_flash_addr1;
    inout ip_flash_addr10;
    inout ip_flash_addr11;
    inout ip_flash_addr12;
    inout ip_flash_addr13;
    inout ip_flash_addr14;
    inout ip_flash_addr15;
    inout ip_flash_addr16;
    inout ip_flash_addr17;
    inout ip_flash_addr18;
    inout ip_flash_addr19;
    inout ip_flash_addr2;
    inout ip_flash_addr20;
    inout ip_flash_addr21;
    inout ip_flash_addr22;
    inout ip_flash_addr23;
    inout ip_flash_addr24;
    inout ip_flash_addr3;
    inout ip_flash_addr4;
    inout ip_flash_addr5;
    inout ip_flash_addr6;
    inout ip_flash_addr7;
    inout ip_flash_addr8;
    inout ip_flash_addr9;
    inout \ip_flash_cs0* ;
    inout \ip_flash_cs1* ;
    inout ip_flash_data0;
    inout ip_flash_data1;
    inout ip_flash_data10;
    inout ip_flash_data11;
    inout ip_flash_data12;
    inout ip_flash_data13;
    inout ip_flash_data14;
    inout ip_flash_data15;
    inout ip_flash_data2;
    inout ip_flash_data3;
    inout ip_flash_data4;
    inout ip_flash_data5;
    inout ip_flash_data6;
    inout ip_flash_data7;
    inout ip_flash_data8;
    inout ip_flash_data9;
    inout \ip_flash_rb* ;
    inout \ip_flash_re* ;
    input ip_flash_vddo_t28;
    input ip_flash_vddo_v28;
    input ip_flash_vddo_y28;
    inout \ip_flash_we* ;
    inout ip_gpio0;
    inout ip_gpio1;
    inout ip_gpio2;
    inout ip_gpio3;
    inout ip_gpio4;
    inout ip_gpio5;
    inout ip_gpio6;
    inout ip_gpio7;
    inout ip_mdc;
    inout ip_mdio;
    inout \ip_pcie_intr* ;
    inout ip_pcie_perstb;
    inout \ip_pcie_pme_wake* ;
    input ip_pcie_pvdd_w12;
    inout ip_pcie_rd0n;
    inout ip_pcie_rd0p;
    inout ip_pcie_refclkn;
    inout ip_pcie_refclkp;
    inout ip_pcie_td0n;
    inout ip_pcie_td0p;
    input ip_pcie_tvdd_aa12;
    input ip_pcie_tvdd_ab12;
    inout \ip_qspi_cs* ;
    inout \ip_qspi_hold* ;
    inout ip_qspi_miso;
    inout ip_qspi_mosi;
    inout ip_qspi_sck;
    inout \ip_qspi_wp* ;
    inout \ip_uart1_cts* ;
    inout \ip_uart1_dcd* ;
    inout \ip_uart1_dsr* ;
    inout \ip_uart1_dtr* ;
    inout \ip_uart1_ri* ;
    inout \ip_uart1_rts* ;
    inout ip_uart1_rx;
    inout ip_uart1_tx;
    inout ip_uart2_rx;
    inout ip_uart2_tx;
    inout jtag_tce;
    inout jtag_tce1;
    inout jtag_tck;
    inout jtag_tdi;
    inout jtag_tdo;
    inout jtag_tms;
    inout \jtag_trst* ;
    inout l1_rcvrd_clk;
    inout l1_rcvrd_clk_bkup;
    inout l1_rcvrd_clk_valid;
    inout l1_rcvrd_clk_valid_bkup;
    input lc_pll0_avdd33_ad28;
    inout lc_pll0_refclkn;
    inout lc_pll0_refclkp;
    input lc_pll1_avdd33_ab28;
    inout lc_pll1_refclkn;
    inout lc_pll1_refclkp;
    inout led_clk;
    inout led_data;
    inout \led_mii_gpio-spi_sel0 ;
    inout \led_mii_gpio-spi_sel1 ;
    inout los_0;
    inout los_1;
    inout los_2;
    inout los_3;
    inout pcie_clkoutn;
    inout pcie_clkoutp;
    input qg_pvdd_af28;
    input qg_pvdd_ag28;
    inout qg_rd0n;
    inout qg_rd0p;
    inout qg_rd1n;
    inout qg_rd1p;
    inout qg_td0n;
    inout qg_td0p;
    inout qg_td1n;
    inout qg_td1p;
    input qg_tvdd_af30;
    input qg_tvdd_ag30;
    input qg_tvdd_ah29;
    input qg_tvdd_ah30;
    inout \sys_reset* ;
    inout ts_ip_gpio0;
    inout ts_ip_gpio1;
    inout ts_pll_refclkn;
    inout ts_pll_refclkp;
    input ts_pll_vdd33_w4;
    input vdd33_ad8;
    input vdd33_af8;
    input vdd33_h11;
    input vdd33_h13;
    input vdd33_h15;
    input vdd33_h17;
    input vdd33_l8;
    input vdd33_n8;
    input vdd33_r8;
    inout vdd_sense_t18;
    input vddc_aa16;
    input vddc_aa17;
    input vddc_aa18;
    input vddc_aa19;
    input vddc_aa20;
    input vddc_aa21;
    input vddc_aa22;
    input vddc_aa23;
    input vddc_aa24;
    input vddc_v16;
    input vddc_v17;
    input vddc_v18;
    input vddc_v19;
    input vddc_v20;
    input vddc_v21;
    input vddc_v22;
    input vddc_v23;
    input vddc_v24;
    input vddc_y16;
    input vddc_y17;
    input vddc_y18;
    input vddc_y19;
    input vddc_y20;
    input vddc_y21;
    input vddc_y22;
    input vddc_y23;
    input vddc_y24;
    input wc0_pvdd_k28;
    input wc0_pvdd_l28;
    inout wc0_rd0n;
    inout wc0_rd0p;
    inout wc0_rd1n;
    inout wc0_rd1p;
    inout wc0_rd2n;
    inout wc0_rd2p;
    inout wc0_rd3n;
    inout wc0_rd3p;
    inout wc0_refclkn;
    inout wc0_refclkp;
    input wc0_rx_avdd_m23;
    input wc0_rx_avdd_m24;
    inout wc0_td0n;
    inout wc0_td0p;
    inout wc0_td1n;
    inout wc0_td1p;
    inout wc0_td2n;
    inout wc0_td2p;
    inout wc0_td3n;
    inout wc0_td3p;
    input wc0_tx_avdd_p23;
    input wc0_tx_avdd_p24;
    input wc1_pvdd_h25;
    input wc1_pvdd_h26;
    inout wc1_rd0n;
    inout wc1_rd0p;
    inout wc1_rd1n;
    inout wc1_rd1p;
    inout wc1_rd2n;
    inout wc1_rd2p;
    inout wc1_rd3n;
    inout wc1_rd3p;
    inout wc1_refclkn;
    inout wc1_refclkp;
    input wc1_rx_avdd_m21;
    input wc1_rx_avdd_n21;
    inout wc1_td0n;
    inout wc1_td0p;
    inout wc1_td1n;
    inout wc1_td1p;
    inout wc1_td2n;
    inout wc1_td2p;
    inout wc1_td3n;
    inout wc1_td3p;
    input wc1_tx_avdd_m19;
    input wc1_tx_avdd_n19;
    inout xg_mdc;
    inout xg_mdio;
    input xg_pll2_avdd33_m3;
    inout xg_pll2_refclkn;
    inout xg_pll2_refclkp;
    input xg_vddo;
    input xtal_avdd_ab33;
    inout xtaln;
    inout xtalp;


    initial
        begin
        end

endmodule
