-- generated by newgenasym Mon May 22 15:24:47 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rf_sw is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end rf_sw;
