// generated by newgenasym  Mon Aug 31 14:04:41 2020


module lcmxo2 (\b0/done , \b0/initn , \b0/jtagenb , \b0/pclkc0_1 , \b0/pclkt0_1 ,
        \b0/programn , \b0/scl/pclkt0_0 , \b0/sda/pclkc0_0 , \b0/tck ,
        \b0/tdi , \b0/tdo , \b0/tms , b0_io00, b0_io01, b0_io02, b0_io03,
        b0_io04, b0_io05, b0_io06, b0_io07, b0_io08, b0_io09,
        b0_io10, b0_io11, b0_io12, b0_io13, b0_io14, b0_io15,
        \b1/pclkc1_0 , \b1/pclkt1_0 , b1_io00, b1_io01, b1_io02,
        b1_io03, b1_io04, b1_io05, b1_io06, b1_io07, b1_io08,
        b1_io09, b1_io10, b1_io11, b1_io12, b1_io13, b1_io14,
        b1_io15, b1_io16, b1_io17, b1_io18, b1_io19, b1_io20,
        b1_io21, b1_io22, b1_io23, b1_nc0, b1_nc1, b1_nc2,
        \b2//mclk/cclk , \b2/csspin , \b2/pclkc2_0 , \b2/pclkc2_1 ,
        \b2/pclkt2_0 , \b2/pclkt2_1 , \b2/si/sispi , \b2/sn , \b2/so/spiso ,
        b2_io00, b2_io01, b2_io02, b2_io03, b2_io04, b2_io05,
        b2_io06, b2_io07, b2_io08, b2_io09, b2_io10, b2_io11,
        b2_io12, b2_io13, b2_io14, b2_io15, b2_io16, b2_io17,
        b2_io18, b2_nc, \b3/l_gpllc_fb , \b3/l_gpllc_in ,
        \b3/l_gpllt_fb , \b3/l_gpllt_in , \b3/pclkc3_0 , \b3/pclkc3_1 ,
        \b3/pclkc3_2 , \b3/pclkt3_0 , \b3/pclkt3_1 , \b3/pclkt3_2 ,
        b3_io00, b3_io01, b3_io02, b3_io03, b3_io04, b3_io05,
        b3_io06, b3_io07, b3_io08, b3_io09, b3_io10, b3_io11,
        b3_io12, b3_io13, b3_io14, b3_io15, b3_nc0, b3_nc1, b3_nc2,
        gnd, gnd1, gnd10, gnd11, gnd12, gnd2, gnd3, gnd4, gnd5, gnd6,
        gnd7, gnd8, gnd9, nc0, pb2a, pb2b, pb2c, pb2d, pb4a, pb4b, pb4c,
        pb4d, pb7a, pb7b, pb7c, pb7d, pb9a, pb9b, pl2a, pl2b, pl2c,
        pl2d, pl3a, pl3b, pl3c, pl3d, pl5a, pl5b, pl5c, pl5d, pl6a,
        pl6b, pnc, pnc1, pnc10, pnc11, pnc12, pnc13, pnc14, pnc15,
        pnc16, pnc17, pnc18, pnc19, pnc2, pnc20, pnc21, pnc22, pnc23,
        pnc24, pnc25, pnc3, pnc4, pnc5, pnc6, pnc7, pnc8, pnc9, pr2a,
        pr2b, pr3a, pr3b, pr3c, pr3d, pr5a, pr5b, pr5c, pr5d, pr6a,
        pr6b, pr6c, pr6d, pt6a, pt6b, pt6c_tdo, pt6d_tdi, pt7a_tck,
        pt7b_tms, pt8a, pt8b, pt8c, pt8d, pt9a_jtagenb,
        pt9b_programn, pt9c_initn, pt9d, vcc, vcc1, vcc2, vcc3, vcc4,
        vccio0, vccio00, vccio01, vccio02, vccio0_1, vccio1,
        vccio10, vccio11, vccio12, vccio1_1, vccio2, vccio20,
        vccio21, vccio22, vccio2_1, vccio3, vccio30, vccio31,
        vccio32, vccio3_1);
    input \b0/done ;
    input \b0/initn ;
    input \b0/jtagenb ;
    input \b0/pclkc0_1 ;
    input \b0/pclkt0_1 ;
    input \b0/programn ;
    input \b0/scl/pclkt0_0 ;
    input \b0/sda/pclkc0_0 ;
    input \b0/tck ;
    input \b0/tdi ;
    input \b0/tdo ;
    input \b0/tms ;
    output b0_io00;
    output b0_io01;
    output b0_io02;
    output b0_io03;
    output b0_io04;
    output b0_io05;
    output b0_io06;
    output b0_io07;
    output b0_io08;
    output b0_io09;
    output b0_io10;
    output b0_io11;
    output b0_io12;
    output b0_io13;
    output b0_io14;
    output b0_io15;
    input \b1/pclkc1_0 ;
    input \b1/pclkt1_0 ;
    output b1_io00;
    output b1_io01;
    output b1_io02;
    output b1_io03;
    output b1_io04;
    output b1_io05;
    output b1_io06;
    output b1_io07;
    output b1_io08;
    output b1_io09;
    output b1_io10;
    output b1_io11;
    output b1_io12;
    output b1_io13;
    output b1_io14;
    output b1_io15;
    output b1_io16;
    output b1_io17;
    output b1_io18;
    output b1_io19;
    output b1_io20;
    output b1_io21;
    output b1_io22;
    output b1_io23;
    input b1_nc0;
    input b1_nc1;
    input b1_nc2;
    input \b2//mclk/cclk ;
    input \b2/csspin ;
    input \b2/pclkc2_0 ;
    input \b2/pclkc2_1 ;
    input \b2/pclkt2_0 ;
    input \b2/pclkt2_1 ;
    input \b2/si/sispi ;
    input \b2/sn ;
    input \b2/so/spiso ;
    output b2_io00;
    output b2_io01;
    output b2_io02;
    output b2_io03;
    output b2_io04;
    output b2_io05;
    output b2_io06;
    output b2_io07;
    output b2_io08;
    output b2_io09;
    output b2_io10;
    output b2_io11;
    output b2_io12;
    output b2_io13;
    output b2_io14;
    output b2_io15;
    output b2_io16;
    output b2_io17;
    output b2_io18;
    input b2_nc;
    input \b3/l_gpllc_fb ;
    input \b3/l_gpllc_in ;
    input \b3/l_gpllt_fb ;
    input \b3/l_gpllt_in ;
    input \b3/pclkc3_0 ;
    input \b3/pclkc3_1 ;
    input \b3/pclkc3_2 ;
    input \b3/pclkt3_0 ;
    input \b3/pclkt3_1 ;
    input \b3/pclkt3_2 ;
    output b3_io00;
    output b3_io01;
    output b3_io02;
    output b3_io03;
    output b3_io04;
    output b3_io05;
    output b3_io06;
    output b3_io07;
    output b3_io08;
    output b3_io09;
    output b3_io10;
    output b3_io11;
    output b3_io12;
    output b3_io13;
    output b3_io14;
    output b3_io15;
    input b3_nc0;
    input b3_nc1;
    input b3_nc2;
    input gnd;
    input gnd1;
    input gnd10;
    input gnd11;
    input gnd12;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    input gnd7;
    input gnd8;
    input gnd9;
    input nc0;
    inout pb2a;
    inout pb2b;
    inout pb2c;
    inout pb2d;
    inout pb4a;
    inout pb4b;
    inout pb4c;
    inout pb4d;
    inout pb7a;
    inout pb7b;
    inout pb7c;
    inout pb7d;
    inout pb9a;
    inout pb9b;
    inout pl2a;
    inout pl2b;
    inout pl2c;
    inout pl2d;
    inout pl3a;
    inout pl3b;
    inout pl3c;
    inout pl3d;
    inout pl5a;
    inout pl5b;
    inout pl5c;
    inout pl5d;
    inout pl6a;
    inout pl6b;
    inout pnc;
    inout pnc1;
    inout pnc10;
    inout pnc11;
    inout pnc12;
    inout pnc13;
    inout pnc14;
    inout pnc15;
    inout pnc16;
    inout pnc17;
    inout pnc18;
    inout pnc19;
    inout pnc2;
    inout pnc20;
    inout pnc21;
    inout pnc22;
    inout pnc23;
    inout pnc24;
    inout pnc25;
    inout pnc3;
    inout pnc4;
    inout pnc5;
    inout pnc6;
    inout pnc7;
    inout pnc8;
    inout pnc9;
    inout pr2a;
    inout pr2b;
    inout pr3a;
    inout pr3b;
    inout pr3c;
    inout pr3d;
    inout pr5a;
    inout pr5b;
    inout pr5c;
    inout pr5d;
    inout pr6a;
    inout pr6b;
    inout pr6c;
    inout pr6d;
    inout pt6a;
    inout pt6b;
    inout pt6c_tdo;
    inout pt6d_tdi;
    inout pt7a_tck;
    inout pt7b_tms;
    inout pt8a;
    inout pt8b;
    inout pt8c;
    inout pt8d;
    inout pt9a_jtagenb;
    inout pt9b_programn;
    inout pt9c_initn;
    inout pt9d;
    input vcc;
    input vcc1;
    output vcc2;
    output vcc3;
    output vcc4;
    input vccio0;
    output vccio00;
    output vccio01;
    output vccio02;
    input vccio0_1;
    input vccio1;
    output vccio10;
    output vccio11;
    output vccio12;
    input vccio1_1;
    input vccio2;
    output vccio20;
    output vccio21;
    output vccio22;
    input vccio2_1;
    input vccio3;
    output vccio30;
    output vccio31;
    output vccio32;
    input vccio3_1;


    initial
        begin
        end

endmodule
