// generated by newgenasym  Mon Aug 31 13:53:27 2020


module eeprom (a0, a1, a2, gnd, scl, sda, vcc, wp);
    inout a0;
    inout a1;
    inout a2;
    input gnd;
    input scl;
    inout sda;
    input vcc;
    inout wp;


    initial
        begin
        end

endmodule
