// generated by newgenasym  Mon Aug 31 14:21:48 2020


module rtl8192fr (chip_en, clk_req, gnd, gnd_sps,
        \gpioa_0/test_mode_sel/led0 , \gpioa_1/ldo_sel , hsin, hsip,
        hson, hsop, perstb, refclk_n, refclk_p, rtx_n_s0, rtx_n_s1,
        rtx_p_s0, rtx_p_s1, va10_afe, va10_pcie, va33_pcie,
        va33_xtal, vd10_out, vd10d, vd33_ldo, vr10_rtx_s0,
        vr10_rtx_s1, vr10_syn, vr33_rxt_s0, vr33_rxt_s1, vr33_syn,
        waken, xi, xo);
    inout chip_en;
    inout clk_req;
    inout gnd;
    inout gnd_sps;
    inout \gpioa_0/test_mode_sel/led0 ;
    inout \gpioa_1/ldo_sel ;
    inout hsin;
    inout hsip;
    inout hson;
    inout hsop;
    inout perstb;
    inout refclk_n;
    inout refclk_p;
    inout rtx_n_s0;
    inout rtx_n_s1;
    inout rtx_p_s0;
    inout rtx_p_s1;
    inout va10_afe;
    inout va10_pcie;
    inout va33_pcie;
    inout va33_xtal;
    inout vd10_out;
    inout vd10d;
    inout vd33_ldo;
    inout vr10_rtx_s0;
    inout vr10_rtx_s1;
    inout vr10_syn;
    inout vr33_rxt_s0;
    inout vr33_rxt_s1;
    inout vr33_syn;
    inout waken;
    inout xi;
    inout xo;


    initial
        begin
        end

endmodule
