// generated by newgenasym  Thu Sep 10 15:34:16 2020


module rs232 (\c1+ , \c1- , \c2+ , \c2- , gnd, r1in, r1out, r2in, r2out, t1in, t1out,
        t2in, t2out, \v+ , \v- , vcc);
    input \c1+ ;
    input \c1- ;
    input \c2+ ;
    input \c2- ;
    input gnd;
    input r1in;
    output r1out;
    input r2in;
    output r2out;
    input t1in;
    output t1out;
    input t2in;
    output t2out;
    input \v+ ;
    input \v- ;
    input vcc;


    initial
        begin
        end

endmodule
