// generated by newgenasym  Fri Dec 10 16:16:27 2021


module v_transformer (k1, k2, l1, l2);
    inout k1;
    inout k2;
    inout l1;
    inout l2;


    initial
        begin
        end

endmodule
