// generated by newgenasym  Thu Jan 18 19:23:45 2024


module mpq8633agle (agnd, bst, cs, en, fb, mode, pgnd, pgood, rgnd, sw, \trk/ref ,
        vcc, vin1, vin2);
    input agnd;
    inout bst;
    inout cs;
    input en;
    input fb;
    inout mode;
    input pgnd;
    output pgood;
    input rgnd;
    output sw;
    inout \trk/ref ;
    input vcc;
    input vin1;
    input vin2;


    initial
        begin
        end

endmodule
