-- generated by newgenasym Thu Jan 18 19:23:45 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mpq8633agle is
    port (    
	AGND:      IN     STD_LOGIC;    
	BST:       INOUT  STD_LOGIC;    
	CS:        INOUT  STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	FB:        IN     STD_LOGIC;    
	MODE:      INOUT  STD_LOGIC;    
	PGND:      IN     STD_LOGIC;    
	PGOOD:     OUT    STD_LOGIC;    
	RGND:      IN     STD_LOGIC;    
	SW:        OUT    STD_LOGIC;    
	\trk/ref\: INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VIN1:      IN     STD_LOGIC;    
	VIN2:      IN     STD_LOGIC);
end mpq8633agle;
