// generated by newgenasym  Mon Aug 31 16:16:28 2020


module led (\1 , \2 , \3 , \4 , anode, cathode, n1, n2, n3, n4, p1, p2, p3, p4);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    output \4 ;
    inout anode;
    inout cathode;
    input n1;
    input n2;
    input n3;
    input n4;
    output p1;
    output p2;
    output p3;
    output p4;


    initial
        begin
        end

endmodule
